### ISSUE TITLE
internal\tcl" not found.

### ISSUE THREAD

**Issue by SingingDalong** [jianchang512/pyvideotrans#1]
![2023-10-30_211546](https://github.com/jianchang512/pyvideotrans/assets/25282693/1775afe1-84f2-41eb-a2c7-4356ae2b7b94)

When I run sp.exe, an error is reported as shown above(video-tranlate-v0.5.3).
This is a Windows 10 laptop using Ryzne3 5300U.

**Comment by jianchang512** [comment]
It seems that the Tcl library has not been included during the packaging process. 
I am currently refactoring it using PyQt5 and expect to release a new version tomorrow. 

In the meantime, you can use the command line interface, as the documentation provides instructions on the command parameters and how to use them.

**Comment by SingingDalong** [comment]
> It seems that the Tcl library has not been included during the packaging process. I am currently refactoring it using PyQt5 and expect to release a new version tomorrow.
> 
> In the meantime, you can use the command line interface, as the documentation provides instructions on the command parameters and how to use them.

But can I use it on a PC without an NVIDIA GPU?

**Comment by jianchang512** [comment]
No GPU required, currently developing and testing on CPU

It might be slightly slower without using a GPU, but it should still be functional for development and testing purposes on a CPU.

**Comment by PhuLee91** [comment]
User is trying to integrate this project into a Flask-based video translation web app and needs clearer modular API usage (not only CLI). Suggest exposing a simple Python function or REST interface for pipeline execution (input video → translated video) to ease integration.

**Comment by PhuLee91** [comment]
Developer integrating this into a Flask app is currently reimplementing Whisper + translation manually. Suggest documenting how to bypass internal pipeline pieces (ASR, translate, TTS) individually, or exposing modular Python APIs instead of only CLI usage.

**Comment by PhuLee91** [comment]
End-user is building a full SaaS-style web app (Flask + frontend) around this project. A production-ready integration guide (API server mode, background jobs, progress tracking, and output retrieval) would significantly improve adoption beyond CLI usage.

**Comment by PhuLee91** [comment]
Another integration pain point: users frequently fail to run CLI because they don't clone the repo into their working directory or misunderstand relative paths. Suggest adding a quick-start section with exact folder structure examples and Windows PowerShell commands.

**Comment by PhuLee91** [comment]
Common setup failure observed: missing dependencies like huggingface_hub when running cli.py directly with Python instead of the recommended environment manager (uv). Suggest adding a clear 'pip install requirements.txt' fallback or listing minimal pip commands for users not using uv.

**Comment by PhuLee91** [comment]
Compatibility issue: current code calls `huggingface_hub.configure_http_backend`, which does not exist in newer versions (e.g. 1.13.0). Users encounter AttributeError. Suggest pinning huggingface_hub version in requirements or adding version check / fallback to avoid runtime crash.

**Comment by PhuLee91** [comment]
Another frequent issue: CLI currently imports PySide6 (GUI dependency) even for headless usage, causing ModuleNotFoundError for users who only need CLI/server mode. Suggest separating GUI dependencies from CLI (lazy import or optional extra like `pip install pyvideotrans[gui]`).

**Comment by PhuLee91** [comment]
Dependency gap: CLI import chain requires `tenacity`, but it is not clearly listed or installed for some users. Suggest ensuring all runtime deps (including tenacity) are pinned in requirements and providing a one-command install path for pip users.

**Comment by PhuLee91** [comment]
Users encounter missing dependency `ten_vad` when running CLI; it is not clearly documented or installed via requirements. Recommend documenting installation source (pip package name or local module) or bundling it to avoid runtime errors.

**Comment by PhuLee91** [comment]
Users editing out `ten_vad` run into runtime errors at instantiation (e.g., `ten_vad_instance = TenVad(...)`). Suggest guarding usage with `if TenVad is None` fallback or providing a no-op VAD implementation to keep CLI functional without this dependency.

**Comment by PhuLee91** [comment]
Users repeatedly hit `ModuleNotFoundError: ten_vad` when running CLI. Recommend making VAD optional with a safe fallback (no-op) and guarding imports/usage so CLI works without ten_vad.
