### ISSUE TITLE
无法启动程序_系统win11_home

### ISSUE THREAD

**Issue by SharkTal** [jianchang512/pyvideotrans#10]
![无法启动程序](https://github.com/jianchang512/pyvideotrans/assets/47451399/d9132192-f3e0-4d57-9578-b87383227a6c)
![系统信息](https://github.com/jianchang512/pyvideotrans/assets/47451399/f7bad51b-faef-4473-9fe1-1ca063df705f)
我使用的是v7.4版本
请问是系统问题，还是版本问题。

**Comment by aimarxjg** [comment]
丢给BING问问看，顺便升级下WIN11，版本是23H2这起码半年没更新了

**Comment by jianchang512** [comment]
你用的英文版是吧
这个暂时有点问题，先使用中文版
config.py 打开大约 63行左右，
`langcode = locale.getdefaultlocale()[0]` 改为 `langcode = 'zh'`
