### ISSUE TITLE
请问是不能用win下的pycharm执行带cuda加速的项目吗

### ISSUE THREAD

**Issue by CHDKBL** [jianchang512/pyvideotrans#104]
我用Pycharm配置环境后启动去听译视频，这个过程cpu满载，到了硬字幕嵌入时，程序闪退了。
pytorch用的是pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118，
我执行了项目里的test.py，它返回了true。
cuda我是安装在win本地了，是得尝试在venv下安装吗。

我又试了一下，就是程序终止了，但是后台的ffmpeg还在高占用。

**Comment by jianchang512** [comment]
1 .videotrans/util/tools.py
搜索  delete_temp
这个函数第一行加个 return None，即先注释掉该函数功能

2. 目标文件夹不要直接放在硬盘根目录。

**Comment by jianchang512** [comment]
说明cuda配置没有生效

执行 pip uninstall torch torchaudio torchvision 卸载，

然后去 [https://pytorch.org/get-started/locally/](https://github.com/jianchang512/pyvideotrans/blob/main) 根据你的操作系统类型和 CUDA 版本，选择命令,如下图  然后将 pip3 改为 pip，再复制命令去执行。

安装完毕后，在该虚拟环境里，执行 python,等待进入后，再分别
执行 import torch
torch.cuda.is_available()

如果有输出，说明CUDA配置正确

**Comment by jianchang512** [comment]
界面中 启用 cuda 选中了吗

**Comment by jianchang512** [comment]
重新试试吧

**Comment by yuppiesnotzhuhao** [comment]
同样的问题，ffmpeg没有启用cuda加速
