### ISSUE TITLE
提示标签错误

### ISSUE THREAD

**Issue by troublemakerMibu** [jianchang512/pyvideotrans#107]
版本：0.9.6.4
视频提取字幕按钮的说明标签：
<img width="261" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/121711734/dc35a56a-96f3-4f2b-b351-f04fbce48665">
提取字幕翻译按钮的说明标签：
<img width="222" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/121711734/20f9e7a5-5f8c-4ee8-a403-1592e381a2d8">
感觉好像这两个说明互相对调了

**Comment by jianchang512** [comment]
多谢，下版修复
