### ISSUE TITLE
ffmpeg是如何工作的？

### ISSUE THREAD

**Issue by aileenfun** [jianchang512/pyvideotrans#108]
感谢大神的作品！
我的台式机电脑CPU比较弱，但显卡是3060 12G，当时专门为了加速训练买的。所以跑本项目时前期ffmpeg纯cpu跑的时候非常慢。
之前我也研究过一段时间ffmpeg，它是可以用各种cuda或者intel加速选项的，加速效果很好。
浏览了一下源码，没有找到相关的参数设置，是否可以快速指点一下在哪里？我看能否自己修改一下。
谢谢！

**Comment by jianchang512** [comment]
目前源码和预编译版已支持n卡CUDA。
界面中开启cuda即可
videotrans/util/tools.py
runffmpeg 函数中
