### ISSUE TITLE
软件再加个人声分离就完美了，就是把原视频的人声和背景音乐分离，那样就能直接在软件中提取背景音乐了，那就完整了！！！

### ISSUE THREAD

**Issue by qudongdong123** [jianchang512/pyvideotrans#109]

**Comment by qudongdong123** [comment]
Ultimate Vocal Remo   https://github.com/Anjok07/ultimatevocalremovergui#ultimate-vocal-remover-gui-v56

**Comment by jianchang512** [comment]
老版本搞过，效果并不怎么好，而且还需要额外绑定模型，导致体积太大了，后续就去掉了

**Comment by q247574452** [comment]
> Author

视频音画不同步，怎么调节呢
