### ISSUE TITLE
使用体验建议

### ISSUE THREAD

**Issue by q247574452** [jianchang512/pyvideotrans#111]
合成之后的视频，音频和画面不匹配的问题，正常合成的视频的音频会很长的空白档，就是每句话之间有很长的空白，这个怎么解决，我感觉把翻译之后的音频进行去掉中间的很长片段，可以和画面比较完美的匹配。是设置静音片段时长那个位置吗，但是感觉设置了还是有很长的空白档，就是每句话之间很长的空白。

**Comment by dsassadasdwz** [comment]
最新版本设置添加百度key 会直接关闭窗口了

**Comment by jianchang512** [comment]
使用 0.9.6.6 版本
你截图显示的不是最新版本

> 最新版本设置添加百度key 会直接关闭窗口了
