### ISSUE TITLE
已有字幕文件，无法完成配音

### ISSUE THREAD

**Issue by liwei19840921** [jianchang512/pyvideotrans#113]
已有中文字幕文件，无法完成配音。
原始语言和目标语言都选择中文，处理完成后只把音视频分离。
0.9.6.5
![1](https://github.com/jianchang512/pyvideotrans/assets/109659199/46f826f8-8729-470c-9ce4-7e2cc606dd2b)

**Comment by liwei19840921** [comment]
“字幕创建配音”模式无法加入视频，因为还需要“视频自动慢速”的功能。
翻译渠道选择其它的结果一样。

**Comment by jianchang512** [comment]
语音识别模型后边选择整体识别

然后看看目标文件夹下是否有 srt 文件

**Comment by liwei19840921** [comment]
结果还是一样，目标文件夹还是这三个文件
![2](https://github.com/jianchang512/pyvideotrans/assets/109659199/9a421051-a7b2-4615-896b-756d3b3fa9d4)

**Comment by jianchang512** [comment]
原语言和目标语言一样，这样不翻译，会对zh-cn进行配音。但检测到已存在 该语言的音频，所以不会再进行配音了

这种你需要使用字幕创建配音，将 zh-cn.srt 进行配音生成wav配音文件，然后再将 音频和视频合并

**Comment by liwei19840921** [comment]
我的视频原语言是英文，字幕是中文；用字幕创建配音就不能使用“视频自动慢速”的功能了，希望改进吧

**Comment by jianchang512** [comment]
如果原语言是英文，那么你就不要把原语言设为中文。
原语言设为英文，目标语言设为中文，然后将字幕拖到右侧字幕区

**Comment by jianchang512** [comment]
编译版还是源码版

**Comment by liwei19840921** [comment]
编译版

**Comment by jianchang512** [comment]
等会，发你个 sp.exe 覆盖

**Comment by jianchang512** [comment]
[解压覆盖同名sp.exe文件.zip](https://github.com/jianchang512/pyvideotrans/files/13601290/sp.exe.zip)

**Comment by jianchang512** [comment]
0.9.6.7 试试吧
