### ISSUE TITLE
大哥可以新增对 Azure OpenAI的支持吗？

### ISSUE THREAD

**Issue by AnthonyCoder** [jianchang512/pyvideotrans#114]

**Comment by AnthonyCoder** [comment]
因为国内大多开通不了OpenAI 只能通过Azure去获取OpenAI的服务，下面是关于AzureOpenAI和OpenAI的区别和切换方式。
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints

**Comment by jianchang512** [comment]
翻译已加
