### ISSUE TITLE
翻译字幕的时候 出错  （由于目标计算机积极拒绝，无法连接）

### ISSUE THREAD

**Issue by 398179063** [jianchang512/pyvideotrans#115]
![微信图片_20231208021958](https://github.com/jianchang512/pyvideotrans/assets/153224320/9268b0bb-4b92-40ab-8988-925c07fa1915)

**Comment by jianchang512** [comment]
先确认你要使用的是 DeepL 还是 DeepLX,后者需要自己 将 DeepLX 部署在计算机上并启动，然后将端口地址粘贴到软件--菜单--DeepLX地址中。如果没有部署或者使用的公共部署地址，就会是这个错误。
