### ISSUE TITLE
文字翻译出错: list index out of range

### ISSUE THREAD

**Issue by residentialproxies** [jianchang512/pyvideotrans#117]
老哥，这个是什么问题？跑完进度后就显示这个，无法翻译字幕，版本是0.9.5.3，代理，端口配置这些好的，用的google接口，Python也安装了的
![333](https://github.com/jianchang512/pyvideotrans/assets/138377120/d74fb899-144d-4f15-8299-be4792b5f809)

**Comment by jianchang512** [comment]
升级到 0.9.6.7

**Comment by residentialproxies** [comment]
谢谢老哥
