### ISSUE TITLE
新需求增融合

### ISSUE THREAD

**Issue by laoma89** [jianchang512/pyvideotrans#118]
是否可以依据配置文件实现视频文件的自动剪辑
例如：视频文件为123.mp4，这个视频文件时长1小时，我通过gpt读取这个视频文件，让gpt分析重构内容为5分钟精彩内容，然后输出字幕时间和片段时间，然后生成配置文件，然后软件加载这个配置后自动剪辑输出剪辑后的视频文件，可以增加字幕的配音。

**Comment by jianchang512** [comment]
太过复杂了，实现不了。
这种需求应该AI生成视频那种工具比较合适
