### ISSUE TITLE
大哥，我用腾讯翻译的时候报错超过1秒5个请求

### ISSUE THREAD

**Issue by bee2287448** [jianchang512/pyvideotrans#120]
大哥，我用腾讯翻译的时候报错超过1秒5个请求，请问能设置每秒提交多少个请求进行翻译吗，不要太快了。
用google翻译感觉又太慢了。能调快吗？

**Comment by jianchang512** [comment]
如果用的源码部署

打开 videotrans/translator/tencent.py，try前面加一行，缩进对齐，添加
import time
time.sleep(0.2)

**Comment by bee2287448** [comment]
hello，那google翻译很慢的问题可以调整参数吗？ 还是google翻译就是这么慢的。

**Comment by jianchang512** [comment]
那个无法调整。那是抓取google的公开接口

**Comment by bee2287448** [comment]
好的，非常非常感谢，我今晚试一下腾讯的翻译
