### ISSUE TITLE
百度翻译key报错了

### ISSUE THREAD

**Issue by dsassadasdwz** [jianchang512/pyvideotrans#124]
![image](https://github.com/jianchang512/pyvideotrans/assets/63733326/24321fd6-3ffd-44c7-92c9-c78ae4f16688)

**Comment by jianchang512** [comment]
百度翻译开放平台--开发者信息--修复服务器信息--删掉服务器地址

**Comment by dsassadasdwz** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jianchang512/pyvideotrans"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jianchang512/pyvideotrans] 百度翻译key报错了 (Issue #124)





 
百度翻译开放平台--开发者信息--修复服务器信息--删掉服务器地址

**Comment by dsassadasdwz** [comment]
百度重来没有连接上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jianchang512/pyvideotrans"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jianchang512/pyvideotrans] 百度翻译key报错了 (Issue #124)





 
Closed #124 as completed.

**Comment by jianchang512** [comment]
那个错误提示就是百度翻译返回的。翻译为中文就是“禁止该IP连接”
