### ISSUE TITLE
大佬，每次选预先分割就报以下错误，选整体识别就没问题。

### ISSUE THREAD

**Issue by bee2287448** [jianchang512/pyvideotrans#128]
大佬，每次选预先分割就报以下错误，选整体识别就没问题。整体识别是不是会抽风，中间如果不说话很长时间，突然说话，他会不翻译。

<img width="491" alt="捕获chat" src="https://github.com/jianchang512/pyvideotrans/assets/120633853/762ee65f-2343-49c8-8325-8ee05558b982">

**Comment by jianchang512** [comment]
GPU显存不足，更换其他模型，比如 small  large
