### ISSUE TITLE
CUDA加速问题

### ISSUE THREAD

**Issue by demon-os** [jianchang512/pyvideotrans#130]
使用的预编译版本，还需要另外下载什么软件才能使用加速吗。是Nvidia的集成显卡

**Comment by jianchang512** [comment]
如果你的显卡是 Nvidia，可以根据显卡驱动版本和操作系统版本，去安装对应的 [CUDA Toolkit 11.8](https://developer.nvidia.com/cuda-downloads) 和 [cudnn for CUDA11.X](https://developer.nvidia.com/rdp/cudnn-archive), 建议预先将显卡驱动升级到最新版，再去安装。

安装成功后，打开 cmd窗口，分别输入 `nvidia-smi` 和 nvcc，都有输出说明可用
