### ISSUE TITLE
出错:ffmpeg执行结果:失败

### ISSUE THREAD

**Issue by wangzhongjun** [jianchang512/pyvideotrans#131]
出错:ffmpeg执行结果:失败 cmd=['ffmpeg', '-hide_banner', '-hwaccel', 'cuda', '-loop', '1', '-i', 'C:/videotrans-970/tmp/04_1/last.jpg', '-vf', 'fps=30.0,scale_cuda=1920:1080', '-c:v', 'h264_nvenc', '-crf', '0', '-to', '00:00:48.647', '-pix_fmt', 'yuv420p', '-y', 'C:/videotrans-970/tmp/04_1/last_clip.mp4'], errs='Error reinitializing filters!\\r\\nFailed to inject frame into filter network: Function not implemented\\r\\nError while filtering: Function not implemented\\r\\n[out#0/mp4 @ 0000016dcb7a8a80] Nothing was written into output file, because at least one of its streams received no packets.\\r\\nframe= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A \\r\\nConversion failed!\\r\\n"'
执行ffmpeg失败:errs='Error reinitializing filters!\\r\\nFailed to inject frame into filter network: Function not implemented\\r\\nError while filtering: Function not implemented\\r\\n[out#0/mp4 @ 0000016dcb7a8a80] Nothing was written into output file, because at least one of its streams received no packets.\\r\\nframe= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A \\r\\nConversion failed!\\r\\n"'出错:末尾添加延长视频帧失败，将保持原样，截断音频,不延长视频

**Comment by wangzhongjun** [comment]
laegeV3 模型 勾了 cuda加速  勾上了配音自动加速   用的 整体识别

**Comment by jianchang512** [comment]
[解压覆盖.zip](https://github.com/jianchang512/pyvideotrans/files/13667380/default.zip)

解压覆盖 sp.exe ，试试

**Comment by midxplore** [comment]
我是通过源构建，也有这个问题，试着您的解决方案，但本地没有.EXE文件可以替换

**Comment by jianchang512** [comment]
> 我是通过源构建，也有这个问题，试着您的解决方案，但本地没有.EXE文件可以替换

拉取最新源码
先确定 cuda 配置正确
`NVIDIA-smi` `nvcc`
