### ISSUE TITLE
使用问题，功能优化

### ISSUE THREAD

**Issue by q247574452** [jianchang512/pyvideotrans#132]
1.字幕创建配音下的功能，只有配音自动加速，没有视频自动慢速选择。

2.假设已经制作好了，英文字幕，想要直接配音后合成视频匹配，没有这个功能，必须要重新用标准功能模式，识别中文在翻译在合成，能不能增加一个，英文字幕直接配音合成视频的。这样就不用那么麻烦等待前几个步骤，在操作了

**Comment by jianchang512** [comment]
字幕创建配音，都没有视频，哪需要“视频自动慢速”

想要已有字幕和视频合并，直接标准模式，原语言随便选个，目标语言选择英文，将字幕拖到右侧字幕编辑区，选择配音，选择视频
