### ISSUE TITLE
TTS OpenAI怎么使用呢？ 

### ISSUE THREAD

**Issue by 861172923** [jianchang512/pyvideotrans#133]
需要在哪里提供秘钥什么么？

**Comment by jianchang512** [comment]
菜单--设置--chatGPT
首先需要确保已有openai账号，并且该账号有使用 TTS-1 模型的权限

**Comment by yousei521** [comment]
我重新申请了key而且在软件中已经能试听了。但是使用是还是弹出请我填写chatgpt key

**Comment by jianchang512** [comment]
1. 截图填写key的那个窗口，看看填写情况
2. 确定升级到最新版本 0.970

**Comment by yousei521** [comment]
![13](https://github.com/jianchang512/pyvideotrans/assets/125034389/0c765c41-9f28-41ad-a209-2f2e8152ddff)
试听没问题。每个语音都可以，但是翻译和tts都不行。

**Comment by jianchang512** [comment]
> 我重新申请了key而且在软件中已经能试听了。但是使用是还是弹出请我填写chatgpt key



> 我重新申请了key而且在软件中已经能试听了。但是使用是还是弹出请我填写chatgpt key

弹出来什么样的，截图

**Comment by yousei521** [comment]
![12](https://github.com/jianchang512/pyvideotrans/assets/125034389/cd938445-d250-4ee2-9d80-8a29146b67c9)

**Comment by jianchang512** [comment]
> ![12](https://private-user-images.githubusercontent.com/125034389/290422973-cd938445-d250-4ee2-9d80-8a29146b67c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzUxMTQsIm5iZiI6MTcwMjUzNDgxNCwicGF0aCI6Ii8xMjUwMzQzODkvMjkwNDIyOTczLWNkOTM4NDQ1LWQyNTAtNGVlMi05ZDgwLThhMjkxNDZiNjdjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwNjIwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTc0ZmU0OTAxNjE4YTVjOWYyYTEyYWEyYzMxOTQzYmRjZjYxNWEzOTNmNTFhN2Q4MjYxOTRlMjA2ZGFkMGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R_xHpyqxEncBvTtu39uzDaRR30kwManP_x1uPIldvt8)

解压覆盖 sp.exe
[sp.zip](https://github.com/jianchang512/pyvideotrans/files/13669660/sp.zip)
