### ISSUE TITLE
大佬，我已经有一些srt文件了，想直接调用翻译，有没有办法操作。

### ISSUE THREAD

**Issue by bee2287448** [jianchang512/pyvideotrans#134]
大佬，我已经有一些srt文件了，想直接调用翻译，有没有办法操作。

**Comment by jianchang512** [comment]
左侧工具栏一排按钮，最下面一个是“文本字幕翻译”，用这个就行

**Comment by bee2287448** [comment]
大佬，这个我把srt贴过去，但是会超过翻译api的限制，只能小段小段的贴，后续能否做成和识别后翻译一下，自动分段去翻译然后最终合成一个srt文件
