### ISSUE TITLE
edgeTTS 没有配音角色可选

### ISSUE THREAD

**Issue by baicaiit** [jianchang512/pyvideotrans#135]
![image](https://github.com/jianchang512/pyvideotrans/assets/42630572/48839418-41d7-4212-af5d-3848a5e547ec)

**Comment by jianchang512** [comment]
项目根目录下看看是否存在voicelist.json文件，如果存在，记事本打开看看有没有内容，如果有很多内容，重启软件，如果没有内容，就删掉这个文件，再重启软件，重启后再检查是否存在这个文件并且里面有内容

win10还是11系统？

**Comment by baicaiit** [comment]
mac, 使用 python sp.py 跑起来的
ui还有点不兼容, 下拉选择框很小

**Comment by baicaiit** [comment]
> 项目根目录下看看是否存在voicelist.json文件，如果存在，记事本打开看看有没有内容，如果有很多内容，重启软件，如果没有内容，就删掉这个文件，再重启软件，重启后再检查是否存在这个文件并且里面有内容
> 
> win10还是11系统？

噢 没有你说的那个json文件
![image](https://github.com/jianchang512/pyvideotrans/assets/42630572/cb7ec360-8cfe-4ea4-9b0d-93cab010c42d)

**Comment by jianchang512** [comment]
将 videotrans/util/tools.py 中第  41-44行代码 
```
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
else:
    asyncio.set_event_loop_policy(asyncio.DefaultEventLoopPolicy())
```
删掉，然后再打开软件，看看有没有产生 voice_list.json

**Comment by baicaiit** [comment]
> 将 videotrans/util/tools.py 中第 41-44行代码
> 
> ```
> if sys.platform == 'win32':
>     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> else:
>     asyncio.set_event_loop_policy(asyncio.DefaultEventLoopPolicy())
> ```
> 
> 删掉，然后再打开软件，看看有没有产生 voice_list.json
> 
> python 使用 3.10

噢噢, 可以了, 谢谢

**Comment by wrqyx** [comment]
同问win11，我也没有配音角色可选，videotrans里只有style，上述方法解决不了啊？
