### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by gxu12** [jianchang512/pyvideotrans#136]
准备配音数据，格式化字幕文件时出错：list index out of range配音结束

大佬，这个是为什么会报错，期待回复

**Comment by jianchang512** [comment]
哪个版本，具体版本号数字
升级到 0.975

https://github.com/jianchang512/pyvideotrans/releases/tag/v0.975

**Comment by gxu12** [comment]
INFO:VideoTrans:开始配音操作:openaiTTS,alloy
INFO:VideoTrans:倒计时停止,更新目标语言字幕
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/a33496bba2ac34264e299786cd08fdb0.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/2303978ad9739088a07ed6c57a701fc0.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/eac189f32c314f8fb01a0661e1605c07.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/0fa8141488f90ff90f5520e1c804c5f7.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/dfadd1ce3c8c4d9036b711f892772eac.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/6ddf7ea4c07941472fbe0411a4fbde0d.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/503f5e47eb4096d3f2fead81a1c8d638.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/bad5c07a5ef14df8ad4834544b741cdb.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/f6048a2f6a2f0137d50ad1d18449b156.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/3aba75a39a308791bfb5f8267da01532.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/559070ca70ed7d65bc78cba6f38953bd.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/c963108b22f96d7b3cf2dc488bf85690.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
INFO:VideoTrans:此 00:00:00,000 - 00:00:03,360 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:03,360 - 00:00:07,776 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:07,940 - 00:00:12,020 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:12,240 - 00:00:14,592 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:14,700 - 00:00:18,612 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:18,612 - 00:00:21,228 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:21,832 - 00:00:26,992 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:27,031 - 00:00:32,598 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:32,598 - 00:00:36,847 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:37,480 - 00:00:41,296 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:41,296 - 00:00:45,112 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:45,756 - 00:00:47,268 时间段内字幕合成语音失败
INFO:VideoTrans:末尾不需要延长
INFO:VideoTrans:配音结束
INFO:VideoTrans:字幕创建配音完毕
INFO:VideoTrans:本次任务全部结束

以及我设置了openaitts，但是代码好像默认还是选了edgetts...

**Comment by jianchang512** [comment]
> > 哪个版本，具体版本号数字 升级到 0.975
> > https://github.com/jianchang512/pyvideotrans/releases/tag/v0.975
> 
> INFO:VideoTrans:本次任务全部结束 INFO:VideoTrans::::开始处理第1个视频(共1个):【】 INFO:VideoTrans:正在处理第1个视频(共1个):【】 INFO:VideoTrans:C:/Users/Administrator/Videos/pyvideotrans/only_dubbing/20231218-181415 INFO:VideoTrans:等待修改配音字幕/点击继续 INFO:VideoTrans:59秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确 INFO:VideoTrans:58秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确 INFO:VideoTrans:57秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确 INFO:VideoTrans:56秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确 INFO:VideoTrans:55秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确 INFO:VideoTrans:54秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确 INFO:VideoTrans:开始配音操作:openaiTTS,alloy INFO:VideoTrans:倒计时停止,更新目标语言字幕 INFO:openai._base_client:Retrying request to /audio/speech in 0.754089 seconds INFO:openai._base_client:Retrying request to /audio/speech in 0.884007 seconds INFO:openai._base_client:Retrying request to /audio/speech in 0.928661 seconds INFO:openai._base_client:Retrying request to /audio/speech in 1.921369 seconds INFO:openai._base_client:Retrying request to /audio/speech in 1.533110 seconds INFO:openai._base_client:Retrying request to /audio/speech in 1.910339 seconds ERROR:VideoTrans:openaiTTS合成失败：request error:Connection error. INFO:VideoTrans:openaiTTS 合成失败：request error:Connection error. ERROR:VideoTrans:使用openaiTTS合成语音失败 ERROR:VideoTrans:openaiTTS合成失败：request error:Connection error. INFO:VideoTrans:openaiTTS 合成失败：request error:Connection error. ERROR:VideoTrans:使用openaiTTS合成语音失败 ERROR:VideoTrans:openaiTTS合成失败：request error:Connection error. INFO:VideoTrans:openaiTTS 合成失败：request error:Connection error. ERROR:VideoTrans:使用openaiTTS合成语音失败 INFO:openai._base_client:Retrying request to /audio/speech in 0.752353 seconds INFO:openai._base_client:Retrying request to /audio/speech in 0.940092 seconds INFO:openai._base_client:Retrying request to /audio/speech in 0.965551 seconds INFO:openai._base_client:Retrying request to /audio/speech in 1.912236 seconds INFO:openai._base_client:Retrying request to /audio/speech in 1.750237 seconds INFO:openai._base_client:Retrying request to /audio/speech in 1.913329 seconds
> 
> 重新安装了975版本，然后使用openai的配音，但是报这个错了，已经搭了梯子，这个是为啥呀

这是梯子问题，连不上。


INFO:VideoTrans:开始配音操作:openaiTTS,alloy
INFO:VideoTrans:倒计时停止,更新目标语言字幕
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/a33496bba2ac34264e299786cd08fdb0.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/2303978ad9739088a07ed6c57a701fc0.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/eac189f32c314f8fb01a0661e1605c07.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/0fa8141488f90ff90f5520e1c804c5f7.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/dfadd1ce3c8c4d9036b711f892772eac.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/6ddf7ea4c07941472fbe0411a4fbde0d.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/503f5e47eb4096d3f2fead81a1c8d638.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/bad5c07a5ef14df8ad4834544b741cdb.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/f6048a2f6a2f0137d50ad1d18449b156.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/3aba75a39a308791bfb5f8267da01532.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/559070ca70ed7d65bc78cba6f38953bd.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
ERROR:VideoTrans:文字合成出错:filename='D:/videotrans/tmp/20231218-185328/c963108b22f96d7b3cf2dc488bf85690.mp3',tts_type='edgeTTS',Invalid voice 'alloy'.
INFO:VideoTrans:此 00:00:00,000 - 00:00:03,360 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:03,360 - 00:00:07,776 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:07,940 - 00:00:12,020 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:12,240 - 00:00:14,592 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:14,700 - 00:00:18,612 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:18,612 - 00:00:21,228 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:21,832 - 00:00:26,992 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:27,031 - 00:00:32,598 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:32,598 - 00:00:36,847 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:37,480 - 00:00:41,296 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:41,296 - 00:00:45,112 时间段内字幕合成语音失败
INFO:VideoTrans:此 00:00:45,756 - 00:00:47,268 时间段内字幕合成语音失败
INFO:VideoTrans:末尾不需要延长
INFO:VideoTrans:配音结束
INFO:VideoTrans:字幕创建配音完毕
INFO:VideoTrans:本次任务全部结束

以及我设置了openaitts，但是代码好像默认还是选了edgetts...

这个问题在0.975版已修复
