### ISSUE TITLE
tools.py中的compos_video函数多了一个参数，导致cli.py运行出错

### ISSUE THREAD

**Issue by dongxiaok** [jianchang512/pyvideotrans#139]
![image](https://github.com/jianchang512/pyvideotrans/assets/45843136/93948c77-21c5-4c83-88bb-2342f337a9ce)
可能需要删除多余的参数

**Comment by jianchang512** [comment]
cli模式久未维护了，可能存在不少问题，有空了再处理下吧。

**Comment by dongxiaok** [comment]
想在linux下运行，只能使用cli模式了是吗？

**Comment by jianchang512** [comment]
如果是Linux桌面，应该是可以使用的。
