### ISSUE TITLE
无法启动，报找不到speech_recognition模块

### ISSUE THREAD

**Issue by gvs** [jianchang512/pyvideotrans#14]
python sp.py
Traceback (most recent call last):
  File "D:\AITest\pyvideotrans-main\sp.py", line 9, in <module>
    from tools import get_list_voices, get_large_audio_transcription, runffmpeg
  File "D:\AITest\pyvideotrans-main\tools.py", line 10, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'

D:\AITest\pyvideotrans-main>pip install speech_recognition
ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.

[notice] A new release of pip is available: 23.0 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by jianchang512** [comment]
pip install -r requirements.txt
