### ISSUE TITLE
单独用 "字幕创建配音" ，生成的文件语音长度多了7%, 导致不同步

### ISSUE THREAD

**Issue by boyangmtl** [jianchang512/pyvideotrans#140]
When I use the function "字幕创建配音" ， 字幕来自youtube视频。 发现最后生成的音频比字幕对应的视频长大约8%，导致后面完全不同步。
测试了好多个字幕文件。

问题可能处在哪里？  是字幕文件的时间标注不准确？

但是如果让程序自己读取那个视频， 生成的语音就是正确的长度。

![image](https://github.com/jianchang512/pyvideotrans/assets/82223084/bcf14598-9410-4777-bcea-f2a5f836d277)

**Comment by boyangmtl** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/82223084/85e1949e-2580-49fa-892e-a3823aa0c83e)

**Comment by jianchang512** [comment]
比如字幕标注是3s，但配音实际发声未必就是3s，有可能5s，不同配音角色语速不同

选中“自动配音加速”试试
