### ISSUE TITLE
标准功能生成字幕文件乱码，背景音乐丢失

### ISSUE THREAD

**Issue by wenzibuding** [jianchang512/pyvideotrans#143]
如题
1.标准功能生成的中文字幕文件用win11自带播放器显示乱码，用记事本打开另存为UTF-8 BOM编码后显示成功
2.生成的中文语音文件只剩人声了，原视频里的背景音乐丢失了，
3.原视频有男有女的多人语音，生成的中文语音只有1个人声，如果可以希望起码男女声可以分开

**Comment by jianchang512** [comment]
1. 生成的srt默认utf-8编码，有的播放器编码可能是ANSI，中文下是GBK，需要自行处理编码
2. 不是丢失了，配音只处理人声，忽略背景，如果你想保留背景声音，需要自行使用其他工具提取背景声音，再和配音文件合并
3. 单角色配音，不支持角色和声音分离。这个复杂度和难度太大，openai-whisper模型都不支持，不考虑
