### ISSUE TITLE
输出结果可否是源文件名字+特殊的后缀

### ISSUE THREAD

**Issue by istingbiao** [jianchang512/pyvideotrans#144]
二次进入文件夹修改名字太痛苦了

**Comment by jianchang512** [comment]
?没看懂什么意思

**Comment by istingbiao** [comment]
就是这里的文件名是否可以是这样的格式
![微信截图_20231231194430](https://github.com/jianchang512/pyvideotrans/assets/24237770/8c454638-8c3e-4e8d-8abe-eff7532907fe)
