### ISSUE TITLE
是否支持linux系统源码部署呢

### ISSUE THREAD

**Issue by suwei999** [jianchang512/pyvideotrans#147]
是否支持linux系统源码部署呢

**Comment by jianchang512** [comment]
支持
仿照win部署

**Comment by suwei999** [comment]
好的我去部署试下,ths

**Comment by suwei999** [comment]
我在安装完环境后启动报错:
ubuntu 20.04

(pyvideotrans) root@aiserver:~/pyvideotrans# python sp.py 
pygame 2.5.2 (SDL 2.28.2, Python 3.9.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
QObject::moveToThread: Current thread (0x7109b30) is not the object's thread (0x80fea30).
Cannot move to target thread (0x7109b30)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/anaconda3/envs/pyvideotrans/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

已放弃 (核心已转储)

**Comment by jianchang512** [comment]
打开sp.py，最底下倒数第二行， pygameinit那行删掉试试

**Comment by jianchang512** [comment]
sudo pacman -S libxcb

**Comment by suwei999** [comment]
(pyvideotrans) root@aiserver:~/pyvideotrans# pacman -S libxcb
命令 'pacman' 可在 '/usr/games/pacman' 处找到
由于/usr/games 不在PATH 环境变量中，故无法找到该命令。
pacman：未找到命令
(pyvideotrans) root@aiserver:~/pyvideotrans# /usr/games/pacman -S libxcb

打开这个是一个小游戏，上面的方式都试了还是没能解决

**Comment by suwei999** [comment]
https://stackoverflow.com/questions/46449850/how-to-fix-the-error-qobjectmovetothread-in-opencv-in-python
这个文档说貌似不能再conda虚拟python环境中使用opencv-python, 是否正确呢

**Comment by jianchang512** [comment]
这个项目没用到 opencv-python，应该和这个无关

执行这个命令试试

sudo pacman -S libxcb

**Comment by suwei999** [comment]
明明已经安装，执行确找不到这个命令

**Comment by suwei999** [comment]
suwei@aiserver:~/桌面$ sudo apt-get install pacman
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
pacman 已经是最新版 (10-18build1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 4 个软件包未被升级。
suwei@aiserver:~/桌面$ sudo pacman -S libxcb
sudo: pacman：找不到命令

**Comment by jianchang512** [comment]
sudo apt-get  -S libxcb

**Comment by jianchang512** [comment]
sudo apt-get install libxcb-cursor0

**Comment by suwei999** [comment]
我知道为什么没有这个命令了，我的conda的默认路径是/root/下面，代码也放到了root下面， 当切换root用户就无法找到pacman命令，因为这个需要调用桌面的程序
suwei@aiserver:~/桌面$ pacman 
XIO:  fatal IO error 22 (Invalid argument) on X server ":1"
      after 1128 requests (1128 known processed) with 0 events remaining.

> sudo apt-get install libxcb-cursor0
> 
> sudo apt-get install -S libxcb
> 
> qt5 兼容问题

**Comment by jianchang512** [comment]
这本来就是个桌面GUI软件啊。在桌面GUI下使用

**Comment by suwei999** [comment]
现在有个问题就是，我的虚拟环境是root目录下面，必须切换root用户才能激活虚拟环境运行程序，这个程序是不是只能以普通用户运行，centos应该没有这样的问题，我测试下

**Comment by dongxiaok** [comment]
项目是依赖了opencv-python==4.8.1.78的，我的也运行报错：
![image](https://github.com/jianchang512/pyvideotrans/assets/45843136/b56a89df-c847-4843-a60a-9b0b89ae3d15)

**Comment by suwei999** [comment]
> 项目是依赖了opencv-python==4.8.1.78的，我的也运行报错： ![image](https://private-user-images.githubusercontent.com/45843136/292745444-b56a89df-c847-4843-a60a-9b0b89ae3d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTkyOTMsIm5iZiI6MTcwMzQ5ODk5MywicGF0aCI6Ii80NTg0MzEzNi8yOTI3NDU0NDQtYjU2YTg5ZGYtYzg0Ny00ODQzLWE2MGEtOWIwYjg5YWUzZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEwMDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MmEzNmNiMTc1YWQ2OTNhYzQ2Zjg1ZTQ4ZTkxZDQxNWEyNjYxNGJhMjAzZmIxZjgwMzI4NDI1MjI3MDJhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5QGYLRbkttdpaK4FuSYMZPexUlhwJswE2FpbpAz86I)
有没有什么解决办法，你的是什么系统

**Comment by jianchang512** [comment]
cv2并没有使用到，你可以卸载掉

**Comment by jianchang512** [comment]
/videotrans/util/tools.py 顶部有个导入 cv2, 可以删掉

**Comment by dongxiaok** [comment]
> /videotrans/util/tools.py 顶部有个导入 cv2, 可以删掉

OK了，就是这个问题。删掉就好了：
![image](https://github.com/jianchang512/pyvideotrans/assets/45843136/743757a5-3ea4-4385-a806-384451856c45)

**Comment by dongxiaok** [comment]
> > 有没有什么解决办法，你的是什么系统
我是deepin系统，应该是基于debian的

**Comment by dongxiaok** [comment]
谢谢解答！问题应该就是这个了。大佬可以按照今天的问题，提交一下这个bug的代码。^_^

**Comment by suwei999** [comment]
ubuntu 20.04已经解决，确实是这个问题

**Comment by jianchang512** [comment]
ok
