### ISSUE TITLE
cuda 配置问题

### ISSUE THREAD

**Issue by q247574452** [jianchang512/pyvideotrans#149]
显示错误日志
ERROR:VideoTrans:[error] Please try upgrading the graphics card driver and reconfigure CUDA
配置截图
![VeryCapture_20231227174141cuda配置](https://github.com/jianchang512/pyvideotrans/assets/77397079/2af48acc-c68f-4506-ad65-0dadfc452709)
log日志全部
[video-20231227.log](https://github.com/jianchang512/pyvideotrans/files/13777423/video-20231227.log)

是因为我版本的问题？还是配置没弄好，cuda一次都没有用过，感觉cpu还是太慢了，

**Comment by jianchang512** [comment]
更新到最新版本 0.981，如何问题还存在，按以下方法尝试

1. 软件放在英文路径目录下，目录中不要含有空格，比如非 `programe file`
2. 选择一个英文名字的视频测试，同样视频所在路径也不要有中文和空格

如果已经是0.981版了，看起来是中文编码转码问题

**Comment by q247574452** [comment]
> 更新到最新版本 0.981，如何问题还存在，按以下方法尝试
> 
> 1. 软件放在英文路径目录下，目录中不要含有空格，比如非 `programe file`
> 2. 选择一个英文名字的视频测试，同样视频所在路径也不要有中文和空格
> 
> 如果已经是0.981版了，看起来是中文编码转码问题

最新版，
1 2 都设置了，保存目录也是纯英文，还是会有提示，
ERROR:VideoTrans:[error] Please try upgrading the graphics card driver and reconfigure CUDA 
最后视频文件是0kb，打不开，但是中翻译英后的英语音频文件是可以正常播放的，

**Comment by jianchang512** [comment]
最新的错误日志最后几十行带ffmpeg的看看

**Comment by q247574452** [comment]
> 最新的错误日志最后几十行带ffmpeg的看看

ffmpeg是什么意思，我不是很懂，要合成的视频原始文件？还是合成后的？还是文件下的ffmpeg.exe 请具体一点描述，

**Comment by jianchang512** [comment]
日志最后出现ffmpeg的地方，上下几十行复制

**Comment by q247574452** [comment]
> 日志最后出现ffmpeg的地方，上下几十行复制



上下十几行

INFO:VideoTrans:[1] end
INFO:VideoTrans:[2] end
INFO:VideoTrans:[3] end
INFO:VideoTrans:[4] end
INFO:VideoTrans:Origin:source_mp4_total_length=9515 + offset:880 = 10395
INFO:VideoTrans:ffprobe error:Command 'ffprobe  -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "C:/Intel/videotrans-0.981/_video_out/test1.1/novoice.mp4"' returned non-zero exit status 1.
INFO:VideoTrans:New videro:total_length=10395
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:dubbing & srt
ERROR:VideoTrans:[error]ffmpeg error: cmd=['ffmpeg', '-hide_banner', '-vsync', '0', '-hwaccel', 'cuda', '-hwaccel_output_format', 'cuda', '-y', '-i', 'C:\\Intel\\videotrans-0.981\\_video_out\\test1.1\\novoice.mp4', '-i', 'C:\\Intel\\videotrans-0.981\\_video_out\\test1.1\\en.wav', '-sub_charenc', 'UTF-8', '-f', 'srt', '-i', 'C:\\Intel\\videotrans-0.981\\_video_out\\test1.1\\en.srt', '-c:v', 'h264_nvenc', '-c:a', 'aac', '-c:s', 'mov_text', '-metadata:s:s:0', 'language=eng', 'C:\\Intel\\videotrans-0.981\\_video_out\\test1.1\\test1.1.mp4'],
errs="Error opening input: Invalid data found when processing input\\r\\nError opening input file C:\\Intel\\videotrans-0.981\\_video_out\\test1.1\\novoice.mp4.\\r\\nError opening input files: Invalid data found when processing input\\r\\n'"
ERROR:VideoTrans:[error] Please try upgrading the graphics card driver and reconfigure CUDA

如果不够可以打开
这个日志全部文件可以下载打开看看，
[video-20231227.log](https://github.com/jianchang512/pyvideotrans/files/13778619/video-20231227.log)

**Comment by jianchang512** [comment]
预编译版用这个覆盖原 sp.exe 试试

[解压覆盖原sp.exe文件.zip](https://github.com/jianchang512/pyvideotrans/files/13792615/sp.exe.zip)

**Comment by q247574452** [comment]
> 预编译版用这个覆盖原 sp.exe 试试
> 
> [解压覆盖原sp.exe文件.zip](https://github.com/jianchang512/pyvideotrans/files/13792615/sp.exe.zip)

覆盖之后，最终视频是无声音的，只有原始视频去掉声音的画面，
log如下参考

INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:Video speed -0.65
ERROR:VideoTrans:[error][except] Please try upgrading the graphics card driver and reconfigure CUDA
INFO:VideoTrans:[1] end
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:d:/program files/myfile/视频/300/videomix/test

**Comment by jianchang512** [comment]
再覆盖试下，看看输出什么错误信息
[覆盖.zip](https://github.com/jianchang512/pyvideotrans/files/13796953/default.zip)

**Comment by q247574452** [comment]
> 再覆盖试下，看看输出什么错误信息 [覆盖.zip](https://github.com/jianchang512/pyvideotrans/files/13796953/default.zip)

显示如下，我看懂了文件名过长，但是都是自动设置的没有修改文件名哦，

4
00:00:06,000 --> 00:00:10,000
For example, a friend recommended me a knife cover.
INFO:VideoTrans:Translate end
INFO:VideoTrans:等待修改配音字幕/点击继续
INFO:VideoTrans:59秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确
INFO:VideoTrans:58秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确
INFO:VideoTrans:57秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确
INFO:VideoTrans:56秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确
INFO:VideoTrans:55秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确
INFO:VideoTrans:54秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确
INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:Video speed -0.69
ERROR:VideoTrans:[error][except] [WinError 206] 文件名或扩展名太长。
INFO:VideoTrans:[1] end
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:C:/Intel/videotrans-0.981/_video_out/test1.1

**Comment by jianchang512** [comment]
软件放其他盘下试试，D E F

**Comment by q247574452** [comment]
> 软件放其他盘下试试，D E F

放其他盘 无空格 中文 测试两个替换sp.exe 都没成功，一直卡在执行中 无法进行下去，
日志目录文件参考
[Uploading video-20231230.log…]()

**Comment by jianchang512** [comment]
更新显卡驱动，再去安装最新的cuda12.3试试

**Comment by q247574452** [comment]
> 更新显卡驱动，再去安装最新的cuda12.3试试

已经是最新的显卡驱动了哦，cuda version显示也是最新12.3，不知道别人能不能用。实在是想不出来到底是哪里设置错了。
