### ISSUE TITLE
split no voice videoerror

### ISSUE THREAD

**Issue by banditnew1978** [jianchang512/pyvideotrans#151]
when i use voice acceleration or video slow i am getting this error.When I do these without selecting everything ok.dubbing ok

i get only en.srt,en.wav,tr.srt and it stops working

https://imgyukle.com/i/yXb6Ue

**Comment by jianchang512** [comment]
Screenshot 404 cannot be viewed. Please upload the latest logs from the logs directory where the error occurred

**Comment by banditnew1978** [comment]
this error when i check cuda and video slow and create only en.srt,en.wav,tr.srt
infinity this error not stopping
INFO:VideoTrans:test split no voice videoerror


INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:Starting
INFO:VideoTrans:Processing 1/1
INFO:VideoTrans:/home/banditnew/Videos/4K Video Downloader+/_video_out/test
INFO:VideoTrans:audio and video split
ERROR:VideoTrans:[error]ffmpeg error: cmd=['ffmpeg', '-hide_banner', '-vsync', '0', '-hwaccel', 'cuda', '-hwaccel_output_format', 'cuda', '-y', '-i', '/home/banditnew/Videos/4K Video Downloader+/test.mkv', '-an', '-c:v', 'h264_nvenc', '/home/banditnew/Videos/4K Video Downloader+/_video_out/test/novoice.mp4'],
errs='"'
ERROR:VideoTrans:[error] Please try upgrading the graphics card driver and reconfigure CUDA
ERROR:VideoTrans:[error] Please try upgrading the graphics card driver and reconfigure CUDA
INFO:VideoTrans:start speech to text
INFO:VideoTrans:Model:base
INFO:VideoTrans:srt:11
INFO:VideoTrans:1
00:00:00,000 --> 00:00:03,680
First reaction to the guidance that was issued Friday by the Treasury.

2
00:00:05,440 --> 00:00:09,360
Disappointing. I think many of us feel it did not fall to the law.

3
00:00:10,160 --> 00:00:15,120
The people who were primarily responsible for writing it. People like Senator Carper and

4
00:00:15,120 --> 00:00:21,360
Senator Manchin have said so. So there is a great deal of disappointment. That being said,

5
00:00:22,320 --> 00:00:25,680
you know, there's a lot of work still to be done. It certainly makes Europe

6
00:00:26,080 --> 00:00:30,000
work much more attractive than in the United States in the near term.

7
00:00:30,480 --> 00:00:35,040
So, but there is now a comment period and plug-all aggressively

8
00:00:35,680 --> 00:00:40,320
participate in the comment period. Yeah, there is a 60-day comment period and I can imagine

9
00:00:40,320 --> 00:00:45,440
there will be intense lobbying andy, but can you give us some specifics on why this hydrogen

10
00:00:45,440 --> 00:00:51,440
credits, which does provide what $3 per kilogram of production, why it won't

11
00:00:51,440 --> 00:00:59,839
firm more domestic production? Yeah, so, you know, out of nowhere, there were three editions
INFO:VideoTrans:Wait to modify original language subtitles / continue
INFO:VideoTrans:60 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:59 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:58 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
I
INFO:VideoTrans:1 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:1
00:00:00,000 --> 00:00:03,680
Hazine'nin Cuma günü yayınladığı rehbere ilk tepkiler geldi.
INFO:VideoTrans:2
00:00:05,440 --> 00:00:09,360
Hayal kırıklığı. Sanırım çoğumuz bunun yasalara uymadığını düşünüyoruz.
INFO:VideoTrans:3
00:00:10,160 --> 00:00:15,120
Bunu yazmaktan birincil olarak sorumlu olan kişiler. Senatör Carper gibi insanlar ve
INFO:VideoTrans:4
00:00:15,120 --> 00:00:21,360
Senatör Manchin öyle söyledi. Dolayısıyla büyük bir hayal kırıklığı yaşanıyor. Söyleniyor ki,
INFO:VideoTrans:5
00:00:22,320 --> 00:00:25,680
biliyorsun, hala yapılması gereken çok iş var. Kesinlikle Avrupa'yı
INFO:VideoTrans:6
00:00:26,080 --> 00:00:30,000
yakın vadede Amerika Birleşik Devletleri'ndekinden çok daha cazip işler.
INFO:VideoTrans:7
00:00:30,480 --> 00:00:35,040
Yani, ancak artık bir yorum dönemi var ve agresif bir şekilde hepsini tamamlayın
INFO:VideoTrans:8
00:00:35,680 --> 00:00:40,320
Yorum dönemine katılın. Evet, 60 günlük bir yorum süresi var ve hayal edebiliyorum
INFO:VideoTrans:9
00:00:40,320 --> 00:00:45,440
Yoğun bir lobi çalışması olacak Andy, ama bize bu hidrojenin neden olduğuna dair biraz ayrıntı verebilir misin?
INFO:VideoTrans:10
00:00:45,440 --> 00:00:51,440
Üretimin kilogramı başına 3 doları sağlayan krediler neden sağlanmıyor?
INFO:VideoTrans:11
00:00:51,440 --> 00:00:59,839
Daha fazla yerli üretim mi sağlam? Evet, birdenbire üç baskı çıktı
INFO:VideoTrans:Translation end
INFO:VideoTrans:1
00:00:00,000 --> 00:00:03,680
Hazine'nin Cuma günü yayınladığı rehbere ilk tepkiler geldi.

2
00:00:05,440 --> 00:00:09,360
Hayal kırıklığı. Sanırım çoğumuz bunun yasalara uymadığını düşünüyoruz.

3
00:00:10,160 --> 00:00:15,120
Bunu yazmaktan birincil olarak sorumlu olan kişiler. Senatör Carper gibi insanlar ve

4
00:00:15,120 --> 00:00:21,360
Senatör Manchin öyle söyledi. Dolayısıyla büyük bir hayal kırıklığı yaşanıyor. Söyleniyor ki,

5
00:00:22,320 --> 00:00:25,680
biliyorsun, hala yapılması gereken çok iş var. Kesinlikle Avrupa'yı

6
00:00:26,080 --> 00:00:30,000
yakın vadede Amerika Birleşik Devletleri'ndekinden çok daha cazip işler.

7
00:00:30,480 --> 00:00:35,040
Yani, ancak artık bir yorum dönemi var ve agresif bir şekilde hepsini tamamlayın

8
00:00:35,680 --> 00:00:40,320
Yorum dönemine katılın. Evet, 60 günlük bir yorum süresi var ve hayal edebiliyorum

9
00:00:40,320 --> 00:00:45,440
Yoğun bir lobi çalışması olacak Andy, ama bize bu hidrojenin neden olduğuna dair biraz ayrıntı verebilir misin?

10
00:00:45,440 --> 00:00:51,440
Üretimin kilogramı başına 3 doları sağlayan krediler neden sağlanmıyor?

11
00:00:51,440 --> 00:00:59,839
Daha fazla yerli üretim mi sağlam? Evet, birdenbire üç baskı çıktı
INFO:VideoTrans:Translate end
INFO:VideoTrans:Wait to modify the dubbed subtitles / click continue
INFO:VideoTrans:59Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate

INFO:VideoTrans:1Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:0Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror
INFO:VideoTrans:test split no voice videoerror

**Comment by banditnew1978** [comment]
this error when i check only video slow and create only en.srt,en.wav,tr.srt,novoice.mp4



INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:Starting
INFO:VideoTrans:Processing 1/1
INFO:VideoTrans:/home/banditnew/Videos/4K Video Downloader+/_video_out/test
INFO:VideoTrans:audio and video split
INFO:VideoTrans:start speech to text
INFO:VideoTrans:Model:base
INFO:VideoTrans:srt:11
INFO:VideoTrans:1
00:00:00,000 --> 00:00:03,680
First reaction to the guidance that was issued Friday by the Treasury.

2
00:00:05,440 --> 00:00:09,360
Disappointing. I think many of us feel it did not fall to the law.

3
00:00:10,160 --> 00:00:15,120
The people who were primarily responsible for writing it. People like Senator Carper and

4
00:00:15,120 --> 00:00:21,360
Senator Manchin have said so. So there is a great deal of disappointment. That being said,

5
00:00:22,320 --> 00:00:25,680
you know, there's a lot of work still to be done. It certainly makes Europe

6
00:00:26,080 --> 00:00:30,000
work much more attractive than in the United States in the near term.

7
00:00:30,480 --> 00:00:35,040
So, but there is now a comment period and plug-all aggressively

8
00:00:35,680 --> 00:00:40,320
participate in the comment period. Yeah, there is a 60-day comment period and I can imagine

9
00:00:40,320 --> 00:00:45,440
there will be intense lobbying andy, but can you give us some specifics on why this hydrogen

10
00:00:45,440 --> 00:00:51,440
credits, which does provide what $3 per kilogram of production, why it won't

11
00:00:51,440 --> 00:00:59,839
firm more domestic production? Yeah, so, you know, out of nowhere, there were three editions
INFO:VideoTrans:Wait to modify original language subtitles / continue
INFO:VideoTrans:60 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:59 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:58 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:57 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:56 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:55 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:54 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:53 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:52 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:51 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:50 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:49 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:48 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:47 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:46 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:45 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:44 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:43 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:42 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:41 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:40 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:39 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:38 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:37 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:36 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:35 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:34 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:33 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:32 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:31 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:30 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:29 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:28 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:27 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:26 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:25 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:24 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:23 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:22 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:21 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:20 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:19 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:18 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:17 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:16 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:15 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:14 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:13 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:12 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:11 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:10 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:9 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:8 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:7 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:6 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:5 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:4 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:3 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:2 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:1 Automatically translated in seconds, you can stop the countdown to modify the subtitles so that the translation is more accurate
INFO:VideoTrans:1
00:00:00,000 --> 00:00:03,680
Hazine'nin Cuma günü yayınladığı rehbere ilk tepkiler geldi.
INFO:VideoTrans:2
00:00:05,440 --> 00:00:09,360
Hayal kırıklığı. Sanırım çoğumuz bunun yasalara uymadığını düşünüyoruz.
INFO:VideoTrans:3
00:00:10,160 --> 00:00:15,120
Bunu yazmaktan birincil olarak sorumlu olan kişiler. Senatör Carper gibi insanlar ve
INFO:VideoTrans:4
00:00:15,120 --> 00:00:21,360
Senatör Manchin öyle söyledi. Dolayısıyla büyük bir hayal kırıklığı yaşanıyor. Söyleniyor ki,
INFO:VideoTrans:5
00:00:22,320 --> 00:00:25,680
biliyorsun, hala yapılması gereken çok iş var. Kesinlikle Avrupa'yı
INFO:VideoTrans:6
00:00:26,080 --> 00:00:30,000
yakın vadede Amerika Birleşik Devletleri'ndekinden çok daha cazip işler.
INFO:VideoTrans:7
00:00:30,480 --> 00:00:35,040
Yani, ancak artık bir yorum dönemi var ve agresif bir şekilde hepsini tamamlayın
INFO:VideoTrans:8
00:00:35,680 --> 00:00:40,320
Yorum dönemine katılın. Evet, 60 günlük bir yorum süresi var ve hayal edebiliyorum
INFO:VideoTrans:9
00:00:40,320 --> 00:00:45,440
Yoğun bir lobi çalışması olacak Andy, ama bize bu hidrojenin neden olduğuna dair biraz ayrıntı verebilir misin?
INFO:VideoTrans:10
00:00:45,440 --> 00:00:51,440
Üretimin kilogramı başına 3 doları sağlayan krediler neden sağlanmıyor?
INFO:VideoTrans:11
00:00:51,440 --> 00:00:59,839
Daha fazla yerli üretim mi sağlam? Evet, birdenbire üç baskı çıktı
INFO:VideoTrans:Translation end
INFO:VideoTrans:1
00:00:00,000 --> 00:00:03,680
Hazine'nin Cuma günü yayınladığı rehbere ilk tepkiler geldi.

2
00:00:05,440 --> 00:00:09,360
Hayal kırıklığı. Sanırım çoğumuz bunun yasalara uymadığını düşünüyoruz.

3
00:00:10,160 --> 00:00:15,120
Bunu yazmaktan birincil olarak sorumlu olan kişiler. Senatör Carper gibi insanlar ve

4
00:00:15,120 --> 00:00:21,360
Senatör Manchin öyle söyledi. Dolayısıyla büyük bir hayal kırıklığı yaşanıyor. Söyleniyor ki,

5
00:00:22,320 --> 00:00:25,680
biliyorsun, hala yapılması gereken çok iş var. Kesinlikle Avrupa'yı

6
00:00:26,080 --> 00:00:30,000
yakın vadede Amerika Birleşik Devletleri'ndekinden çok daha cazip işler.

7
00:00:30,480 --> 00:00:35,040
Yani, ancak artık bir yorum dönemi var ve agresif bir şekilde hepsini tamamlayın

8
00:00:35,680 --> 00:00:40,320
Yorum dönemine katılın. Evet, 60 günlük bir yorum süresi var ve hayal edebiliyorum

9
00:00:40,320 --> 00:00:45,440
Yoğun bir lobi çalışması olacak Andy, ama bize bu hidrojenin neden olduğuna dair biraz ayrıntı verebilir misin?

10
00:00:45,440 --> 00:00:51,440
Üretimin kilogramı başına 3 doları sağlayan krediler neden sağlanmıyor?

11
00:00:51,440 --> 00:00:59,839
Daha fazla yerli üretim mi sağlam? Evet, birdenbire üç baskı çıktı
INFO:VideoTrans:Translate end
INFO:VideoTrans:Wait to modify the dubbed subtitles / click continue
INFO:VideoTrans:59Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:58Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:57Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:56Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:55Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:54Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:53Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:52Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:51Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:50Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:49Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:48Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:47Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:46Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:45Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:44Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:43Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:42Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:41Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:40Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:39Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:38Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:37Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:36Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:35Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:34Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:33Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:32Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:31Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:30Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:29Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:28Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:27Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:26Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:25Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:24Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:23Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:22Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:21Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:20Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:19Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:18Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:17Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:16Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:15Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:14Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:13Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:12Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:11Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:10Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:9Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:8Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:7Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:6Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:5Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:4Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:3Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:2Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:1Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:0Automatically merge in seconds, you can stop the countdown to modify the subtitles so that the dubbing is more accurate
INFO:VideoTrans:Video speed -0.76
ERROR:VideoTrans:[error]ffmpeg error: cmd=['ffmpeg', '-hide_banner', '-vsync', '0', '-y', '-ss', '0', '-to', '00:00:03.680', '-i', '/home/banditnew/Videos/4K Video Downloader+/_video_out/test/novoice.mp4', '-vf', 'setpts=1.31*PTS', '-c:v', 'libx264', '-crf', '0', '/home/banditnew/pyvideotrans/tmp/test/novice-0-clip.mp4'],
errs='Error splitting the argument list: Option not found\\n"'
INFO:VideoTrans:ffmpeg error:errs='Error splitting the argument list: Option not found\\n"'
INFO:VideoTrans:[1] end
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:/home/banditnew/Videos/4K Video Downloader+/_video_out/test

**Comment by jianchang512** [comment]
Try using this to overwrite the original sp.exe in the pre compiled version

[Decompression overlay zip](https://github.com/jianchang512/pyvideotrans/files/13792615/sp.exe.zip)
