### ISSUE TITLE
每一步都按提示来的，还是有错

### ISSUE THREAD

**Issue by Guardemail** [jianchang512/pyvideotrans#154]
python sp.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
**Error accessing Windows registry: [WinError 2] The system cannot find the file specified**
res.status_code=200
res=<Response [200]>
d={'version': '0.982', 'version_num': 982}
QThread: Destroyed while thread is still running

**Comment by jianchang512** [comment]
项目/videotrans/util/tools.py 190行--205行，这些代码删掉试试
```
        # 打开 Windows 注册表
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER,
                            r'Software\Microsoft\Windows\CurrentVersion\Internet Settings') as key:
            # 读取代理设置
            proxy_enable, _ = winreg.QueryValueEx(key, 'ProxyEnable')
            proxy_server, _ = winreg.QueryValueEx(key, 'ProxyServer')
            if proxy_enable == 1 and proxy_server:
                # 是否需要设置代理
                if proxy_server.startswith("http") or proxy_server.startswith('sock'):
                    os.environ['http_proxy'] = proxy_server
                    os.environ['https_proxy'] =proxy_server
                else:
                    proxy_server= "http://"+proxy_server
                    os.environ['http_proxy'] =proxy_server
                    os.environ['https_proxy'] =proxy_server
                return proxy_server
```

window哪个版本

**Comment by Guardemail** [comment]
Microsoft Windows [Version 10.0.22621.2861]
after commenting out the lines, it no long shows that error msg. thanks

**Comment by Guardemail** [comment]
还是不行啊
》》
pygame 2.5.2 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
res.status_code=200
res=<Response [200]>
d={'version': '0.983', 'version_num': 983}
noextname=CPU Cooling,target_dir=C:/Users/guard/Downloads/_video_out/CPU Cooling
text='Ended click to open C:/Users/guard/Downloads/_video_out/CPU Cooling'
C:/Users/guard/Downloads/_video_out/CPU Cooling/novoice.mp4
C:/Users/guard/Downloads/_video_out/CPU Cooling/en.wav
C:/Users/guard/Downloads/_video_out/CPU Cooling/zh-cn.srt
cmd=['-y', '-i', 'C:/Users/guard/Downloads/_video_out/CPU Cooling/novoice.mp4', '-i', 'C:/Users/guard/Downloads/_video_out/CPU Cooling/en.wav', '-filter_complex', '[0:a][1:a]amerge=inputs=2[aout]', '-map', '0:v', '-map', '[aout]', '-c:v', 'libx264', '-c:a', 'aac', 'C:/LAI/pyvideotrans/tmp/1704000733.4779186.mp4']
runffmpeg: cmd=['ffmpeg', '-hide_banner', '-vsync', '0', '-y', '-i', 'C:/Users/guard/Downloads/_video_out/CPU Cooling/novoice.mp4', '-i', 'C:/Users/guard/Downloads/_video_out/CPU Cooling/en.wav', '-filter_complex', '[0:a][1:a]amerge=inputs=2[aout]', '-map', '0:v', '-map', '[aout]', '-c:v', 'libx264', '-c:a', 'aac', 'C:/LAI/pyvideotrans/tmp/1704000733.4779186.mp4']
b"Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:/Users/guard/Downloads/_video_out/CPU Cooling/novoice.mp4':\r\n  Metadata:\r\n    major_brand     : isom\r\n    minor_version   : 512\r\n    compatible_brands: isomiso2avc1mp41\r\n    encoder         : Lavf58.29.100\r\n  Duration: 00:10:04.67, start: 0.000000, bitrate: 1937 kb/s\r\n    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 1936 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)\r\n    Metadata:\r\n      handler_name    : ISO Media file produced by Google Inc. Created on: 08/25/2023.\r\nGuessed Channel Layout for Input Stream #1.0 : mono\r\nInput #1, wav, from 'C:/Users/guard/Downloads/_video_out/CPU Cooling/en.wav':\r\n  Metadata:\r\n    encoder         : Lavf58.29.100\r\n  Duration: 00:10:04.67, bitrate: 705 kb/s\r\n    Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s\r\nStream specifier ':a' in filtergraph description [0:a][1:a]amerge=inputs=2[aout] matches no streams.\r\n"
False
cmd=['-y', '-i', 'C:/LAI/pyvideotrans/tmp/1704000733.4779186.mp4', '-vf', 'subtitles=C\\\\:/Users/guard/Downloads/_video_out/CPU Cooling/zh-cn.srt', 'C:/Users/guard/Videos/pyvideotrans/hebing-novoice.mp4/novoice.mp4.mp4']
runffmpeg: cmd=['ffmpeg', '-hide_banner', '-vsync', '0', '-y', '-i', 'C:/LAI/pyvideotrans/tmp/1704000733.4779186.mp4', '-vf', 'subtitles=C\\\\:/Users/guard/Downloads/_video_out/CPU Cooling/zh-cn.srt', 'C:/Users/guard/Videos/pyvideotrans/hebing-novoice.mp4/novoice.mp4.mp4']
b**'C:/LAI/pyvideotrans/tmp/1704000733.4779186.mp4: No such file or directory\r\n'**
False
noextname=CPU Cooling,target_dir=c:/users/guard/downloads/_video_out/CPU Cooling
text='Ended click to open c:/users/guard/downloads/_video_out/CPU Cooling'

最后没有什么合成的文件。

**Comment by jianchang512** [comment]
无法复现，暂时不要选择 cuda 了
