### ISSUE TITLE
最新0.983 cuda错误反馈

### ISSUE THREAD

**Issue by q247574452** [jianchang512/pyvideotrans#155]
最新版，合成最后视频没有声音，只有画面，
错误日志显示如下，

INFO:VideoTrans:text to speech speed +30%
INFO:VideoTrans:Video speed -0.69
ERROR:VideoTrans:[error][except] [WinError 206] 文件名或扩展名太长。
INFO:VideoTrans:[1] end
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:d:/program files/myfile/视频/300/videomix/test1.1

**Comment by jianchang512** [comment]
视频所在路径不要那么深，直接放在 D:/sp/xxx.mp4 这样再试试

**Comment by q247574452** [comment]
> 视频所在路径不要那么深，直接放在 D:/sp/xxx.mp4 这样再试试


还是一样提示，
我还设置根目录了，还有设置D:/sp/xxx.mp4 结果反馈回来都是一样，

INFO:VideoTrans:Video speed -0.69
ERROR:VideoTrans:[error][except] [WinError 206] 文件名或扩展名太长。
INFO:VideoTrans:[1] end
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:d:/sp/test1.1

我的完成目录文件下 只有四个文件，我记得之前正常结果有六个吧，
![image](https://github.com/jianchang512/pyvideotrans/assets/77397079/552d1694-0df7-4e5f-b4ef-037885f7000c)

**Comment by q247574452** [comment]
> > 视频所在路径不要那么深，直接放在 D:/sp/xxx.mp4 这样再试试
> 
> 还是一样提示， 我还设置根目录了，还有设置D:/sp/xxx.mp4 结果反馈回来都是一样，
> 
> INFO:VideoTrans:Video speed -0.69 ERROR:VideoTrans:[error][except] [WinError 206] 文件名或扩展名太长。 INFO:VideoTrans:[1] end INFO:VideoTrans:Dubbing ended INFO:VideoTrans:Start last step INFO:VideoTrans:d:/sp/test1.1
> 
> 我的完成目录文件下 只有四个文件，我记得之前正常结果有六个吧，
novoice 文件只有画面没有声音，
 ![image](https://private-user-images.githubusercontent.com/77397079/293496736-552d1694-0df7-4e5f-b4ef-037885f7000c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTE5NDEsIm5iZiI6MTcwNDAxMTY0MSwicGF0aCI6Ii83NzM5NzA3OS8yOTM0OTY3MzYtNTUyZDE2OTQtMGRmNy00ZTVmLWI0ZWYtMDM3ODg1ZjcwMDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA4MzQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMGM4NTc1MmY5ZjRlMGMyNGE2ODY3YWJmZjVkMWFjYWUwYjJiMTU3MGMzNGUyMmM4ZmQ3NjJmYzJjZmYwOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NTd72FPMiWjfArDEVgTN3Ak9nrxvo5YU2PLwvSV7ffw)

**Comment by jianchang512** [comment]
1. 源码部署还是预编译，换成预编译版本
2. 取消选中“视频慢速”，是否正常
3. 先清空日志，然后执行，上传完整日志

**Comment by q247574452** [comment]
预编译版 就是exe那个，取消慢速了，只勾选cuda，
输出结果有六个文件，但是视频只有画面无声音，
新的日志如下
[video-20231231.log](https://github.com/jianchang512/pyvideotrans/files/13800700/video-20231231.log)

**Comment by q247574452** [comment]
不勾选 cuda 就能正使用  预编译版本

**Comment by jianchang512** [comment]
显卡什么型号

**Comment by q247574452** [comment]
> 显卡什么型号

nvidia gtx 1050ti

**Comment by jianchang512** [comment]
0.986.1版本再试试
