### ISSUE TITLE
开启cuda加速无法生成配音视频

### ISSUE THREAD

**Issue by infernoshoot** [jianchang512/pyvideotrans#157]
![image](https://github.com/jianchang512/pyvideotrans/assets/29793108/940c81a2-263e-4182-b015-fde67a467334)

你好 開啟cuda加速無法生成配音視頻 只會生成音檔和字幕檔
![image](https://github.com/jianchang512/pyvideotrans/assets/29793108/529118be-6c2e-4475-a549-aeabab329949)

**Comment by jianchang512** [comment]
logs下日志信息

**Comment by infernoshoot** [comment]
INFO:VideoTrans:offset=176>0，end add video frame 176 ms
ERROR:VideoTrans:[error][except] [WinError 206] 檔名或副檔名太長。
ERROR:VideoTrans:[error]Failed to add extended video frame at the end, will remain unchanged, truncate audio, and do not extend video
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:c:/users/user/desktop/66/ps

**Comment by infernoshoot** [comment]
> 日誌下日誌訊息



> 日誌下日誌訊息

INFO:VideoTrans:offset=176>0，end add video frame 176 ms
ERROR:VideoTrans:[error][except] [WinError 206] 檔名或副檔名太長。
ERROR:VideoTrans:[error]Failed to add extended video frame at the end, will remain unchanged, truncate audio, and do not extend video
INFO:VideoTrans:Dubbing ended
INFO:VideoTrans:Start last step
INFO:VideoTrans:c:/users/user/desktop/66/ps

**Comment by jianchang512** [comment]
[覆盖原sp.exe试试.zip](https://github.com/jianchang512/pyvideotrans/files/13804088/sp.exe.zip)

**Comment by infernoshoot** [comment]
第一次只会生成字幕档跟音档
 我又在第一次的基础上再重新生成一次又可以了

**Comment by jianchang512** [comment]
覆盖了吗

**Comment by infernoshoot** [comment]
> 覆盖了

覆盖了

**Comment by jianchang512** [comment]
删掉已生成的所有文件，然后重新测试个看看

**Comment by infernoshoot** [comment]
> 删掉已生成的所有文件，然后重新测试个看看

还是一样
需要先生成一次然后再重新指定一次视频跟字幕档他才会生成配音视频
