### ISSUE TITLE
无法正常翻译视频

### ISSUE THREAD

**Issue by suwei999** [jianchang512/pyvideotrans#158]
在使用过程中，无法正常翻译视频，
操作系统  ubuntu 20.04

详细日志如下:
text='已完成，点击打开 /home/suwei/桌面/_video_out/ShortGPT_intra'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

(org.gnome.Nautilus:295157): IBUS-WARNING **: 12:43:35.625: Unable to connect to ibus: 无法连接： 拒绝连接
Nautilus-Share-Message: 12:43:35.667: Called "net usershare info" but it failed: 执行子进程“net”失败（No such file or directory）
VLC media player 3.0.9.2 Vetinari (revision 3.0.9.2-0-gd4c1aefe4d)
[0000556726a2dd30] vlcpulse audio output error: PulseAudio server connection failure: 拒绝连接
[00005567269725c0] main libvlc: 正在以默认界面运行 vlc。使用“cvlc”可以无界面模式使用 vlc。
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[00007f735cc0f390] main demux error: option sub-original-fps does not exist
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by jianchang512** [comment]
看起来是qt配置问题
重新拉取源码再重新配置试试

**Comment by suwei999** [comment]
经过测试，应该是VLC的问题，我不添加字幕就不会有问题，可正常使用，经过查询相关资料发现VLC只支持 -60-60，若字幕和配音严重不符也会出现这个问题，十分感谢
