### ISSUE TITLE
key/api/key of elevenlabs.io

### ISSUE THREAD

**Issue by komangulo** [jianchang512/pyvideotrans#159]
hello ! great project my friend !
would it be possible the translation and dubbing with the key/api/key of elevenlabs.io?

你好！我的朋友，这个项目很棒！
可以用 elevenlabs.io 的 key/api/key 进行翻译和配音吗？

**Comment by jianchang512** [comment]
The translation uses requests to request Google API and then extracts it. If it is too frequent, it may be restricted.

**Comment by komangulo** [comment]
it would still be possible to use the elevenlabs translation? If necessary, each user can change the google api.

**Comment by jianchang512** [comment]
Sorry, wrong reply. The speech synthesis of elevenlabs.io could be considered to be added, but this site does not seem to have a translation service

**Comment by komangulo** [comment]
that's exactly what I'm talking about, the voice of elevenlabs.
For video dubbing services they are fantastic. :D
