### ISSUE TITLE
我使用了代理软件，但是还是提示 error Google Api

### ISSUE THREAD

**Issue by CMG-CEO** [jianchang512/pyvideotrans#16]
我的代理软件的IP地址是 2605:52c0:1001:472:e853:44ff:fe39:ba6a
可以正常使用google翻译
输入后，还是提示
Please check the connectivity of the proxy or consider changing the IP address.

**Comment by jianchang512** [comment]
有ipv4代理地址吗，使用v4

**Comment by CMG-CEO** [comment]
也不行，使用本机ipv4在线查询的地址也不行
![微信图片_20231107094833](https://github.com/jianchang512/pyvideotrans/assets/64698981/61e2ee97-5f91-4547-bde6-529adb558192)

> 有ipv4代理地址吗，使用v4

**Comment by jianchang512** [comment]
没测试过 ipv6 ，或许存在问题。

新版加了百度翻译，可以去申请个百度key，免费的也足够用了
https://fanyi-api.baidu.com/product/11

**Comment by Copy2Translator** [comment]
> 没测试过 ipv6 ，或许存在问题。
> 
> 新版加了百度翻译，可以去申请个百度key，免费的也足够用了 https://fanyi-api.baidu.com/product/11

能不能增加 deepL free api ，百度白嫖额度限制的废了，每月只有5w字符免费使用

**Comment by jianchang512** [comment]
deepL free api
这个国内好像注册不了吧, 免费也得绑定信用卡，不支持国区。api 也是用不了的
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/763aaa3b-ce05-475a-ab88-ef381e8b81c6)


可以挂代理用google。或者尝试使用 baidu(noKey) 这个翻译选项，爬虫抓取百度公开接口

**Comment by Copy2Translator** [comment]
> deepL free api 这个国内好像注册不了吧, 免费也得绑定信用卡，不支持国区。api 也是用不了的 ![image](https://user-images.githubusercontent.com/3378335/281334138-763aaa3b-ce05-475a-ab88-ef381e8b81c6.png)
> 
> 可以挂代理用google。或者尝试使用 baidu(noKey) 这个翻译选项，爬虫抓取百度公开接口

是不支持国区，但是可以走深水宝弄一个free api用，谷歌的翻译现在一言难尽啊

**Comment by jianchang512** [comment]
这个可以加下

**Comment by jianchang512** [comment]
deepl 加了
