### ISSUE TITLE
报错 "symbol lookup error libcudnn_cnn_infer.so.8: undefined symbol" ，自动退出 

### ISSUE THREAD

**Issue by ilihu** [jianchang512/pyvideotrans#160]
OS: ubuntu 20.04 
python: python3.10
NVIDIA-SMI 535.129.03             
Driver Version: 535.129.03   
CUDA Version: 12.2
显卡型号: GTX 1660s 

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_18:23:41_PST_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0
```

```
$ cat /usr/local/cuda/include/cudnn_version.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 3
#define CUDNN_PATCHLEVEL 2
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#endif /* CUDNN_VERSION_H */
```

无论开不开启 cuda  ，程序都会自动退出，报错如下:

> python: symbol lookup error:  "../anaconda3/envs/pyvideotrans/lib/python3.10/site-packages/torch/lib/../../nvidia/cudnn/lib/libcudnn_cnn_infer.so.8: undefined symbol: _Z20traceback_iretf_implPKcRKN5cudnn16InternalStatus_tEb, version libcudnn_ops_infer.so.8
"

设置如下

![2024-01-03_12-25](https://github.com/jianchang512/pyvideotrans/assets/96740327/b74227c5-ce26-48b7-b980-44cfbdbc7ee2)

**Comment by jianchang512** [comment]
取消 cuda 勾选试试，看报错是cudnn问题

**Comment by ilihu** [comment]
> 取消 cuda 勾选试试，看报错是cudnn问题

取消勾选依旧闪退，报错相同

**Comment by jianchang512** [comment]
pip install nvidia-cublas-cu11 nvidia-cudnn-cu11

安装下试试，如果还不行，先卸载 torch, 然后 去 https://pytorch.org/get-started/locally/ 根据你的环境重新安装 torch

**Comment by ilihu** [comment]
大概因为我CUDA的版本是 12.2 更新 

```
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```

后，再run就不闪退了 ?
