### ISSUE TITLE
最新版986.1

### ISSUE THREAD

**Issue by q247574452** [jianchang512/pyvideotrans#162]
最后合成的文件夹下只有四个文件，没有视频，你看还需要设置什么？

![image](https://github.com/jianchang512/pyvideotrans/assets/77397079/6347085a-798b-46da-ade9-1b3349cdf92c)

日志参考
[video-20240103.log](https://github.com/jianchang512/pyvideotrans/files/13819609/video-20240103.log)

**Comment by jianchang512** [comment]
生成的这几个文件尺寸都多大，2个wav能播放吗

看不出错误。重试下吧

**Comment by q247574452** [comment]
> > 生成的这几个文件尺寸都多大，2个wav能播放吗
> > 看不出错误。重试下吧
> 
两个文件都是可以播放的，就是视频找不到了，

还有就是单独字幕创建配音，勾选cuda合成之后没有音频，只有srt文字，不勾选cuda还是一样的结果，显示下边，不知道什么原因， INFO:VideoTrans:srt error:not enough values to unpack (expected 2, got 1) INFO:VideoTrans:Dubbing ended INFO:VideoTrans:Ended INFO:VideoTrans:C:/Users/xiaobao/Videos/pyvideotrans/only_dubbing/20240105-124013
