### ISSUE TITLE
upload the video from a youtube link

### ISSUE THREAD

**Issue by komangulo** [jianchang512/pyvideotrans#163]
Hello ! is it possible to upload the video directly from a youtube link ?
thank you very much friend.

你好！可以直接从 Youtube 链接上传视频吗？
非常感谢你，朋友。

**Comment by jianchang512** [comment]
No such plan is available at the moment. You can try using other YouTube downloading tools to download the video for now.

**Comment by komangulo** [comment]
Thank you very much!
I appreciate the addition to the new version, I meant to insert the video from a youtube link and not have to download but this is also valuable.
Best regards my friend.
