### ISSUE TITLE
字幕翻译存在大量缺失

### ISSUE THREAD

**Issue by Johnnyhhhhh** [jianchang512/pyvideotrans#164]
![QQ截图20240105200406](https://github.com/jianchang512/pyvideotrans/assets/87590242/c15d2ab8-2fb9-4bf8-b2db-22c2eb013de3)
每当需要翻译的文字更多的时候，翻译的结果就会有非常多的遗漏

**Comment by jianchang512** [comment]
测试未复现，是否使用的免费api key，如果是的话，限制一分钟3次请求，可能出现该问题，更换付费openai账号或者第三方api
