### ISSUE TITLE
gpt翻译怎么使用？

### ISSUE THREAD

**Issue by mjtlyzbsy** [jianchang512/pyvideotrans#165]
申请到的api不会调用，该怎么设置
![image](https://github.com/jianchang512/pyvideotrans/assets/73173384/2602c13a-0e35-4b31-924d-2209d7e0cab3) 
![image](https://github.com/jianchang512/pyvideotrans/assets/73173384/4a8bba9e-7f60-4e78-ad15-064c4831c388)

**Comment by jianchang512** [comment]
填写到 /v1 就行，后边的去掉
