### ISSUE TITLE
"保存到..."中的路径重启程序后变小写

### ISSUE THREAD

**Issue by chinese-wzq** [jianchang512/pyvideotrans#166]
我使用Linux从源码运行，_video_out文件夹位于一个包含大写的文件夹下。在程序执行过程中，novoice.mp4和en.wav均会被保存到另一个文件夹下（路径等于原_video_out文件夹路径所有大写变成小写后的路径）。
我知道这样说有点抽象，因此以下是tree的输出：
![图片](https://github.com/jianchang512/pyvideotrans/assets/40971680/83cfe7ca-16b8-43b2-87c1-e17ae2057db8)
![图片](https://github.com/jianchang512/pyvideotrans/assets/40971680/2b3f84e0-fc26-4b71-80f4-0b2948b0eb87)

**Comment by chinese-wzq** [comment]
发现是程序保存到路径中的路径变小写了
![图片](https://github.com/jianchang512/pyvideotrans/assets/40971680/13190393-acdc-4b0e-83c3-4d669dd30e52)

**Comment by jianchang512** [comment]
ok，下次修复
