### ISSUE TITLE
EdgeTTS spanish voices /  subtitles and voices aligned

### ISSUE THREAD

**Issue by komangulo** [jianchang512/pyvideotrans#167]
Hello my friend!
Would it be possible to add all the EdgeTTS (text to speech) voices in Spanish es-ES ? 
Currently there are only 2 (Elvira and Alvaro) and as far as I know there are more options available that could be integrated into the project.

On the other hand, regarding the problem that the subtitles and voices can not be aligned I have seen a project that manages to solve it in case you can help in this part:

https://github.com/ThioJoe/Auto-Synced-Translated-Dubs

你好，我的朋友！
有可能在西班牙语 es-ES 中添加所有 EdgeTTS（文本到语音）语音吗？
目前只有 2 种语音（Elvira 和 Alvaro），据我所知，还有更多可供选择的语音可以集成到项目中。

另一方面，关于字幕和语音无法对齐的问题，我看到过一个项目可以解决这个问题，希望对这部分有所帮助：

https://github.com/ThioJoe/Auto-Synced-Translated-Dubs

**Comment by jianchang512** [comment]
Currently, I'm using the free edgeTTS which only has two es-ES characters. AzureTTS does offer more, but that one comes with a charge, something I'm not supporting right now.

In terms of aligning voice-over with subtitles, let's say the original subtitles run for 5 seconds, but when dubbed in another language, it might span over 10 seconds. To contract it back to 5 seconds, the only option is to speed up the audio. No matter how it's done, as long as the voice content remains the same, it can only manifest as faster speech during playback or speed up the talking speed during synthesis. The project you mentioned operates on the same principle.

Upon selecting "Auto Dubbing Acceleration" in the software, you can implement this functionality. It aligns the dubbed voice with the subtitles, though, the maximum speed-up is only 1.8 times. Anything faster would compromise audibility.

**Comment by komangulo** [comment]
Hello! 
no problem then, the free version is great no cost for Azure services.

Exactly, it works the same way. It modifies the speed of a large audio only that the large audio cuts it into smaller chunks (audios of the timestamps of an SRT)so that way they can match the timestamps of the subtitles (SRT).
This way the audios match the lips more exactly, when modified as a whole audio or not chopped up that may be the case.
 
Best regards and thank you very much :D



您好！
那就没问题了，免费版本很棒，Azure 服务不收费。
没错，它的工作原理是一样的。它修改大型音频的速度，只是将大型音频切成较小的块状（SRT 时间戳的音频），以便与字幕（SRT）的时间戳相匹配。
这样，音频和嘴唇就能更准确地匹配，如果音频是作为一个整体修改的，或者没有被切碎，情况可能就会是这样。
 
致以最崇高的敬意，非常感谢 :D
