### ISSUE TITLE
changes in the voices by role

### ISSUE THREAD

**Issue by komangulo** [jianchang512/pyvideotrans#168]
Hello!
would it be possible for the choice of the roles of the voices something similar to the video that I attach below? it would be much more comfortable and easier to use than the current way.
Instead of putting in each of the voices the lines that they should say (which sometimes is a bit confusing when there are many people) it would be in each line the voice that would speak.

你好
在选择声音角色时，是否可以使用类似于我下面所附视频的方法？ 这样会比现在的方法更舒适、更容易使用。
不用在每个配音中加入他们应该说的台词（人多的时候有时会有点混乱），而是在每一行中加入他们应该说的台词。

[video-convert-1704582873650.webm](https://github.com/jianchang512/pyvideotrans/assets/43007108/31bf0ec4-5405-4bf9-a4b7-fe51492fb936)

**Comment by jianchang512** [comment]
The video method is not very convenient. I plan to change it to this in the future: Display each line of subtitles in the pop-up window, with a checkbox in front of each line, and a drop-down list of all roles at the bottom. First select multiple lines, and then set the dubbing roles for these lines.

**Comment by komangulo** [comment]
Hello! 
Of course I do not mean exactly the method of the video, if not a similar way or something similar. 
That method you mentioned seems to me very useful and convenient in my opinion.
If I understand correctly is like a multicheck that in each of the lines of subtitles/srt you want and finally choose the voice/role you want to speak. And in the same way in all the voices.

I am very glad that this will be implemented in the future, it will be amazing.
Best regards and thanks a lot my friend :D


您好！
当然，我指的并不是视频中的方法，而是类似的方法或类似的东西。
在我看来，您提到的方法非常有用和方便。
如果我没理解错的话，它就像一个多切卡，在每个字幕/字幕行中选择你想要的声音/角色，最后选择你想说的声音/角色。所有的声音都是如此。

我真的很高兴将来能实现这个功能，这将会非常棒。
向您致以最诚挚的问候和最衷心的感谢，我的朋友 :D

**Comment by jianchang512** [comment]
optim multi role setting at 0.989
