### ISSUE TITLE
关于配音自动加速的建议

### ISSUE THREAD

**Issue by yousei521** [jianchang512/pyvideotrans#169]
程序已经比较完美了。但是希望能把配音自动加速的算法改一下，因为使用后声音快了，慢了音色会改变，导致配音不像同一个声音配的音，我用chatgpt让它写一个方法，好像就挺好的。会加快播放速度，但是音色不会变。我不是很懂代码。您参考一下。非常感谢。

import subprocess

def change_wav_speed(input_file, output_file, speed):
  """
  改变 wav 文件的播放速度。

  Args:
    input_file: 输入 wav 文件的路径。
    output_file: 输出 wav 文件的路径。
    speed: 播放速度，大于 1 表示加快，小于 1 表示变慢。
  """
  command = ["ffmpeg", "-i", input_file, "-af", "atempo={}".format(speed), output_file]
  subprocess.run(command)

if __name__ == "__main__":
  input_file = input("输入 wav 文件的路径：")
  output_file = input("输出 wav 文件的路径：")
  speed = float(input("输入播放速度："))
  change_wav_speed(input_file, output_file, speed)

这样调整出来的声音变快或变慢。音色不会变。再次感谢您的付出！

**Comment by jianchang512** [comment]
你可以在 bilibili上播放一个视频，然后加速2.5倍，试试音色会不会改变。只要加速的够快，一样都会改变。目前也是通过加速实现的，只是没有使用ffmpeg加速

**Comment by jx1994** [comment]
确实配音自动加速后，每句话配音都会变调。这是我生成的。你可以看看。https://www.alipan.com/t/ACejtil905x74OeEzP5P
