### ISSUE TITLE
关于在mac上 novoice_xxx.mp4 没有生成成功的问题，以及添加百度翻译和兼容ios的pr

### ISSUE THREAD

**Issue by Xuenew** [jianchang512/pyvideotrans#17]
## 第一点 关于novoice的mp4没有正确生成以及mac上操作
/pyvideotrans/tmp/novoice_xxx.mp4: No such file or directory，

`
config.video['voice_role'] != 'No' and config.video['subtitle_type']>0 
`
这里判断的subtitle_type 是0，只有这里生成novoice的mp4文件。 我改写了一下

```
   #get no voice mp4
    runffmpeg(f"-y -i {source_mp4} -c:v copy -an {config.rootdir}/tmp/novoice_{mp4name}")
    # add voice dubbing and subtitle
    if config.video['voice_role'] != 'No' and config.video['subtitle_type']>0:
```
在mac上我添加了能启动，

```
#windows
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
else:
    asyncio.set_event_loop_policy(asyncio.DefaultEventLoopPolicy())
```

## 第二点 最近梯子太不稳定了，我打算加一个百度的翻译接口，在pyqt哪里加个下拉框选择翻译平台，
关于这个pr 有没有需要遵循你的格式或者特殊要求，我打算就google下面加个函数，pyqt哪里加个框，你看这样是否可以，可以的话我去提交pr 周三前应该可以提交

**Comment by Xuenew** [comment]
> subtitle_type =0 就是不添加字幕。这个无需动 百度的可以加，不过百度需要自行去申请key，比较麻烦

百度的可以用公开的接口吧，不用申请key。
 subtitle_type =0 这里我的情况是我选择了配音角色没有选择加字幕，就会一直在生成 novoice_xx.mp4这里报错，我就把 生成novoice_xx.mp4这一步放到了前面，或许这里是我操作有误吗？ 我没有选择字幕，

**Comment by jianchang512** [comment]
你是对的，那里有点问题

翻译下拉加个tooltips提示吧，百度翻译只可中英文，其他不支持。

**Comment by Leslie-Luo** [comment]
> > subtitle_type =0 就是不添加字幕。这个无需动 百度的可以加，不过百度需要自行去申请key，比较麻烦
> 
> 百度的可以用公开的接口吧，不用申请key。 subtitle_type =0 这里我的情况是我选择了配音角色没有选择加字幕，就会一直在生成 novoice_xx.mp4这里报错，我就把 生成novoice_xx.mp4这一步放到了前面，或许这里是我操作有误吗？ 我没有选择字幕，

你好  我的也是Mac用最新的版本运行会报错，能留个联系方式吗？想咨询一下

**Comment by Xuenew** [comment]
> > > subtitle_type =0 就是不添加字幕。这个无需动 百度的可以加，不过百度需要自行去申请key，比较麻烦
> > 
> > 
> > 百度的可以用公开的接口吧，不用申请key。 subtitle_type =0 这里我的情况是我选择了配音角色没有选择加字幕，就会一直在生成 novoice_xx.mp4这里报错，我就把 生成novoice_xx.mp4这一步放到了前面，或许这里是我操作有误吗？ 我没有选择字幕，
> 
> 你好 我的也是Mac用最新的版本运行会报错，能留个联系方式吗？想咨询一下

vx：ForXYY_yeah
