### ISSUE TITLE
视频显示合并完成,但是实际视频合并失败，使用标准模式， 系统win10 

### ISSUE THREAD

**Issue by namejee** [jianchang512/pyvideotrans#170]
设置如下 
![1704599532063](https://github.com/jianchang512/pyvideotrans/assets/22115094/834c03b2-c796-4ad3-99e7-b7dc4490b909)
![1704599638979](https://github.com/jianchang512/pyvideotrans/assets/22115094/1f6a3492-f0ce-45a4-a585-e71f0095e7dc)

附上日志信息 
[video-20240107.log](https://github.com/jianchang512/pyvideotrans/files/13852158/video-20240107.log)

**Comment by jianchang512** [comment]
进入 软件根目录，文件夹地址栏输入 `cmd`，回车，

确保 E:\\videoDown\\_video_out\\13349003856946046\\novoice.mp4 和 E:\\videoDown\\_video_out\\13349003856946046\\en.wav 和 E:\\videoDown\\_video_out\\13349003856946046\\en.srt  这三个文件存在，然后在弹出的黑窗口输入 下面这个命令，输出结果完整截图，尤其是后边红色部分


```
ffmpeg -hide_banner -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -y -i 'E:\\videoDown\\_video_out\\13349003856946046\\novoice.mp4' -i 'E:\\videoDown\\_video_out\\13349003856946046\\en.wav' -sub_charenc UTF-8 -f srt -i 'E:\\videoDown\\_video_out\\13349003856946046\\en.srt' -c:v h264_nvenc -c:a aac -c:s mov_text  '-metadata:s:s:0' 'language=eng'  'E:\\videoDown\\_video_out\\13349003856946046\\13349003856946046.mp4'

```


同样保证那3个文件存在，然后继续输出下面这个命令，截图解脱

```

ffmpeg -hide_banner -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -y -i 'E:\\videoDown\\_video_out\\13349003856946046\\novoice.mp4' -i 'E:\\videoDown\\_video_out\\13349003856946046\\en.wav -sub_charenc UTF-8 -f srt -i 'E:\\videoDown\\_video_out\\13349003856946046\\en.srt' -c:v h264_nvenc -c:a aac -c:s mov_text  '-metadata:s:s:0' 'language=eng'  -vf hwdownload 'E:\\videoDown\\_video_out\\13349003856946046\\13349003856946046.mp4'
```

**Comment by jianchang512** [comment]
https://github.com/jianchang512/pyvideotrans/releases/download/v0.9.6.7/debug-spexe.zip

解压覆盖 sp.exe
