### ISSUE TITLE
使用https://deepl.com/ 翻译字幕失败 相关配置图和log在详情里面

### ISSUE THREAD

**Issue by namejee** [jianchang512/pyvideotrans#171]
[video-20240107.log](https://github.com/jianchang512/pyvideotrans/files/13852179/video-20240107.log)
![1704600281968](https://github.com/jianchang512/pyvideotrans/assets/22115094/d10f8699-dc01-4860-a5db-bf386a70ef51)

**Comment by namejee** [comment]
![Uploading 1704600281968.jpg…]()

**Comment by jianchang512** [comment]
有点bug,解压覆盖 sp.exe 

https://github.com/jianchang512/pyvideotrans/releases/download/v0.9.6.7/debug-spexe.zip
