### ISSUE TITLE
部署好deepl后，却出现翻译失败

### ISSUE THREAD

**Issue by fengqingyang2023** [jianchang512/pyvideotrans#172]
我部署好deepl后，却发现用不了，不管联不联外网

联外网的显示错误如下：[error]DeepLX error:timed out，

不联外网的显示错误如下：[error]deeplx translate:response.status_code=406,result['code']=406
                                             或者：[error]DeepLX error:[WinError 10061] 由于目标计算机积极拒绝，无法连接

**Comment by jianchang512** [comment]
首先在浏览器里自己试试能不能打开你的 deeplx 端口，如果打不开，说明部署有问题

**Comment by fengqingyang2023** [comment]
你好，浏览器可以打开，但还是翻译不了，应该是这样打开吧，
![image](https://github.com/jianchang512/pyvideotrans/assets/129174130/42548a00-f2b4-4e57-a2d6-c4370654ad06)

**Comment by jianchang512** [comment]
软件菜单 设置里填写 地址了吗

**Comment by fengqingyang2023** [comment]
填了，软件只要填一次就会默认填好

**Comment by jianchang512** [comment]
这个deeplx其实用的也是deepl，只是通过特殊手段避过频率检测，不太可靠，可能被限制了

**Comment by fengqingyang2023** [comment]
好的，不过其他翻译都能用，很不错
