### ISSUE TITLE
还有视频提取字幕总是失败以及一个建议

### ISSUE THREAD

**Issue by fengqingyang2023** [jianchang512/pyvideotrans#173]
我以为的提取视频字幕，应该是给我提供一个自己选择的区域，把硬字幕提取出来，但是好像不是这样工作的，然后，提取视频字幕总是失败，我换了一个几分钟的带硬字幕的视频也不行

还有个建议，当我把字幕翻译后，却没有导出这个按键啊，那如何导出呢？

**Comment by jianchang512** [comment]
提取字幕就是识别字幕里的人声，导出文字，不是提取里面的硬字幕。


自行复制，就是纯文字而已
