### ISSUE TITLE
使用CUDA翻译视频报错

### ISSUE THREAD

**Issue by elementlo** [jianchang512/pyvideotrans#174]
0.988exe版，使用默认google翻译，base模型， 整体识别， 开启CUDA加速，报错：split error。log截图如下：
![image](https://github.com/jianchang512/pyvideotrans/assets/10020581/fb4b1f7d-6628-4feb-9d2d-94abd3463727)

多次点击开始后，可以运行，但是每次到5分钟左右就提示执行完成，停止执行，实际视频有一个多小时。

**Comment by jianchang512** [comment]
看不到图

https://github.com/jianchang512/pyvideotrans/releases/download/v0.9.6.7/debug-spexe.zip

解压覆盖 sp.exe 试试

**Comment by elementlo** [comment]
> 看不到图
> 
> https://github.com/jianchang512/pyvideotrans/releases/download/v0.9.6.7/debug-spexe.zip
> 
> 解压覆盖 sp.exe 试试

换完可以了
