### ISSUE TITLE
有一点困惑，视频合并不可以无声视频合并哦

### ISSUE THREAD

**Issue by fengqingyang2023** [jianchang512/pyvideotrans#175]
![image](https://github.com/jianchang512/pyvideotrans/assets/129174130/99dd9ce2-d1c6-4a3d-9710-c5aa9d70cd0c)
有一点迷惑，视频合并不可以无声视频合并哦，我的意思是为啥不应该是无声视频加音频，再加字幕，三个合成，我的操作告诉我只能是有声视频加音频，再加字幕才行，有声视频本身就有声音，何必再加音频呢？有点困惑

**Comment by jianchang512** [comment]
没看懂什么意思
