### ISSUE TITLE
ffprobe error:result.stdout='',result.stderr=''

### ISSUE THREAD

**Issue by baboonSTW** [jianchang512/pyvideotrans#176]
![image](https://github.com/jianchang512/pyvideotrans/assets/67298905/f6303c94-cd2a-4a2f-9d83-29a0c74c6855)
感谢作者开源，我想合并视频，音频和字幕的时候遇到了一下报错：
INFO:VideoTrans:ffprobe error:result.stdout='',result.stderr=''
请问我应该在哪里填写result path?

**Comment by jianchang512** [comment]
重新下载 预编译版。再试试
