### ISSUE TITLE
最新版本 0.990 正确配置了CUDA但仍报错

### ISSUE THREAD

**Issue by qxk2005** [jianchang512/pyvideotrans#177]
最新版本 0.9990 用chatgpt做中英文翻译，出现错误提示，无法切割视频
Please try upgrading the graphics card driver and reconfigure CUDA

![image](https://github.com/jianchang512/pyvideotrans/assets/61008180/2d483239-f6ea-4407-b03d-c7648fcde1f6)

**Comment by qxk2005** [comment]
补充下，上一个版本没问题，新下载的这个 无cuda也没问题，就是选择了cuda加速后会出现这个提示

**Comment by jianchang512** [comment]
上传出错时logs目录下当前日期的日志

**Comment by qxk2005** [comment]
这个是log

[video-20240109.log](https://github.com/jianchang512/pyvideotrans/files/13871258/video-20240109.log)

**Comment by jianchang512** [comment]
在软件目录下，地址栏输出 cmd 然后回车，在弹出的cmd中，执行命令. 确认这个视频存在，然后执行命令，将报错信息截图
`ffmpeg -hide_banner -vsync 0 -hwaccel cuvid -c:v h264_cuvid -extra_hw_frames 2 -y -i "D:/OneDrive - 牛股份/下载-视频/Apple Vision Pro.mp4" -ac 1 "D:/_out_videos/Apple Vision Pro/en.wav"


然后再执行  `ffmpeg -hide_banner -vsync 0 -hwaccel cuda -c:v h264_cuvid -extra_hw_frames 2 -y -i "D:/OneDrive - 牛股份/下载-视频/Apple Vision Pro.mp4" -ac 1 "D:/_out_videos/Apple Vision Pro/en.wav"

同样截图报错信息

**Comment by qxk2005** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/61008180/cbcc92e6-2969-4ea1-9ec5-8f3e99258072)

……

![image](https://github.com/jianchang512/pyvideotrans/assets/61008180/3a7af5d8-9e5b-4a76-960a-d07ff04994b5)

**Comment by jianchang512** [comment]
命令改了下，重新执行。在软件目录下，地址栏输出 cmd 然后回车，在弹出的cmd中，执行命令. 确认这个视频存在，然后执行命令，将报错信息截图
`ffmpeg -hide_banner -vsync 0 -hwaccel cuvid -hwaccel_output_format  cuda -c:v h264_cuvid -extra_hw_frames 2 -y -i "D:/OneDrive - 牛股份/下载-视频/Apple Vision Pro.mp4" -ac 1 "D:/_out_videos/Apple Vision Pro/en.wav"


然后再执行  `ffmpeg -hide_banner -vsync 0 -hwaccel cuda -hwaccel_output_format  cuda -c:v h264_cuvid -extra_hw_frames 2 -y -i "D:/OneDrive - 牛股份/下载-视频/Apple Vision Pro.mp4" -ac 1 "D:/_out_videos/Apple Vision Pro/en.wav"

同样截图报错信息

**Comment by qxk2005** [comment]
cuowuyi错误依旧

![image](https://github.com/jianchang512/pyvideotrans/assets/61008180/43d7a334-4a54-427f-84ef-edb86fb387fe)

……

![image](https://github.com/jianchang512/pyvideotrans/assets/61008180/95b2f109-b976-43d1-b519-35071296b079)

**Comment by jianchang512** [comment]
2条命令都是一样错误吗。另一条呢

ffmepg是不是内置的，预编译版还是源码版

**Comment by qxk2005** [comment]
另外一条同样的错误，用的是编译版

![image](https://github.com/jianchang512/pyvideotrans/assets/61008180/6b4aec01-230c-4cc5-9fe3-ab6a56da09dc)


……


![image](https://github.com/jianchang512/pyvideotrans/assets/61008180/a26811d3-0b1c-4f31-9fab-4b412a9328d4)

**Comment by jianchang512** [comment]
视频多大，发下

**Comment by qxk2005** [comment]
视频太大 1G，我现在换个思路，重新用剪映转码导出下，然后再看看，怀疑可能是FFMPEG对视频编码识别有问题，晚点回复

**Comment by jianchang512** [comment]
视频需要是正确的mp4编码，你先确认这个没问题

**Comment by jianchang512** [comment]
h264 不是 h265

**Comment by qxk2005** [comment]
重新用剪映导出了一个新H264格式文件，现在正常了。

这个是我从apple网站下载的视频，没看码率。有2个信息反馈，1是4K视频，2是用流下载而非文件下载。希望对你和其他人有帮助。

**Comment by qxk2005** [comment]
已赞助，多谢做了这么好的软件再接再厉 
![047A30BE](https://github.com/jianchang512/pyvideotrans/assets/61008180/c6ef030c-61ca-4c21-923b-4fc2e70ac9ef)

**Comment by jianchang512** [comment]
感谢支持
