### ISSUE TITLE
有英文字幕文件只能先翻译中文再进行配音吗？

### ISSUE THREAD

**Issue by anyinni** [jianchang512/pyvideotrans#179]
本来想着有字幕文件能更快点，但是标准功能模式好像不会将英文字幕翻译成中文再配音，只能自己翻译后再选择配音，这样反而更慢了。
还有就是文字合成语音和字幕创建配音好像功能差不多，有什么重要的不同点吗

**Comment by jianchang512** [comment]
是的先自行翻译
直接google网站里或者软件  “文字字幕翻译”功能
