### ISSUE TITLE
没有生成视频文件和字幕文件

### ISSUE THREAD

**Issue by Lier-Accuser** [jianchang512/pyvideotrans#18]
![image](https://github.com/jianchang512/pyvideotrans/assets/133242188/b0c9a1a9-de08-49b1-a10b-bb7cdd7936a7)
![image](https://github.com/jianchang512/pyvideotrans/assets/133242188/1b11ccdd-3985-4cd2-90c3-5c58a1ae4c7d)
您好，请问为什么这里会报这样的错误，右边的字幕好像也翻译了，但是就是没办法生成对应的视频文件和字幕文件

**Comment by jianchang512** [comment]
字幕也选择，然后再试下
如果还有错，将根下的video.log上传下

**Comment by Lier-Accuser** [comment]
感谢！解决了

**Comment by jianchang512** [comment]
当前有点bug，下次提交解决

**Comment by jianchang512** [comment]
当前有点bug，下次提交解决
