### ISSUE TITLE
使用文字合成语音功能时,勾选（是srt字幕？）报错显示before dubbing erroglist index oul ol range。

### ISSUE THREAD

**Issue by jx1994** [jianchang512/pyvideotrans#180]
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:有新的版本可以下载了:0.992
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/AAA.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215345.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215350.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215350.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215350.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215351.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215351.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215355.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215355.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215356.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215356.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215356.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215356.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215356.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215357.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215357.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215357.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215411.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215414.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215414.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215415.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215415.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215415.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215415.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215415.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215416.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215416.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215416.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215416.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215417.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215417.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215417.wav'
INFO:VideoTrans:start hecheng self.tts_type='edgeTTS',self.role='zh-CN-XiaoxiaoNeural',self.rate='+0%',self.filename='C:/Users/jx249/Videos/pyvideotrans/tts/tts-zh-CN-XiaoxiaoNeural-0-20240111-215417.wav'

**Comment by jianchang512** [comment]
你的字幕是什么样的，贴上来。并截图你操作时的界面

**Comment by jianchang512** [comment]
好的，我先看看，估计是因为字幕中存在空文字的情况，有行号有时间但无文字

**Comment by jianchang512** [comment]
v0.993 fixed
