### ISSUE TITLE
配音自动加速后，出现每句话都不一样的语调问题。

### ISSUE THREAD

**Issue by jx1994** [jianchang512/pyvideotrans#181]
配音自动加速后，每句话配音都会变调。这是我生成的。你可以看看。https://www.alipan.com/t/ACejtil905x74OeEzP5P    。我想是不是每段话都是分开配的，字多的就快，子少的慢。然后把这些配完得音频段落合成一起。所以才出现每句话不同的语调。

**Comment by jianchang512** [comment]
强制加速播放，在原字幕的时间内完成。比如原字幕是 00:00:00 --> 00:00:03, 配音后是6s，那么就强制加速2倍。至于加速多少是由原字幕时间段和配音后时间共同决定，每个字幕都是不同的。

只要加速播放，语调肯定变化，这是常识。
