### ISSUE TITLE
最新版本0.994，在win平台下，如果文件路径带中文或中文符号（包括空格），会报错

### ISSUE THREAD

**Issue by Againstthewindtofly** [jianchang512/pyvideotrans#183]
以下是我自己的测试结果
1. 文件名不能包含中文（文字和标点符号都不行）
2. 文件夹只能包含1个空格，不能包含其他中文
1,2 报错 【'NoneType' object has no attribute 'strip'】
3. 文件名如果包含空格，或者文件夹名称内超过1个空格，会提示程序无法访问
    【另一个程序正在使用此文件，进程无法访问。: 'D:/Desktop/_video_out/1. 23/novoice.mp4'】
 希望作者可以处理下中文路径支持的问题

**Comment by jianchang512** [comment]
logs下出错时的日志信息

**Comment by jianchang512** [comment]
中文名问题可解决，但“另一个程序正在使用此文件，进程无法访问” 这个无法复现，是不是很大的视频文件，执行了一半然后强制关闭了，又重新开始的

**Comment by WXXVC** [comment]
> logs下出错时的日志信息

请问一下软件运行不调用gpu是什么情况?

**Comment by jianchang512** [comment]
> > logs下出错时的日志信息
> 
> 请问一下软件运行不调用gpu是什么情况?


GPU下对视频进行硬件解码编码对数据正确性要求严格，容错率几乎为0，任何一点错误都会导致失败，加上显卡型号、驱动版本、CUDA版本、ffmpeg版本之间差异等，导致兼容性很差，不同版本上很容易出现兼容性错误。目前加了回退，GPU上失败后自动使用CPU软件编解码。logs日志下会有出错信息。

**Comment by jianchang512** [comment]
实测无法复现。
v0.996 再试试
