### ISSUE TITLE
why can view my own voice in elevenlabTTS

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#187]
https://github.com/jianchang512/pyvideotrans/assets/428820/e3331575-06dc-4615-a5e6-2e9c13f9eba8

**Comment by jianchang512** [comment]
If the key for elevenlabs is filled in, the sound under the current key will be obtained through elevenlabs. voices()

https://github.com/elevenlabs/elevenlabs-python?tab=readme-ov-file#%EF%B8%8F-voices

**Comment by johnfelipe** [comment]
Give me support for how use my own voice, with cheatsheet steps, because I'm new and rookie in your app and elevenlabs

**Comment by johnfelipe** [comment]
![Screenshot_2024-01-21-10-37-27-43_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/jianchang512/pyvideotrans/assets/428820/2f79d311-8577-460a-b4c5-09ec4685a912)

How much time elevenlabs complete fine tuning?

**Comment by jianchang512** [comment]
I don't understand what you mean. If you're talking about cloning, this project doesn't support cloning functionality.
If you just want to pull your voice in the voice tab.
1. Menu - elevenlabs keys Set your keys
2. Add sound to voice lab or add other sounds to lab
3. Delete the elevenlabs.json file from the software directory
4. Start the software
