### ISSUE TITLE
提取字幕翻译和内置的文本字幕翻译功能都没办法正常使用，申请了百度api，文本字幕翻译不使用str模式好像可以，之前用deeplx的时候也是，一直显示正在处理中，没响应，但是确实链接了deeplx，处理几条之后可能会没响应，不关闭deeplx仅仅重启翻译工具就可以继续翻译，按理说即使超时也应该有报错的

### ISSUE THREAD

**Issue by refuckable** [jianchang512/pyvideotrans#189]
![image](https://github.com/jianchang512/pyvideotrans/assets/142878514/50402cd8-df3b-40fc-95e7-f6a52a1a68a2)

**Comment by refuckable** [comment]
更新到最新版之后同样的设置好像deeplx不会断线了，有一种大便通畅的感觉，爽，但是视频字幕翻译还没在最新版用过

**Comment by jianchang512** [comment]
所有问题都升级到最新版再说

标题太长了，难以阅读
