### ISSUE TITLE
CPU 75%

### ISSUE THREAD

**Issue by komangulo** [jianchang512/pyvideotrans#191]
I don't know why, but now with the new version even with a graphic card it consumes more than 70% of cpu, of the processor capacity.
Is this normal?
I am using the large v3 model although it is the one I always use.
Best regards friend and thanks for your work.

![Caasdasdsdptura](https://github.com/jianchang512/pyvideotrans/assets/43007108/0db192d3-ffb3-419d-986b-addad69172aa)

**Comment by jianchang512** [comment]
The latest version has adjusted the number of threads and will use threads with the same number of CPU cores. Previously, only 4 threads were used, which will increase CPU usage
The next version will add a configuration in set.ini that can be manually adjusted
