### ISSUE TITLE
Installation tutorial 

### ISSUE THREAD

**Issue by vedanthkadam555** [jianchang512/pyvideotrans#193]
Can you please provide the Installation Tutorial of the Software. Actually I Found One but. It's in Chinese Language. Can you please give that in English.  Thanks.

**Comment by jianchang512** [comment]
https://github.com/jianchang512/pyvideotrans/blob/main/README_EN.md

**Comment by vedanthkadam555** [comment]
![Screenshot_2024-01-21-23-45-12-510_com android chrome](https://github.com/jianchang512/pyvideotrans/assets/144011548/b02bc520-d17e-472b-a7b0-f60e4bfc4924)
But in that tutorial there is already software installed . I don't have much program knowledge I'm struggling to install it.  Thanks for Response.

**Comment by jianchang512** [comment]
https://github.com/jianchang512/clone-voice/releases/download/v0.888/clone-voice-v0.888.7z

On Windows, download and unzip, double-click spxe

**Comment by jianchang512** [comment]
If Mac or Linux 

1.  git clone https://github.com/jianchang512/pyvideotrans
2. cd pyvideotrans
3. python -m venv venv
4.  run source ./venv/bin/activate.
5. `pip install -r requirements.txt`, if version conflict error occurred, please executable `pip install -r requirements.txt --no-deps`
6. Manually installing ffmpeg on your own
7. Open the software interface by running `python sp.py`.

**Comment by vedanthkadam555** [comment]
Oh I see. Then I guess it doesn't need any programing installation. As it was showing in Chinese tutorial that. We need to install Pycharm and all that. Okay Got it. Thank You Ma'am : )

**Comment by vedanthkadam555** [comment]
Please Please Add the Hindi language in Source file. So that I can convert that into English. Please I'm waiting for that. Thank you.

**Comment by jianchang512** [comment]
v0.9982  Supports the use of Hindi as the original and target languages

**Comment by vedanthkadam555** [comment]
I selected Hindi language. But while the video is generating. Beside it showing captions and those captions are in Urdu Language, Not Hindi. 

Even after completing the video process. The output audio is not even near to original audio. It's just saying random words which are in the original audio. Thanks

**Comment by vedanthkadam555** [comment]
Look this is Urdu language ![IMG_20240122_100033.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/dc753191-43b8-48e8-913e-7761a7dbf21e)

**Comment by jianchang512** [comment]
"The weather is nice today"
Translate this period into Hindi
And provide a link to the translation results of Google Translate

**Comment by vedanthkadam555** [comment]
> "The weather is nice today"
> Translate this period into Hindi
> And provide a link to the translation results of Google Translate

![Screenshot_2024-01-22-13-23-05-069_com.google.android.apps.translate-edit.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/24ec8d62-1eef-4741-878e-b9fbd0789d23)

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/3c433221-ddfd-4cf6-bdd0-5231e97ceb4c)

看起来没什么不对啊

**Comment by jianchang512** [comment]
this is my transate result

```
1
00:00:00,000 --> 00:00:01,280
यह उपवन में है

2
00:00:01,280 --> 00:00:04,600
सबसे पहले हमें एक इलेक्ट्रोमैग्नेटिक कमरा मिलता है

3
00:00:04,600 --> 00:00:08,440
यहाँ तीन हैं

4
00:00:08,440 --> 00:00:10,240
यहाँ दो खुरच हैं

5
00:00:10,240 --> 00:00:11,520
यहाँ एक मिट्टी है

6
00:00:11,520 --> 00:00:12,560
फिर देखें

7
00:00:14,600 --> 00:00:16,079
नीचे है

8
00:00:16,079 --> 00:00:17,080
आरपीएस

9
00:00:17,080 --> 00:00:20,480
सब देखें, वास्तव में यह सर्किट क्या करता है

10
00:00:20,480 --> 00:00:22,520
इस चक्की द्वारा

11
00:00:22,520 --> 00:00:23,800
यह क्रिया है

12
00:00:23,800 --> 00:00:24,760
उचित लंबाई तुलना

13
00:00:24,760 --> 00:00:26,120
तुम इसी तरह समझते हो तो ठीक है

14
00:00:26,120 --> 00:00:26,640
सही है ना

15
00:00:26,640 --> 00:00:27,920
सब देखो

16
00:00:27,920 --> 00:00:29,360
यह AD है

17
00:00:29,360 --> 00:00:29,960
सब देखो
```


this is translation to English

```
1
00:00:00,000 --> 00:00:01,280
it is in the garden

2
00:00:01,280 --> 00:00:04,600
First we get an electromagnetic room

3
00:00:04,600 --> 00:00:08,440
here are three

4
00:00:08,440 --> 00:00:10,240
here are two scratches

5
00:00:10,240 --> 00:00:11,520
there is a soil here

6
00:00:11,520 --> 00:00:12,560
see again

7
00:00:14,600 --> 00:00:16,079
is below

8
00:00:16,079 --> 00:00:17,080
rps

9
00:00:17,080 --> 00:00:20,480
See all, what this circuit actually does

10
00:00:20,480 --> 00:00:22,520
by this mill

11
00:00:22,520 --> 00:00:23,800
this is action

12
00:00:23,800 --> 00:00:24,760
proper length comparison

13
00:00:24,760 --> 00:00:26,120
It's okay if you understand it that way

14
00:00:26,120 --> 00:00:26,640
that's right

15
00:00:26,640 --> 00:00:27,920
See all

16
00:00:27,920 --> 00:00:29,360
This is AD

17
00:00:29,360 --> 00:00:29,960
See all
```

its seems no error


https://translate.google.com/?sl=auto&tl=en&text=1%0A00%3A00%3A00%2C000%20--%3E%2000%3A00%3A01%2C280%0A%E0%A4%AF%E0%A4%B9%20%E0%A4%89%E0%A4%AA%E0%A4%B5%E0%A4%A8%20%E0%A4%AE%E0%A5%87%E0%A4%82%20%E0%A4%B9%E0%A5%88%0A%0A2%0A00%3A00%3A01%2C280%20--%3E%2000%3A00%3A04%2C600%0A%E0%A4%B8%E0%A4%AC%E0%A4%B8%E0%A5%87%20%E0%A4%AA%E0%A4%B9%E0%A4%B2%E0%A5%87%20%E0%A4%B9%E0%A4%AE%E0%A5%87%E0%A4%82%20%E0%A4%8F%E0%A4%95%20%E0%A4%87%E0%A4%B2%E0%A5%87%E0%A4%95%E0%A5%8D%E0%A4%9F%E0%A5%8D%E0%A4%B0%E0%A5%8B%E0%A4%AE%E0%A5%88%E0%A4%97%E0%A5%8D%E0%A4%A8%E0%A5%87%E0%A4%9F%E0%A4%BF%E0%A4%95%20%E0%A4%95%E0%A4%AE%E0%A4%B0%E0%A4%BE%20%E0%A4%AE%E0%A4%BF%E0%A4%B2%E0%A4%A4%E0%A4%BE%20%E0%A4%B9%E0%A5%88%0A%0A3%0A00%3A00%3A04%2C600%20--%3E%2000%3A00%3A08%2C440%0A%E0%A4%AF%E0%A4%B9%E0%A4%BE%E0%A4%81%20%E0%A4%A4%E0%A5%80%E0%A4%A8%20%E0%A4%B9%E0%A5%88%E0%A4%82%0A%0A4%0A00%3A00%3A08%2C440%20--%3E%2000%3A00%3A10%2C240%0A%E0%A4%AF%E0%A4%B9%E0%A4%BE%E0%A4%81%20%E0%A4%A6%E0%A5%8B%20%E0%A4%96%E0%A5%81%E0%A4%B0%E0%A4%9A%20%E0%A4%B9%E0%A5%88%E0%A4%82%0A%0A5%0A00%3A00%3A10%2C240%20--%3E%2000%3A00%3A11%2C520%0A%E0%A4%AF%E0%A4%B9%E0%A4%BE%E0%A4%81%20%E0%A4%8F%E0%A4%95%20%E0%A4%AE%E0%A4%BF%E0%A4%9F%E0%A5%8D%E0%A4%9F%E0%A5%80%20%E0%A4%B9%E0%A5%88%0A%0A6%0A00%3A00%3A11%2C520%20--%3E%2000%3A00%3A12%2C560%0A%E0%A4%AB%E0%A4%BF%E0%A4%B0%20%E0%A4%A6%E0%A5%87%E0%A4%96%E0%A5%87%E0%A4%82%0A%0A7%0A00%3A00%3A14%2C600%20--%3E%2000%3A00%3A16%2C079%0A%E0%A4%A8%E0%A5%80%E0%A4%9A%E0%A5%87%20%E0%A4%B9%E0%A5%88%0A%0A8%0A00%3A00%3A16%2C079%20--%3E%2000%3A00%3A17%2C080%0A%E0%A4%86%E0%A4%B0%E0%A4%AA%E0%A5%80%E0%A4%8F%E0%A4%B8%0A%0A9%0A00%3A00%3A17%2C080%20--%3E%2000%3A00%3A20%2C480%0A%E0%A4%B8%E0%A4%AC%20%E0%A4%A6%E0%A5%87%E0%A4%96%E0%A5%87%E0%A4%82%2C%20%E0%A4%B5%E0%A4%BE%E0%A4%B8%E0%A5%8D%E0%A4%A4%E0%A4%B5%20%E0%A4%AE%E0%A5%87%E0%A4%82%20%E0%A4%AF%E0%A4%B9%20%E0%A4%B8%E0%A4%B0%E0%A5%8D%E0%A4%95%E0%A4%BF%E0%A4%9F%20%E0%A4%95%E0%A5%8D%E0%A4%AF%E0%A4%BE%20%E0%A4%95%E0%A4%B0%E0%A4%A4%E0%A4%BE%20%E0%A4%B9%E0%A5%88%0A%0A10%0A00%3A00%3A20%2C480%20--%3E%2000%3A00%3A22%2C520%0A%E0%A4%87%E0%A4%B8%20%E0%A4%9A%E0%A4%95%E0%A5%8D%E0%A4%95%E0%A5%80%20%E0%A4%A6%E0%A5%8D%E0%A4%B5%E0%A4%BE%E0%A4%B0%E0%A4%BE%0A%0A11%0A00%3A00%3A22%2C520%20--%3E%2000%3A00%3A23%2C800%0A%E0%A4%AF%E0%A4%B9%20%E0%A4%95%E0%A5%8D%E0%A4%B0%E0%A4%BF%E0%A4%AF%E0%A4%BE%20%E0%A4%B9%E0%A5%88%0A%0A12%0A00%3A00%3A23%2C800%20--%3E%2000%3A00%3A24%2C760%0A%E0%A4%89%E0%A4%9A%E0%A4%BF%E0%A4%A4%20%E0%A4%B2%E0%A4%82%E0%A4%AC%E0%A4%BE%E0%A4%88%20%E0%A4%A4%E0%A5%81%E0%A4%B2%E0%A4%A8%E0%A4%BE%0A%0A13%0A00%3A00%3A24%2C760%20--%3E%2000%3A00%3A26%2C120%0A%E0%A4%A4%E0%A5%81%E0%A4%AE%20%E0%A4%87%E0%A4%B8%E0%A5%80%20%E0%A4%A4%E0%A4%B0%E0%A4%B9%20%E0%A4%B8%E0%A4%AE%E0%A4%9D%E0%A4%A4%E0%A5%87%20%E0%A4%B9%E0%A5%8B%20%E0%A4%A4%E0%A5%8B%20%E0%A4%A0%E0%A5%80%E0%A4%95%20%E0%A4%B9%E0%A5%88%0A%0A14%0A00%3A00%3A26%2C120%20--%3E%2000%3A00%3A26%2C640%0A%E0%A4%B8%E0%A4%B9%E0%A5%80%20%E0%A4%B9%E0%A5%88%20%E0%A4%A8%E0%A4%BE%0A%0A15%0A00%3A00%3A26%2C640%20--%3E%2000%3A00%3A27%2C920%0A%E0%A4%B8%E0%A4%AC%20%E0%A4%A6%E0%A5%87%E0%A4%96%E0%A5%8B%0A%0A16%0A00%3A00%3A27%2C920%20--%3E%2000%3A00%3A29%2C360%0A%E0%A4%AF%E0%A4%B9%20AD%20%E0%A4%B9%E0%A5%88%0A%0A17%0A00%3A00%3A29%2C360%20--%3E%2000%3A00%3A29%2C960%0A%E0%A4%B8%E0%A4%AC%20%E0%A4%A6%E0%A5%87%E0%A4%96%E0%A5%8B&op=translate

**Comment by jianchang512** [comment]
Chinese
```
1
00:00:00,000 --> 00:00:01,280
这发的公园里

2
00:00:01,280 --> 00:00:04,600
首先我们拿到的是一款电磁房

3
00:00:04,600 --> 00:00:08,440
这上面有这里有三个

4
00:00:08,440 --> 00:00:10,240
这里有两个孔

5
00:00:10,240 --> 00:00:11,520
这里有一个土

6
00:00:11,520 --> 00:00:12,560
再看一下

7
00:00:14,600 --> 00:00:16,079
下面是

8
00:00:16,079 --> 00:00:17,080
RPS

9
00:00:17,080 --> 00:00:20,480
大家看一下其实这个电路它就是通过什么

10
00:00:20,480 --> 00:00:22,520
通过这个线圈

11
00:00:22,520 --> 00:00:23,800
动作就是

12
00:00:23,800 --> 00:00:24,760
常态变长比

13
00:00:24,760 --> 00:00:26,120
你就这样认为就可以了

14
00:00:26,120 --> 00:00:26,640
对不对

15
00:00:26,640 --> 00:00:27,920
大家看一下

16
00:00:27,920 --> 00:00:29,360
这个是AD

17
00:00:29,360 --> 00:00:29,960
大家看一下

```

Hidin
```
1
00:00:00,000 --> 00:00:02,760
यह उपवन में है

2
00:00:02,760 --> 00:00:07,944
सबसे पहले हमें एक इलेक्ट्रोमैग्नेटिक कमरा मिलता है

3
00:00:07,944 --> 00:00:11,784
यहाँ तीन हैं

4
00:00:11,784 --> 00:00:14,736
यहाँ दो खुरच हैं

5
00:00:14,736 --> 00:00:17,736
यहाँ एक मिट्टी है

6
00:00:17,736 --> 00:00:19,632
फिर देखें

7
00:00:21,672 --> 00:00:23,928
नीचे है

8
00:00:23,928 --> 00:00:25,704
आरपीएस

9
00:00:25,704 --> 00:00:30,672
सब देखें, वास्तव में यह सर्किट क्या करता है

10
00:00:30,672 --> 00:00:32,904
इस चक्की द्वारा

11
00:00:32,904 --> 00:00:34,968
यह क्रिया है

12
00:00:34,968 --> 00:00:37,416
उचित लंबाई तुलना

13
00:00:37,416 --> 00:00:41,568
तुम इसी तरह समझते हो तो ठीक है

14
00:00:41,568 --> 00:00:43,536
सही है ना

15
00:00:43,536 --> 00:00:45,456
सब देखो

16
00:00:45,456 --> 00:00:48,072
यह AD है

17
00:00:48,072 --> 00:00:49,992
सब देखो
```

https://github.com/jianchang512/pyvideotrans/assets/3378335/ce372564-08a1-4ffe-9fbb-e5872f49ecae

I didn't find any errors, according to Google translation, this is indeed Hindi

**Comment by vedanthkadam555** [comment]
Can you translate this Hindi video into English. 

https://youtu.be/a5PyzSDIwLE?si=1XQEC42q3HWv7pWj

**Comment by vedanthkadam555** [comment]
![IMG_20240122_142037.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/ab677975-699e-4043-aacd-14513fe34a85)

I selected source file as Hindi. But it is showing Urdu Language here. 

It is translating Urdu to English. 

Instead it should translate Hindi to English

**Comment by vedanthkadam555** [comment]
https://github.com/jianchang512/pyvideotrans/assets/144011548/3b90cbbb-32ab-4788-aa74-fc5918e3eff1

I tried this file.

**Comment by jianchang512** [comment]
These two languages only have different writing styles, but their pronunciations are similar and difficult to accurately recognize. Please try using the large-v3 model, as the effect should be better

**Comment by vedanthkadam555** [comment]
You're right. Pronunciation is Similar. 

And also using ElevenLabs in TTS is unlimited? Because yesterday I have put a Script in TTS by selecting evenlabs. And the script was 2 hours length. I kept it while night. But I didn't received the output.

**Comment by jianchang512** [comment]
The software itself has no restrictions, and if there are restrictions, it should also be an issue with the API.
If it does not meet expectations, please check if there is any error message in the logs directory and search for the word "error"

**Comment by vedanthkadam555** [comment]
But it is working with Edgetts. It gave 2 hours audio file in 10 Minutes.

**Comment by vedanthkadam555** [comment]
![IMG_20240122_145121.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/71d5c47a-ed08-4f94-a619-e607f3b77329)

I have found this in logs folder.

**Comment by jianchang512** [comment]
I don't quite understand. Are you translating videos or synthesizing text into speech?
If you choose to use elevenlabs TTS, then the speaker should not be edgeTTS
You can delete the log information and try again. If there are still issues, you can record a video of the operation

**Comment by vedanthkadam555** [comment]
Ma'am I'm using Text to Speech synthesis.

**Comment by jianchang512** [comment]
Is it a free account or a paid account? If it is free, there are restrictions

**Comment by vedanthkadam555** [comment]
My elevenlabs account is free account.

**Comment by vedanthkadam555** [comment]
Chatgpt Translation also not working ![IMG_20240122_100407.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/34c3875d-65af-44c5-8d35-a2c57696da1b)

**Comment by jianchang512** [comment]
No error message visible, please check for errors. There may be reasons for errors when not in use

**Comment by jianchang512** [comment]
It seems that you filled in the wrong chatGPT API address

**Comment by vedanthkadam555** [comment]
And for Chatgpt also we need Paid Subscription? To use that?

**Comment by jianchang512** [comment]
ChatGPT free account is basically unavailable, only allowing 3 requests per minute as API

**Comment by vedanthkadam555** [comment]
I will buy paid GPT account. Only if it works well. If you have that. Can you please try the video link which I sent you earlier.

**Comment by jianchang512** [comment]
large-v3 model

Hindi
```
1
00:00:00,000 --> 00:00:30,000
तो फाइनली बिडो कूमा ने अपना पंच सैटन पर चड़ी थिया, और सही में ये पंच लिटरली काफी जादा सेटिस्फाइंग था, बस एक आदा और चड़ जाता ना, तो पूरा कूमा का दर्द मेरे अंदर से भी निकल जाता, बट हम इतने में भी खुश हैं, क्योंकि

2
00:00:30,000 --> 00:01:00,000
जैसे की कूमा में सेल्फ डिस्टक्शन मेकनिज्म डाला ही नहीं गया, लेकिन जो मेकनिज्म डाला गया है कूमा में, उसके बापजूद भी कूमा जिन्दा कैसे है, एंड पनी तक कैसे पहुँचा है, जिनको हम इस वीडियो में जानेंगे, तो चेक्टर 1104 की सुरुवा

3
00:01:00,000 --> 00:01:30,000
दिया था, हे वेगा पंग, आखिर ये क्या सीन है, लेकिन विचारे वेगा पंग के भी, कूमा को देखकर खोब शुरुवा होते हैं, एंड इतने में ही कूमा अपना एक ही पंच सैटन पर बरसा देता है, जिससे उसकी रेल बन जाती है, और ये रेल जाके टकराती है वहा

4
00:01:30,000 --> 00:02:00,000
मूव कर पा रहे होते हैं, जिससे कई बनी को बचाने भागते हैं, एंड डॉक्टर वेगा पंग तसली से बैट कर, सैटन द्वारा पुझे गए सिनेरियोस के वारे में, कि आखिर कूमा जिन्दा कैसे है और यहां तक कैसे पूचा है, अपनी खटेवी कोपली से सोचने ल

5
00:02:00,000 --> 00:02:30,000
अक्टिवेट किया था, जिसकी वज़े से वो किसी भी ओर्डर को रिसीप करने में इंकैपेबल बन जाता है, लेकिन फिर भी डॉक्टर वेगा पंग की खोपडी, कूमा के यहां आने का रीजन नहीं खोच पाती, लेकिन अचाने की उसे कूमा के ब्रेड लाइन से लिटे

6
00:02:30,000 --> 00:03:00,000
वो एजिली अपनी पावर से रीजनेट कर लेता है, और सैटन की इस पावर के बारे में भी अपने को कोई आइडिया नहीं था, और वो अगेन वही अटेक्ट यूज़ करता है, जिसे उसने लास्टली बनी पर यूज़ किया था, लेकिन इस पॉइंट अफ टाइम पर कू

7
00:03:00,000 --> 00:03:30,000
जो कि सैटन के बोड़ी के आरपार चला जाता है, लेकिन जैसे कि अपने वो पता है कि सैटन अप रीजन नेट भी कर सकता है, तो इस अटेक्ट का कोई फायदा नहीं होता, लेकिन वहाँ कि जारू फ्रैंक के पीछे आकर अपनी किक से उसे डेल कर देता है, और इस पॉइ

8
00:03:30,000 --> 00:03:38,920
और तुम भी मेरे तरह कुमा के इस पंच का वेट कर रहे होगे, तो वीडियो का एक लाइक करके जाना, और चैनल पर अगर नए हो तो चैनल को सब्सक्राइब मारो, मिलता है तुमसे एक और चैप्टर के एक्स्प्रिणेशन में

```

English
```
1
00:00:00,000 --> 00:00:30,000
So finally Bido Kuma landed his punch on Satan, and in fact this punch was
literally very satisfying, if only one more punch had been landed, then all the
pain of Kuma would have gone out of me too, but we are happy even with this. ,
Because

2
00:00:30,000 --> 00:01:00,000
Like, self-destruction mechanism has not been put in Cooma, but despite the
mechanism which has been put in Cooma, how is Cooma alive, and how did it reach
the end, which we will know in this video, then the beginning of Sector 1104.

3
00:01:00,000 --> 00:01:30,000
Had given, Hey Vega Pang, what a scene is this, but even the thoughts of Vega
Pang, after seeing Kuma, they start getting restless, and just then Kuma rains
his single punch on Satan, due to which he becomes a rail, And this train hits
there

4
00:01:30,000 --> 00:02:00,000
are able to move, causing many to run to save the bunny, and Doctor Vega Pang
calmly bats, talking about the scenarios suggested by Satan, as to how Kouma is
alive and even asking, with his sour copy. lets think

5
00:02:00,000 --> 00:02:30,000
Was activated, due to which he becomes incapable of receiving any orders, but
still Doctor Vega Pangs skull is unable to find the reason for coming to Koomas
place, but suddenly he is taken to Koomas bread line.

6
00:02:30,000 --> 00:03:00,000
He easily regenerates with his power, which Satan had no idea about, and he
again uses the same attack that he used last time, but at this point of time.
coo

7
00:03:00,000 --> 00:03:30,000
Which goes through Satans body, but as he knows that Satan can also net in the
up region, then this attack is of no use, but there Jaru comes behind Frank and
defeats him with his kick. does, and this poi

8
00:03:30,000 --> 00:03:40,800
And like me, you too must be waiting for this punch of Kuma, then do like the
video, and if you are new to the channel then hit subscribe to the channel, see
you in the explanation of another chapter.
```


**mp4**

https://drive.google.com/file/d/1ZAtiiARUfaFTzyaTz_1rE76Qp9PfQLfP/view?usp=sharing



The Openai Whisper model has always had this problem, as it cannot accurately recognize languages with consistent pronunciation but different writing styles. For example, Chinese has two writing styles: Simplified and Traditional, but with consistent pronunciation. When recognizing Chinese, the original intention was to recognize Simplified Chinese, but always recognized as Traditional Chinese.

**Comment by vedanthkadam555** [comment]
Oh Nice. Large v3 does work well. Now there is not much issue with Translation. 

But if you observe the video the first Sentence till "Because" is stopping at 18 Seconds. And there is a Pause till 30 Seconds. 

I also tried to use voice acceleration to fix that. But still it is giving that Pause. What should I do ma'am.

**Comment by jianchang512** [comment]
Try using the whole  mode in conjunction with voice acceleration or video deceleration. "countdown_sec" in videotrans/set.ini, Set to 0 to skip pause. Restart software

**Comment by vedanthkadam555** [comment]
Ma'am Software Runs without Internet too?

**Comment by vedanthkadam555** [comment]
Ma'am Look I have selected "whole"
And Enable "Voice Acceleration"
Also Edited "Countdown sec=0"

And When I restart and run the project. Then it gave me output with the pause.

**Comment by jianchang512** [comment]
countdown_sec  set 1

**Comment by vedanthkadam555** [comment]
Ma'am I set Countdown Sec to 1


Still I am getting Pause

**Comment by jianchang512** [comment]
？record video

**Comment by vedanthkadam555** [comment]
https://github.com/jianchang512/pyvideotrans/assets/144011548/32cd00c9-4349-4b75-bbe3-8a7dfe469af4

**Comment by vedanthkadam555** [comment]
Ma'am can we please Connect on Telegram? 

My User ID : t.me/Maximum51

**Comment by jianchang512** [comment]
I don’t see any problem. If the execution has been completed, of course it will be displayed like this. Then select again and continue clicking to continue execution.
You record a video of the entire process starting from opening the software, selecting the video, and then executing it.

**Comment by vedanthkadam555** [comment]
> countdown_sec  set 1
> 
> print screen 

You about about something "Print screen" in this message.  what should I do with that?

I just did Countdown_sec to 1

**Comment by jianchang512** [comment]
After changing to 1, it should be paused for 1 second before automatically continuing.
I tested it and there was no problem. If there is a problem on your end, please change it to 1 and record the screen

**Comment by vedanthkadam555** [comment]
Ok I have put on recording. Till then can you please check this video. 

Take this video. It is in Original Hindi Language. And need to Target in English. Please give me this video without pause. Let's see how it works for you. 

https://youtu.be/a5PyzSDIwLE?si=1XQEC42q3HWv7pWj

Original: Hindi

Target: English

Thank you

**Comment by vedanthkadam555** [comment]
Here I recorded the whole process.

https://drive.google.com/file/d/1APx3HgofU76tahBbtEPc4dPYzKVyN3tp/view?usp=sharing

**Comment by jianchang512** [comment]
There will definitely be pauses because automatic recognition always has errors. Intentionally reserving pauses for manual adjustment. If you don't want the 60 second pause, changing the parameter  "countdown_sec" to 1 will change it to pause for 1 second before continuing. If you want to completely avoid this prompt, it is not allowed

**Comment by vedanthkadam555** [comment]
Speech recognition is done perfectly with Large V3 model. But output speech and the video is not aligned with audio. 

Because when we convert Hindi to English. Then English Speech will take less time to complete. 

So there is a Long pause after 14 seconds to 30 Seconds. But if i enable the voice acceleration it should make the speech faster or slower that it should Align with the video.

**Comment by jianchang512** [comment]
its normal

The pronunciation duration in different languages after translation is different. For example, a sentence in Chinese is 3s, which may be 5s when translated into English, leading to inconsistent duration and video.

2 solutions:

1. Forced dubbing to speed up and play, in order to shorten the dubbing duration and align with the video 


2. Forced video to play slowly, in order to prolong the video duration and align with the dubbing.

**Comment by vedanthkadam555** [comment]
You're Correct. 

![IMG_20240124_173119.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/3f1bba7c-2930-46de-a449-a3061ad95d69)

And you also gave two solutions for this. Which are "Voice Acceleration" and "Video Slow". 

But they're not working.

**Comment by vedanthkadam555** [comment]
By enabling the Voice Acceleration. The pause should be removed. As it will force voice over to align with the video. 

But after enabling that also. It not giving me same output with long pause of 15 seconds.

**Comment by jianchang512** [comment]
Does the sound not accelerate after selecting automatic acceleration? Or is there no slow playback after selecting the video to slow down?

**Comment by vedanthkadam555** [comment]
> Does the sound not accelerate after selecting automatic acceleration? Or is there no slow playback after selecting the video to slow down?

Yesss. Both the features are not working.

**Comment by vedanthkadam555** [comment]
Ma'am you please try this video. And

Enable the Voice Acceleration or Video Slow Feature 

https://youtu.be/a5PyzSDIwLE?si=1XQEC42q3HWv7pWj


Convert this

Source Original: Hindi

Target: English

**Comment by jianchang512** [comment]
will faster

**Comment by vedanthkadam555** [comment]
Ma'am I have another doubt. 

I'm now using Text to Speech Synthesis Feature.

But in that it is giving long pause after every "Full Stop.". 

How can I Decrease that long pause.

**Comment by jianchang512** [comment]
dont understand

**Comment by jianchang512** [comment]
https://elevenlabs.io/dubbing

 elevenlab's  video translate and dubbing ,very well

**Comment by vedanthkadam555** [comment]
Ma'am I have enabled Cuda. 

After that it is giving me some error. 

And I have Properly Installed the Cuda in my Pc. Also Checked in CMD. That is showing me the Version. So Installation is done properly. And also Driver is at latest version. 

Still it's giving me error.

**Comment by vedanthkadam555** [comment]
> https://elevenlabs.io/dubbing
> 
>  elevenlab's  video translate and dubbing ,very well

But Ma'am. It's Not Free. It's Paid.

**Comment by vedanthkadam555** [comment]
I got this error. after enable of CUDA.
![Screenshot (1)](https://github.com/jianchang512/pyvideotrans/assets/144011548/94333537-9917-411c-a4c5-65313c6afceb)

**Comment by jianchang512** [comment]
update to v0.9983

https://github.com/jianchang512/pyvideotrans/releases/tag/v0.9983

**Comment by vedanthkadam555** [comment]
![IMG_20240125_135940.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/fc660980-fead-4f6a-a346-261d4e6e2bf0)

Getting this error. If i enable CUDA. 

I'm using latest 84 version.
