### ISSUE TITLE
can you add multi speaker for multi role 

### ISSUE THREAD

**Issue by guowei3399** [jianchang512/pyvideotrans#194]
这2天设置多角色tts, 都快疯了, 每次设错一个就要重来一遍, 好几个角色,尴尬... 

能否设置speakers, 在speaker 里面设tts ,这样我只要设定speaker, 就可以轻松完成, 不需要每次重复设定tts voice

**Comment by guowei3399** [comment]
对了,今天设了几次 elevenlabtts, 导出的都是空白音频, 11lab的api 配置好的. 不知道哪里的问题

**Comment by jianchang512** [comment]
> 这2天设置多角色tts, 都快疯了, 每次设错一个就要重来一遍, 好几个角色,尴尬...
> 
> 能否设置speakers, 在speaker 里面设tts ,这样我只要设定speaker, 就可以轻松完成, 不需要每次重复设定tts voice

这个无法实现，难度和复杂度太大，作为一个免费项目不太现实。





> 对了,今天设了几次 elevenlabtts, 导出的都是空白音频, 11lab的api 配置好的. 不知道哪里的问题

这个首先确定你是不是免费账号，免费账号有限制，如果是付费账号，看看 logs目录下的出错时的日志信息
