### ISSUE TITLE
deteccion speaker

### ISSUE THREAD

**Issue by komangulo** [jianchang512/pyvideotrans#195]
Hello my friend! 
Would there be any way that in video with different speakers the application would automatically detect which are the different people who are speaking and assign them a voice automatically as you tell it?
And is it possible to clone the voice of the speakers?
thank you very much for your work.

你好，我的朋友！
有什么方法可以让应用程序自动检测视频中的不同发言者，并根据您的指示自动为他们分配声音？
是否可以克隆发言人的声音？
非常感谢你的工作。

**Comment by jianchang512** [comment]
openai whisper mode  dont support detect  speaker.

no plan to clone voice
