### ISSUE TITLE
dont run sp.exe after install all CUDA enviroment

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#196]
https://github.com/jianchang512/pyvideotrans/assets/428820/8758558b-886e-4f00-9563-ea36a302bbaa

how can solve this?

**Comment by johnfelipe** [comment]
Only working in this moment is videotrans-v0.998

**Comment by jianchang512** [comment]
In the sp. exe directory, input `cmd` from the address bar, then press enter, drag sp. exe to the open cmd window, press enter, and see what is output

**Comment by johnfelipe** [comment]
https://github.com/jianchang512/pyvideotrans/assets/428820/0e3e8c31-85a8-4ba3-b330-b75763e3455b

show splash and 3 sec later down

**Comment by jianchang512** [comment]
update to v0.9983

https://github.com/jianchang512/pyvideotrans/releases/tag/v0.9983
