### ISSUE TITLE
无法拖动文件至视频工具箱处理

### ISSUE THREAD

**Issue by bingsunny0730** [jianchang512/pyvideotrans#198]
![GIF 2024-1-24 17-28-24](https://github.com/jianchang512/pyvideotrans/assets/131505889/b0dabd24-d6d7-43e9-9245-7a0f03b3b428)

基本都是拖动了不显示内容，光标变为禁止拖动符号，只试了其中几个，“文字合成为语音”无法拖入srt文件，“音视频格式转换”无法拖入任何音视频文件，貌似有提示拖拽功能的基本都不能拖入，已经使用管理员身份运行了。这是为啥？？

**Comment by jianchang512** [comment]
右上角版本号，如果不是 0.9982，则升级

**Comment by bingsunny0730** [comment]
![GIF 2024-1-25 15-08-58](https://github.com/jianchang512/pyvideotrans/assets/131505889/e986d5b4-63a5-4b9b-869e-ec0b39eaa758)
其实上方录制的版本已经是0.9982，重新下载升级至0.9984还是同样的问题，不知为何。。。
能否在“音视频格式转换"标签页上增加类似选择目录文件的功能，而非只有拖入，就像其它标签页有选择文件或拖入这两种选择方式（至少有平替性）

**Comment by jianchang512** [comment]
macxi't

**Comment by bingsunny0730** [comment]
好的，谢谢大佬

**Comment by jianchang512** [comment]
升级到 0.9985
