### ISSUE TITLE
错误提示：list indices must be integers or slices not str

### ISSUE THREAD

**Issue by wpillow87** [jianchang512/pyvideotrans#199]
![image](https://github.com/jianchang512/pyvideotrans/assets/23335768/8823189c-5fb6-48d0-9a82-eae208e50962)

系统：windows11

软件版本：0.9982.用的是Windows部署包直接安装的。

### 问题出现在英文字幕翻译为中文的阶段。
使用百度api翻译英文：
情况1：只有英文，正常。情况2：srt格式错误，会提示错误。如下图：
![4N2W6PYT$Y7627L(LDXL} 4](https://github.com/jianchang512/pyvideotrans/assets/23335768/386e501d-008a-42df-baa6-3845b19c6b9b)

情况3：srt格式为序号、时间、英文，不会提示错误，界面会一直显示start translate。如下图
![HCX~)(O2FJE6D_ 8(A7G8`E](https://github.com/jianchang512/pyvideotrans/assets/23335768/0af218df-fae4-4adf-b7fa-08461991e6ff)
log文件内容如下：
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:start translate
ERROR:VideoTrans:baidu api error:[error]百度翻译失败:Invalid Access Limit

以下是执行左侧第一项【标准功能模式】的log文件
用百度api和deeplx都出现这个错误提示。
deeplx时的log
--- 

INFO:VideoTrans:deeplx:data={'text': "now i want to take this opportunity to give you some advice.  over the course of your life, you will find that things are not always fair.  you will find that things are not always fair. .\nyou will find that things happen to you, that you do not deserve, and that are not always warranting.  but you have to put... .\nput your head down and fight fight fight never ever ever give up things will work out .\nworkout just fine.  look at the way i've been treated lately.  especially by the media. .\nno politician in history.  and i say this with great c.s. security has been treated worse.  one more answer. .\nor unfairly. you can't let them get you down.  you can't let the critics and the naysayers get in the way of your dreams. .\nadversity makes you stronger. don't give in, don't back down, and never stop doing what you know is right. .\neverything worth doing, ever, ever, ever can be.  and the more righteous you're fighting, the more opposition that you will face. .\nin the name of god, i am not a real god  i am not a god, i am not a god  i am not a god, i am not a god .\nwho thinks i should run for president?  who thinks i should run for president? .", 'source_lang': 'auto', 'target_lang': 'ZH'}
ERROR:VideoTrans:[error]DeepLX error:EOF occurred in violation of protocol (_ssl.c:997)
ERROR:VideoTrans:deeplx error:res='[error]DeepLX error:EOF occurred in violation of protocol (_ssl.c:997)'
INFO:VideoTrans:list indices must be integers or slices, not str

百度api时的log文件如下：
--- 
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:G:/AI/videotrans/特朗普这段脱稿演讲，我可以看一天！.mp4
INFO:VideoTrans:Processing 1/1
INFO:VideoTrans:开始处理...
INFO:VideoTrans:G:/AI/videotrans/_video_out/特朗普这段脱稿演讲，我可以看一天！
INFO:VideoTrans:1
0:00:00 --> 0:00:10,500

0:02:50 --> 0:03:00,500
please rise for the national flag and anthem of the people's republic of china. .

19
0:03:00 --> 0:03:08,907
let's say china. .
INFO:VideoTrans:等待修改原始字幕,以便翻译更准确/点击继续
INFO:VideoTrans:60 秒后自动翻译，你可以暂停后去修改字幕，以便翻译更准确
INFO:VideoTrans:59 秒后自动翻译，你可以暂停后去修改字幕，以便翻译更准确
INFO:VideoTrans:开始翻译
INFO:VideoTrans:开始翻译
INFO:VideoTrans:list indices must be integers or slices, not str

**Comment by wpillow87** [comment]
deeplx的问题是因为地址输入的是https://localhost:1188/translate.出现的是ssl错误997，把https的s去掉就可以了。

**Comment by jianchang512** [comment]
下载0.9983试试

**Comment by wpillow87** [comment]
> 下载0.9983试试
## 前三张图是想说问题依旧存在。
![](assets/2024-01-25-15-35-28-image.png)
![](assets/2024-01-25-15-35-41-image.png)
![](assets/2024-01-25-15-35-56-image.png)

## log文件最后的内容如下

---

INFO:VideoTrans:开始翻译
INFO:VideoTrans:这五辆坦克真的要向这50万美元发射导弹了。
INFO:VideoTrans:Google 返回响应:{'error_code': '54003', 'error_msg': 'Invalid Access Limit'}
INFO:VideoTrans:Baidu error:[error]百度翻译失败:Invalid Access Limit
INFO:VideoTrans:start translate

### 单独使用百度翻译时是正常的。
![](assets/2024-01-25-15-36-30-image.png)
