### ISSUE TITLE
macOS 14 使用源码无法正常运行

### ISSUE THREAD

**Issue by Leslie-Luo** [jianchang512/pyvideotrans#20]
系统版本：**macOS 14.1**
Python版本：**3.9.6** 「系统自带版本」

使用 `pip3 install -r requirements.txt` 安装依赖后执行 cli 命令
`python3 cli.py --source_mp4 "/Users/leslie/Downloads/xxxx.mp4" --source_language ja --target_language zh-cn --proxy "http://127.0.0.1:7890" --voice_replace zh-CN-XiaoxiaoNeural`
终端输入错误提示
`Traceback (most recent call last):
  File "/Users/xxx/Documents/Code/GitHub/pyvideotrans/cli.py", line 8, in <module>
    from configure.tools import get_list_voices, get_large_audio_transcription, logger, runffmpeg,delete_temp
  File "/Users/xxx/Documents/Code/GitHub/pyvideotrans/configure/tools.py", line 19, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
`

再使用 pip3安装 openai
`pip3 install openai `
安装完成后再次执行 cli 命令，提示这个错误
`
Traceback (most recent call last):
  File "/Users/xxx/Documents/Code/GitHub/pyvideotrans/cli.py", line 8, in <module>
    from configure.tools import get_list_voices, get_large_audio_transcription, logger, runffmpeg,delete_temp
  File "/Users/xxx/Documents/Code/GitHub/pyvideotrans/configure/tools.py", line 25, in <module>
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'
`

**Comment by jianchang512** [comment]
macos暂未测试
可能存在问题。

先执行下 pip install openai再试试

**Comment by printfCYQ** [comment]
@Leslie-Luo 在Mac上能成功运行了吗

**Comment by Leslie-Luo** [comment]
> @Leslie-Luo 在Mac上能成功运行了吗

成功了
