### ISSUE TITLE
两种安装方式目前都有点问题...麻烦大佬了

### ISSUE THREAD

**Issue by raccooooons** [jianchang512/pyvideotrans#201]
预编译模式：
目前简单使用，未配置CUDA
sl: ffmpeg error:errs='Error opening output file D:/Users/xsccc/Downloads/_video_output'/s1/en
![image](https://github.com/jianchang512/pyvideotrans/assets/25006781/e9affc05-8971-4b92-bf3c-eb460981571e)

自己编译模式：
![image](https://github.com/jianchang512/pyvideotrans/assets/25006781/eb7bdaa2-e553-490d-87f5-c173c6bb3135)
main window name 'g' is not defined
另外可能直接建议上3.10以上比较好，我用3.9会有报错

**Comment by jianchang512** [comment]
重新下载
