### ISSUE TITLE
software getting closed

### ISSUE THREAD

**Issue by vedanthkadam555** [jianchang512/pyvideotrans#203]
Ma'am Software getting closed immediately after completion of hindi translation. getting closed automatically.

https://drive.google.com/file/d/1WXWSttR9AnF48obc52KDvnK_MAn1LtVG/view?usp=sharing

**Comment by jianchang512** [comment]
videotrans/set.ini 
beam_size   best_of   
set is 1 and  restart

**Comment by vedanthkadam555** [comment]
> videotrans/set.ini 
> beam_size   best_of   
> set is 1 and  restart

I have set both to 1

Still the software automatically getting closed.

**Comment by jianchang512** [comment]
Open the Task Manager and pay attention to how much GPU memory is occupied when the software crashes

**Comment by vedanthkadam555** [comment]
I recorded whole process by opening performance of GPU from task manager.

https://drive.google.com/file/d/1Ir0awLX9xkH4yJXSrr9z7GJexPTmhnh1/view?usp=sharing

I also getting other error with other file

error : local variable "trans" referenced before assignment

**Comment by jianchang512** [comment]
restart soft

**Comment by vedanthkadam555** [comment]
> restart soft

I closed the software and restarted it many times

**Comment by jianchang512** [comment]
select google  and exec，if error,rstart

**Comment by vedanthkadam555** [comment]
I have already selected "Google" in the Translate Language. Look at my previous video link ma'am

**Comment by jianchang512** [comment]
open videotrans/set.ini  .screen image

**Comment by jianchang512** [comment]
medium model  retry

**Comment by vedanthkadam555** [comment]
![IMG_20240126_174430.jpg](https://github.com/jianchang512/pyvideotrans/assets/144011548/03db1d3d-9126-43a2-83b5-cdaf99e2b0fe)

Ma'am Medium model won't detect text properly

**Comment by jianchang512** [comment]
LG3 will occupy a very large amount of graphics card memory, and videos larger than 20m can easily run out of flash. Further optimization will be considered to save some graphics card memory

**Comment by jianchang512** [comment]
set.ini
no_decode set to  true

retry

**Comment by vedanthkadam555** [comment]
> set.ini no_decode set to true
> 
> retry

I have set it to "True". Still Software getting closed automatically. And I'm only using 1 minute video.
