### ISSUE TITLE
local variable "trans" referenced before assignment

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#205]
![SNAG-0260](https://github.com/jianchang512/pyvideotrans/assets/428820/542d2c95-3c6a-488a-b4d3-4faff5bd0da0)

i want to dubbin from english to english - NOT WORKS
i want to dubbing from english to spanish and show me "local variable "trans" referenced before assignment"

how solve this?

**Comment by jianchang512** [comment]
restart will good or 

![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/d4f96af2-f94a-4d2c-be43-8222eaecd6ca)

**Comment by yousei521** [comment]
9984版本。删除注册表中这个文件夹后仍然报这个错误

**Comment by jianchang512** [comment]
重启软件即可

**Comment by jianchang512** [comment]
或升级到 0.9985
