### ISSUE TITLE
stock in 93.2% - dubbing english to spanish using chatgpt like translate channel

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#206]
![SNAG-0261](https://github.com/jianchang512/pyvideotrans/assets/428820/abc05bee-b9ca-4da3-947f-ea3866dcfa38)

translation is rare, because put a lot of text in one section of time:

	106
	00:13:40,110 --> 00:13:56,620
	["como puedes ver defendemos la URL así que vamos a ver vamos a quitar esto y esta es la respuesta final", "eso fue un desafío intermedio con Splunk no involucró tantos filtros tanto procesamiento", "búsquedas en Splunk fue solo un análisis simple de un incidente que nos requirió", "entender los ID de eventos y cómo saltar entre diferentes etapas durante una", "compromiso ok chicos espero que les guste eso y definitivamente los veré en", "el próximo video"]

this is log after translate to spanish:

	INFO:VideoTrans:Wait to modify the dubbed subtitles / click continue
	INFO:VideoTrans:29Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:28Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:27Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:26Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:25Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:24Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:23Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:22Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:21Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:20Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:19Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:18Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:17Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:16Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:15Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:14Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:13Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:12Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:11Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:10Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:9Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:8Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:7Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:6Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:5Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:4Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:3Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:2Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:1Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:0Automatically merge in seconds, you can click Pause to modify the subtitles so that the dubbing is more accurate
	INFO:VideoTrans:Start voiceover [1/32]
	INFO:VideoTrans:Start voiceover [2/32]
	INFO:VideoTrans:Start voiceover [3/32]
	INFO:VideoTrans:Start voiceover [4/32]
	INFO:VideoTrans:Start voiceover [5/32]
	INFO:VideoTrans:Start voiceover [6/32]
	INFO:VideoTrans:Start voiceover [7/32]
	INFO:VideoTrans:Start voiceover [8/32]
	INFO:VideoTrans:Start voiceover [9/32]
	INFO:VideoTrans:Start voiceover [10/32]
	INFO:VideoTrans:Start voiceover [11/32]
	INFO:VideoTrans:Start voiceover [12/32]
	INFO:VideoTrans:Start voiceover [13/32]
	INFO:VideoTrans:Start voiceover [14/32]
	INFO:VideoTrans:Start voiceover [15/32]
	INFO:VideoTrans:Start voiceover [16/32]
	INFO:VideoTrans:Start voiceover [17/32]
	INFO:VideoTrans:Start voiceover [18/32]
	INFO:VideoTrans:Start voiceover [19/32]
	INFO:VideoTrans:Start voiceover [20/32]
	INFO:VideoTrans:Start voiceover [21/32]
	INFO:VideoTrans:Start voiceover [22/32]
	INFO:VideoTrans:Start voiceover [23/32]
	INFO:VideoTrans:Start voiceover [24/32]
	INFO:VideoTrans:Start voiceover [25/32]
	INFO:VideoTrans:Start voiceover [26/32]
	INFO:VideoTrans:Start voiceover [27/32]
	INFO:VideoTrans:Start voiceover [28/32]
	INFO:VideoTrans:Start voiceover [29/32]
	INFO:VideoTrans:Start voiceover [30/32]
	INFO:VideoTrans:Start voiceover [31/32]
	INFO:VideoTrans:Start voiceover [32/32]
	INFO:VideoTrans:Extend video end 686347ms
	INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuvid -hwaccel_output_format nv12 -extra_hw_frames 2 -c:v h264_cuvid -y -sseof -3 -i C:/Users/GAMEMAX/Videos/pyvideotrans/renamemp4/CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)/novoice.mp4 -q:v 1 -qmin:v 1 -qmax:v 1 -update true d:/Users/GAMEMAX/Downloads/videotrans-v0.9984/tmp/CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)/last.jpg
	INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuvid -hwaccel_output_format nv12 -extra_hw_frames 2 -loop 1 -i d:/Users/GAMEMAX/Downloads/videotrans-v0.9984/tmp/CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)/last.jpg -vf fps=60,scale=1920:1080 -c:v h264_nvenc -crf 13 -to 00:11:26.347 -y d:/Users/GAMEMAX/Downloads/videotrans-v0.9984/tmp/CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)/last_clip.mp4
	INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuvid -hwaccel_output_format nv12 -extra_hw_frames 2 -c:v h264_cuvid -y -f concat -safe 0 -i d:/Users/GAMEMAX/Downloads/videotrans-v0.9984/tmp/1706224686.4587398.txt -c:v h264_nvenc -crf 13 -an C:/Users/GAMEMAX/Videos/pyvideotrans/renamemp4/CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)/novoice.mp4
	INFO:VideoTrans:Extend video 686347ms
	INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuvid -hwaccel_output_format nv12 -extra_hw_frames 2 -c:v h264_cuvid -y -i d:/Users/GAMEMAX/Downloads/videotrans-v0.9984/tmp/CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)/target.wav -c:a aac C:/Users/GAMEMAX/Videos/pyvideotrans/renamemp4/CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)/es.m4a
	INFO:VideoTrans:Synthesizing voice-over + hard subtitle
	INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuvid -hwaccel_output_format nv12 -extra_hw_frames 2 -c:v h264_cuvid -y -i C:\Users\GAMEMAX\Videos\pyvideotrans\renamemp4\CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)\novoice.mp4 -i C:\Users\GAMEMAX\Videos\pyvideotrans\renamemp4\CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)\es.m4a -c:v h264_nvenc -c:a copy -vf subtitles=tmp.srt C:\Users\GAMEMAX\Videos\pyvideotrans\renamemp4\CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC)\CyberIncidentInvestigationwithSplunk_TryHackMeInvestigatingwithSplunk(1080p_60fps_H264-128kbit_AAC).mp4

how solve this?

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/43d4ed9d-8282-4b73-ad59-26afeaa22a2f)

**Comment by jianchang512** [comment]
update 0.9985
