### ISSUE TITLE
源码部署出错

### ISSUE THREAD

**Issue by xialixx** [jianchang512/pyvideotrans#207]
我在winows 上部署，提示报这个错误，是什么原因呢？无法加载文件 D:\python\pyvideotrans-main\pyvideotrans-main\venv\Scripts\Activate.ps1，因为在此系统上禁止运行脚本。有关详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=13
5170 中的 about_Execution_Policies。
所在位置 行:2 字符: 1
+ venv/Scripts/activate
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by jianchang512** [comment]
用cmd命令行运行

如果powsershell  以.\开头执行

**Comment by xialixx** [comment]
还是不行，我按照源码（win下执行 %cd%/venv/scripts/activate），提示如下：
.\venv\Scripts\activate : 无法加载文件 D:\python\pyvideotrans-main\pyvideotrans-main\venv\Scripts\Activate.ps1，因为在
此系统上禁止运行脚本。有关详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execution_Policies
。
所在位置 行:1 字符: 1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by jianchang512** [comment]
如果使用 powsershell ,要遵循powershell的安全限制，自行搜索下  https://cloud.tencent.com/developer/article/2221046

或者 源码目录下，地址栏中输入 cmd，在打开的cmd窗口中输入命令，cmd和powershell不是一个东西
