### ISSUE TITLE
语音识别文字，转来出的文字不完整

### ISSUE THREAD

**Issue by kevinqingqinga** [jianchang512/pyvideotrans#209]
语音识别文字，如果用Large-v3模型，转来出的文字不完整，只转了60%，后面的都没有了。

**Comment by jianchang512** [comment]
显存多大，低于6g不要用lg模型

**Comment by kevinqingqinga** [comment]
我的笔记本现存才2G. 应该是这个原因了。谢谢您。

________________________________
