### ISSUE TITLE
When will have diarization?

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#211]
Put name of speaker

Speaker 1: xxxxxx
Speaker 2: yyyyyy
Speaker 2: zzz zzz
.
.
.
Etc

It seems to already be in some Whisper projects.
I was able to make this caption through the command prompt (whisper-ctranslate2).
These functions also seem to already exist in some projects on SubtitleEdit's Whisper, but I couldn't run them because they need the token on huggingface.co.
WhisperX also already has Diarization in the project, but it does not have a parameter field in SubtitleEdit.
Do we have any progress in Faster-Whisper?

**Comment by jianchang512** [comment]
It's too complicated, and that requires a graphics card with a storage capacity of 8GB or more, so we won't consider it for now
