### ISSUE TITLE
not works english to spanish subtitle translation process with latest version / translation have looong text in timestap

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#212]
spanish translation using chatgpt channel:
https://gist.github.com/johnfelipe/11dbb432e1f53b937fae5dc2d0152642

original in english works fine:

https://gist.github.com/johnfelipe/abedda886a030d15e4557a7534c66896

**Comment by jianchang512** [comment]
retry at v0.9985
