### ISSUE TITLE
Software getting closed in New Version too. 

### ISSUE THREAD

**Issue by vedanthkadam555** [jianchang512/pyvideotrans#215]
Software getting Closed automatically while translating the text.

**Comment by jianchang512** [comment]
use medium model

**Comment by jianchang512** [comment]
After updating the version, it is necessary to reset the set.ini file.

**Comment by vedanthkadam555** [comment]
I used Base Model. still it is getting closed automatically.

**Comment by vedanthkadam555** [comment]
Can you please check that by accessing my screen.

Anydesk address: 1 693 182 991

**Comment by jianchang512** [comment]
ok

**Comment by jianchang512** [comment]
Sure, take your time. I'll be here if you have any further questions or need assistance.

**Comment by jianchang512** [comment]
install python 3.10 and git 

git pull source code ,deply

**Comment by vedanthkadam555** [comment]
okay. and not the latest python version?

**Comment by jianchang512** [comment]
3.10.x

**Comment by vedanthkadam555** [comment]
installed python 3.10.10 and Git

**Comment by jianchang512** [comment]
anydesk

**Comment by vedanthkadam555** [comment]
1 693 182 991

**Comment by jianchang512** [comment]
instal cudnn for cuda12.x

1. download cudnn for cuda12.x
2. extract zip, bin  & lib & include folder copy to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3 .

**Comment by vedanthkadam555** [comment]
> instal cudnn for cuda12.x
> 
> 1. download cudnn for cuda12.x  https://developer.nvidia.com/rdp/cudnn-download
> 2. extract zip, bin  & lib & include folder copy to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3 .

Downloaded this.

1693182991

**Comment by jianchang512** [comment]
install  copy ，set system environ var

**Comment by jianchang512** [comment]
https://juejin.cn/post/7318704408727519270

**Comment by jianchang512** [comment]
update to 0.9987

**Comment by vedanthkadam555** [comment]
I dont know how to update by doing program. can I install the update with normal exe file?

**Comment by jianchang512** [comment]
download  exe version  0.9987 from release

**Comment by vedanthkadam555** [comment]
Now that is fixed. software not getting closed while translating.

**Comment by vedanthkadam555** [comment]
but now it is giving different hindi translation than before. translation is inaccurate. and Im using Large V3 model.

**Comment by vedanthkadam555** [comment]
But I have found an alternate solution for accurate translation of Hindi video. 

for that I have selected 
Source : English
Target : English

This settings giving me accurate Translation. but after completing the process. in the Output file it is giving me the original video. 
it is not dubbing the video.
![Screenshot (3)](https://github.com/jianchang512/pyvideotrans/assets/144011548/42d5ec95-51a5-4363-becb-8955dd61e7f9)

**Comment by vedanthkadam555** [comment]
![Screenshot (4)](https://github.com/jianchang512/pyvideotrans/assets/144011548/3465d58c-c368-4624-aa0f-27a11d947243)
Ma'am this transcript is freaking Accurate... 99.99% Accurate translation.

But after completing the process it is giving me the original video. not the dubbed video. 

Ma'am Just fix this please. then everything will run smooth.

Any : 1 693 182 991

**Comment by jianchang512** [comment]
原语言和目标语言一样，那你是想他干什么呢？
这是无效的用法

**Comment by jianchang512** [comment]
open videotrans/set.ini and set temperature=1    , set  condition_on_previous_text=true

There will be better recognition results, but recognition is not related to translation

**Comment by jianchang512** [comment]
If you don't want it to be translated and instead use your own  local subtitles, then choose the language of your subtitles for the target language, and choose another language for the source language

**Comment by vedanthkadam555** [comment]
Anyway. I have found a Solution for this. I will make use of other features of this software. And I combine all of them manually.


Thank You Very Much for Awesome Support 🙏

**Comment by jianchang512** [comment]
If you don't want it to be translated and instead use your own local subtitles, then you can choose the source language and target language normally, just import the subtitles of the target language locally.

For example, if you want to translate Hindi to English, then choose Hindi as the source language, English as the target language, and import English subtitles. When the imported subtitles are detected, they will no longer be recognized and translated.
