### ISSUE TITLE
人声分离是否缺少配置文件？

### ISSUE THREAD

**Issue by newcomerinAC** [jianchang512/pyvideotrans#218]
人声分离时提示：No such file or directory: 'D:/xx/pyvideotrans/uvr5_weights/modelparams/4band_v2.json'
 
请问是不是少了配置文件呢？

**Comment by jianchang512** [comment]
下载完整包 升级不能只覆盖sp.exe

**Comment by newcomerinAC** [comment]
这是来自QQ邮箱的假期自动回复邮件。已收到邮件，谢谢！
