### ISSUE TITLE
解压后第一次执行报错

### ISSUE THREAD

**Issue by yuwine77** [jianchang512/pyvideotrans#22]
Traceback (most recent call last):
  File "sp.py", line 391, in <module>
  File "sp.py", line 89, in __init__
  File "sp.py", line 110, in initUI
AttributeError: 'MainWindow' object has no attribute 'translate_type'

**Comment by jianchang512** [comment]
英文界面版本?

**Comment by yuwine77** [comment]
对的

**Comment by jianchang512** [comment]
这个忘记加了。
如果方便可以将电脑设为中文界面或者使用源码版， configure/config.py 17行左右 `defaulelang="en"`  后面的都删掉

**Comment by jianchang512** [comment]
下载新版再试试，应该可以了
