### ISSUE TITLE
timestamp translation english to spanish using chatgpt is toooo long

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#221]
[es-en.zip](https://github.com/jianchang512/pyvideotrans/files/14091612/es-en.zip)

spanish - WRONG
![SNAG-0276](https://github.com/jianchang512/pyvideotrans/assets/428820/b671cc75-b82f-4f4e-ba61-f690e1b6d4aa)

english - PERFECT
![SNAG-0277](https://github.com/jianchang512/pyvideotrans/assets/428820/02770e58-7e95-4107-a91f-5700b36f37c0)

How solve that timestamp in spanish?

**Comment by jianchang512** [comment]
after `whisper mode` select  "whole"

**Comment by johnfelipe** [comment]
Give me screenshots pls

**Comment by jianchang512** [comment]
![pen1](https://github.com/jianchang512/pyvideotrans/assets/3378335/299c180d-c37a-4758-8d14-8a81a83eaac9)

click whole select "first split"

**Comment by johnfelipe** [comment]
Sorry where "first split"?

**Comment by jianchang512** [comment]
![IMG_20240130_202956.jpg](https://github.com/jianchang512/pyvideotrans/assets/3378335/bf12bf52-986c-4d11-af5e-a2cd86738329)

**Comment by johnfelipe** [comment]
Yes, that is already selected.
But Spanish translation have that timestamp with a lot of text, not related like English.
I'm select CHAT-GPT for translation
I put API key id and leave gpt3.5
Need to select another setup?

**Comment by jianchang512** [comment]
update to  0.9991，if also，change to google retry

**Comment by johnfelipe** [comment]
ok in this video shows:

- Transcribe to original lang - english, show lines and % (PERFECT)
- translate to spanish, begin with raw text and finish with lines (PERFECT)
- embed hard subtitles

https://drive.google.com/file/d/1WNnEhtLXStrnY6jql16TYlKXcGPTNPx-/view?usp=drivesdk

works with chatgpt

**Comment by johnfelipe** [comment]
180
	00:24:29,430 --> 00:24:31,790
	Las reglas de Sigma son reglas para convertir o convertir consultas de Splunk u
	otros dispositivos o aplicaciones SIM en una fórmula universal y unificada que
	puede ser utilizada por la comunidad de inteligencia de amenazas. Si observa el
	repositorio de Github de Sigma, Sigma HQ, verá que es un formato genérico y
	abierto de firma que le permite describir eventos relevantes de registros de
	manera sencilla. Sigma no es diferente de las consultas de Splunk u otros
	softwares SIM, es solo un formato. ¿Por qué usamos Sigma? Lo usamos para
	compartir reglas o consultas entre la comunidad de inteligencia. Si vas al
	repositorio y haces clic en las reglas, verás reglas para cada categoría. Por
	ejemplo, si quiero reglas para Windows, puedo ir a la categoría de Windows,
	hacer clic en malware y ver las reglas de malware aquí. Por ejemplo, antivirus
	que explota, esta es la fórmula de Sigma. Si quieres convertir esto a Splunk o a
	otro formato basado en el producto que estés utilizando para caza de amenazas o
	gestión de eventos, puedes usar el codificador.io, pegar el formato de Splunk y
	seleccionar tu producto aquí, por ejemplo, en nuestro caso ...

	181
	00:26:05,770 --> 00:26:09,730
	estamos usando Splunk si tienes otro producto puedes seleccionarlo de la lista y
	hacer clic en traducir ahora, esta es la consulta que puedes usar en la barra de
	búsqueda de Splunk, ¿de acuerdo? Entonces, ahora las preguntas, necesitas
	seleccionar la característica de documento, ¿cuál es la consulta de Splunk para
	Sigma APT 29? Simplemente Sigma APT 29. Déjame volver a eso, ¿vale? Podemos
	usar, si no sabes cuál es el formato Sigma para una regla, puedes seleccionarlo
	de aquí o usar la funcionalidad de selección de documento. Aquí hay múltiples
	consultas Sigma que puedes usar, o puedes buscar entre las consultas, si tienes
	algo en mente. Por ejemplo, en la pregunta, queremos formar una consulta de
	Splunk para el grupo persistente avanzado 29. También podemos buscar en las
	consultas de Sigma para encontrar el equivalente en Splunk. Por ejemplo, apt29.
	Esta es la consulta de Splunk para apt29. En cuanto a la descripción, este
	método detecta una combinación sospechosa de línea de comandos de PowerShell
	utilizada por APT29 en una campaña contra tanques de pensamiento de EE.UU. y
	esta es la referencia a la que puedes hacer clic en Splunk Translate y esta es
	tu consulta de Splunk para sospechar que los registros generados o los eventos
	generados por la máquina que estás monitoreando o investigando contienen
	incidentes o huellas.

nop still not works, i will try with google then

**Comment by johnfelipe** [comment]
with google works
any other provider more acurate for translate?

**Comment by jianchang512** [comment]
may be deepl
