### ISSUE TITLE
ott-v0.1d无法下载模型

### ISSUE THREAD

**Issue by kevinqingqinga** [jianchang512/pyvideotrans#222]
![error](https://github.com/jianchang512/pyvideotrans/assets/139779464/dc7d25b6-ade2-44d6-8008-b2884d56a5c2)

**Comment by jianchang512** [comment]
这错误提示不是很明显吗，设置代理。仓库readme也有说明，可以百度网盘下载

![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/4b9ceaef-3fd5-4c32-a179-2e95b1853da5)

https://github.com/jianchang512/ott?tab=readme-ov-file#windows%E9%A2%84%E7%BC%96%E8%AF%91exe%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8

**Comment by kevinqingqinga** [comment]
谢谢回复，下载后，把文件放到哪个文件夹呢？
________________________________
发件人: okmyworld ***@***.***>
发送时间: 2024年1月30日 15:21
收件人: jianchang512/pyvideotrans ***@***.***>
抄送: kevinqingqinga ***@***.***>; Author ***@***.***>
主题: Re: [jianchang512/pyvideotrans] ott-v0.1d无法下载模型 (Issue #222)


这错误提示不是很明显吗，设置代理。仓库readme也有说明，可以百度网盘下载

image.png (view on web)<https://github.com/jianchang512/pyvideotrans/assets/3378335/4b9ceaef-3fd5-4c32-a179-2e95b1853da5>

https://github.com/jianchang512/ott?tab=readme-ov-file#windows%E9%A2%84%E7%BC%96%E8%AF%91exe%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8

―

**Comment by jianchang512** [comment]
上面回复的图片仔细看

解压后有个.local文件夹，覆盖到ott下，同名文件夹

**Comment by kevinqingqinga** [comment]
好的，非常感谢！
________________________________
发件人: okmyworld ***@***.***>
发送时间: 2024年1月30日 21:16
收件人: jianchang512/pyvideotrans ***@***.***>
抄送: kevinqingqinga ***@***.***>; Author ***@***.***>
主题: Re: [jianchang512/pyvideotrans] ott-v0.1d无法下载模型 (Issue #222)


上面回复的图片仔细看

解压后有个.local文件夹，覆盖到ott下，同名文件夹

―
