### ISSUE TITLE
dubbing is not merge or sync

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#224]
https://github.com/jianchang512/pyvideotrans/assets/428820/e7f3a1d5-6934-4e93-a1ee-f38cbaf50d07

if u see video unsyncronized dubbing with real english subtitles
how solve that?

**Comment by jianchang512** [comment]
![IMG_20240131_094859.jpg](https://github.com/jianchang512/pyvideotrans/assets/3378335/02524abb-76e5-4c83-8cac-9ac5227398ba)

**Comment by johnfelipe** [comment]
In UI witch option is each?

**Comment by jianchang512** [comment]
![IMG_20240131_104747.jpg](https://github.com/jianchang512/pyvideotrans/assets/3378335/e1d0c831-5c48-4eb4-a67d-b9c3b1822c1d)

**Comment by johnfelipe** [comment]
English to Spanish witch is better?
