### ISSUE TITLE
how can dubbing english to english with my voice using elevenlabsTTS

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#227]
![SNAG-0283](https://github.com/jianchang512/pyvideotrans/assets/428820/51b4ce93-ef51-4b03-a54d-b1e9b553dea3)

but output show same voice or original english voice in video

![SNAG-0284](https://github.com/jianchang512/pyvideotrans/assets/428820/cf749d5b-7476-4b02-8bfc-e19b7dc8b5f0)

**Comment by jianchang512** [comment]
The original language and the target language are the same, so dubbing operations will not be performed, which is illogical
