### ISSUE TITLE
is normal take a looong time for dubbing english to english -using video slow option- using subtitles imported by another app

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#228]
video slow option take more of 2 hours, that is normal, pls review this video:

https://drive.google.com/file/d/11vs6RY53n4Z_b_o9Kke_oHUK3dW1mey3/view?usp=drivesdk

340/387 to 343/387 in 4 min

If that normal how can performance?

if not normal how solve this?

**Comment by jianchang512** [comment]
The original language and the target language are the same, so dubbing operations will not be performed, which is illogical
