### ISSUE TITLE
Gemini not good spanish translation srt

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#233]
Gemini spanish to english: 30% bad parametrized
[gemini.zip](https://github.com/jianchang512/pyvideotrans/files/14142700/gemini.zip)
comparing:
![SNAG-0287](https://github.com/jianchang512/pyvideotrans/assets/428820/6a0635d0-90d3-4012-960f-00636d1765bf)

**Comment by jianchang512** [comment]
There's nothing you can do about it, just use a more effective translation.

**Comment by johnfelipe** [comment]
But is not translation is timestamp
