### ISSUE TITLE
自定义tts

### ISSUE THREAD

**Issue by windkind88** [jianchang512/pyvideotrans#235]
happy new year
**I wish I could add a custom tts proxy, thank you very much!**

**Comment by jianchang512** [comment]
I don't understand what it means to be sexy

**Comment by windkind88** [comment]
> I don't understand what it means

Custom TTS api, similar to Custom Translator's proxy.
自定义TTS api，类似于自定义翻译的代理。

**Comment by windkind88** [comment]
Hello developer, could  u add this request, thank you very much~

**Comment by windkind88** [comment]
Hello developer, could  u add this request, thank you very much~

**Comment by jianchang512** [comment]
Cannot be added because different tts require different numbers, names, and types of parameters, not just a single URL

**Comment by windkind88** [comment]
> 无法添加，因为不同的 tt 需要不同的数字、名称和参数类型，而不仅仅是单个 URL
This is simple, you can add multiple custom agents, API I can solve.
