### ISSUE TITLE
Intel or Amd?

### ISSUE THREAD

**Issue by opoczki** [jianchang512/pyvideotrans#237]
Hi! 
Can it be used on Intel or Amd cards? I tried it with a laptop with nvidia, but the program asks me to download the latest nvidia driver, but unfortunately there is no update.

**Comment by jianchang512** [comment]
Need to have NVIDIA graphics card and configure CUDA environment well
If there is no Nvidia graphics card or if the CUDA environment is not configured properly, CUDA acceleration cannot be used.
CPU unlimited, everything is possible

Error screenshot

**Comment by opoczki** [comment]
Unfortunately, I am a very beginner in this field and my English is not so good. I am from Hungary. So, if I understand correctly. 
It can only be used with NVidia graphics cards, Intel or Amd are not supported... Or if I want to use it on Intel or Amd computer, will the program work with the CPU?

**Comment by jianchang512** [comment]
Just don't select "Eable CUDA"

**Comment by opoczki** [comment]
I tried to start it, but I got an error message. What could be the problem, please help! 
![IMG_20240205_134338](https://github.com/jianchang512/pyvideotrans/assets/140985031/a08d8998-a56b-494e-bd94-377f72b32da8)

**Comment by opoczki** [comment]
![IMG_20240205_134626](https://github.com/jianchang512/pyvideotrans/assets/140985031/942d3e4c-bb0b-4e9c-bfb9-e37ccd67c037)

**Comment by opoczki** [comment]
The clone voice works for me!

**Comment by jianchang512** [comment]
> ![IMG_20240205_134626](https://private-user-images.githubusercontent.com/140985031/302293227-942d3e4c-bb0b-4e9c-bfb9-e37ccd67c037.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDkyODIsIm5iZiI6MTcwNzIwODk4MiwicGF0aCI6Ii8xNDA5ODUwMzEvMzAyMjkzMjI3LTk0MmQzZTRjLWJiMGItNGU5Yy1iZmI5LWUzN2NjZDY3YzAzNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwODQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OThjMTgyMmNiN2RiY2ZiYzk0ODFmYWNjNjNiODAwYmUzN2YzNzVmY2RkZGQxMTJhYzEyMmEyYjVjOWMyZWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vscwk5V8opEGf1yWn2lsM9fecmNmresBlqLVwr7rUh8)


https://github.com/jianchang512/pyvideotrans/releases/download/v0.9995/sp.exe

override sp.exe
