### ISSUE TITLE
使用 TTS clone-voice 合成后无声音

### ISSUE THREAD

**Issue by zhangdszq** [jianchang512/pyvideotrans#241]
![image](https://github.com/jianchang512/pyvideotrans/assets/5317416/00805d9c-78de-4991-8664-fbd53b4a6f4b)

   一旦TTS 选择clone， 就会默认勾选「保留背景音」（手动还勾不掉）， 然后输出的 Mp4 就没有声音了~，  如果我换为 ElevenLabs TTS 取消勾选「保留背景音」就可以有声音， （但如果选择保留背景音合成也是没声音）

辛苦作者查看下～

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/1129c314-e235-4145-83a5-48cf736ddaa5)


如果没有声音，可能分离时出现错误，查看目录文件夹下是否存在 vocal.wav 音频文件，能否播放

**Comment by zhangdszq** [comment]
有 vocal.wav 文件，并且可以播放~

日志为：
`INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i C:/Users/Admin/Downloads/_video_out/WeChat_20240205212050/vocal.wav -ss 00:00:01.070 -to 00:00:05.580 -ar 8000 D:/AI/Video/videotrans-v0.9996/tmp/WeChat_20240205212050/33fe189ed09deb81d186bcb42c822e6b.mp3.wav
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i C:/Users/Admin/Downloads/_video_out/WeChat_20240205212050/vocal.wav -ss 00:00:05.580 -to 00:00:12.780 -ar 8000 D:/AI/Video/videotrans-v0.9996/tmp/WeChat_20240205212050/8cdfe4d93955fd2ce95d2b2e83b78a8b.mp3.wav
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i C:/Users/Admin/Downloads/_video_out/WeChat_20240205212050/vocal.wav -ss 00:00:12.780 -to 00:00:16.580 -ar 8000 D:/AI/Video/videotrans-v0.9996/tmp/WeChat_20240205212050/a7e05a6454304e71fa205e90d5db4d04.mp3.wav
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i C:/Users/Admin/Downloads/_video_out/WeChat_20240205212050/vocal.wav -ss 00:00:16.580 -to 00:00:25.020 -ar 8000 D:/AI/Video/videotrans-v0.9996/tmp/WeChat_20240205212050/c00cc56bae1bcb6dc1d86cb61b797c57.mp3.wav
INFO:VideoTrans:开始配音 [1/4]
INFO:VideoTrans:'Logger' object is not callable
INFO:VideoTrans:'Logger' object is not callable
ERROR:VideoTrans:cloneVoice合成失败:'Logger' object is not callable,api_url='http://127.0.0.1:9988'
ERROR:VideoTrans:cloneVoice合成失败:'Logger' object is not callable,api_url='http://127.0.0.1:9988'
INFO:VideoTrans:开始配音 [2/4]
INFO:VideoTrans:'Logger' object is not callable
ERROR:VideoTrans:cloneVoice合成失败:'Logger' object is not callable,api_url='http://127.0.0.1:9988'
INFO:VideoTrans:'Logger' object is not callable
ERROR:VideoTrans:cloneVoice合成失败:'Logger' object is not callable,api_url='http://127.0.0.1:9988'
INFO:VideoTrans:开始配音 [3/4]
INFO:VideoTrans:开始配音 [4/4]`
