### ISSUE TITLE
Clone voice

### ISSUE THREAD

**Issue by opoczki** [jianchang512/pyvideotrans#242]
Hi! 

I have installed the clone voice program, it supports Hungarian by default, but when I start Videotrans and connect it to clone voice, Hungarian is not in the list of source language selection. I tried to rewrite the language code list to "hu" and "Hungarian", but it gives an error... I thought this method would solve it, because if clone voice supports it, I don't understand why Videotrans doesn't when I combine the two. Is there any way to solve this?

**Comment by jianchang512** [comment]
next version
