### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by MC-dusk** [jianchang512/pyvideotrans#246]
你好，很有意思的工具，之前都是几个散装组合的，比如whisper desktop + tts-vue之类的，现在一套完整工具链一键操作还是很爽的。

几个小问题：

1. 几个库的readme的末尾的“人声背景乐分离“的超链接写错了，都写成stt的链接了。包括https://github.com/jianchang512/pyvideotrans https://github.com/jianchang512/clone-voice https://github.com/jianchang512/stt ，实际是https://github.com/jianchang512/vocal-separate 。
2. 既然这个pyvideotrans是一套工具链，为什么还要独立一个stt出来呢，我看整合包体积也没小多少，独立的stt的功能和pyvideotrans里面stt的功能应该是一样的，还是说以后会差异化。
3. 希望pyvideotrans能把人声背景乐分离也独立一个功能栏，就像stt一样，毕竟都塞在里面了。另外注意到pyvideotrans的分离用的uvr5，但https://github.com/jianchang512/vocal-separate 用的spleeter，有考虑合并然后让用户可以选择使用吗

**Comment by jianchang512** [comment]
2. stt和videotrans里的字幕识别功能一样，没有区别，单独提取出来是方便只想简单提取字幕的用户

3. 背景分离已基于uvr5集成到videotrans了，那个单独的原计划是配合videotrans的，但效果不太好，不如uvr5，并且打包存在问题。

字幕识别和背景抽离已集成到videotrans，未来也不会分离出去。
