### ISSUE TITLE
关于视频速度

### ISSUE THREAD

**Issue by zhangdszq** [jianchang512/pyvideotrans#247]
一个小提议， 目前有配音提速和视频慢速两个选项来适应实际配音长度变化

但实际体验下来不是语速过快就是视频速度过慢， 能否折中？ 也就是同时勾选配音提速和视频慢速两个选项，体验应该能好一些

感谢作者

**Comment by jianchang512** [comment]
后续可以考虑增加

**Comment by jianchang512** [comment]
后续可以考虑增加

**Comment by zhangdszq** [comment]
> 后续可以考虑增加

感谢作者 已支付宝捐赠支持👍

**Comment by jianchang512** [comment]
感谢支持
下个版本试试加上看效果

**Comment by jianchang512** [comment]
升级到 v1.01

**Comment by zhangdszq** [comment]
> 升级到 v1.01

作者你可太6了
