### ISSUE TITLE
Error in version 1.0

### ISSUE THREAD

**Issue by MarcoPoloxx1** [jianchang512/pyvideotrans#249]
Hello . I think in version 1.0 you have problems checking the "Slow video" and "Voice acceleration?" generates errors. I use version 0.9998 perfectly. Thank and congratulate the pyvideotrans team for their great tool.

**Comment by jianchang512** [comment]
When an error occurs, send the latest log file in the logs directory and the bottom ten lines of information

**Comment by MarcoPoloxx1** [comment]
[image: image.png]
Log:

INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr
-y -i C:/XXX/XXX/Videos/pyvideotrans/renamemp4/8.2No-codeAITools/en.m4a -ac
1 -ar 8000 -b:a 128k C:/pyvideotrans/tmp/8.2No-codeAITools/tmp.wav

INFO:faster_whisper:Processing audio with duration 05:41.612

INFO:faster_whisper:VAD filter removed 00:04.876 of audio

INFO:VideoTrans:1

.

.

.

INFO:VideoTrans:text to speech speed +10%

INFO:VideoTrans:Iniciar voiceover  [91/92]

INFO:VideoTrans:Iniciar voiceover  [92/92]

INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr
-y -ss 0 -to 00:00:00.180  -i
C:/XXX/XXX/Videos/pyvideotrans/renamemp4/8.2No-codeAITools/novoice.mp4 -c:v
libx264 -crf 13 C:/pyvideotrans/tmp/8.2No-codeAITools/novoice_tmp.mp4

ERROR:VideoTrans:[error]TTS:[error]Vídeo automático de error lento, por
favor, intente cancelar la opción 'Video auto down' :ffmpeg
error:errs='Error parsing options for input file
C:/XXX/XXX/Videos/pyvideotrans/renamemp4/8.2No-codeAITools/novoice.mp4.
Error opening input files: Invalid argument '


Hello.

I attach the requested information. With the option marked as voice
acceleration? sometimes too (not always).
Thanks for your interest.

Joan Carles

**Comment by jianchang512** [comment]
update to v1.01 and retry

**Comment by MarcoPoloxx1** [comment]
Updated to v.1.01 and it is perfect. Thank you so much

Joan Carles
