### ISSUE TITLE
使用 GPT 翻译后字幕时间段不对

### ISSUE THREAD

**Issue by zhangdszq** [jianchang512/pyvideotrans#250]
英文内容翻译为中文后， 翻译内容堆到一个时间区间内了， 见下图

![image](https://github.com/jianchang512/pyvideotrans/assets/5317416/e45843b0-6ed8-4e9e-9286-ce9ce6d8cf85)
![image](https://github.com/jianchang512/pyvideotrans/assets/5317416/e5abc86a-dc8c-450c-a3e8-8ae610763396)

**Comment by jianchang512** [comment]
软件左上角版本号数字是多少，如果不是v1.01.就先更新到1.01再试试

**Comment by zhangdszq** [comment]
> 软件左上角版本号数字是多少，如果不是v1.01.就先更新到1.01再试试

1.01 源码编译的

**Comment by zhangdszq** [comment]
我发现一个很有意思的事情~~

使用视频工具箱子中的「视频识别字幕」功能，选取base模式，比「标准功能模式」中的英文断句效果要好，间下图（可以和上面的英文对比下~）

![image](https://github.com/jianchang512/pyvideotrans/assets/5317416/f11dbc7a-f6ce-425e-a9a4-1a8f0a6979b1)

**Comment by jianchang512** [comment]
两者是同一个函数处理的
唯一不同是标准功能下识别模式可以预先分割或者整体识别模式，而工具箱强制整体识别

**Comment by zhangdszq** [comment]
> > 软件左上角版本号数字是多少，如果不是v1.01.就先更新到1.01再试试
> 
> 1.01 源码编译的



> 两者是同一个函数处理的 唯一不同是标准功能下识别模式可以预先分割或者整体识别模式，而工具箱强制整体识别
> 
> 你可能标准功能下使用了预先分割模式

![image](https://github.com/jianchang512/pyvideotrans/assets/5317416/9fb3dd9f-845a-4560-a98c-d7f2b3742e12)


我又杀进程重新试了一遍， 选整体识别，仍然是不好的效果..

**Comment by zhangdszq** [comment]
不过这个问题可以通过工具箱识别字幕暂时解决， GPT 翻译没按格式进行这个更重要些，因为 GPT 的翻译效果确实会更好点

**Comment by jianchang512** [comment]
如果都是整体识别，那么两者识别结果不会有区别的
差别可能在翻译上

翻译prompt可以自己调整，videotrabs/chatgpt.txt
保证给它几行它返回几行结果就行
{lang}是动态目标语言变量，不要更改

**Comment by zhangdszq** [comment]
> 如果都是整体识别，那么两者识别结果不会有区别的 差别可能在翻译上
> 
> 翻译prompt可以自己调整，videotrabs/chatgpt.txt 保证给它几行它返回几行结果就行 {lang}是动态目标语言变量，不要更改

好的 谢谢作者~
