### ISSUE TITLE
GPU上执行出错，回退到CPU执行

### ISSUE THREAD

**Issue by zhangdszq** [jianchang512/pyvideotrans#251]
同时勾选配音加速和视频慢速后提示的这个错误，视频时长20分钟左右

idx=18,mp3len=1194,wavlen=960,diff=234
INFO:VideoTrans:[19/155] 视频延长 234ms
INFO:VideoTrans:cut_clip>0, cut_clip=14 ,last_endtime=164610
INFO:VideoTrans:pert==0,中间无片段
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -ss 00:02:44.610 -to 00:02:45.570 -i C:/Users/Admin/Videos/pyvideotrans/rename/_video_out/Readingfor36HoursonaTrain.mp4/novoice.mp4 -vf setpts=1.24*PTS -c:v h264_nvenc -crf 13 D:/AI/Video/pyvideotrans/tmp/Readingfor36HoursonaTrain.mp4/tmppert-18.mp4
INFO:VideoTrans:GPU上执行出错，回退到CPU执行
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -y -ss 00:02:44.610 -to 00:02:45.570 -i C:/Users/Admin/Videos/pyvideotrans/rename/_video_out/Readingfor36HoursonaTrain.mp4/novoice.mp4 -vf setpts=1.24*PTS -c:v libx264 -crf 13 D:/AI/Video/pyvideotrans/tmp/Readingfor36HoursonaTrain.mp4/tmppert-18.mp4
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -f concat -safe 0 -i D:/AI/Video/pyvideotrans/tmp/1707662392.2089493.txt -c:v h264_nvenc -crf 13 -an D:/AI/Video/pyvideotrans/tmp/Readingfor36HoursonaTrain.mp4/tmppert2-18.mp4
INFO:VideoTrans:视频降速处理中
INFO:VideoTrans:

**Comment by jianchang512** [comment]
你调整了set.ini里的cuda参数，可能存在问题，恢复原始，或者自己尝试其他不同参数

**Comment by zhangdszq** [comment]
> 你调整了set.ini里的cuda参数，可能存在问题，恢复原始，或者自己尝试其他不同参数

ok  我先恢复看看
