### ISSUE TITLE
v1.02翻译出错

### ISSUE THREAD

**Issue by q247574452** [jianchang512/pyvideotrans#253]
![image](https://github.com/jianchang512/pyvideotrans/assets/77397079/5be6d24f-bc1c-494e-bb88-55071d080daa)

INFO:VideoTrans:4 秒后自动翻译，可以暂停后去修改字幕，以便翻译更准确
INFO:VideoTrans:3 秒后自动翻译，可以暂停后去修改字幕，以便翻译更准确
INFO:VideoTrans:开始翻译
INFO:VideoTrans:第2次出错重试
INFO:VideoTrans:第3次出错重试
INFO:VideoTrans:第4次出错重试
INFO:VideoTrans:第5次出错重试
ERROR:VideoTrans:[error]: 5次重试后依然出错:target_lang="EN" is deprecated, please use "EN-GB" or "EN-US"instead.

**Comment by jianchang512** [comment]
升级到 v1.03
