### ISSUE TITLE
使用百度api翻译的字幕出现空白

### ISSUE THREAD

**Issue by xigongyue** [jianchang512/pyvideotrans#256]
应用版本：videotrans-v1.04
使用百度翻译api个人开发者高级版
测试Google、微软翻译未出现此现象
查询百度翻译平台api说明文档发现个人开发者高级版QPS 为 10
百度翻译平台api说明文档https://fanyiapp.cdn.bcebos.com/api/doc/%E7%99%BE%E5%BA%A6%E7%BF%BB%E8%AF%91%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0%E9%80%9A%E7%94%A8%E7%BF%BB%E8%AF%91API%E6%9C%8D%E5%8A%A1%E5%8D%87%E7%BA%A7%E8%AF%B4%E6%98%8E.docx
怀疑问题可能是该原因导致，是否可以尝试增加限制翻译并发请求数解决此问题
![image](https://github.com/jianchang512/pyvideotrans/assets/59411948/0d257af0-1a27-49a8-aea5-dd7267cbad39)
上图为使用百度翻译
![image](https://github.com/jianchang512/pyvideotrans/assets/59411948/bb3d2092-2131-4be4-ae74-5996954a0079)
微软
![image](https://github.com/jianchang512/pyvideotrans/assets/59411948/c3c453dc-dfdb-46e0-8cd3-303e65ef6aef)
Google

**Comment by xigongyue** [comment]
可以尝试增加一个选项来设置翻译时的并发请求数

**Comment by jianchang512** [comment]
问题应该不在这里
软件logs目录下，出错时的最新日志后边十几行看看

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
是的 我也出现这个问题，现在我处理办法是 识别出英文字幕后，把srt直接用沉浸式翻译扩展翻译为双语字幕

**Comment by jianchang512** [comment]
升级到 v1.05 试试

**Comment by xigongyue** [comment]
> 升级到 v1.05 试试

v1.05仍然是同样问题，测试在set.ini中设置`trans_thread=1`后该问题消失

**Comment by jianchang512** [comment]
日志完整文件上传下

**Comment by jianchang512** [comment]
和并发无关，代码bug，最初是每次只发送一行的，后来改为了自己定义多少，但baidu翻译代码遗漏修改了。
稍后会更新

**Comment by xigongyue** [comment]
> 和并发无关，代码bug，最初是每次只发送一行的，后来改为了自己定义多少，但baidu翻译代码遗漏修改了。 稍后会更新

好的，好项目支持一下₍₍Ϡ(੭•̀ω•́)੭✧⃛
