### ISSUE TITLE
大模型翻译方式（chatGPT|Azure|Gemini）的上下文支持

### ISSUE THREAD

**Issue by chinese-wzq** [jianchang512/pyvideotrans#258]
可以参考这个项目![gnehs/subtitle-translator-electron](https://github.com/gnehs/subtitle-translator-electron)

**Comment by jianchang512** [comment]
那个非开源，无法参考

**Comment by chinese-wzq** [comment]
> 那个非开源，无法参考

靠很抱歉我找错了！是这个![gnehs/subtitle-translator](https://github.com/gnehs/subtitle-translator)，上面那个是别人开发的electron版的，这个是nodejs版的
