### ISSUE TITLE
What's this? 

### ISSUE THREAD

**Issue by opoczki** [jianchang512/pyvideotrans#259]
What's this? What is the problem? 
![17082043744372854990593513607837](https://github.com/jianchang512/pyvideotrans/assets/140985031/cfc5f507-f42f-446e-8c7c-7e8a8815f952)

**Comment by fakerloveu** [comment]
提示 FFmepg 不存在

首先查看确定软件根目录下存在 ffmpeg.exe, ffprobe.exe 文件或是否存在ffmpeg目录，如果不存在，解压 ffmpeg.7z，将这2个文件放到软件根目录下

FFmepg does not exist

First check to make sure that ffmpeg.exe, ffprobe.exe files exist in the root directory of the software or if the ffmpeg directory exists, if it does not exist, unzip ffmpeg.7z, and put these two files into the root directory of the software.

**Comment by jianchang512** [comment]
There is no reproduction, and there is no way provided that it can be reproduced. Please try restarting the software before
