### ISSUE TITLE
设置百度翻译后软件停止运行

### ISSUE THREAD

**Issue by 1335344215** [jianchang512/pyvideotrans#26]
![image](https://github.com/jianchang512/pyvideotrans/assets/33363399/45c33a85-4697-4331-a975-00092a8b16bd)
![image](https://github.com/jianchang512/pyvideotrans/assets/33363399/28ae217a-053f-422a-8c4e-1787c01a541a)
已经正确的设置了百度翻译的api,但是一点baidu翻译软件就停止运行

**Comment by jianchang512** [comment]
打开 video.log ，最后几十行，复制粘贴上来

**Comment by 1335344215** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/33363399/f93eb127-5bec-4683-b0c2-1c4536d302a6)
你看看行不

**Comment by jianchang512** [comment]
重新执行，到出错的时候，再去复制
这里看不出来

或者把 log文件直接拖到文本框里上传

**Comment by 1335344215** [comment]
[video.log](https://github.com/jianchang512/pyvideotrans/files/13280222/video.log)

**Comment by 1335344215** [comment]
这是我删掉文件后重新执行报错的文件

**Comment by jianchang512** [comment]
太少了，看不出来
是win系统吗，哪个版本

**Comment by 1335344215** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/33363399/867b0822-bb09-44c4-b425-dd0198443a21)
win10 22h2

**Comment by jianchang512** [comment]
删掉video.log
重启这个软件

然后先随便设置下 chatgpt，看看有没有同样错误，如果没有，再继续测试baidu，如果还这样，就强制关闭。然后再把 video.log 发上来

**Comment by 1335344215** [comment]
[video.log](https://github.com/jianchang512/pyvideotrans/files/13280280/video.log)
设置chatgpt不会闪退,,但是切换到百度就闪退
![image](https://github.com/jianchang512/pyvideotrans/assets/33363399/91d6229c-303f-49ce-b59d-3ca0e7e8db96)

**Comment by jianchang512** [comment]
设置好后，点击 “OK”按钮闪退？

**Comment by 1335344215** [comment]
等下我录一个gif把这样更容易理解

**Comment by 1335344215** [comment]
只要点击框选的百度就闪退
![image](https://github.com/jianchang512/pyvideotrans/assets/33363399/4104e617-8f53-4674-8343-c55477ba8fd6)

https://github.com/jianchang512/pyvideotrans/assets/33363399/b1b8561c-8548-4139-b64f-3f058ef70991

**Comment by jianchang512** [comment]
好的。了解了。我调试下看看。
视频可以删了，注意隐私

**Comment by 1335344215** [comment]
感谢,辛苦了

**Comment by jianchang512** [comment]
已修复，应该可以了
