### ISSUE TITLE
mac m1启动报错”OSError: cannot load library '/usr/local/lib/libsndfile.dylib'“

### ISSUE THREAD

**Issue by MustardWithRice** [jianchang512/pyvideotrans#261]
mac m1安装依赖输入”python sp.py“启动时报错，报错信息如下：
”“”
OSError: cannot load library '/usr/local/lib/libsndfile.dylib': dlopen(/usr/local/lib/libsndfile.dylib, 0x0002): tried: '/usr/local/lib/libsndfile.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/usr/local/Cellar/libsndfile/1.2.0_1/lib/libsndfile.1.0.35.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
“”“

解决方案：
`brew install libsndfile`安装libsndfile即可。

**Comment by jianchang512** [comment]
好的，已加readme
