### ISSUE TITLE
latest version is not dubbing correctly with elevenlabs

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#264]
Only correctly with video slow version 0.9993:

![SNAG-0096](https://github.com/jianchang512/pyvideotrans/assets/428820/27d4e1f7-e2ba-4d04-87ba-e45223cf2f61)

pls correct latest version for use all new features and fixes

**Comment by jianchang512** [comment]
I tested it. It's fine.

Delete all the files in the logs directory, then retest to the point of error and upload the log files in the logs directory

Upgrade to v1.12 first

**Comment by johnfelipe** [comment]
https://drive.google.com/drive/folders/1pMoxwPUzV9i_OctoKDtA7grGJmy3EtQA?usp=sharing

SNAG-0004 works, perfect sync without slow video with videotrans-v0.9993 version
SNAG-0004 not works, unsiync with latest verision videotrans-v1.14

how can solve this?

**Comment by jianchang512** [comment]
I don't know what that means.
Is it not dubbable, or is it dubbable but the sound and picture are not synchronized?
If it can't be dubbed, there is a dubbing error, check the latest log file in the logs folder in the software directory.

**Comment by johnfelipe** [comment]
is new one, i delete prev version
"is it dubbable but the sound and picture are not synchronized?" CORRECT
only is sync with videotrans-v0.9993

**Comment by johnfelipe** [comment]
[video-20240223.log](https://github.com/jianchang512/pyvideotrans/files/14408822/video-20240223.log)

**Comment by johnfelipe** [comment]
still not working

https://drive.google.com/drive/folders/1Hg4TDPtPlJEX_7mcS3Sy_Oh04PTpRorH?usp=sharing

[video-20240228.log](https://github.com/jianchang512/pyvideotrans/files/14439738/video-20240228.log)

look video works with latest version

https://drive.google.com/drive/folders/1_XXlqU2pYg-2cKft_7U2t94sL2_fCgfI?usp=sharing

im continue dubbing with videotrans-v0.9993, pls help me to solve this issue asap

**Comment by jianchang512** [comment]
As long as the dubbing length will change, can only be adjusted through the "audio automatically speed up" and "video automatically slow down" to adjust, if you want to be perfectly synchronized, in addition to manual editing, there is no way, the program can not be automatically achieved!

**Comment by johnfelipe** [comment]
but my question is why difference btwn 0.9993 version and latest, with
older version dubbing correctly without speed or slow feature, can u help
me to understand

**Comment by jianchang512** [comment]
There's no difference, there's a "first split" and a "whole all" at the end of the speech model, so maybe you're confused.

If you think there is a difference, we recommend deploying the source code, and modifying videotrans/recognition/__init__.py to adjust

**Comment by johnfelipe** [comment]
i will do VIDEO 1: with same video and dubbing with old version and VIDEO
2: same with latest version and you review difference, give me 30 mini

**Comment by johnfelipe** [comment]
[VIDEO1](https://drive.google.com/file/d/1C54EOtF7mkOU16ZWV5UZ_C-105bex8O9/view?usp=drivesdk)

I will download latest version and put same options and you view difference

**Comment by johnfelipe** [comment]
[VIDEO2](https://drive.google.com/file/d/11NMkc0CxuFxEaLq3FxRvwGTinZ4tb9Od/view?usp=drivesdk)

[video-20240229.log](https://github.com/jianchang512/pyvideotrans/files/14451691/video-20240229.log)

I dont know if is understandable..

**Comment by johnfelipe** [comment]
ok now i know how solve:

Pause - Edit srt with previous time - next 

DONE is dubbed correctly with slow video

tnks
