### ISSUE TITLE
一直报错

### ISSUE THREAD

**Issue by 709411fan** [jianchang512/pyvideotrans#266]
<img width="326" alt="微信图片_20240225200252" src="https://github.com/jianchang512/pyvideotrans/assets/155301029/8eb1b713-214f-4768-9bcf-e0ab44194096">
<img width="453" alt="微信图片_20240225200334" src="https://github.com/jianchang512/pyvideotrans/assets/155301029/2e70e344-8d03-470c-8046-046da9604691">

**Comment by jianchang512** [comment]
logs目录下最新日志文件上传下

**Comment by 709411fan** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/155301029/a84f684d-e30d-48e9-a214-448de7a1d73b)

**Comment by jianchang512** [comment]
代理问题
