### ISSUE TITLE
调用clone-voice服务的时候报错

### ISSUE THREAD

**Issue by hs117** [jianchang512/pyvideotrans#267]
[
![111111111111](https://github.com/jianchang512/pyvideotrans/assets/30688802/d7b32865-2875-4f6c-818e-10e152785908)
![222222222222222222](https://github.com/jianchang512/pyvideotrans/assets/30688802/0a5b70c4-adfa-42f8-917b-7644113982f1)
](url)

**Comment by hs117** [comment]
不知道是不是字数太少、音频太短的原因

**Comment by jianchang512** [comment]
打开 videotrans/set.ini 找到 cuda_com_type=int8 这行，改为  cuda_com_type=float32

**Comment by hs117** [comment]
问题解决了，谢谢！

**Comment by hs117** [comment]
![333333](https://github.com/jianchang512/pyvideotrans/assets/30688802/39fd1f5c-025e-48aa-be4b-95da6caf2bc5)
![44444444](https://github.com/jianchang512/pyvideotrans/assets/30688802/c33365d4-7d0b-41a6-86a3-f075a2761604)
处理440M的视频，又出现这个错误，已经改为 cuda_com_type=float32的情况下。请问这个如何解决？

**Comment by jianchang512** [comment]
语音模型后有个整体识别和预先分割，选择预先分割

**Comment by hs117** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/30688802/2acd8ce9-3402-4cfe-a3e3-a12cbb014954)
又出现这个错误

**Comment by jianchang512** [comment]
这种一般是配音失败，去 logs 目录下查看最新的日志

**Comment by hs117** [comment]
D:/videotrans-v1.14/tmp/wailian/acf698b6b6b14cb8bf8a7365b8dd4f20.mp3.wav
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuvid -hwaccel_output_format nv12 -extra_hw_frames 2 -y -i D:/88888/wailian/wailian/vocal.wav -ss 00:07:19.99 -to 00:07:19.945 -ar 8000 D:/videotrans-v1.14/tmp/wailian/db341762246128ebdd76faec75b02936.mp3.wav
INFO:VideoTrans:GPU上执行出错，回退到CPU执行
INFO:VideoTrans:runffmpeg: ffmpeg -hide_banner -ignore_unknown -vsync vfr -y -i D:/88888/wailian/wailian/vocal.wav -ss 00:07:19.99 -to 00:07:19.945 -ar 8000 D:/videotrans-v1.14/tmp/wailian/db341762246128ebdd76faec75b02936.mp3.wav
INFO:VideoTrans:TTS:ffmpeg error:errs='Error opening output file D:/videotrans-v1.14/tmp/wailian/db341762246128ebdd76faec75b02936.mp3.wav. Error opening output files: Invalid argument '

**Comment by jianchang512** [comment]
清空日志重新测试，然后去看看配音那块报的错误。

什么配音渠道，软件升级到 1.14版本

**Comment by hs117** [comment]
目前已经是1.14版本，用的是本地的clone-voice接口

**Comment by jianchang512** [comment]
在日志文件里找找吧，看是什么原因配音失败
