### ISSUE TITLE
无法使用自建本地gpt的api来翻译

### ISSUE THREAD

**Issue by lin16303** [jianchang512/pyvideotrans#268]
![QQ图片20240228174213](https://github.com/jianchang512/pyvideotrans/assets/130566478/fe8283a8-a972-4618-a3ed-5e9e12a7649c)
通过类似这个链接，浏览器里的几个翻译软件包括chatgptbox，沉浸式翻译插件都能正常运作，但在本程序测试时，gpt后台也无反应。
http://localhost:1234/v1/chat/completions

**Comment by lin16303** [comment]
测试了koboldcpp，lmstudio,text-generation-webui，这几个api都没反应

**Comment by jianchang512** [comment]
不要带/api 
确保ip:port/v1
和官方一致

**Comment by lin16303** [comment]
用这个api格式短视频测通了，大家试一下

koboldcpp
http://localhost:5001
lm studio
http://localhost:1234
text-generation-webui
http://localhost:5000/v1/chat/completions
