### ISSUE TITLE
使用vpn需开启全局模式并且不需要设置代理端口

### ISSUE THREAD

**Issue by sven3329** [jianchang512/pyvideotrans#27]
使用vpn的时候需要全局模式，并且不需要也不可以进行代理端口设置。

我想可能是我使用的vpn工作在最底层物理层，虚拟了一个网卡强制接管了本机的所有数据。所以不需要任何代理的端口设置。如果使用vpn的智能模式，我尝试了各种设置都无效。
我想可能也有一些人和我一样使用vpn而不是机场，所以提出来，希望能够有所帮助。

**Comment by jianchang512** [comment]
如果设置了代理，则使用，不设置的话就走底层。

全部也是可以的

**Comment by sven3329** [comment]
那是我没设置好。
