### ISSUE TITLE
Malware detected in download?

### ISSUE THREAD

**Issue by rvanweerd** [jianchang512/pyvideotrans#271]
I always scan everything I download before unzipping. Avast came up with this message: 

Is that a false positive? Can you clarify what it is? thanks!

![image](https://github.com/jianchang512/pyvideotrans/assets/364966/e189c2ca-5835-4667-b41c-5a16e218dfe2)

**Comment by jianchang512** [comment]
Use pyinstall package, no signature certificate, suggest toxic is a false alarm, can be ignored.
Or use the source code
