### ISSUE TITLE
使用远程的 clone-voice 失败

### ISSUE THREAD

**Issue by thunderyan** [jianchang512/pyvideotrans#272]
pyvideotrans
  -- 版本： V1.15

clone-voice
  -- 版本：v0.901

如果 clone-voice 跟 pyvideotrans 不是运行在同一部机器，则转换声音的时候会提示读取不到wav文件错误。
因为显存原因，clone-voice 跟 pyvideotrans 部署在不同的电脑上，clone-voice API 调用正常，但 pyvideotrans 会提示读不到文件。

**Comment by jianchang512** [comment]
默认本地地址读取，不在一台读不到

clone那台绑定内网地址，确保这台能读到内网地址

**Comment by thunderyan** [comment]
两台机是在同一个内网，意思就是分开部署就读取不到吗？

**Comment by jianchang512** [comment]
默认绑定的127.0.0.1
你需要修改
.env中绑定地址
然后翻译软件计算机上要确定能连到clone所在ip
然后翻译软件菜单设置原音色克隆里修改为所用ip

**Comment by thunderyan** [comment]
是的，这些是都设置好了，不然都跑不起来。从 clone-voice 的控制台上可以看出 pyvideotrans 的调用是正常的。
盲猜问题是路径的问题，例如：在 clone-voice 上转好的WAV文件是  /aaa/bbb/ccc ，但是在 pyvideotrans 上没有这个路径。
报了找不到wav文件的错误提示。

**Comment by jianchang512** [comment]
clone更新到0.905
视频翻译更新到1.17
试试

**Comment by thunderyan** [comment]
测试中，比较慢，但我在设置界面那里测试API，还是有报错
![Uploading iShot_2024-03-01_20.06.21.png…]()

**Comment by thunderyan** [comment]
奇怪还是不行；
已经更新版本：
clone更新到0.905
视频翻译更新到1.17

![iShot_2024-03-01_20 16 44](https://github.com/jianchang512/pyvideotrans/assets/22948357/28f8f660-84d0-4be3-8965-dd2efaf5800b)
![iShot_2024-03-01_20 17 05](https://github.com/jianchang512/pyvideotrans/assets/22948357/344b22e6-7952-422e-ba04-b3d007dd27d7)

**Comment by jianchang512** [comment]
我测试没问题
视频翻译下载1.17完整包覆盖
clone-voice下载0.905完整包覆盖
试试

**Comment by KalvinThien** [comment]
I get an error ： 你可能需要先安装VLC解码器
该语音已经过克隆测试，并在克隆语音中得到了很好的使用。但是，从SRT转换为Audio时，会遇到上述错误！

谢谢
我已经安装了 VLC

![image](https://github.com/jianchang512/pyvideotrans/assets/120565705/8a03754e-f01e-4923-b6c4-e3506f62eda2)

**Comment by thunderyan** [comment]
@jianchang512 我所有的东西全部重新装过测试了都还是不行。
clone-voice 我用源码0.905版本部署在Linux系统上，用WebUI测试功能都是正常的。
pyvideotrans 我是用打好exe包的1.17版本解压直接运行的。

**Comment by jianchang512** [comment]
我没有复现该问题
你试试将clone-voice下static/ttslist里的所有文件删掉，然后视频翻译里重新测试，看看有没有生成音频文件

**Comment by thunderyan** [comment]
按步骤清掉 clone-voice下static/ttslist里的所有文件，点击测试，重新生成，还是一样的报错。
再检查 static/ttslist 确实是有文件生成的。
videotrans 我更新到 V1.20 也是一样。
会不会是 videotrans 有cache呢？因为我打开不同版本的 videotrans 都会读到之前的设置项。
![iShot_2024-03-04_00 26 34](https://github.com/jianchang512/pyvideotrans/assets/22948357/5a5b6e84-2b1c-478f-b066-c3ad052c8a5b)
![iShot_2024-03-04_00 26 49](https://github.com/jianchang512/pyvideotrans/assets/22948357/46ee4a1e-6732-4c64-9119-dd78b144178e)
![iShot_2024-03-04_00 26 39](https://github.com/jianchang512/pyvideotrans/assets/22948357/bba5130f-2403-427e-8e4d-8b36069fef56)

**Comment by jianchang512** [comment]
试试1.21

**Comment by thunderyan** [comment]
刚试了，还是不行呢，一样的报错。各种方法我都尝试过了，都是一样的结果，不知道是哪里的问题。
videotrans 就提示 文件不存在，而 clone-voice 就提示文件已经存在。
另外想问一下，如何清理掉已有的配置项的缓存呢？我打开几个版本的videotrans发现配置都有跟随。

**Comment by thunderyan** [comment]
![iShot_2024-03-04_23 07 57](https://github.com/jianchang512/pyvideotrans/assets/22948357/15533c46-a27b-49d2-a61c-a90925b189f2)

**Comment by thunderyan** [comment]
解决了，最终还是得debug源码。发现几处有问题的地方：
1、clone.py 判断是否为远程HTTP调用的时候，条件少了判断是否 > -1
`if api_url.find('127.0.0.1')>-1 or api_url.find('localhost')>-1:`
![iShot_2024-03-06_10 25 32](https://github.com/jianchang512/pyvideotrans/assets/22948357/46909012-5ec7-4e0c-ac79-30df2299a259)

2、文件用with 打开的时候，已经被占用，而应该等with跑完再unlink
`with open(filename+".wav",'wb') as f:     
    f.write(resb.content)
    tools.wav2mp3(filename+".wav",filename) 
if os.path.exists(filename + ".wav"):
    os.unlink(filename + ".wav")`

![iShot_2024-03-06_10 26 37](https://github.com/jianchang512/pyvideotrans/assets/22948357/cdd0e671-fed9-41b5-bfff-a0996e4e0b69)

**Comment by jianchang512** [comment]
第2个已修复，第一个下版修复，感谢反馈
