### ISSUE TITLE
关于libsndfile有个报错，建议大佬加到readme里

### ISSUE THREAD

**Issue by neilwyh** [jianchang512/pyvideotrans#274]
我是macos系统，源代码运行

按照readme操作后，执行`python sp.py`报错，提示：
`OSError: ctypes.util.find_library() did not manage to locate a library called 'sndfile'`

网上搜了下解决办法：
找到libsndfile安装位置，通过brew安装的话一般在：/opt/homebrew/Cellar/libsndfile，
然后将该路径添加到环境变量：`export DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/libsndfile/1.2.2/lib:$DYLD_LIBRARY_PATH`
注意将1.2.2替换成自己的版本号

这样就可以正常运行了。

**Comment by jianchang512** [comment]
已加入常见问题，谢谢反馈
