### ISSUE TITLE
1.14版以后的音频转文字没有1.09版那么精准

### ISSUE THREAD

**Issue by XiongXiong2023** [jianchang512/pyvideotrans#275]
新版的音频转文字虽然多了批处理功能，但是语音切的长度很不好，有时长长一大段，而且时间普遍有10秒那么长，大小写也识别不出来。1.08、1.09版的语音转文字，目前是我最满意的，每一段话切的长度都很适中，大小写也能准确识别，翻译起来非常舒服，就是没有批处理功能。希望能出一版有1.09版语音转文字识别能力，又有批处理的新版本吧。

**Comment by jianchang512** [comment]
试试1.17

**Comment by XiongXiong2023** [comment]
我用的模型是fast whisper large V2
这是我的设置
![QQ浏览器截图20240301214349](https://github.com/jianchang512/pyvideotrans/assets/153164710/8113ee32-e64d-4847-9ba8-ccbd957451eb)

大佬辛苦了，1.17版的语音转文字是这么多版以来识别最差的了。
同样的文件，在1.09版里面，识别完全正确，1.17版出现了大范围的识别错误。识别结束的时候，有一次还出现了报错，无法生成字幕文件。如下图
![QQ浏览器截图20240301210830](https://github.com/jianchang512/pyvideotrans/assets/153164710/18a362a5-4952-4e69-aed6-71ba4ab61c61)
![QQ浏览器截图20240301213923](https://github.com/jianchang512/pyvideotrans/assets/153164710/505de727-8e9a-4039-bd78-7b526dd3453f)
![QQ浏览器截图20240301214105](https://github.com/jianchang512/pyvideotrans/assets/153164710/078b02bc-e631-4d2f-8d6b-7f7e3bf6ccde)
![QQ浏览器截图20240301214155](https://github.com/jianchang512/pyvideotrans/assets/153164710/a01b65e1-247b-4a6c-b2bb-57942d4ede14)

**Comment by jianchang512** [comment]
使用整体识别

**Comment by jianchang512** [comment]
如果你使用的工具箱中的 音视频转文字，可以是 主界面试试 视频识别文字，然后选择整体识别。

**Comment by XiongXiong2023** [comment]
我用的就是整体识别，我要识别的是音频，没法用视频识别。而且语音识别频繁报错，报('list index out of range')

**Comment by jianchang512** [comment]
我测试没有复现

1.18版本重新试试。

如果还有这问题，上传一个你的音频我试试

**Comment by XiongXiong2023** [comment]
我把音频和出现问题都放在百度网盘了，你看看吧
链接：https://pan.baidu.com/s/1pGnXHgN8-Rg_OMpWWx5czA 
提取码：1111

**Comment by jianchang512** [comment]
你仔细看下吧。我认为 1.18 的断句 切分更合理。

音视频转文字功能只能是预分割，1.09及之前是强制最大时长10s，静音200-500，1.18版改为最大5s，静音100-200。

**Comment by XiongXiong2023** [comment]
可以给1.09版单独出个语音转文字的批处理升级包吗。英文字幕我会在字母软件里面处理一遍的，切分的问题对我不重要，准确度才是重要的。而且有标点符号也方便我翻译，我翻译的方式跟你们不一样。

**Comment by jianchang512** [comment]
faster模型那里可以选择 openai模型，或者使用源码部署，然后用 1.09的文件直接覆盖 videotrans/recongition/__init__.py 文件
