### ISSUE TITLE
视频提取字幕有办法按句提取吗？

### ISSUE THREAD

**Issue by th10010** [jianchang512/pyvideotrans#277]
![微信截图_20240303102037](https://github.com/jianchang512/pyvideotrans/assets/55772277/cac01ba5-e212-409b-8eef-a7c53a786232)
如图，用视频识别字幕的功能提取的字幕都是一长段一长段的，有办法提取成1句1句的吗？

**Comment by jianchang512** [comment]
选择使用faster模型
