### ISSUE TITLE
视频过长的时候会卡住但不报错，不关闭不退出

### ISSUE THREAD

**Issue by sven3329** [jianchang512/pyvideotrans#28]
翻译已完成，在合并的阶段。
这是日志里面的最后三行记录：
INFO:srt:Legalised content '大卫·哈塞尔霍夫主演的《沙卡祖鲁》电影的成员..\n\n' to '大卫·哈塞尔霍夫主演的《沙卡祖鲁》电影的成员..'
INFO:srt:Legalised content '永远不会忘记..\n\n' to '永远不会忘记..'
ERROR:VideoTrans:Get_large_audio_transcription error:list index out of range

**Comment by jianchang512** [comment]
这是出错了。
Get_large_audio_transcription error:list index out of range

根据这个信息看不出具体是哪行的错误。
前后范围可以再贴大点

**Comment by sven3329** [comment]
日志文件我已经删了。明天我再拿长视频测试。

**Comment by sven3329** [comment]
对不起，我重新操作了，正常完成。推测可能是昨天我操作的时候还在打游戏，电脑内存不够导致的。对不起啊，麻烦请关闭issu。

**Comment by jianchang512** [comment]
好的

**Comment by Doutianbao** [comment]
情况一样，卡住，不关闭不退出
INFO:VideoTrans:sr.AudioFile:chunk_filename='C:/Users/docxu/Downloads/Programs/video-translate-v0.8.2/##wonyesgallery_tmp/c52_499_510.wav'
INFO:VideoTrans:start_time=509640,end_time=520140,duration=(509640, 520140, True)
INFO:VideoTrans:sr.AudioFile:chunk_filename='C:/Users/docxu/Downloads/Programs/video-translate-v0.8.2/##wonyesgallery_tmp/c53_509_520.wav'
INFO:VideoTrans:start_time=519640,end_time=526057,duration=(519640, 526057, False)
INFO:VideoTrans:sr.AudioFile:chunk_filename='C:/Users/docxu/Downloads/Programs/video-translate-v0.8.2/##wonyesgallery_tmp/c54_519_526.wav'
ERROR:VideoTrans:Get_large_audio_transcription error:list index out of range

似乎是README里的中文原版视频

**Comment by jianchang512** [comment]
是不是之前没完成重新开始的

删除之前生成的srt文件再试试

下版增减中断继续
