### ISSUE TITLE
I get this error when done, I do not check the CUDA box

### ISSUE THREAD

**Issue by KalvinThien** [jianchang512/pyvideotrans#281]
![image](https://github.com/jianchang512/pyvideotrans/assets/120565705/84c1678e-e262-4a9b-a056-98ac5db5fa61)
ERROR:VideoTrans:cloneVoice合成失败:{'code': 6, 'msg': 'CUDA error: the launch timed out and was terminated\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'},api_url='http://127.0.0.1:9988'

**Comment by jianchang512** [comment]
install cuda11.8 or 12.3

**Comment by jianchang512** [comment]
A new version for clone-voice  will be updated tomorrow to allow forcing cpu to be used to avoid cuda configuration issues

**Comment by KalvinThien** [comment]
thanks for help

**Comment by jianchang512** [comment]
clone-voice update to 0.906
pyvideotrans update to 1.22
