### ISSUE TITLE
cuda用不了

### ISSUE THREAD

**Issue by 2298834669** [jianchang512/pyvideotrans#282]
已经部署了环境了的，但这里cuda用不了
![QQ截图20240304183123](https://github.com/jianchang512/pyvideotrans/assets/100649768/9ec7f632-4b60-4c52-b593-70b122fa0e9f)
![QQ截图20240304183144](https://github.com/jianchang512/pyvideotrans/assets/100649768/0690c1c3-e262-4d7c-8f51-74cf59b91a48)

**Comment by jianchang512** [comment]
安装cuda11.8或者12.1试试

**Comment by 1353604736** [comment]
我也是用不了cuda，环境确定已配置

**Comment by jianchang512** [comment]
cuda版本不能低于11.8 并且需要安装cudnn

**Comment by 1353604736** [comment]
> cuda版本不能低于11.8 并且需要安装cudnn

![2024-03-05_105111](https://github.com/jianchang512/pyvideotrans/assets/12869582/8005cafd-9e96-46f3-885d-fda67a163294)

**Comment by jianchang512** [comment]
需要再安装 cudnn

**Comment by 1353604736** [comment]
> cudnn

cudnn已安装

**Comment by 1353604736** [comment]
> 是预配置版本吗，还是自己源码部署的？
> 
> 预安装的cuda11.8
> 
> 如果是预设版本，尝试添加到环境变量中
> 
> https://juejin.cn/post/7318704408727519270#heading-2

![2024-03-05_165845](https://github.com/jianchang512/pyvideotrans/assets/12869582/62d993e5-73c0-4652-8a6a-f36d064c6d54)
都加入了还是不行

**Comment by jianchang512** [comment]
是预打包还是源码部署，预打包不应该有这问题。
软件目录下是否有testcuda.exe，如果有，复制一个mp4，命名为raw.mp4放软件目录下，双击testcuda

**Comment by 1353604736** [comment]
> 是预打包还是源码部署，预打包不应该有这问题。 软件目录下是否有testcuda.exe，如果有，复制一个mp4，命名为raw.mp4放软件目录下，双击testcuda

torch\cuda\__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
no CUDA environ

Press enter for close

我是下载的发布的完整包下载(1.82G,内含base模型)链接解压运行的sp.exe，还需要搭建其他环境吗

**Comment by jianchang512** [comment]
看报错信息
你的驱动太久了，更新驱动到最新

驱动太久和cuda不兼容，即使安装了cuda也是无法使用的

**Comment by 1353604736** [comment]
> 看报错信息 你的驱动太久了，更新驱动到最新
> 
> 驱动太久和cuda不兼容，即使安装了cuda也是无法使用的

已解决，更新到最新驱动就好了

**Comment by 1353604736** [comment]
> 看报错信息 你的驱动太久了，更新驱动到最新
> 
> 驱动太久和cuda不兼容，即使安装了cuda也是无法使用的

已解决，更新到最新驱动就好了
