### ISSUE TITLE
这完全搞乱了我在1.13到1.21所有版本上尝试的所有配音。四天前一切都很完美，但突然间就搞砸了！ its messing up all dubbing i tried in all versions from 1.13 to 1.21 four days ago eveerything was perfect but all of sudden its messing things up !

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#283]
its messing up all dubbing i tried in all versions from 1.13 to 1.21 four days ago eveerything was perfect but all of sudden its messing things up ! 
 i have joined the log file  , srt file and also screen shout of how audio is splitted everywhere and every thing is messed up.
 i have checked srt and its correct so ther is no problem in srt.
 i have tried on all version with my laptop and on my all  freinds laptop . its doing same everywhere.

![Screenshot 2024-03-04 2134307](https://github.com/jianchang512/pyvideotrans/assets/131840042/a69a3324-b245-4245-8dff-cd19e641d76a)

四天前，我尝试了从1.13到1.21所有版本的所有配音，结果都搞砸了！之前一切都完美无缺，但突然间就出问题了！我已经上传了日志文件、SRT文件，还有屏幕截图显示音频在各处被分割并且一团糟。我已经检查了SRT文件，它是正确的，所以SRT没有问题。我已经在我的笔记本电脑上和我所有朋友的笔记本电脑上都尝试过了，结果都一样。 @ @
[video-20240304.log](https://github.com/jianchang512/pyvideotrans/files/14484321/video-20240304.log)

**Comment by jianchang512** [comment]
use "whole all " after model

**Comment by jianchang512** [comment]
update to 1.22

**Comment by abhijeet12s** [comment]
WHERE TO FIND WHOLE ALL OPTION ??

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/6a42fa44-a7e5-45c5-9ebe-47d9fc77a2bc)


update to v1.22

**Comment by abhijeet12s** [comment]
[Visual Explanation]

1. **Transcribing & Translating:**
   - ✅ Perfectly executed
   - 🔄 No issues
   
2. **Dubbing:**
   - ❌ Incorrect placement of voiceovers
   - ❌ Dubbing not synchronized with timestamps
   - ❌ Voiceovers unrelated to scenes
   - ❌ Dubbing voiceovers present before 4 minutes of scenes

[video-20240305.log]
[SUBTITLES.txt](https://github.com/jianchang512/pyvideotrans/files/14492543/SUBTITLES.txt)

(https://github.com/jianchang512/pyvideotrans/files/14492511/video-20240305.log)

**Comment by abhijeet12s** [comment]
> use "whole all " after model
> 
> "first split" has bug
no its not working

**Comment by jianchang512** [comment]
Create an empty file in the root directory of the software with the name old.txt, then restart the software, use 'pre-split' and try again!

**Comment by abhijeet12s** [comment]
where to find root directery can you upload screenshot

**Comment by jianchang512** [comment]
sp.exe  direct  is root

**Comment by jianchang512** [comment]
sp.exe文件同目录下创建个空的old.txt，然后重启软件，使用 pre-split
