### ISSUE TITLE
whole all CUDA failed with error out of memory(‘whole all CUDA failed with error out of memory,)

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#284]
![SNAG-0137](https://github.com/jianchang512/pyvideotrans/assets/428820/4fbac98f-b7bf-434a-8722-f486828c5fb0)

how solve?

**Comment by jianchang512** [comment]
use medium model

**Comment by johnfelipe** [comment]
before in older version i can do it enabling CUDA, i need to use large version for accuracy how can solve this in latest version?
