### ISSUE TITLE
In 1 of Coqui's discussions I saw they say that some languages can add emotions, can you add an emotion list to use?

### ISSUE THREAD

**Issue by KalvinThien** [jianchang512/pyvideotrans#285]
![image](https://github.com/jianchang512/pyvideotrans/assets/120565705/efba989d-7f52-402c-b5f0-aca72299b226)
In 1 of Coqui's discussions I saw they say that some languages can add emotions, can you add an emotion list to use? thanks

https://huggingface.co/coqui/XTTS-v2/discussions/19

**Comment by jianchang512** [comment]
No such program at this time
