### ISSUE TITLE
GPU执行出错，退回CPU执行

### ISSUE THREAD

**Issue by 2298834669** [jianchang512/pyvideotrans#287]
解决了cuda用不了的问题，但用的时候出错了，cudnn都配置好了的，cuBLAS也装了
![QQ截图20240306103938](https://github.com/jianchang512/pyvideotrans/assets/100649768/d8d925f6-ec28-41bd-8bff-2b3de95def35)
![QQ截图20240306104027](https://github.com/jianchang512/pyvideotrans/assets/100649768/847d0821-a15f-4aa5-b49d-3c82b572a6bf)
![QQ截图20240306104105](https://github.com/jianchang512/pyvideotrans/assets/100649768/25e3a25f-b435-4ef4-8d03-f94a2fe460e8)

**Comment by 2298834669** [comment]
这样的执行效率还不如不勾选cuda加速

**Comment by 2298834669** [comment]
开始卡，90%也卡
![QQ截图20240306105308](https://github.com/jianchang512/pyvideotrans/assets/100649768/2debc304-b542-47c0-a5ed-b84de38fefe9)

**Comment by jianchang512** [comment]
报错时，logs目录下，最新的log文件，最后10行日志复制贴上来

确保已安装了cudnn
https://juejin.cn/post/7318704408727519270#heading-1

**Comment by 2298834669** [comment]
INFO:VideoTrans:正在嵌入硬字幕，无配音
INFO:VideoTrans:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-hwaccel', 'cuvid', '-hwaccel_output_format', 'nv12', '-extra_hw_frames', '2', '-y', '-i', 'E:\\sp\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4\\novoice.mp4', '-i', 'E:\\sp\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4\\ko.m4a', '-c:v', 'h264_nvenc', '-c:a', 'aac', '-vf', 'subtitles=tmp.srt:force_style=Fontsize=14', 'E:\\sp\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4.mp4']
INFO:VideoTrans:GPU上执行出错，回退到CPU执行
ERROR:VideoTrans:cuda上执行出错，退回到CPU执行
INFO:VideoTrans:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-y', '-i', 'E:\\sp\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4\\novoice.mp4', '-i', 'E:\\sp\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4\\ko.m4a', '-c:v', 'libx264', '-c:a', 'aac', '-vf', 'subtitles=tmp.srt:force_style=Fontsize=14', 'E:\\sp\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4\\무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4.mp4']
INFO:VideoTrans:E:/sp/무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4##898

**Comment by jianchang512** [comment]
如果文件还在， 进入到 软件目录下的 ffmpeg 目录，地址栏输入cmd回车，然后执行下面命令，看看报什么错
```
ffmpeg -hide_banner -ignore_unknown -vsync  vfr -hwaccel cuvid -hwaccel_output_format nv12 -extra_hw_frames 2 -y -i "C:/Users/Administrator/Downloads/Video/무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4"  -vn -c:a aac "E:/sp/ko.m4a"

```

**Comment by 2298834669** [comment]
这个
![QQ截图20240306172922](https://github.com/jianchang512/pyvideotrans/assets/100649768/09e0174e-934e-4b5b-9bac-bc42728b9cab)

**Comment by jianchang512** [comment]
这个mp4能播放吗

**Comment by 2298834669** [comment]
> 这个mp4能播放吗？



> 这个mp4能播放吗

可以的

**Comment by jianchang512** [comment]
ffmpeg -hide_banner -ignore_unknown -vsync  vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i "C:/Users/Administrator/Downloads/Video/무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4"  -vn -c:a aac "E:/sp/ko.m4a"


这样执行试试

**Comment by 2298834669** [comment]
> ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i "C:/Users/Administrator/Downloads/Video/무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4" -vn -c:a aac "E:/sp/ko.m4a"
> 
> 这样执行试试

D:\fy\ffmpeg>ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i "C:/Users/Administrator/Downloads/Video/무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4" -vn -c:a aac "E:/sp/ko.m4a"
-vsync is deprecated. Use -fps_mode
[in#0 @ 00000292324a5e40] Error opening input: Illegal byte sequence
Error opening input file C:/Users/Administrator/Downloads/Video/무기고중국공군의진정한주력J-10전투기j10f16샤를세환이세환.mp4.
Error opening input files: Illegal byte sequence

**Comment by jianchang512** [comment]
这视频多大，方便的话把这个视频发下，我看看

**Comment by jianchang512** [comment]
jianchang512@gmail.com

**Comment by 2298834669** [comment]
https://www.123pan.com/s/Cd9jVv-uSBr.html提取码:jnrn

**Comment by jianchang512** [comment]
好的  晚上我看看试下 然后回复

**Comment by jianchang512** [comment]
我测试没有问题，试试放在英文目录下，然后视频名字也改为英文，类似下面这样

ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i "C:/Users/Administrator/Downloads/Video/1234.mp4" -vn -c:a aac "C:/Users/Administrator/Downloads/Video/ko.m4a"

**Comment by 2298834669** [comment]
> 我测试没有问题，试试放在英文目录下，然后视频名字也改为英文，类似下面这样
> 
> ffmpeg -hide_banner -ignore_unknown -vsync vfr -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -y -i "C:/Users/Administrator/Downloads/Video/1234.mp4" -vn -c:a aac "C:/Users/Administrator/Downloads/Video/ko.m4a"

![QQ截图20240307121234](https://github.com/jianchang512/pyvideotrans/assets/100649768/1fa405f1-512d-426d-aaae-d3c180d6b95c)

**Comment by 2298834669** [comment]
> 看起来是路径字符韩文导致的。
> 
> 尽量使用 英文数字路径和命名吧。ffmpeg对非ansii字符支持不好

但在标准功能模式下一样会报错，识别字幕翻译模式却不会，用一样的功能，其他的未勾选，仅用翻译加cuda加速

**Comment by 2298834669** [comment]
我发现嵌入字幕会造成报错，GPU执行出错，退回CPU执行

**Comment by jianchang512** [comment]
硬字幕格式吧

ffmpeg在执行这个操作时，里面很多格式符号和win路径符重合  比如空格  特殊符号  ，以及无法识别出的 非英文字母，都会导致

**Comment by 2298834669** [comment]
> 硬字幕格式吧
> 
> ffmpeg在执行这个操作时，里面很多格式符号和win路径符重合 比如空格 特殊符号 ，以及无法识别出的 非英文字母，都会导致

软字幕也是
