### ISSUE TITLE
运行sp.py 报Qt错误

### ISSUE THREAD

**Issue by vvvvvx** [jianchang512/pyvideotrans#289]
Linux:[user]:~/py/pyvideotrans$ python sp.py 
Traceback (most recent call last):
  File "/home/user/py/pyvideotrans/sp.py", line 5, in <module>
    from PySide6.QtCore import Qt, QTimer
ModuleNotFoundError: No module named 'PySide6'

**Comment by jianchang512** [comment]
没有按照源码部署的说明一步步操作吗
需要很多模块的，按那个说明操作下

如果确定已那么做了，那么再执行下

pip install pyside6
