### ISSUE TITLE
videotrans-v1.23完整包和升级包下载时提示有病毒，请检查开发环境是否有问题

### ISSUE THREAD

**Issue by johney** [jianchang512/pyvideotrans#291]
![image](https://github.com/jianchang512/pyvideotrans/assets/1620393/2c123258-a711-4bcf-8390-49a303d25a6e)

**Comment by jianchang512** [comment]
仓库页面有说明，直接使用 pyinstaller 打包的，未签名和过杀软，报毒正常，要么忽略要么源码部署

**Comment by johney** [comment]
好的，最近版本升级很快，很赞，但代码质量有些不稳定，加油！
----- 原始邮件 -----
发件人：okmyworld ***@***.***>
收件人：jianchang512/pyvideotrans ***@***.***>
抄送人：solielune ***@***.***>,  Author ***@***.***>
主题：Re:_[jianchang512/pyvideotrans]_videotrans-v1.23完整包和升级包下载时提示有病毒，请检查开发环境是否有问题_(Issue_#291)
日期：2024年03月07日 15点33分


仓库页面有说明，直接使用 pyinstaller 打包的，未签名和过杀软，报毒正常，要么忽略要么源码部署
