### ISSUE TITLE
whe i upolad the video then software trasnsribe the video and then automatically failde and show this missing clublasxx.dll error

### ISSUE THREAD

**Issue by pratikboss19** [jianchang512/pyvideotrans#294]
![Screenshot 2024-03-06 224945](https://github.com/jianchang512/pyvideotrans/assets/162543425/f20e343c-41ce-42e0-9fc5-c97d8e87bc62)
![Screenshot 2024-03-06 224945](https://github.com/jianchang512/pyvideotrans/assets/162543425/b8f4d5ad-fa98-4a47-a466-509bca71be53)

**Comment by jianchang512** [comment]
The prompts are not very clear, follow the instructions to download and install the dll.

**Comment by jianchang512** [comment]
https://github.com/jianchang512/stt/releases/tag/0.0
