### ISSUE TITLE
字幕自动翻译中不同翻译渠道产生的文字错误

### ISSUE THREAD

**Issue by anbangli** [jianchang512/pyvideotrans#296]
1、翻译渠道选用 Microsoft 时，翻译结果中的时间轴中的英文冒号 ":" 被改成了中文冒号 "："。例如：

00：00：01,520 --> 00：00：04,640
蛋白质在整个生物界发挥着无数的作用。

2、翻译渠道选用 Google 时，翻译结果中的时间轴中的英文大于号 ">" 被改成了  "&gt;" 。例如：

00:00:01,520 --&gt; 00:00:04,640
蛋白质在整个生物世界中发挥着无数的作用。

百度 和 DeepL 需要 Key，没有测试

**Comment by jianchang512** [comment]
如果你使用的左侧“文本字幕翻译”按钮中的功能，在翻译字幕时，选择“是srt字幕”后，不会处理时间轴那行，否则按文本翻译，自然会变
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/eecc27f5-238c-4213-9dc0-ee5aa434fa50)
