### ISSUE TITLE
视频翻译报错

### ISSUE THREAD

**Issue by Bob8852** [jianchang512/pyvideotrans#297]
求助：错误提示如下
出错:ffmpes执行结果:失败cnd-l ffmpeg, "-hide banner, -sync', o, -hwaccel", cuda', -hraccel-output fornat', cuda', "y, "sseof, '3, H,a:/baidusynodisk/ai学习/06ai费号学习课/视物/How AI forks/noroice.mp4, sync, 0,-gv,1,-gminv,1-omaxy, 1,
update true D:/download/万能视物译字幕离线软件/videotrans-975/tmp/How Al Works/last. ipg errs- Error reinitializing filters!rllnPailed to inject frame into filter network: Function not implementediirlinError while filtering: Funotion not implementediirlinlout#0/image2
000002151ed95800] Nothing was written into output file because at least one of its streans received no packets. lriinfrane- 0 fps-0.0 -0.0 Lsize- OkB time-N/A bitrate-N/A speed-N/A llrllnConversion failed! llrlln
执行ffmpes失败:errs- Error reinitializing filters!llrllnPailed to inject frane into filter network: Function not implementedllrllnError while filtering: Function not implementedllrlin[out#0/image2 @ 000002151ed95800] Nothing was written into output file, because at least one of its streans received no packets lrlinfrane- 0 fps-00 g-0.0 Lsize- OkB tine-i/A bitrate-i/A speed-N/A lrllnConversion failed!Virlln"出错:末尾添加延 长视频帧失败，将保持原样，截断音频，不延长视频

**Comment by jianchang512** [comment]
1.27版试试
