### ISSUE TITLE
关于srt和语音对齐的建议

### ISSUE THREAD

**Issue by royliaoz** [jianchang512/pyvideotrans#298]
当前的【配音自动加速】效果不太好，不够智能，一旦长度超出就通通按照【配音语速】去转换，这样出来的效果不太好。
希望有一个自动的选项，语音长度超出的句子就自动从srt中的时间计算出这句话所允许的最大长度，然后再计算这句话配音文件的长度，去自动的尽可能的铺满最大长度，这样整体出来的效果应该会更好一些吧，
工具很强大很好用，这是我的一个使用后的建议，谢谢了。
![微信截图_20240307162425](https://github.com/jianchang512/pyvideotrans/assets/67729951/481429ee-7244-4dbb-ae0d-f22de9b4a397)

**Comment by jianchang512** [comment]
已优化，目前的实现原理

https://juejin.cn/post/7343691521601290240?share_token=32f20c8c-11d5-430a-b94b-d0de5aa44d48
