### ISSUE TITLE
使用 clone-voice 失败

### ISSUE THREAD

**Issue by thunderyan** [jianchang512/pyvideotrans#299]
videotrans-v1.23
videotrans-v1.24
版本使用 clone-voice 即时是本地的 clone-voice (127.0.0.1) 的，合成声音的时候也会报错。
videotrans-v1.22 就没有问题
![iShot_2024-03-07_22 07 57](https://github.com/jianchang512/pyvideotrans/assets/22948357/41a3b207-8d22-4aab-a1ae-785cbbb0099f)

**Comment by thunderyan** [comment]
INFO:VideoTrans:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-y', '-i', 'E:\\3月7日\\3月7日\\vocal.wav', '-ss', '00:00:00.00 ', '-to', '00:00:01.600', '-ar', '8000', 'C:/Users/Code/videotrans-v1.24/tmp/3月7日/5968625adf87654002bf05300c9c1914.mp3']

ERROR:VideoTrans:cmd执行出错:Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-y', '-i', 'E:\\3月7日\\3月7日\\vocal.wav', '-ss', '00:00:00.00 ', '-to', '00:00:01.600', '-ar', '8000', 'C:/Users/Code/videotrans-v1.24/tmp/3月7日/5968625adf87654002bf05300c9c1914.mp3']' returned non-zero exit status 4294967274.

INFO:VideoTrans:配音失败:Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-y', '-i', 'E:\\3月7日\\3月7日\\vocal.wav', '-ss', '00:00:00.00 ', '-to', '00:00:01.600', '-ar', '8000', 'C:/Users/Code/videotrans-v1.24/tmp/3月7日/5968625adf87654002bf05300c9c1914.mp3']' returned non-zero exit status 4294967274.

**Comment by jianchang512** [comment]
字幕时间格式问题，毫秒处少了一个0
明早更新修复

**Comment by thunderyan** [comment]
看了一下代码，就是处理字幕字符串的时候，只是判断没有 strip() 掉空格，导致后面毫秒数处理的时候有问题

**Comment by jianchang512** [comment]
已修复
