### ISSUE TITLE
why this error show

### ISSUE THREAD

**Issue by pratikboss19** [jianchang512/pyvideotrans#300]
![Screenshot 2024-03-06 224945](https://github.com/jianchang512/pyvideotrans/assets/162543425/a2a3d4f9-e2d8-4f00-9503-54f041f4ff5f)
![Screenshot 2024-03-06 224945](https://github.com/jianchang512/pyvideotrans/assets/162543425/7db1ac4e-5bd8-4200-bc60-8336cd7c54e0)

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/9bcb5b61-ff32-446c-b37e-697b856bc55f)

https://github.com/jianchang512/stt/releases/tag/0.0

![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/9d0772cd-d4ef-4175-aeb5-b4bd6166cb24)
