### ISSUE TITLE
提一个建议，翻译好的视频，中文的配音速度如何更好的和英文发音完美匹配？

### ISSUE THREAD

**Issue by Bob8852** [jianchang512/pyvideotrans#303]
现在翻译的效果是，1-部分段落的配音与画面不符合，2-影片播放完毕，配音还没说完，或者配音说完，影片已经结束。3-建议作者能将英文字幕的时间戳与中文翻译后的时间戳能保持一致语速，就能完美解决。我觉得这个问题解决了，此软件几乎完美了！已经捐赠作者，真的良心软件啊！

**Comment by jianchang512** [comment]
https://juejin.cn/post/7343691521601290240?share_token=32f20c8c-11d5-430a-b94b-d0de5aa44d48

实现原理
