### ISSUE TITLE
chatgpt翻译问题

### ISSUE THREAD

**Issue by Ayimuzus** [jianchang512/pyvideotrans#304]
[新建文本文档.txt](https://github.com/jianchang512/pyvideotrans/files/14555952/default.txt)
1. 翻译返回后没有执行拆分的操作就进行下一次调用（主要问题）
2. 提前翻译完，最后几句重复
3. gpt返回的结果没有按格式输出
一次翻译10句出现的，一次一句没有问题，但是效果很差，和机翻差不多
后面两个问题应该是gpt的问题，不知道有没有什么好的提示词可以避免这个问题

**Comment by jianchang512** [comment]
没什么办法
除非一次翻译一行，否则只要翻译的行数足够多，翻译任务执行足够长，总会出现一次合并行的问题。
尤其在前一行很长后一行很短只有一两个词，又是前一句的延伸时，chatgpt大概率会将后边一行和前一行翻译为一行内容，这是chatgpt强于普通翻译的地方，不会僵硬翻译每一行，而是照看上下文，但这样对于严格要求返回行数的显然造成了问题。

试了很多办法，包括用更强烈语气要求它不合并，返回行数必须同原文一致。包括用更多的符号分割限制，甚至包括发送和返回都用标准json格式，但无论怎样，只要一个任务用行数大于1000，并且不是一行一译，至少会出现一次这种合并。

如果只有几十数百，倒很少这情况。

目前只能这样。暂无好办法

**Comment by Ayimuzus** [comment]
做了一些测试，使用更大的模型进行识别字幕，可以整体字幕长度比较适中，不会出现一句话30秒的情况
然后出现翻译结果被合并的句子都是原英文字幕句末没有标点符号的句子
个人认为在结合上下文的情况下，对一些长难句中添加标点符号进行断句，对翻译后的影响比较小
是否可以在配置中增加一个字段，用于在每句末尾强制添加标点符号
能够一次翻译多行对翻译效果，执行效率，api费用都有提升
可以试一试

**Comment by jianchang512** [comment]
测试过，并没有什么用，不管添加标点符号还是其他什么符号，只要翻译的足够多，总会出现一两个这样的。

500行时没有出错，1000行时出现了。少量测试似乎没问题，一旦大量用起来，总有那么一两行有问题

**Comment by Ayimuzus** [comment]
看来现在只能这样了

**Comment by Ayimuzus** [comment]
好像第一个问题还没有解决，chatgpt返回了翻译的结果，但是没有进行任何处理，就进行了下一次翻译
关于翻译合并的问题是否可以查考这个方法https://github.com/jesselau76/srt-gpt-translator?tab=readme-ov-file
加一个校验机制，比如我设置一次翻译20行，返回的结果不是20行，就舍弃这次翻译，重新翻译前10行，直到返回的结果行数正确
我作为使用者来说，这个校验的流量和行数正确的翻译比不值一提
