### ISSUE TITLE
please give the solution

### ISSUE THREAD

**Issue by pratikboss19** [jianchang512/pyvideotrans#305]
![Screenshot 2024-03-11 202704](https://github.com/jianchang512/pyvideotrans/assets/162543425/99bc1a28-7252-4626-a133-3eee32713f17)

**Comment by jianchang512** [comment]
win7? don't support win7

**Comment by jianchang512** [comment]
The patchupdate 140MB 7z is for upgrading older versions, i.e. you need to download it, unzip it and overwrite it in the old version directory.

If you don't have the old version and want to download it, you need to download videotrand-.7z  a 1.87G zip file.
