### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Eyion** [jianchang512/pyvideotrans#306]
提示：从视频中提取声音失败，请检查视频中是否含有音轨，或该视频是否存在编码问题。
请问这是什么原因造成的？要如何解决？
标准模式就可以直接将A语言视频转换成B语言视频吗？

**Comment by jianchang512** [comment]
1. 检查视频中是否有声音，如果无声音是没办法处理的
2. 如果有声音，是否存在人类说话声，并且噪声不是太大
3. 视频放网页中能否播放

如果都没问题，自己先尝试下转换格式为 h264.4

**Comment by Eyion** [comment]
上述链接只是举例，我要转换的没有音乐背景声，只有纯人声，不过找不到原链接了，所以不存在背景噪声大的问题。

**Comment by jianchang512** [comment]
那就发个有这问题的视频，能复现的
