### ISSUE TITLE
几个问题想要请教

### ISSUE THREAD

**Issue by steven225** [jianchang512/pyvideotrans#308]
非常感谢开发此软件，也发出很详细的教程。几个问题想要请教如下：

1. 在set.ini文件里，目前的vad设置只有true或false，请问之后有考虑加入vad其他可以微调的变项如vad_threshold等等吗？因为似乎有些影片里有说话的片段，但却没有字幕录制出来，不知道是否可以从该项目来调整？或是有其他的建议做法？

2. 我的电脑没有NVIDIA的独立显卡，在set.ini文件里，我想要选择使用int8，将cuda_com_type=float32改cuda_com_type=int8，是正确的做法吗？

3. 昨天有看到您在微信公众号的文章，才了解原来使用语音前后延展功能很花时间和硬盘空间。想请问的是，如果没有使用语音前后延展功能，是否会影响字幕录制内容的准确性？

4. 虽然我不太知道word-level timings是什么，但不知道如果未来加入此功能，是否可以增加字幕录制内容的准确性？

麻烦了，非常感谢。

**Comment by jianchang512** [comment]
1. 暂无计划，若有需要可以源码部署，自行修改
2. 可以
3. 视频自动慢速花时间和硬盘，并不是前后延展，1.32及以后版本已去掉了视频慢速
4. 实际上 整体识别 和 预先分割 下，已使用了这个，用于精确确定每天字幕的开始和结束时间，但这个对中文支持不太好，无法按照每个字标记时间，有时会多个字或字和标点一起。

**Comment by jianchang512** [comment]
1. 暂无计划，若有需要可以源码部署，自行修改
2. 可以
3. 视频自动慢速花时间和硬盘，并不是前后延展，1.32及以后版本已去掉了视频慢速
4. 实际上 整体识别 和 预先分割 下，已使用了这个，用于精确确定每天字幕的开始和结束时间，但这个对中文支持不太好，无法按照每个字标记时间，有时会多个字或字和标点一起。

**Comment by steven225** [comment]
感谢回答，有几个问题想再釐清如下：

1. 我目前只有用到「视频识别字幕」功能，想确认的是在1.32版以前，该功能即内建「视频自动慢速」吗？而在1.32版将该内建功能移除了吗？

2. 想请问「语音前后延展」是否会佔据大量的硬碟空间？

3. 影片有些地方有人在讲话，在没有嘈杂的背景音之下，讲话的内容有些并没有被认别出来，有讲话却没有字幕生成，不太知道问题出在那里？想请问有可能和电脑设备太差有关吗？目前还没有试过1.32版，在使用之前版本的「视频识别字幕」功能时，model使用large-V3，通常会跑很慢，虽然最后还是可以完成字幕生成，但不知道会不会是因为这样导致有些讲话的内容没有被辨识成字幕？

感谢

**Comment by jianchang512** [comment]
1.  只识别字幕用不到那个功能，前后延展也用不到，也不会占用硬盘。

**Comment by steven225** [comment]
谢谢回答，试着把背景声音移除后，再去transcribe纯人声，确实会提升准确度。
