### ISSUE TITLE
配乐和视频配音同步问题

### ISSUE THREAD

**Issue by troublemakerMibu** [jianchang512/pyvideotrans#309]
版本：v1.34
我为配音视频添加配乐时，如果bgm时间短于视频时长，在bgm播放结束后整个视频会静音，tts生成的配音也跟着消失了。字幕可以正常显示。
建议能否对配乐时间和视频时间进行对齐处理。如果配乐时间较短，则自动循环播放，或者可以添加多首配乐；如果配乐时间比视频时间长，则剪辑配乐时间，使二者同步

**Comment by jianchang512** [comment]
升级到1.35
