### ISSUE TITLE
pretrained_models 有链接可以下载吗？

### ISSUE THREAD

**Issue by blldd** [jianchang512/pyvideotrans#31]
pretrained_models 有链接可以下载吗？

**Comment by jianchang512** [comment]
这个功能已经去掉了。这是消除背景音乐的，实际测试发现作用并不大，主要适合纯粹音乐类型的视频，对于其他的没什么用，反而 导致包过大，打包exe后无法隐藏黑窗口

https://github.com/deezer/spleeter
