### ISSUE TITLE
怎么现在长一点的视频提取文字都无法完成了?

### ISSUE THREAD

**Issue by 10000-ok** [jianchang512/pyvideotrans#310]
识别字幕耗的是不是显存?怎么感觉越更新显存要求越来越高了,以前半小时的视频都能完美成功,现在十几分钟的视频进行到一半就停止了.用的是同样的模型和设置.顺便问一下,怎么去除背景音,提取纯粹人声?

**Comment by jianchang512** [comment]
默认占用显存较多，可调整减少

减少显存占用：当显存不足时，可通过以下修改降低显存占用

打开 videotrans/set.ini文件

cuda_com_type=float32 改为 cuda_com_type=int8 

beam_size=5改为 beam_size=1 

best_of=5 改为 best_of=1 

temperature=1改为 temperature=0

同时在软件主界面中，"整体识别"改为"预先分割"或"均等分割"，将能最大化降低显存占用

**Comment by 10000-ok** [comment]
谢谢大佬

**Comment by 10000-ok** [comment]
还想问一下,这样设置后会影响什么?会影响提取的准确度吗?

**Comment by 10000-ok** [comment]
新增的distil-whisper-large-v2模型是什么模型??和原来的large-v2哪个好?

**Comment by jianchang512** [comment]
看文档 有说明
dis开头的都是只适用于英文视频识别

**Comment by 10000-ok** [comment]
好的
