### ISSUE TITLE
好像第一个问题还没有解决，chatgpt返回了翻译的结果，但是没有进行任何处理，就进行了下一次翻译

### ISSUE THREAD

**Issue by Ayimuzus** [jianchang512/pyvideotrans#311]
好像第一个问题还没有解决，chatgpt返回了翻译的结果，但是没有进行任何处理，就进行了下一次翻译
关于翻译合并的问题是否可以查考这个方法https://github.com/jesselau76/srt-gpt-translator?tab=readme-ov-file
加一个校验机制，比如我设置一次翻译20行，返回的结果不是20行，就舍弃这次翻译，重新翻译前10行，直到返回的结果行数正确
我作为使用者来说，这个校验的流量和行数正确的翻译比不值一提

_Originally posted by @Ayimuzus in https://github.com/jianchang512/pyvideotrans/issues/304#issuecomment-1999619651_

**Comment by jianchang512** [comment]
很多句子重试再多次也是一样，只会白白浪费token

新版 1.36 采用新方法解决了这个问题
