### ISSUE TITLE
is not save video dubbed only audio

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#315]
![SNAG-0037](https://github.com/jianchang512/pyvideotrans/assets/428820/1af338a3-b28a-4901-b446-ef8d8f500b7b)

how integrate new audio to video?

**Comment by jianchang512** [comment]
I don't know what that means.

**Comment by johnfelipe** [comment]
When I run latest version, is not save video dubbed, is only put video
without sound and in other folder audio dubbed

**Comment by jianchang512** [comment]
update 1.38

**Comment by johnfelipe** [comment]
solved with update
