### ISSUE TITLE
1.37 文字合成为语音

### ISSUE THREAD

**Issue by FreemanZ** [jianchang512/pyvideotrans#316]
有大量精校srt字幕需要合成语音
视频工具箱中的文字合成为语音
1、是否支持“语音前后扩展”，窗口中没有看到可选项，
2、是否可以加入批处理功能。
thx

**Comment by jianchang512** [comment]
同时选中多个srt即可，排队处理
目前暂没有前后扩展

**Comment by jianchang512** [comment]
1.38
