### ISSUE TITLE
Can Clone voice add multiple reading roles? I want to create 2 voices in 1 video

### ISSUE THREAD

**Issue by KalvinThien** [jianchang512/pyvideotrans#319]
Can Clone voice add multiple reading roles? I want to create 2 voices in 1 video

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/b1c300b8-38e0-4660-8625-cc48953a633f)

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/cafef8e4-057a-4f41-9732-6a5c33cd8357)

or
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/818b5ff3-c745-4694-9d23-5e2c0722a9d2)

**Comment by KalvinThien** [comment]
https://github.com/jianchang512/pyvideotrans/assets/120565705/600db93d-cc60-4b9f-aa86-4ad604a57b48

i tried but, i can't see anything change

**Comment by jianchang512** [comment]
No reproduction, I tested without problems
Try changing the  `lang=`  line in videotrans/set.ini to `lang=en`
and restart the software

**Comment by KalvinThien** [comment]
> No reproduction, I tested without problems Try changing the `lang=` line in videotrans/set.ini to `lang=en` and restart the software

thanks @jianchang512  , its work , my bad when i tried translate
