### ISSUE TITLE
openai api的代理地址是https://xxxx还是https://xxxx/v1，不是很懂。谢谢

### ISSUE THREAD

**Issue by Doutianbao** [jianchang512/pyvideotrans#32]
RT

**Comment by jianchang512** [comment]
openai 官方的接口地址是 https://api.openai.com/v1  ，但因为墙的缘故，国内无法访问，所以国内很多人创建了中转服务，和官方接口兼容，只是地址需要改成他们的地址

**Comment by Doutianbao** [comment]
好的，明白了
谢谢大神的作品，
有个小小疑问，运行中断后能否继续 呢？
我看视频切片完成了，卡在了翻译这里，下次又得重新切片和语音识别（比较费时的部分）

**Comment by jianchang512** [comment]
是可以的，只是暂时没加这个功能，可能存在一些同名的文件，会导致一些混乱

后续再考虑下如何实现

**Comment by Doutianbao** [comment]
关于翻译的服务，我有一些推荐 ，可能和 DeepLX 相关的
1.这个链接https://api.deeplx.org/translate 放在沉浸性翻译插件里就能使用，速度蛮快的
2.POT（开源翻译软件）也内置很多服务（没去考究源）
RESPECT

**Comment by jianchang512** [comment]
一般google+chatgpt+百度，也差不多了，非官方集合的可能不太稳

内置翻译模型准确的也可以，只是体积太大了，下载安装不方便

**Comment by Doutianbao** [comment]
明白，谢谢
