### ISSUE TITLE
帮助教程和文档列表

### ISSUE THREAD

**Issue by jianchang512** [jianchang512/pyvideotrans#320]
## 帮助教程和文档列表-最新文档发布在掘金博客和微信公众号

> 
>[掘金博客](https://juejin.cn/user/4441682704623992/posts)
>
> 微信公众号搜一搜 **pyvideotrans**
>

----

- [一文搞懂“视频翻译与配音工具”](https://juejin.cn/post/7331558973657251840)
- [详解软件各个功能及界面设置](https://juejin.cn/post/7338335869709123636)
- [选择faster-whisper还是openai-whisper](https://juejin.cn/post/7337853478113804325)
- [提高视频翻译质量的几个方法](https://juejin.cn/post/7337517508151705635)
- [翻译Api申请和使用：百度/腾讯/DeepL/Gemini/chatGPT](https://juejin.cn/post/7343447701948645428)
- [视频翻译配音中几个高频问题解析与应对](https://juejin.cn/post/7345312252478275624)
- [视频翻译配音时几个常见错误与解决方法](https://juejin.cn/post/7346427641350996020)
- [视频翻译并配音后声音、字幕、画面同步问题与应对方法](https://juejin.cn/post/7347513259132682280)
- [在cloudflare上基于m2m100创建完全免费的翻译API服务](https://juejin.cn/post/7344697321799073832)
- [ChatGPT接入指南：快速获取与配置API密钥并填写到软件/工具中使用](https://juejin.cn/post/7342327642852999168)
- [windows操作系统安装配置CUDA12.3和cuDNN](https://juejin.cn/post/7318704408727519270)
- [在软件中使用GPT-SoVITS将文字合成语音](https://juejin.cn/post/7341401110631350324)
- [GPT-SoVITS项目的API改良与使用](https://juejin.cn/post/7343138052973297702)
- [2个分离人声和背景伴奏的工具：urv5和vocal-separate](https://juejin.cn/post/7341617163353341986)
- [在软件中使用clone-voice实现原音色克隆](https://juejin.cn/post/7339746416930062351)
- [在本地部署Qwen通义千问大模型的超简单方法-兼容OpenAi接口](https://juejin.cn/post/7346610589986226176)

- [小白必看：跟随我一步步将中文视频翻译为英文视频并配音](https://mp.weixin.qq.com/s?__biz=MzA5MDgyNjgxOA==&mid=2447805024&idx=2&sn=da6b27f38a175138547fa1bb3f678109)
- [视频翻译配音工具中的高级设置解说](https://mp.weixin.qq.com/s?__biz=MzA5MDgyNjgxOA==&mid=2447804998&idx=1&sn=e06a426db6ee28d95ffb9ee03f8411ef)
- [新增一个无需key无需代理的免费翻译渠道-仅限小白使用](https://mp.weixin.qq.com/s?__biz=MzA5MDgyNjgxOA==&mid=2447804969&idx=2&sn=9cdd192919424a90f391d9f3856a391b)
- [顺畅使用Google翻译渠道的简单方法](https://mp.weixin.qq.com/s?__biz=MzA5MDgyNjgxOA==&mid=2447804942&idx=2&sn=12db325d141ee7e586b6a10d4984d6a9)

----

## 捐助该项目，助力项目持续维护

你可以向微信或支付宝二维码付款，然后备注你的github名称

<img width="200" src="https://github.com/jianchang512/pyvideotrans/raw/main/images/wx.png">

<img width="200" src="https://github.com/jianchang512/pyvideotrans/assets/3378335/fe1aa29d-c26d-46d3-b7f3-e9c030ef32c7">

*备注你的github名称*

----

<img width="200" src="https://github.com/jianchang512/pyvideotrans/assets/3378335/27918373-8f2b-46c6-8817-d14231322b62">

**Comment by Hungthanhmobile** [comment]
请更新视频的原始子模糊功能。
