### ISSUE TITLE
INFO:VideoTrans:配音失败:[Errno 13] Permission denied: 'd:/Users/GAMEMAX/Downloads/videotrans-v1.38/tmp/1.IntroductiontoAI_new.mp4/30f472b146fe657fa1df3a33e67f608e.mp3-speed.mp3'

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#321]
[video-20240319.log](https://github.com/jianchang512/pyvideotrans/files/14655230/video-20240319.log)

![SNAG-0053](https://github.com/jianchang512/pyvideotrans/assets/428820/8ced8e8f-ef73-493c-b990-e671cae61053)

How solve this?

**Comment by jianchang512** [comment]
Looks like a permissions issue, right click to run with administrator privileges
