### ISSUE TITLE
可以做一期配置翻译api的选择解释说明么？freegoogle的翻译质量真的是还不太完美

### ISSUE THREAD

**Issue by Bob8852** [jianchang512/pyvideotrans#322]

**Comment by jianchang512** [comment]
freegoogle就是google翻译

最好的翻译是 deepl，其次是chatgpt

首先语音识别结果要准确，使用 large-v2 v3 将更精确，其次选择更精准的翻译渠道

https://juejin.cn/post/7337517508151705635

**Comment by Copy2Translator** [comment]
> freegoogle就是google翻译
> 
> 最好的翻译是 deepl，其次是chatgpt
> 
> 首先语音识别结果要准确，使用 large-v2 v3 将更精确，其次选择更精准的翻译渠道
> 
> https://juejin.cn/post/7337517508151705635

识别英文我使用的结果是 large v3 不如 medium.en, large v3 识别完总是在某些地方出现不该出现的字幕
白嫖 deepl 或者本地部署 ollama 大预言模型翻译也很不错

**Comment by xdy8888888** [comment]
本地部署 ollama 大预言模型翻译部署完如何接入软件？

**Comment by jianchang512** [comment]
https://www.pyvideotrans.com/14.html
