### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by jeshs** [jianchang512/pyvideotrans#323]
使用了这个软件的视频转字幕功能，以下是一些使用体验的建议：
1、视频识别字幕和音视频转文字是同一个功能吗，看起来重复的功能？
2、鼠标放到选项上弹出提示说明，提示说明过一段时间就消失了，但是还没看完，要动一下鼠标才能看到。建议不要自动消失
3、识别字幕翻译，识别后会自动停止一段时间再翻译。建议加个选项让用户决定要不要自动停止，否则是在浪费时间
4、输出文件夹（保存到...），未设置时，建议默认和源文件路径相同，方便查找
5、视频大概前20秒的语音识别不到
6、识别英文视频语音效果很不好，即使使用了 large 模型也有部分语音识别不到，同时有字幕缺失，还可能有时间轴问题（字幕提前显示和延后显示）。建议增加纯英文模型，效果可能好点。同样的英文视频对比 voxscripts 的 medium.en模型以及 WhisperDesktop 的 ggml-medium.en 模型 ，都差很多

**Comment by jianchang512** [comment]
1. 看名字就知道不同啊，一个只能视频，一个可以音频
2. 需要自动消失，不然太乱了
3. videotrans/set.ini countdown_sec 可自行调整
4. 如果视频和视频所在路径无空格、特殊符号、非英文字母数字外的其他符号，默认就在同文件夹
5. 没发现
6. -
