### ISSUE TITLE
一直显示“视频翻译配音启动中”

### ISSUE THREAD

**Issue by IcyFeather233** [jianchang512/pyvideotrans#324]
# Env

- Mac Pro 2022 M2
- python 3.10

# Description

运行 `python sp.py` 后一直在这个界面：
<img width="560" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/56245435/4ab17497-018e-46dc-8c09-dde024fa575e">
与此同时的m命令行：
<img width="570" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/56245435/af98408f-41af-4d19-83ab-bb7e0742ac5b">

```
main window cannot load library '/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib'
```

看报错应该是和 `libsndfile` 有关，但是我已经通过 `brew install libsndfile` 安装了：
<img width="570" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/56245435/6f6f6133-3914-48d9-984b-46b00ffc518b">

**Comment by jianchang512** [comment]
还是这个 libsndfile 安装问题



cannot load library '/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/cmz/anaconda3/envs/pyvideo/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried:

google 搜索下
