### ISSUE TITLE
音视频转文字问题

### ISSUE THREAD

**Issue by steven225** [jianchang512/pyvideotrans#330]
我使用UVR5将视频先分离出人声的部分，存档类型为mp3档，但在使用声音识别为文字的功能时，2个小时的人声mp3档，大约只识别6至8分钟（尝试了2至3次），程序会自动结束并显示完成，但实际上并没有完成，不知道是发生什么事情？我是用CPU运行，并选预先分割。 再麻烦解惑，十分感谢。

**Comment by jianchang512** [comment]
1. 试试不分离直接识别
2. 如果CPU和内存资源足够，试试 large-v2 large-v1 等模型
3. 如果还是不行，将原音频传上来看看

**Comment by Hung9094** [comment]
在SRT子文件翻译功能中，是否可以添加批量翻译功能，以避免必须单独添加每个文件？

**Comment by Hung9094** [comment]
在语音功能中，您可以添加FPT AI、VBEE或VIETTEL AI的语音功能。

**Comment by q1979635364** [comment]
google有免费的直接用于文本转语音的接口，也有免费的文本翻译接口。
有大佬知道有那种免费的语音转文本的接口吗？

**Comment by jianchang512** [comment]
免费的都很大限制，频率 字符数量等，没什么用处
