### ISSUE TITLE
使用报错 whole all File model.bin is incomplete

### ISSUE THREAD

**Issue by doumilk** [jianchang512/pyvideotrans#335]
点击开始翻译  出现错误 whole all File model.bin is incomplete: failed to read a value of size 4 at position 0('whole all File model.bin is incomplete: failed to read a value of size 4 at position 0',)  请问是什么原因造成

**Comment by jianchang512** [comment]
看下set.ini里 cuda_com_type=是多少，改成float16或float32试试

**Comment by zgbjmy2009** [comment]
该过32和16都不行，有是什么问题的么？

**Comment by jianchang512** [comment]
不要启用cuda了，可能显卡兼容问题

**Comment by jianchang512** [comment]
问题不清晰，无法处理。至少要说明在使用哪个模型时出现的问题，tiny/base/small，另外是 faster模式还是openai模式

**Comment by jianchang512** [comment]
下载完整包
