### ISSUE TITLE
V1.45不能正确识别英文或中文引号等标点符号（如 it's 中的 ‘）

### ISSUE THREAD

**Issue by KevinQ-BIT** [jianchang512/pyvideotrans#337]
我下载了两个版本的windows客户端，其中v1.32可正确识别英文或中文的引号，如it's won't等，在v1.45中，配音时会将中文引号转义成#8217; 英文引号#39; ，导致最终语音读出hash tag，是否是由字符编码引起的问题，望排查，感谢

**Comment by jianchang512** [comment]
升级 v1.48补丁包
