### ISSUE TITLE
能否拉个群组，比如tg,discord

### ISSUE THREAD

**Issue by Doutianbao** [jianchang512/pyvideotrans#34]
RT

**Comment by jianchang512** [comment]
目前用户太少，等些时间搞个 discord

**Comment by leedstyh** [comment]
这个置顶吧，想要建群的进来点个赞统计下人数

**Comment by zihaoxingstudy1** [comment]
892904341977，这是我的抖音粉丝群的群号码，非 qq 群，要在抖音 app 里搜索该群号加群，关于 GPT使用信息在我的抖音邢博士谈科教的粉丝1群的粉丝群里，大家可以先关注我加下我的粉丝群，以后有什么问题都可以在我的粉丝群 进行提问交流，有时候我有事没在群里发言的时候，可以直接问群友要我发过的资料截图呀

**Comment by zihaoxingstudy1** [comment]
> RT

892904341977，这是我的抖音粉丝群的群号码，非 qq 群，要在抖音 app 里搜索该群号加群，关于 GPT使用信息在我的抖音邢博士谈科教的粉丝1群的粉丝群里，大家可以先关注我加下我的粉丝群，以后有什么问题都可以在我的粉丝群 进行提问交流，有时候我有事没在群里发言的时候，可以直接问群友要我发过的资料截图呀

**Comment by JinOuYongGu** [comment]
我来了，一直在等待交流群

**Comment by songxue726** [comment]
坐等discord
