### ISSUE TITLE
视频操作后，清晰度问题

### ISSUE THREAD

**Issue by kpsmail** [jianchang512/pyvideotrans#340]
经常处理后，视频的大小减少了50%，清晰度也是明显降低，是否有办法按原来的清晰度处理。我试了标准模式，音视字幕合并，都不能提高视频清晰度。UI是1.48版

**Comment by jianchang512** [comment]
https://www.pyvideotrans.com/adv.html

![IMG_20240403_213854.jpg](https://github.com/jianchang512/pyvideotrans/assets/3378335/4599fecc-fab6-460a-9227-87097677c752)

**Comment by kpsmail** [comment]
我又试了一下，重新下载1.45完整版。原来是从1.3覆盖升级包的。填了0，还是一样的没有无损

**Comment by kpsmail** [comment]
![屏幕截图 2024-04-05 124418](https://github.com/jianchang512/pyvideotrans/assets/156741049/d1600ab4-0717-468e-8608-2e38c0530da7)
![屏幕截图 2024-04-05 124237](https://github.com/jianchang512/pyvideotrans/assets/156741049/17abf1f9-c9df-4504-bc01-07cd54fc9ec5)
![屏幕截图 2024-04-05 124314](https://github.com/jianchang512/pyvideotrans/assets/156741049/249e5173-1f09-42b9-b77b-c8ed419dbf91)
![屏幕截图 2024-04-05 124338](https://github.com/jianchang512/pyvideotrans/assets/156741049/1f956c8b-63ee-4883-8179-b69917ced05b)
![屏幕截图 2024-04-05 131808](https://github.com/jianchang512/pyvideotrans/assets/156741049/62164971-5b7b-450d-8176-f6ffe412bba7)
![屏幕截图 2024-04-05 131856](https://github.com/jianchang512/pyvideotrans/assets/156741049/18f9fe37-00cd-4cff-92e2-ccb8a75aba77)
![屏幕截图 2024-04-05 131921](https://github.com/jianchang512/pyvideotrans/assets/156741049/ba396141-c854-46e6-9f67-26e5a515cc5a)
这两个参数都设置了，还是没有效果，也重启过了，我发现分离声音的时候，就已经把视频质量减半了

**Comment by jianchang512** [comment]
https://pyvideotrans.com/videoqua.html

先升级到 1.49

**Comment by kpsmail** [comment]
谢谢，换H264模式，确实好多了
