### ISSUE TITLE
语音会多次出现“与井号34”的语音

### ISSUE THREAD

**Issue by WangShuXian6** [jianchang512/pyvideotrans#342]
问题描述：
配音中会出现“与井号34”的语音，也可能是“与井号3次”。
如果启用 保留背景音会少点，不启用 保留背景音出现很多次~~~
但是字幕中，没有 “与井号34”的内容。
且在视频结尾2秒处出现短暂噪音。

faster 模式，base模型没出现过这种情况。

这是配置：
![image](https://github.com/jianchang512/pyvideotrans/assets/30850497/aa5202da-fef7-43e9-9c95-9b7de1666e92)

最后，感谢大佬的开源软件，很伟大。我目前创业，负债较大。以后工作或者赚钱了一定大力捐助。现在只能捐助个小小钱。

**Comment by jianchang512** [comment]
升级补丁包到1.48

**Comment by WangShuXian6** [comment]
> 结尾2秒处出现短暂噪音

感谢大佬，1.48的确没这个“与井号34”问题了。

只是 结尾2秒处出现短暂噪音还是会出现。
