### ISSUE TITLE
请问 DeeplX 地址中是否可以支持查询参数？

### ISSUE THREAD

**Issue by WangShuXian6** [jianchang512/pyvideotrans#343]
这是我买的deeplx api,但是作为私有api，地址带有授权参数：
格式如下：
```
https://deepl.xxx.com/translate?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MTIyOTE3OTgsInVubGltaXRlZCI6ZmFsc2UsImV4cCI6MTcxNDk3MDE5OCwiaWF0IjoxNzEyMjkxNzk4LCJtIjoyMTQ3N
```
填入这个地址后，翻译会报错 401。

目前一直在用deepl api,但是太贵了~~~所以想用x。

**Comment by WangShuXian6** [comment]
> DeeplX 还要买？自己不买服务器架设本地运行也是可以的啊

请问稳定性如何？我还没用过

**Comment by Copy2Translator** [comment]
> > DeeplX 还要买？自己不买服务器架设本地运行也是可以的啊
> 
> 请问稳定性如何？我还没用过

我自己7.5买了个德国的小鸡，稳定使用半年了，本地运行的话也是很稳定的，你可以去 deeplx 的项目下载对应操作系统的文件运行就行，deeplx 本来就是白嫖的官方 api ，并发请求上肯定有限制，不算缺点
