### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by ZhangShen6** [jianchang512/pyvideotrans#344]
在V1.45版本的“视频识别字幕”功能里面，识别视频里的简体中文文字，为什么总会识别成繁体文字

**Comment by jianchang512** [comment]
打开videotrans/set.ini   搜索 initial_prompt_zh=  ，看说明

**Comment by ZhangShen6** [comment]
大佬，我感觉就除了initial_prompt_zh=这条看不懂，其他大部分都看懂了
