### ISSUE TITLE
faster模式部分视频在把字幕从英文翻译到简体中文时会出现 whole all list index out of range

### ISSUE THREAD

**Issue by WangShuXian6** [jianchang512/pyvideotrans#345]
版本：1.48/1.49
faster模式
distil-whisper-medium.en 模型

配置：
![image](https://github.com/jianchang512/pyvideotrans/assets/30850497/1cf00439-e8ec-4c07-96b7-637d6597e068)
报错时机：原字幕识别到一定百分比时。

当前我有6个特定的视频会出现这种情况。
如果需要我可以提供百度盘或其他网盘下载。

链接：https://pan.baidu.com/s/1WX5DHzbCgQBPKVi0vonrcQ 
提取码：wnwt 

报错信息：
```
whole all list index out of range('whole all list index out of range',)
```

日志截取：
```
Sorry, set value as Enum.
INFO:VideoTrans:当前字幕行数  49
INFO:VideoTrans:50
00:05:41,310 --> 00:05:42,370
There we go.
INFO:VideoTrans:当前字幕行数  50
INFO:VideoTrans:51
00:05:42,610 --> 00:05:50,960
Get it out of the way.
INFO:VideoTrans:当前字幕行数  51
INFO:VideoTrans:whole all list index out of range('whole all list index out of range',)
INFO:VideoTrans:Processing 7/40
INFO:VideoTrans:开始处理
```

经过测试，换成 openai 模式，medium.en 模型，完全不会再报错了。

**Comment by Hung9094** [comment]
你好。 这个工具非常好，但是我认为你应该添加隐藏视频原始子部分的功能，那就太好了。
