### ISSUE TITLE
能否新增这功能：批零将字幕转语音后替换原视频的语音

### ISSUE THREAD

**Issue by ipp9** [jianchang512/pyvideotrans#348]
现在我是翻译后 粗略核对了字幕
有一堆中文字幕和英文视频
我希望自动批量逐个中文字幕生成语音然后再把英文视频的语音替换为中文语音
目前好像只能手动一个一个操作 
能否新增这功能 谢谢

**Comment by steven225** [comment]
我也需要这样的功能，希望有机会新增回来，感谢

**Comment by jianchang512** [comment]
https://pyvideotrans.com/localsrt.html

![Screenshot_2024-04-17-20-06-01-784_org.mozilla.firefox.jpg](https://github.com/jianchang512/pyvideotrans/assets/3378335/dd4a8a4b-5a61-4157-8b8f-1b814ff30cf2)
