### ISSUE TITLE
频繁出现5次失败翻译

### ISSUE THREAD

**Issue by dolangong** [jianchang512/pyvideotrans#349]
![屏幕截图 2024-04-10 213750](https://github.com/jianchang512/pyvideotrans/assets/154431951/9439e118-4f74-41d9-a333-1fecc2521c34)

**Comment by WangShuXian6** [comment]
服务器问题吧，用代理或者手动测试下接口

**Comment by jianchang512** [comment]
deeplx本地部署基本不可用。字幕翻译会频繁请求，容易触发封禁ip
