### ISSUE TITLE
进度到99.9%就卡住了，未响应了

### ISSUE THREAD

**Issue by diantongren** [jianchang512/pyvideotrans#35]
如题

**Comment by SharkTal** [comment]
我也碰到了相同情况，使用最新版8.0
![卡住](https://github.com/jianchang512/pyvideotrans/assets/47451399/ec81f2c3-03da-4a1d-a52d-a4efae81ba5a)

**Comment by SharkTal** [comment]
o(￣▽￣)ｄ👍👍👍
