### ISSUE TITLE
升级到1.50后，字幕创建配音功能出现问题

### ISSUE THREAD

**Issue by welles1123** [jianchang512/pyvideotrans#352]
版本:1.50 
字幕创建配音功能中，再入字幕文件，点击"开始配音"按钮，显示红色错误提示"'NoneType' object is not subscriptable"
log文件中同样留下一条记录INFO:VideoTrans:'NoneType' object is not subscriptable
测试了edgeTTS和GPT-SoVITS，都会出现上述错误。

同一台电脑上的1.45版没有上述问题，可以正常运行

**Comment by jianchang512** [comment]
升级 1.51 版本
