### ISSUE TITLE
mac安装提示需要 torch==2.1.2+cu121 

### ISSUE THREAD

**Issue by chloechien520** [jianchang512/pyvideotrans#353]
mac安装后显示ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10

ERROR: Could not find a version that satisfies the requirement torch==2.1.2+cu121 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)

ERROR: No matching distribution found for torch==2.1.2+cu121

WARNING: There was an error checking the latest version of pip.
 mac如何安装呢？

**Comment by jianchang512** [comment]
pip install -r requirements.txt --no-deps

pip install torch

**Comment by ziyangxiami** [comment]
用 3.10 环境就好了，在 3.12 环境一直报错
