### ISSUE TITLE
使用mac版本app显示无法打开。是因为不支持吗

### ISSUE THREAD

**Issue by chloechien520** [jianchang512/pyvideotrans#354]

**Comment by chloechien520** [comment]
<img width="982" alt="Screenshot 2024-04-16 at 00 29 29" src="https://github.com/jianchang512/pyvideotrans/assets/167023331/7190aaf4-9ca6-4c03-a8da-2727690194cb">
<img width="309" alt="Screenshot 2024-04-16 at 00 30 35" src="https://github.com/jianchang512/pyvideotrans/assets/167023331/9ba7007d-031f-438b-915e-24171e3fe591">

**Comment by jianchang512** [comment]
**如果Mac上双击start.app无法打开，请尝试在start.app所属的文件夹上右键->服务->新建位于文件夹位置的终端窗口，然后在终端中执行如下2条命令**
![136f1832fdbd93bdcecbf9ed9c5f7ced](https://github.com/jianchang512/pyvideotrans/assets/3378335/fd53811b-1c69-42df-88c7-5945f6fb9712)

- 命令1 `chmod +x ./do`
- 命令2 `./do`

**Comment by dingdayu** [comment]
![CleanShot 2024-04-16 at 22 49 26@2x](https://github.com/jianchang512/pyvideotrans/assets/2040348/880a6377-b1b5-4fdb-ae7b-013527909dcb)

无法打开“do”，因为Apple无法检查其是否包含恶意软件。

@jianchang512 可以帮忙看看吗？

**Comment by moonlight520rr** [comment]
![螢幕截圖 2024-04-19 21 42 30](https://github.com/jianchang512/pyvideotrans/assets/167542098/0c2b7527-26e2-40df-9601-c11744e4bfe9)
<img width="296" alt="螢幕截圖 2024-04-19 21 44 36" src="https://github.com/jianchang512/pyvideotrans/assets/167542098/e662cd04-7756-4775-81ab-666677f33e56">
同一樣的問題，漏了安裝所需的驅動器？？？

**Comment by ihxperfect** [comment]
./do后会报错
~/mac-videotrans-v1.51 % ./do         
[54187] Error loading Python lib '~/mac-videotrans-v1.51/_internal/Python': dlopen: dlopen(~/mac-videotrans-v1.51/_internal/Python, 0x000A): tried: '~/mac-videotrans-v1.51/_internal/Python' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/XX/Downloads/mac-videotrans-v1.51/_internal/Python' (no such file), '~/mac-videotrans-v1.51/_internal/Python' (not a mach-o file)

**Comment by DoubleStarK** [comment]
> ./do后会报错
> ~/mac-videotrans-v1.51 % ./do [54187] Error loading Python lib '~/mac-videotrans-v1.51/_internal/Python': dlopen: dlopen(~/mac-videotrans-v1.51/_internal/Python, 0x000A): tried: '~/mac-videotrans-v1.51/_internal/Python' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/XX/Downloads/mac-videotrans-v1.51/_internal/Python' (no such file), '~/mac-videotrans-v1.51/_internal/Python' (not a mach-o file)

应该是不支持arm芯片的mac，我后来用源码部署的

**Comment by ihxperfect** [comment]
看来只能这样了

**Comment by jianchang512** [comment]
先源码部署吧
没有mac，不方便打包
