### ISSUE TITLE
从视频中提取声音失败，请检查视频中是否含有音轨，或该视频是否存在编码问题

### ISSUE THREAD

**Issue by UtterlyUseless000** [jianchang512/pyvideotrans#356]
从1.3到现在1.5，我一直遇到这个问题，有时候我双击ffmpeg文件夹里的ffmpeg.exe和ffprobe.exe再运行就没事了，但现在这个方法不行了，这个问题有时候重启又能解决问题。
但这个问题真的比较严重，一直存在。
以下是log：
INFO:VideoTrans:C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4
INFO:VideoTrans:Processing 1/1
INFO:VideoTrans:开始处理
INFO:VideoTrans:C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4
ERROR:VideoTrans:cmd执行出错:-vsync is deprecated. Use -fps_mode
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\CG.DESKTOP-9QUMK26\Desktop\IsolvedUnrealEnginesPackageSizeProblem....mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-04-11T04:25:58.000000Z
  Duration: 00:14:34.95, start: 0.000000, bitrate: 910 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 778 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
[out#0/mp4 @ 000001c5be3b5840] Error opening output C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/novoice.mp4: No such file or directory
Error opening output file C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/novoice.mp4.
Error opening output files: No such file or directory

ERROR:VideoTrans:cmd执行出错:-vsync is deprecated. Use -fps_mode
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\CG.DESKTOP-9QUMK26\Desktop\IsolvedUnrealEnginesPackageSizeProblem....mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-04-11T04:25:58.000000Z
  Duration: 00:14:34.95, start: 0.000000, bitrate: 910 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 778 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
[out#0/ipod @ 0000021369117d00] Error opening output C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/en.m4a: No such file or directory
Error opening output file C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/en.m4a.
Error opening output files: No such file or directory

INFO:VideoTrans:从视频中提取声音失败，请检查视频中是否含有音轨，或该视频是否存在编码问题
INFO:VideoTrans:C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4
INFO:VideoTrans:Processing 1/1
INFO:VideoTrans:开始处理
INFO:VideoTrans:C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4
ERROR:VideoTrans:cmd执行出错:-vsync is deprecated. Use -fps_mode
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\CG.DESKTOP-9QUMK26\Desktop\IsolvedUnrealEnginesPackageSizeProblem....mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-04-11T04:25:58.000000Z
  Duration: 00:14:34.95, start: 0.000000, bitrate: 910 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 778 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
[out#0/mp4 @ 000001cc6c13b800] Error opening output C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/novoice.mp4: No such file or directory
Error opening output file C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/novoice.mp4.
Error opening output files: No such file or directory

ERROR:VideoTrans:cmd执行出错:-vsync is deprecated. Use -fps_mode
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\CG.DESKTOP-9QUMK26\Desktop\IsolvedUnrealEnginesPackageSizeProblem....mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-04-11T04:25:58.000000Z
  Duration: 00:14:34.95, start: 0.000000, bitrate: 910 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 778 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
[out#0/ipod @ 0000028f0f36e6c0] Error opening output C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/en.m4a: No such file or directory
Error opening output file C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/en.m4a.
Error opening output files: No such file or directory

INFO:VideoTrans:从视频中提取声音失败，请检查视频中是否含有音轨，或该视频是否存在编码问题
INFO:VideoTrans:C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4
INFO:VideoTrans:Processing 1/1
INFO:VideoTrans:开始处理
INFO:VideoTrans:C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4
ERROR:VideoTrans:cmd执行出错:-vsync is deprecated. Use -fps_mode
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\CG.DESKTOP-9QUMK26\Desktop\IsolvedUnrealEnginesPackageSizeProblem....mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-04-11T04:25:58.000000Z
  Duration: 00:14:34.95, start: 0.000000, bitrate: 910 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 778 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
[out#0/mp4 @ 00000150ee558ec0] Error opening output C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/novoice.mp4: No such file or directory
Error opening output file C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/novoice.mp4.
Error opening output files: No such file or directory

ERROR:VideoTrans:cmd执行出错:-vsync is deprecated. Use -fps_mode
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\CG.DESKTOP-9QUMK26\Desktop\IsolvedUnrealEnginesPackageSizeProblem....mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-04-11T04:25:58.000000Z
  Duration: 00:14:34.95, start: 0.000000, bitrate: 910 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 778 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2024-04-11T04:25:58.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 04/10/2024.
      vendor_id       : [0][0][0][0]
[out#0/ipod @ 000002b62843e380] Error opening output C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/en.m4a: No such file or directory
Error opening output file C:/Users/CG.DESKTOP-9QUMK26/Desktop/IsolvedUnrealEnginesPackageSizeProblem....mp4/en.m4a.
Error opening output files: No such file or directory

INFO:VideoTrans:从视频中提取声音失败，请检查视频中是否含有音轨，或该视频是否存在编码问题
![微信截图_20240417175422](https://github.com/jianchang512/pyvideotrans/assets/162782160/03a5995e-8178-4293-9974-214832eef8f9)

**Comment by jianchang512** [comment]
1.  播放下确定有声音
2. 视频移动个位置，名字改短点，看你的日志，似乎视频从盘符开始的路径有二百多个字符吧，改个简短名字比如1.mp4，放到 d:/001/1.mp4 再试试
