### ISSUE TITLE
translate_type error

### ISSUE THREAD

**Issue by SharkTal** [jianchang512/pyvideotrans#36]
我使用cli 进行了测试，发生错误如下--
![tranlate_type_error](https://github.com/jianchang512/pyvideotrans/assets/47451399/b14542c4-05a5-43f2-ab26-cccdbbbf0970)

**Comment by jianchang512** [comment]
这几天GUI界面变动较大，cli 未充分测试，存在些问题，下次修改

**Comment by aimarxjg** [comment]
@jianchang512 大佬，OPENAI的这个TTS   类似的功能是不是能加上啊，（也直接调用微软语音配呗~） 
https://video.weibo.com/show?fid=1034:4965936038608994
要是特别麻烦就算了，似乎大家用的也不多😊

COMFYUI 也有类似的 文字转语音直接生成MP3的，这个小程序功能就更强了
https://github.com/chflame163/ComfyUI_MSSpeech_TTS

**Comment by SharkTal** [comment]
👍👍👍
