### ISSUE TITLE
1.55 批量工作时无法完成 所有工作

### ISSUE THREAD

**Issue by HelloKittyWrongNumber** [jianchang512/pyvideotrans#364]
1.55 批量工作时无法完成 所有工作.  只能完成部份， 但是软件已经停止运作. (1.54 没有这个问题, 可能是1.55 同時進行 多个任务所致)

**Comment by lin16303** [comment]
用户能不能根据自己硬件配置选择是否开启批量工作？

**Comment by WangShuXian6** [comment]
我也是这样，试了2次，覆盖升级，硬件配置没问题，i7,3060GTX,32GB内存。
![image](https://github.com/jianchang512/pyvideotrans/assets/30850497/34fa5721-aca9-45ba-ae49-d1e94ff381b3)
只有第一个视频成功，其他都视频连输出文件都没有，按说至少有识别出来的英语字幕，但啥都没有。

**Comment by jianchang512** [comment]
1. 等升级
2. 视频重命名下，只使用 英文 数字 .-这些符号命名

**Comment by jianchang512** [comment]
1. 等升级
2. 视频重命名下，只使用 英文 数字 .-这些符号命名

**Comment by WangShuXian6** [comment]
> 1. 等升级
> 2. 视频重命名下，只使用 英文 数字 .-这些符号命名

这是视频名称`1. Pickup Class.mp4`,没有中文，但是有空格~~~而且第一个视频总会成功，其他的都会失败。
是不是空格名称的原因？

**Comment by HelloKittyWrongNumber** [comment]
问题依然存在.  升级了1.56问题依然存在. 不能完成所有任务 或所有任务同时开始，但并没有完成. 确认软件已停止运作. 
1.54比較好. 1.54完美運作

**Comment by WangShuXian6** [comment]
> 问题依然存在. 升级了1.56问题依然存在. 不能完成所有任务 或所有任务同时开始，但并没有完成. 确认软件已停止运作. 1.54比較好. 1.54完美運作

音频视频分离等处理会占用CPU资源，并发处理会长时间占用，可能会导致软件卡顿~~~只能试试关掉其他软件，释放资源。或者加个好处理器。

之前的版本CPU高峰时我这会稍微卡几秒，但是1.56没在出现这情况，即时CPU很高~~
