### ISSUE TITLE
新版本的人声分离功能没有了吗?

### ISSUE THREAD

**Issue by 10000-ok** [jianchang512/pyvideotrans#367]
新版本的人声分离功能没有了吗?想要那种纯人声,不带音乐和杂音的,能实现吗?

**Comment by jianchang512** [comment]
如果仅仅是想分离背景，建议使用专门工具分离吧，内置的太慢
https://pyvideotrans.com/vocal.html

**Comment by lin16303** [comment]
不分离的话识别率会大大降低，这个软件王牌优势之一啊，建议保留，也可以加设置选项给需要加快配音流程的人。

**Comment by lin16303** [comment]
还有一个问题，发现157无论是否点击保留背景音都无法分离人声后，改回148也还是同157一样无法分离人声，恢复系统映像后148才可正常分离人声，是否设置保留在了注册表里？还是希望作者把人声分离这一个选项加回来，谢谢

**Comment by jianchang512** [comment]
这个功能一直都z在，测试无异常，去掉的是单独使用的“人声背景分离”
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/8439d7bb-5cc5-4e84-996a-c0b9747745c4)

**Comment by lin16303** [comment]
157不再分离出instrument.wav和vocal.wav，之前版本是用无背景声的人声来识别，现在是直接识别原视频音轨？

**Comment by jianchang512** [comment]
选中“保留背景音”后仍会分离出这2个文件的。如果没有，那就是分离中出错跳过了。看logs下日志

**Comment by lin16303** [comment]
157即使勾选保留背景音，就是不再分离了，logs无错
INFO:VideoTrans:E:/QQDownload/_video_out/1.mp4
INFO:VideoTrans:96a73301e2ef5a7bffc0a29ac6646c9c
INFO:VideoTrans:1.mp4
INFO:VideoTrans:开始处理
INFO:VideoTrans:开始进行语音识别
INFO:VideoTrans:语音识别前先分割数据进行
INFO:VideoTrans:若视频很大，此步会比较耗时，请耐心等待
INFO:VideoTrans:语音识别进度 1/10
INFO:VideoTrans:1
0:00:00 --> 0:00:06,200
this message is for my gen x brothers and sisters. looks like it's time for us to clean up this .

**Comment by lin16303** [comment]
下载的新文件，还是老样子
![Uploading QQ截图20240425140358.jpg…]()

**Comment by jianchang512** [comment]
update
