### ISSUE TITLE
请求大佬支持 claude 3和 deepseek 翻译接口

### ISSUE THREAD

**Issue by WangShuXian6** [jianchang512/pyvideotrans#368]
deepseek 提供了免费额度，和gpt的格式一样，但是要选择自己的特有模型~~~ https://platform.deepseek.com/

买了 claude 3，据说比gpt3.5turbo翻译质量更好，价格更便宜~~~

**Comment by jianchang512** [comment]
chatGPT兼容接口都可使用菜单-设置-chatgpt里配置。模型名字在 videotrans/set.ini 中 chatgpt_model 参数里添加
