### ISSUE TITLE
1.57 FreeChatGpt进行翻译字幕报错无法使用

### ISSUE THREAD

**Issue by lxm15930** [jianchang512/pyvideotrans#370]
版本1.57 ,选择一个英文视频后，选择freeChatGpt进行翻译报错，如下图
![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/f4a8a91a-2105-4b5f-b657-d6f35761e3fa)

**Comment by jianchang512** [comment]
三方免费赞助的，不能用没办法，换其他渠道
