### ISSUE TITLE
1.57 音频转字幕时已安装的模型认别不到

### ISSUE THREAD

**Issue by lxm15930** [jianchang512/pyvideotrans#371]
系统1.57，已安装相应的识别模型，进行音频转字幕时却识别不到

![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/ee4187e1-eaba-4cd5-9597-e00e00c9a503)

![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/f99ab443-77b1-417d-8eff-44b4cb1250fb)

**Comment by jianchang512** [comment]
模型下载后需要重启软件，并且确保目录正确，看下载页面图片说明

**Comment by lxm15930** [comment]
@jianchang512 目前下载后已启动多次软件。
1.下载模板目录如下:
![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/8c9660a8-6cf9-447a-b24b-76513a256daa)

2.在标准模式下是可以使用v2的
![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/ef6d7430-01e7-4574-8dc1-d1788f82b4cc)

3.而在"音频转字幕"窗口，同样选择v2就不行
![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/ac053c84-8ea2-409c-b892-037279d56d5d)
![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/823d7ebf-2fab-464d-9e82-4cdd3c0a34fe)
