### ISSUE TITLE
无法使用Microsoft、Google和chatGPT翻译

### ISSUE THREAD

**Issue by steven225** [jianchang512/pyvideotrans#373]
因为人不在国内，所以不用挂代理，都可以翻译成功。 而今天早上使用1.61版的翻译时，都显示Microsoft、Google和chatGPT翻译失败的讯息如下，但是使用DeepL翻译没有问题。 想请问这是Microsoft、Google和chatGPT的问题吗？还是程式的问题？感谢。

Microsoft翻译失败回传讯息：连接微软翻译失败，请更换其他翻译渠道

Google翻译失败回传讯息：2次重试后依然出错：HTTPSConnectionPool（host='translate.google.com'， port=443）： Max retries exceeded

<img width="560" alt="螢幕擷取畫面 2024-04-27 103155" src="https://github.com/jianchang512/pyvideotrans/assets/21309548/0e696b93-2305-4f06-871f-95a211362f5d">

**Comment by jianchang512** [comment]
看报错类型还是连接问题，如果设置了系统代理，先取消
如果网络地址文本框内有输入就删掉，然后重试

确认浏览器里能打开google

**Comment by steven225** [comment]
感谢作者的回复，我后来有找到了原因。 

原本以为只要将在「批量翻译字幕」里的「网络代理地址」内容地址删除即可，但发现不能只删除该位置，连「标准功能模式」里的「网络代理地址」内容地址删除也需要一并删除。 否则，在「批量翻译字幕」的「网络代理地址」内容地址为空白，但「标准功能模式」里的「网络代理地址」内容地址仍有网址的话，该程序仍然会经由代理连出去，就会使得在国外使用时反而连接错误。

**Comment by jianchang512** [comment]
是的。批量翻译时，也会判断主界面里是否有填写代理，有填写就使用，主要是为了方便，主界面有填写，这里就无需再填写
