### ISSUE TITLE
关于翻译的个人做法

### ISSUE THREAD

**Issue by ipp9** [jianchang512/pyvideotrans#376]
很感谢作者提供了google翻译字幕功能，翻译质量大部分时候还算看的懂。
但我最近试了，用subtitle edit打开字幕文件，使用他的复制黏贴翻译功能，复制英文原文给kimi先翻译为中文，以后润色处理。再把润色后的译文黏贴到subtitle edit,这样效果挺好的。只不过行数很多时候要自己手动调整。
感觉随着技术的发展，过几年有专门针对字幕翻译润色的大模型，那时候可以全自动化了。

**Comment by WangShuXian6** [comment]
是不是把翻译后的整个srt内容再给gpt一次，让他润色，好想法~~关键是不能出错，不要修改时间戳~~防止gpt把时间戳搞坏~~
