### ISSUE TITLE
【暂勿使用large-v3模型】ERROR:VideoTrans:Get_large_audio_transcription error:list index out of range

### ISSUE THREAD

**Issue by zhangzzgz** [jianchang512/pyvideotrans#38]
用google baidu chatgpt都会卡在这个错误上

**Comment by jianchang512** [comment]
哪个版本，是 0.8.3吗，不是的话升级下。之前有这个错误，是翻译失败了

**Comment by zhangzzgz** [comment]
0.8.3也会出现这个错误
log
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:folder_path='D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日'
aud_path='D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/11月8日.wav'
sub_name='D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/11月8日.srt'
INFO:VideoTrans:start_time=0,end_time=10500,duration=[0, 10500, True]
INFO:VideoTrans:sr.AudioFile:chunk_filename='D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/##11月8日_tmp/c0_0_10.wav'
INFO:VideoTrans:start_time=10000,end_time=19728,duration=[10000, 19728, False]
INFO:VideoTrans:sr.AudioFile:chunk_filename='D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/##11月8日_tmp/c1_10_19.wav'
ERROR:VideoTrans:Get_large_audio_transcription error:'code'
INFO:VideoTrans:准备合成语音 source_mp4='C:/Users/cloudox/Desktop/test/11月8日.mp4'
ERROR:VideoTrans:Get_large_audio_transcription error:list index out of range

**Comment by Copy2Translator** [comment]
我的0.83报这个错误
Win10 专业工作站版 22H2 19045.3636
已经把 ffmpeg 加入环境变量了

INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:Will execute: ffmpeg -y -i D:/BaiduNetdiskDownload/2.Shader Nodes/1.PrincipledNodeWithImages.mp4 -acodec pcm_s16le -ac 1 -f wav D:/videotrans-v0.8.3/tmp/1.PrincipledNodeWithImages/1.PrincipledNodeWithImages.wav
ERROR:VideoTrans:FFmepg exec error:Command 'ffmpeg -y -i D:/BaiduNetdiskDownload/2.Shader Nodes/1.PrincipledNodeWithImages.mp4 -acodec pcm_s16le -ac 1 -f wav D:/videotrans-v0.8.3/tmp/1.PrincipledNodeWithImages/1.PrincipledNodeWithImages.wav' returned non-zero exit status 4294967294.
INFO:VideoTrans:folder_path='D:/videotrans-v0.8.3/tmp/1.PrincipledNodeWithImages'
aud_path='D:/videotrans-v0.8.3/tmp/1.PrincipledNodeWithImages/1.PrincipledNodeWithImages.wav'
sub_name='D:/videotrans-v0.8.3/tmp/1.PrincipledNodeWithImages/1.PrincipledNodeWithImages.srt'
ERROR:VideoTrans:Get_large_audio_transcription error:[Errno 2] No such file or directory: 'D:/videotrans-v0.8.3/tmp/1.PrincipledNodeWithImages/1.PrincipledNodeWithImages.wav'

**Comment by jianchang512** [comment]
> D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/11月8日.srt

D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/11月8日.srt 这个文件打开看看里面有没有内容

**Comment by jianchang512** [comment]
> PrincipledNodeWithImages

所有用到的目录，包括原始视频和目标视频保存目录以及软件所在目录，都不要有空格，对空格没有特殊处理，可能有错

**Comment by zhangzzgz** [comment]
> > D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/11月8日.srt
> 
> D:/迅雷下载/videotrans-v0.8.3/tmp/11月8日/11月8日.srt 这个文件打开看看里面有没有内容，如果没内容，说明翻译出错了，如果有内容，将软件放在英文或数字目录下再试试

srt文件是空白的。

**Comment by jianchang512** [comment]
用的什么翻译，换个翻译试试
然后执行前清空video.log，注意看都有什么错误，以及界面里的日志区域，看看有没有提示翻译错误

**Comment by jianchang512** [comment]
google  chatgpt需要用代理，百度不要用代理，百度用了代理反而不可使用，百度限制了只能国内区域

**Comment by zhangzzgz** [comment]
之前用的chatgpt，现在用的gogle。我的代理是在路由器上的

INFO:VideoTrans:start_time=436567,end_time=440506,duration=(436567, 440506, False)
INFO:VideoTrans:sr.AudioFile:chunk_filename='D:/videotrans/tmp/1/##1_tmp/c65_436_440.wav'
INFO:VideoTrans:准备合成语音 source_mp4='C:/Users/cloudox/Desktop/test/1.mp4'
ERROR:VideoTrans:Get_large_audio_transcription error:list index out of range

![1699513713469](https://github.com/jianchang512/pyvideotrans/assets/125445373/28bdb8a9-2251-41c4-9c41-50042b24346b)

**Comment by jianchang512** [comment]
如果 srt 文件里没有内容，那肯定是会出错的。

先不要进行合成这一步，语音识别可能没成功。

目录下 voice_list.json 打开看看有没有内容

**Comment by zhangzzgz** [comment]
> 如果 srt 文件里没有内容，那肯定是会出错的。
> 
> 先不要进行合成这一步，语音识别可能没成功。
> 
> 目录下 voice_list.json 打开看看有没有内容

有内容
{"af": ["No", "af-ZA-AdriNeural", "af-ZA-WillemNeural"], "sq": ["No", "sq-AL-AnilaNeural", "sq-AL-IlirNeural"], "am": ["No", "am-ET-AmehaNeural", "am-ET-MekdesNeural"], "ar": ["No", "ar-DZ-AminaNeural", "ar-DZ-IsmaelNeural", "ar-BH-AliNeural", "ar-BH-LailaNeural", "ar-EG-SalmaNeural", "ar-EG-ShakirNeural", "ar-IQ-BasselNeural", "ar-IQ-RanaNeural", "ar-JO-SanaNeural", "ar-JO-TaimNeural", "ar-KW-FahedNeural", "ar-KW-NouraNeural", "ar-LB-LaylaNeural", "ar-LB-RamiNeural", "ar-LY-ImanNeural", "ar-LY-OmarNeural", "ar-MA-JamalNeural", "ar-MA-MounaNeural", "ar-OM-AbdullahNeural", "ar-OM-AyshaNeural", "ar-QA-AmalNeural", "ar-QA-MoazNeural", "ar-SA-HamedNeural", "ar-SA-ZariyahNeural", "ar-SY-AmanyNeural", "ar-SY-LaithNeural", "ar-TN-HediNeural", "ar-TN-ReemNeural", "ar-AE-FatimaNeural", "ar-AE-HamdanNeural", "ar-YE-MaryamNeural", "ar-YE-SalehNeural"], "az": ["No", "az-AZ-BabekNeural", "az-AZ-BanuNeural"], "bn": ["No", "bn-BD-NabanitaNeural", "bn-BD-PradeepNeural", "bn-IN-BashkarNeural", "bn-IN-TanishaaNeural"], "bs": ["No", "bs-BA-GoranNeural", "bs-BA-VesnaNeural"], "bg": ["No", "bg-BG-BorislavNeural", "bg-BG-KalinaNeural"], "my": ["No", "my-MM-NilarNeural", "my-MM-ThihaNeural"], "ca": ["No", "ca-ES-EnricNeural", "ca-ES-JoanaNeural"], "zh": ["No", "zh-HK-HiuGaaiNeural", "zh-HK-HiuMaanNeural", "zh-HK-WanLungNeural", "zh-CN-XiaoxiaoNeural", "zh-CN-XiaoyiNeural", "zh-CN-YunjianNeural", "zh-CN-YunxiNeural", "zh-CN-YunxiaNeural", "zh-CN-YunyangNeural", "zh-CN-liaoning-XiaobeiNeural", "zh-TW-HsiaoChenNeural", "zh-TW-YunJheNeural", "zh-TW-HsiaoYuNeural", "zh-CN-shaanxi-XiaoniNeural"], "hr": ["No", "hr-HR-GabrijelaNeural", "hr-HR-SreckoNeural"], "cs": ["No", "cs-CZ-AntoninNeural", "cs-CZ-VlastaNeural"], "da": ["No", "da-DK-ChristelNeural", "da-DK-JeppeNeural"], "nl": ["No", "nl-BE-ArnaudNeural", "nl-BE-DenaNeural", "nl-NL-ColetteNeural", "nl-NL-FennaNeural", "nl-NL-MaartenNeural"], "en": ["No", "en-AU-NatashaNeural", "en-AU-WilliamNeural", "en-CA-ClaraNeural", "en-CA-LiamNeural", "en-HK-SamNeural", "en-HK-YanNeural", "en-IN-NeerjaExpressiveNeural", "en-IN-NeerjaNeural", "en-IN-PrabhatNeural", "en-IE-ConnorNeural", "en-IE-EmilyNeural", "en-KE-AsiliaNeural", "en-KE-ChilembaNeural", "en-NZ-MitchellNeural", "en-NZ-MollyNeural", "en-NG-AbeoNeural", "en-NG-EzinneNeural", "en-PH-JamesNeural", "en-PH-RosaNeural", "en-SG-LunaNeural", "en-SG-WayneNeural", "en-ZA-LeahNeural", "en-ZA-LukeNeural", "en-TZ-ElimuNeural", "en-TZ-ImaniNeural", "en-GB-LibbyNeural", "en-GB-MaisieNeural", "en-GB-RyanNeural", "en-GB-SoniaNeural", "en-GB-ThomasNeural", "en-US-AriaNeural", "en-US-AnaNeural", "en-US-ChristopherNeural", "en-US-EricNeural", "en-US-GuyNeural", "en-US-JennyNeural", "en-US-MichelleNeural", "en-US-RogerNeural", "en-US-SteffanNeural"], "et": ["No", "et-EE-AnuNeural", "et-EE-KertNeural"], "fil": ["No", "fil-PH-AngeloNeural", "fil-PH-BlessicaNeural"], "fi": ["No", "fi-FI-HarriNeural", "fi-FI-NooraNeural"], "fr": ["No", "fr-BE-CharlineNeural", "fr-BE-GerardNeural", "fr-CA-AntoineNeural", "fr-CA-JeanNeural", "fr-CA-SylvieNeural", "fr-FR-DeniseNeural", "fr-FR-EloiseNeural", "fr-FR-HenriNeural", "fr-CH-ArianeNeural", "fr-CH-FabriceNeural"], "gl": ["No", "gl-ES-RoiNeural", "gl-ES-SabelaNeural"], "ka": ["No", "ka-GE-EkaNeural", "ka-GE-GiorgiNeural"], "de": ["No", "de-AT-IngridNeural", "de-AT-JonasNeural", "de-DE-AmalaNeural", "de-DE-ConradNeural", "de-DE-KatjaNeural", "de-DE-KillianNeural", "de-CH-JanNeural", "de-CH-LeniNeural"], "el": ["No", "el-GR-AthinaNeural", "el-GR-NestorasNeural"], "gu": ["No", "gu-IN-DhwaniNeural", "gu-IN-NiranjanNeural"], "he": ["No", "he-IL-AvriNeural", "he-IL-HilaNeural"], "hi": ["No", "hi-IN-MadhurNeural", "hi-IN-SwaraNeural"], "hu": ["No", "hu-HU-NoemiNeural", "hu-HU-TamasNeural"], "is": ["No", "is-IS-GudrunNeural", "is-IS-GunnarNeural"], "id": ["No", "id-ID-ArdiNeural", "id-ID-GadisNeural"], "ga": ["No", "ga-IE-ColmNeural", "ga-IE-OrlaNeural"], "it": ["No", "it-IT-DiegoNeural", "it-IT-ElsaNeural", "it-IT-IsabellaNeural"], "ja": ["No", "ja-JP-KeitaNeural", "ja-JP-NanamiNeural"], "jv": ["No", "jv-ID-DimasNeural", "jv-ID-SitiNeural"], "kn": ["No", "kn-IN-GaganNeural", "kn-IN-SapnaNeural"], "kk": ["No", "kk-KZ-AigulNeural", "kk-KZ-DauletNeural"], "km": ["No", "km-KH-PisethNeural", "km-KH-SreymomNeural"], "ko": ["No", "ko-KR-InJoonNeural", "ko-KR-SunHiNeural"], "lo": ["No", "lo-LA-ChanthavongNeural", "lo-LA-KeomanyNeural"], "lv": ["No", "lv-LV-EveritaNeural", "lv-LV-NilsNeural"], "lt": ["No", "lt-LT-LeonasNeural", "lt-LT-OnaNeural"], "mk": ["No", "mk-MK-AleksandarNeural", "mk-MK-MarijaNeural"], "ms": ["No", "ms-MY-OsmanNeural", "ms-MY-YasminNeural"], "ml": ["No", "ml-IN-MidhunNeural", "ml-IN-SobhanaNeural"], "mt": ["No", "mt-MT-GraceNeural", "mt-MT-JosephNeural"], "mr": ["No", "mr-IN-AarohiNeural", "mr-IN-ManoharNeural"], "mn": ["No", "mn-MN-BataaNeural", "mn-MN-YesuiNeural"], "ne": ["No", "ne-NP-HemkalaNeural", "ne-NP-SagarNeural"], "nb": ["No", "nb-NO-FinnNeural", "nb-NO-PernilleNeural"], "ps": ["No", "ps-AF-GulNawazNeural", "ps-AF-LatifaNeural"], "fa": ["No", "fa-IR-DilaraNeural", "fa-IR-FaridNeural"], "pl": ["No", "pl-PL-MarekNeural", "pl-PL-ZofiaNeural"], "pt": ["No", "pt-BR-AntonioNeural", "pt-BR-FranciscaNeural", "pt-PT-DuarteNeural", "pt-PT-RaquelNeural"], "ro": ["No", "ro-RO-AlinaNeural", "ro-RO-EmilNeural"], "ru": ["No", "ru-RU-DmitryNeural", "ru-RU-SvetlanaNeural"], "sr": ["No", "sr-RS-NicholasNeural", "sr-RS-SophieNeural"], "si": ["No", "si-LK-SameeraNeural", "si-LK-ThiliniNeural"], "sk": ["No", "sk-SK-LukasNeural", "sk-SK-ViktoriaNeural"], "sl": ["No", "sl-SI-PetraNeural", "sl-SI-RokNeural"], "so": ["No", "so-SO-MuuseNeural", "so-SO-UbaxNeural"], "es": ["No", "es-AR-ElenaNeural", "es-AR-TomasNeural", "es-BO-MarceloNeural", "es-BO-SofiaNeural", "es-CL-CatalinaNeural", "es-CL-LorenzoNeural", "es-CO-GonzaloNeural", "es-CO-SalomeNeural", "es-CR-JuanNeural", "es-CR-MariaNeural", "es-CU-BelkysNeural", "es-CU-ManuelNeural", "es-DO-EmilioNeural", "es-DO-RamonaNeural", "es-EC-AndreaNeural", "es-EC-LuisNeural", "es-SV-LorenaNeural", "es-SV-RodrigoNeural", "es-GQ-JavierNeural", "es-GQ-TeresaNeural", "es-GT-AndresNeural", "es-GT-MartaNeural", "es-HN-CarlosNeural", "es-HN-KarlaNeural", "es-MX-DaliaNeural", "es-MX-JorgeNeural", "es-NI-FedericoNeural", "es-NI-YolandaNeural", "es-PA-MargaritaNeural", "es-PA-RobertoNeural", "es-PY-MarioNeural", "es-PY-TaniaNeural", "es-PE-AlexNeural", "es-PE-CamilaNeural", "es-PR-KarinaNeural", "es-PR-VictorNeural", "es-ES-AlvaroNeural", "es-ES-ElviraNeural", "es-US-AlonsoNeural", "es-US-PalomaNeural", "es-UY-MateoNeural", "es-UY-ValentinaNeural", "es-VE-PaolaNeural", "es-VE-SebastianNeural"], "su": ["No", "su-ID-JajangNeural", "su-ID-TutiNeural"], "sw": ["No", "sw-KE-RafikiNeural", "sw-KE-ZuriNeural", "sw-TZ-DaudiNeural", "sw-TZ-RehemaNeural"], "sv": ["No", "sv-SE-MattiasNeural", "sv-SE-SofieNeural"], "ta": ["No", "ta-IN-PallaviNeural", "ta-IN-ValluvarNeural", "ta-MY-KaniNeural", "ta-MY-SuryaNeural", "ta-SG-AnbuNeural", "ta-SG-VenbaNeural", "ta-LK-KumarNeural", "ta-LK-SaranyaNeural"], "te": ["No", "te-IN-MohanNeural", "te-IN-ShrutiNeural"], "th": ["No", "th-TH-NiwatNeural", "th-TH-PremwadeeNeural"], "tr": ["No", "tr-TR-AhmetNeural", "tr-TR-EmelNeural"], "uk": ["No", "uk-UA-OstapNeural", "uk-UA-PolinaNeural"], "ur": ["No", "ur-IN-GulNeural", "ur-IN-SalmanNeural", "ur-PK-AsadNeural", "ur-PK-UzmaNeural"], "uz": ["No", "uz-UZ-MadinaNeural", "uz-UZ-SardorNeural"], "vi": ["No", "vi-VN-HoaiMyNeural", "vi-VN-NamMinhNeural"], "cy": ["No", "cy-GB-AledNeural", "cy-GB-NiaNeural"], "zu": ["No", "zu-ZA-ThandoNeural", "zu-ZA-ThembaNeural"]}

**Comment by jianchang512** [comment]
先不要选择配音，只生成字幕，然后注意观察 GUI 记录区和日志，先能srt里有内容，后续才能正常

**Comment by zhangzzgz** [comment]
按照图上设置未见到有输出srt

![1699515100227](https://github.com/jianchang512/pyvideotrans/assets/125445373/bb77cd03-cc88-4b4d-9669-82c1e1d1884c)
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:Will execute: ffmpeg -y -i C:/Users/cloudox/Desktop/test/1.mp4 -acodec pcm_s16le -ac 1 -f wav D:/videotrans/tmp/1/1.wav
INFO:VideoTrans:folder_path='D:/videotrans/tmp/1'
aud_path='D:/videotrans/tmp/1/1.wav'
sub_name='D:/videotrans/tmp/1/1.srt'
INFO:VideoTrans:start_time=0,end_time=10500,duration=(0, 10500, True)
INFO:VideoTrans:sr.AudioFile:chunk_filename='D:/videotrans/tmp/1/##1_tmp/c0_0_10.wav'
INFO:VideoTrans:start_time=10000,end_time=19728,duration=(10000, 19728, False)
INFO:VideoTrans:sr.AudioFile:chunk_filename='D:/videotrans/tmp/1/##1_tmp/c1_10_19.wav'
INFO:VideoTrans:准备合成语音 source_mp4='C:/Users/cloudox/Desktop/test/1.mp4'
INFO:VideoTrans:准备完毕，开始合成视频，target_mp4='c:/users/cloudox/desktop/test/_video_out/1.mp4'
source_mp4='C:/Users/cloudox/Desktop/test/1.mp4'
INFO:VideoTrans:合成软字幕
INFO:VideoTrans:Will execute: ffmpeg -y -i C:/Users/cloudox/Desktop/test/1.mp4 -sub_charenc UTF-8 -f srt -i D:/videotrans/tmp/1/1.srt -c:v libx264  -c:s mov_text -metadata:s:s:0 language=chi c:/users/cloudox/desktop/test/_video_out/1.mp4

**Comment by jianchang512** [comment]
模型使用 small 试试，先不要使用 large-v3

**Comment by zhangzzgz** [comment]
> 模型使用 small 试试，先不要使用 large-v3

small模型可以正常使用

**Comment by jianchang512** [comment]
应该是这个模型有变化。这是 11.6 openai号刚出的新模型，还未测试

**Comment by Copy2Translator** [comment]
> 应该是这个模型有变化。这是 11.6 openai号刚出的新模型，还未测试

我也用的 large-v3，运行了一个多小时之后报错

Traceback (most recent call last):
  File "sp.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "videotrans\configure\config.py", line 9, in <module>
  File "logging\__init__.py", line 2040, in basicConfig
  File "logging\__init__.py", line 1169, in __init__
  File "logging\__init__.py", line 1201, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\system32\\video.log'

**Comment by jianchang512** [comment]
这个模型非常大，确保内存充足。另外不要在c盘下，更不要在需要系统权限的目录下
