### ISSUE TITLE
感謝, 只想提一個用戶的建議. 

### ISSUE THREAD

**Issue by HelloKittyWrongNumber** [jianchang512/pyvideotrans#381]
软件功能齐全，但是用户体验不佳.
原因:
很抱憾的，现在AI直接翻译效果不完美(例如：原来视频发音不准, AI侦测到错误的字, 再翻译成错误的外语). 这些时候百分百需要人手优化更改字幕， 否则翻译出来的影片根本就没法使用。
但軟件在批量 处理视频(应该是1.6后)，暂停按钮 已经不见了. 无法在批量处理的时候更改自动生成字幕中的错字。

个人觉得大多数用户需要 批量批量 更改/ 优化 字幕文件, 再由AI配音, 然后制成新的影片. 

个人建议 添加功能：
1- 首先把原视频批量输出字幕档案。
2- 用户 手动 把字幕文件内容优化后
3- 批量把视频和更改/优化后 的字幕文件 由AI批量处理。

如果软件能做到这个功能，就完美了。

可能是我不专业不懂得操作， 大师. 请求指教!
现在的AI翻译经常出现错字 然后再翻译成错误的 英语， 令影片质量非常差 甚至不能使用。 辜負了开发者软件的原意。

非常感谢你的贡献.

**Comment by lin16303** [comment]
这个软件可以自定义的选型非常丰富，建议使用者多看文档，同时也可以发挥自己的想象力来使用它。比如你的说这种需求，只要识别语音简称asr，在标准功能里，原始语言和目标语言都选取英文，配音edgetts选取配音no，系统就只会识别生成en.srt字幕文件，自己翻译后把zh-cn.srt文件放入同一个工作目录，再把目标语言改成中文，并选择配音声优就可以了。

**Comment by jianchang512** [comment]
1. 单个视频处理会自动暂停
2. 批量时可以提前修改 videotrans/set.ini 将底部的参数 `cros_run=true`改为 cros_run=false，再执行，也会暂停
