### ISSUE TITLE
添加硬件编解码

### ISSUE THREAD

**Issue by chenziliang0725** [jianchang512/pyvideotrans#383]
视频解码能使用硬件编解码吗，感觉目前应该是软件解码和编码，速度比较慢，吃cpu

**Comment by jianchang512** [comment]
目前只有启用cuda时使用硬件编码
后续计划增加 intel 苹果 硬件编码

解码都用软解，时间主要耗费在编码上

intel amd apple nvida linux windows macos不同硬件平台和操作系统解码编码都存在兼容问题，因此简单可靠起见，只考虑硬件 intel  apple  nvida硬件编码

**Comment by chenziliang0725** [comment]
我amd不配了🙍‍♂️
