### ISSUE TITLE
1.68-批量音视频转字幕功能除生成srt字幕文件外原先视频文件重复生成

### ISSUE THREAD

**Issue by lxm15930** [jianchang512/pyvideotrans#384]
打开1.68批量音视频转字幕功能，执行成功后输出的文件除了srt字幕文件外，还同时将原先视频文件重复也生成了一个新的视频文件。
![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/96c82965-cf22-4d51-9a12-c555eb73f401)
![image](https://github.com/jianchang512/pyvideotrans/assets/68838392/d0bc0591-a130-41da-9a33-efaeecfd20ed)

**Comment by jianchang512** [comment]
视频名字存在空格  非英文文字  特殊符号时，为避免出错，会预先标准化名字，不动原始视频，所以复制一个
