### ISSUE TITLE
GPT-SoVITS 自带的api.py文件出现错误？

### ISSUE THREAD

**Issue by DXTREASURE** [jianchang512/pyvideotrans#386]
我想使用这个双语文件，但是出现了错误，有人能知道怎么解决吗？？？
![{6FB59A17-553D-4cc4-9762-600187C57CB2}](https://github.com/jianchang512/pyvideotrans/assets/40051552/2a0c8230-27fe-45e6-bf61-6d6f62627dc5)
![{B922CFFD-768F-4cbf-8EC5-ED3F28E36B06}](https://github.com/jianchang512/pyvideotrans/assets/40051552/dc4425fd-d0c5-49d0-ae21-96c64ae2d767)
![{E643EBB4-DB9E-4411-8C39-DE1CCE1E4619}](https://github.com/jianchang512/pyvideotrans/assets/40051552/7a2b1229-de52-4c0a-89ef-c735d8821ad0)
![{E643EBB4-DB9E-4411-8C39-DE1CCE1E4619}](https://github.com/jianchang512/pyvideotrans/assets/40051552/d76454a7-69ef-477b-bba9-2c82c3d17aad)

**Comment by jianchang512** [comment]
试试这个
自带的新版本有改变，目前还是针对旧版整合的

https://github.com/jianchang512/gptsovits-api
