### ISSUE TITLE
ISSUE：下载的模型不完整

### ISSUE THREAD

**Issue by DoubleStarK** [jianchang512/pyvideotrans#389]
从这里下载的模型不完整https://pyvideotrans.com/model，可以先从hugging-face下载
如图所示：以下两个模型（均为github地址）是从上述链接下载的，但是实际程序读取会报错：
```bash
Error in speech recognition:File model.bin is incomplete: failed to read a value of size 4 at position 0('File model.bin is incomplete: failed to read a value of size 4 at position 0',)("File model.bin is incomplete: failed to read a value of size 4 at position 0('File model.bin is incomplete: failed to read a value of size 4 at position 0',)",)
```
<img width="212" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/20124029/dd926f4c-f3f3-4e3c-9818-8f4adef04045">

经解压查看，发现snapshots/xxx下面的文件均为空文件：
<img width="841" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/20124029/ee8b8c8f-f0d4-40c2-9b57-25a6fa00dffe">
猜测是用git上传但是未安装git-lfs

**Comment by jianchang512** [comment]
windows上使用的符号链接，实际连接到blob下的文件，但存在点问题，已更新
