### ISSUE TITLE
在使用1.70完整包的时候遇到了缺少cuBLAS..dll，我按照谁说明下载了并解压在了相应目录但还是出现相同的问题。

### ISSUE THREAD

**Issue by chenziliang0725** [jianchang512/pyvideotrans#393]
最开始，我装好了驱动、cuda、cudnn，1.68完整包是可以正常使用的。

当我下载了1.70完整包的时候，使用fast模型的时候，出现了缺少cuBLAS..dll，我按照谁说明下载了并解压在了相应目录仍然无法解决，缺少cuBLAS..dll相同的问题。

然后换成openai模式的时候，则出现了本在1.68版本能够正常使用的超出显存范围，我的显存是8g，但使用最小的模型也同样出现cuda out of mem。。

**Comment by jianchang512** [comment]
更新cuda到11.8

videotrans/set.ini  中 cuda_com_type=float16 改成 int8 试试

**Comment by chenziliang0725** [comment]
> 更新cuda到11.8
> 
> videotrans/set.ini 中 cuda_com_type=float16 改成 int8 试试

我的cuda是11.8

**Comment by chenziliang0725** [comment]
也改了 int8，同样报错超出显存，，同样的情况下，1.68版本没有问题

**Comment by jianchang512** [comment]
下载 1.73升级包解压覆盖试试

**Comment by chenziliang0725** [comment]
也试过了，同样的错误。

**Comment by chenziliang0725** [comment]
我现在就用1.68吧🥲

**Comment by jianchang512** [comment]
刚更新了，重新下载 1.73 包，102M的

**Comment by chenziliang0725** [comment]
ok，I will try
