### ISSUE TITLE
软件打不开哦。

### ISSUE THREAD

**Issue by love24051** [jianchang512/pyvideotrans#396]
只能打开v1.68版本的。1.68以上版本根本是打不开了。。。不是慢。包括升级包覆盖，完整包下来都停留在启动画面。。。

**Comment by jianchang512** [comment]
下载1.75完整包，有个bat文件，看文件名，管理员先运行bat

**Comment by love24051** [comment]
试过了，还是一直停留在启动画面。进不去软件。。

**Comment by love24051** [comment]
1.76版本完整包可以打开了。。。。
