### ISSUE TITLE
【求助】转换完画质问题

### ISSUE THREAD

**Issue by DoubleStarK** [jianchang512/pyvideotrans#398]
<img width="1228" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/20124029/8d20156d-8c3c-4629-ad9e-084d938a09e9">
如图，没有选对视频有影响的配置项（无配音，无慢速等），set.ini按照issue#340设置好了，视频也是h264，转换完了视频还是减小了一半，画质特别模糊
<img width="598" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/20124029/ce7f7957-3050-4e79-ac61-e965ec09a2f5">
<img width="232" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/20124029/45399292-fc59-481d-b465-0d9e2b29f089">
p.s.感觉改了配置项没有生效

**Comment by jianchang512** [comment]
为什么字幕嵌入那里无法显示选项？
只确保界面都正常显示再处理，硬字幕嵌入时质量肯定会改变的，因为需要重新编码

具体看文档
https://pyvideotrans.com/videoqua.html

**Comment by DoubleStarK** [comment]
> 为什么字幕嵌入那里无法显示选项？ 只确保界面都正常显示再处理，硬字幕嵌入时质量肯定会改变的，因为需要重新编码
> 
> 具体看文档 https://pyvideotrans.com/videoqua.html

嵌入字幕选硬字幕和软字幕都没有效果，这个下拉框在我这里就是0宽度😂

**Comment by jianchang512** [comment]
未复现

1. 升级到 1.76
2. 清空logs目录下所有文件，然后重新测试
3. 完毕后贴上logs下新生成的log文件

**Comment by jianchang512** [comment]
`ffprobe  -v quiet -print_format json -show_format -show_streams 
 /Users/x/work/fun_projects/you2bi/downloads/0d35a3a3a6dcab5c9c99bbed1cd69540/vgYi3Wr7v_g.mp4`

这些，结果复制下

**Comment by jianchang512** [comment]
重新 拉取 git pull 再试一次

**Comment by DoubleStarK** [comment]
ok now, how did you do that man? Just like magic
