### ISSUE TITLE
gemini升级了，效果不错，但程序似乎不支持新版本了

### ISSUE THREAD

**Issue by dindom999** [jianchang512/pyvideotrans#400]
梯子没有问题的，看了一下源码，应该是很久没有更新了，新版本的gemini变化有点大
错误提示：
翻译字幕C:/Users/dom/Downloads/_video_out/aaa.srt出错:Gemini:2次重试后依然出错:cannot access local variable 'response' where it is not associated with a value

**Comment by jianchang512** [comment]
实测无问题

1. secret可能失效了，更换个
2. 如果是源码部署，自行更新googleAI依赖

**Comment by dindom999** [comment]
1，secret是刚刚申请的，我用googleai的api自己写了执行没问题，能正常翻译，代码还是有些区别的，比如新版的model name要换一下。
2，用的是windows打包最新版

**Comment by jianchang512** [comment]
代码发下
