### ISSUE TITLE
OR: Could not find a version that satisfies the requirement intel-openmp==2021.4.0 (from versions: none) ERROR: No matching distribution found for intel-openmp==2021.4.0

### ISSUE THREAD

**Issue by techbirds** [jianchang512/pyvideotrans#401]
按照 https://github.com/jianchang512/pyvideotrans?tab=readme-ov-file#macos%E6%BA%90%E7%A0%81%E9%83%A8%E7%BD%B2 执行的，发现报这个错，查了下这个包似乎兼容的是英特尔的

<img width="1374" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/3411696/739e2356-f056-4740-9b7a-d14ae75501ae">

我的环境是：

<img width="485" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/3411696/b959a24e-c57f-4e8c-a0f1-48e898ee50f1">

**Comment by jianchang512** [comment]
打开 requirements.txt
找到 intel-openmp==2021.4.0改成 intel-openmp

**Comment by techbirds** [comment]
仍旧是相同的错误

**Comment by jianchang512** [comment]
直接删掉那行，重新安装

**Comment by techbirds** [comment]
删掉重装报错：

ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tbb==2021.11.0 (from versions: none)
ERROR: No matching distribution found for tbb==2021.11.0

**Comment by jianchang512** [comment]
ERROR: No matching distribution found for tbb==2021.11.0

这类错误都将==和后边的版本号去掉

**Comment by techbirds** [comment]
删掉tbb后重装就可以了，谢谢！
