### ISSUE TITLE
合并阶段出错

### ISSUE THREAD

**Issue by techbirds** [jianchang512/pyvideotrans#402]
合并阶段出错

<img width="474" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/3411696/4fa0c6f4-4ac0-482a-9b8f-826b8bc4f253">

<img width="1572" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/3411696/3e33b1d4-a476-4dd2-80e3-9e1657c72960">

版本

{
"version": "1.77",
"version_num": 11077
}

具体版本源码：https://github.com/jianchang512/pyvideotrans/tree/1a23daf86a681b4abada36ae229e00d1c2c7608a

**Comment by lin16303** [comment]
是不是非标文件名引起的，建议作者加入预检强制更名功能，只用源文件中的26个英文字母和数组来命名新的文件名和目录

**Comment by techbirds** [comment]
@jianchang512 帮忙看看

**Comment by jianchang512** [comment]
信息太少看不出错误
原始视频改名为 1.mp4，不要放在 软件的tmp目录下再试试
