### ISSUE TITLE
cloudflareWorkers 翻译API搭建教程代码失效

### ISSUE THREAD

**Issue by CirnoSalt** [jianchang512/pyvideotrans#405]
第一行：`import { Ai } from '@cf/meta/m2m100-1.2b/ai.js';`
编辑器报错：
Uncaught Error: No such module "@cf/meta/m2m100-1.2b/ai.js". imported from "index.js" (Code: 10021)
![屏幕截图 2024-05-21 003857](https://github.com/jianchang512/pyvideotrans/assets/23478997/385d0eed-c85d-4904-b22d-34a336182b3a)

**Comment by death4444** [comment]
散了吧兄弟，CF已经改了规则，这个方法失效了。
白嫖党太多了。

**Comment by jianchang512** [comment]
之前是免费beta版，现在要收费了，代码结构也有所调整
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/be4692fd-809d-40e6-8c07-72405a1081da)

重新查看这个教程  https://github.com/jianchang512/translate-api


更好的方法是在cf上代理 google翻译api，教程见  https://juejin.cn/post/7384632027230519330
