### ISSUE TITLE
不能启动

### ISSUE THREAD

**Issue by 2362** [jianchang512/pyvideotrans#406]
![image](https://github.com/jianchang512/pyvideotrans/assets/22723486/70a8b268-b4e3-4695-9a7f-ccbf65221625)
启动时加载中和运行2个窗口同时出现，点击功能按钮会提示尚未完成初始化
![image](https://github.com/jianchang512/pyvideotrans/assets/22723486/9204d12e-5554-4a1f-9677-0b7d1b8ffa7d)

**Comment by 2362** [comment]
1.7.6完整包或1.7.8升级包覆盖都会出现一样的问题

**Comment by jianchang512** [comment]
目录下有bat文件，管理员权限右键执行试试
