### ISSUE TITLE
请问为什么下载的油管原始视频是无声的？

### ISSUE THREAD

**Issue by lixplor** [jianchang512/pyvideotrans#407]
Q1.使用下载油管视频功能下载的视频使用播放器播放时，是没有声音的。是特意去掉原始声音来实现后期TTS配音吗？

Q2.有些油管视频里面包含音乐和音效，我看软件还有人声背景声分离功能，我理解的是程序支持保留视频背景音乐和音效，只把其中对白语音翻译嵌入。我对此的理解是否有误？能否实现这样的操作？

**Comment by jianchang512** [comment]
1. 下载不完全，youtube下载是音频和视频分别单独下载，然后再本地合并的，等待音频和完全下载结束后再播放视频，否则播放会无声，并且因为文件占用，可能导致后续合并音频失败
2. 是的。可以，但太长的视频可能分离声音失败，可以单独使用其他工具分离出背景音频，然后以 添加背景音 的形式添加
