### ISSUE TITLE
无论源码版还是打包版都用不了CUDA加速（并且打包版会在运行过程中自动退出）

### ISSUE THREAD

**Issue by rockingapple** [jianchang512/pyvideotrans#408]
我用的win11，安装了CUDA，配置好了环境，确保所有packages都安装好了，并且，torchaudio和pytorch都是cuda版本。

运行源码时勾选了“CUDA加速”，但GPU利用率最高只有8%，基本上GPU利用率在4%至5%左右，貌似没有利用GPU

运行打包版时，同样勾选了“CUDA加速”，但在运行过程中会自动退出程序无法使用

**Comment by rockingapple** [comment]
经测试，在win11系统下，无论源码版本还是打包版，只要开启了CUDA加速都会在运行过程中闪退

**Comment by jianchang512** [comment]
https://pyvideotrans.com/11.html

**Comment by rockingapple** [comment]
我在set.ini中把beam_size和best_of都改为了3，不闪退了。
终于知道为什么了，GPU的算力利用率与解码能力无关，我用的2080，之前默认设置下翻译视频时，输入nvidia-smi查看GPU算力的利用率最高只有45%左右，而且显存利用只有1G多点，GPU资源并未过载但却闪退，实际上这时应该是解码能力不够了，要不没法解释显存只利用1G，且GPU算力最高只用到45%却闪退的问题。
