### ISSUE TITLE
ERROR: Cannot install ctranslate2==3.24.0 and faster-whisper==1.0.2 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by rockingapple** [jianchang512/pyvideotrans#410]
![微信截图_20240523090709](https://github.com/jianchang512/pyvideotrans/assets/77232972/b0aa90ac-c578-4668-8b59-f69c192fe2fe)
即报错如下：
ERROR: Cannot install ctranslate2==3.24.0 and faster-whisper==1.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested ctranslate2==3.24.0
    faster-whisper 1.0.2 depends on ctranslate2<5 and >=4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

说明下，我按照要求用pip install -r requirements.txt --no-deps安装依赖包，但总会在这步出错。切换pip镜像到阿里镜像也试过了，依然报错。
（注：用WSL中ubuntu和win11的系统环境测试，均无法正常安装依赖包，怀疑源码多次更新后开发环境的依赖包随着pip仓库的更新变得不兼容了）
建议重建一个新环境安装依赖包，确定程序正确执行无误后，再把依赖包导出到requirements.txt

**Comment by jianchang512** [comment]
如果cuda是1.2+。打开requirements.txt删除 ctranslate2后的==3.24.0

如果低于12，删除整行，然后安装完毕后再单独安装   pip install ctranslate2==3.24.0

**Comment by jianchang512** [comment]
ctranslate2最新版仅支持cuda12+，为兼容cuda11强制指定了3.24版本。
