### ISSUE TITLE
在使用GPT翻译时，加入自定义prompt的功能。并且，和oneapi进行对接，希望接入更多AI翻译工具。

### ISSUE THREAD

**Issue by rockingapple** [jianchang512/pyvideotrans#411]
GPT翻译的功能没有充分利用起来，默认使用GPT这样的AI工具翻译视频内容时没有考虑视频的背景，也没有考虑视频讲话人的角色。

例如，观看机器学习或深度强化学习教学视频时，GPT这样的AI工具默认会把policy翻译为“政策”，但如果在翻译前指定翻译者的角色为：“机器学习教授或深度强化学习专家”，GPT会正确地把policy翻译为“策略”。
此外，利用GPT工具翻译视频前，在prompt中提供更详细的信息会极大程度上提升翻译质量，秒杀DeepL等传统翻译工具。

因此，希望在利用GPT翻译时，能够提供自定义prompt的功能，把AI工具的翻译能力充分利用起来。

最后，希望和oneapi对接，oneapi可以接入很多AI模型，例如coze，kimi，google gemini， 还有deepseek等等，GPT并不是唯一的翻译工具。这些AI工具只要结合自定义prompt，可以通杀任何传统的翻译工具。

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/9d604c91-2024-4e5b-88d9-6e85e5ceb671)

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/cde81110-16be-45b3-ae1c-bdd917df8426)
