### ISSUE TITLE
第二次及以后进度条卡97%

### ISSUE THREAD

**Issue by leexinxu** [jianchang512/pyvideotrans#412]
<img width="1533" alt="截屏2024-05-29 00 12 52" src="https://github.com/jianchang512/pyvideotrans/assets/46738432/dc405b08-d29e-4a3f-a852-ce53195cbb99">
<img width="571" alt="截屏2024-05-29 00 05 12" src="https://github.com/jianchang512/pyvideotrans/assets/46738432/456eb5be-8cfc-4797-9c00-58635254f401">

self.tasklist = {} 置空早了，挪到最后就好了
<img width="1492" alt="截屏2024-05-29 00 06 41" src="https://github.com/jianchang512/pyvideotrans/assets/46738432/0fda4a93-4f1a-40b4-b4fa-ced51c3b107b">

**Comment by lin16303** [comment]
同win， @leeyi2019 mac下全流程都能支持gpu加速吗

**Comment by leeyi2019** [comment]
> 同win， @leeyi2019 mac下全流程都能支持gpu加速吗

初步看是不支持的，周末准备研究一下
