### ISSUE TITLE
调用elevenlabs的api，处理音频无法成功

### ISSUE THREAD

**Issue by AiDreamerOoO** [jianchang512/pyvideotrans#414]
调用的是elevenlabs的api的免费额度，处理进度上显示把音频生成完成了，但是下一步就卡到这里了，有大佬知道怎么回事么
![d6136e93e6496679af9e379cbbc1d7d](https://github.com/jianchang512/pyvideotrans/assets/154967620/2a59402f-a0f3-4ef1-ac80-342600410b9f)

**Comment by jianchang512** [comment]
出错时软件目录下 logs文件夹内最新的log文件最后几行复制下

**Comment by AiDreamerOoO** [comment]
> 出错时软件目录下 logs文件夹内的最新的日志文件最后几行复制下来
找到原因了，显示因为用了梯子，把免费的api接口禁用了
INFO:VideoTrans:elevenlabs:Unusual activity detected. Free Tier usage disabled. If you are using a proxy/VPN you might need to purchase a Paid Plan to not trigger our abuse detectors. Free Tier only works if users do not abuse it, for example by creating multiple free accounts. If we notice that many people try to abuse it, we will need to reconsider Free Tier altogether. 
Please play fair and purchase any Paid Subscription to continue.
ERROR:VideoTrans:elevenlabsTTS：request error:Unusual activity detected. Free Tier usage disabled. If you are using a proxy/VPN you might need to purchase a Paid Plan to not trigger our abuse detectors. Free Tier only works if users do not abuse it, for example by creating multiple free accounts. If we notice that many people try to abuse it, we will need to reconsider Free Tier altogether. 
Please play fair and purchase any Paid Subscription to continue.
ERROR:VideoTrans:'NoneType' object is not subscriptable
