### ISSUE TITLE
大佬，升级videotrans欲打包版本需要重新下载吗

### ISSUE THREAD

**Issue by lanpao123** [jianchang512/pyvideotrans#417]
大佬，升级videotrans欲打包版本需要把原来的删除掉，再重新下载吗

**Comment by jianchang512** [comment]
如果是1.5后的版本不需要，下载升级包解压覆盖就行。
覆盖后如果迟迟无法打开，双击 bat脚本

**Comment by jianchang512** [comment]
https://github.com/jianchang512/pyvideotrans/releases

**Comment by lanpao123** [comment]
> https://github.com/jianchang512/pyvideotrans/releases

 好的，谢谢大佬🙂
