### ISSUE TITLE
使用distil-whisper-large-v3 模型 后使用标准功能后，翻译到一半后就后面这个应用程序就自动关闭了这个如何解决，已经更新到最新exe版本

### ISSUE THREAD

**Issue by Lucas-cen-ai** [jianchang512/pyvideotrans#419]

**Comment by jianchang512** [comment]
查看闪退问题
https://pyvideotrans.com/11.html

**Comment by Lucas-cen-ai** [comment]
大佬，我看了一下log出现了以下问题
DEBUG:faster_whisper:Processing segment at 00:27.380
DEBUG:faster_whisper:Log probability threshold is not met with temperature 0.0 (-1.009665 < -1.000000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.2 (2.560000 > 2.400000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 0.2 (-1.225621 < -1.000000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 0.4 (-1.026379 < -1.000000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 0.6 (-1.083090 < -1.000000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 0.8 (-1.120015 < -1.000000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 1.0 (-1.687015 < -1.000000)
INFO:VideoTrans:19 这个是表示什么意思呢麻烦您帮解答一下谢谢

**Comment by jianchang512** [comment]
打开 videotrans/set.ini 将 temperature=1 改为 temperature=0
再试试

**Comment by Lucas-cen-ai** [comment]
大佬，我更改了set.ini中temperature=1 改为 temperature=0  就启动不了了

**Comment by Lucas-cen-ai** [comment]
log里面说的是这样的
ERROR:VideoTrans:set.ini 中有语法错误:not enough values to unpack (expected 2, got 1)
ERROR:VideoTrans:set.ini 中有语法错误:not enough values to unpack (expected 2, got 1)
我写的内容如下
temperature=0，就是简单的换了应该数字，是不是我的操作有误，或者是需要什么特殊手段重启一下呢？

**Comment by jianchang512** [comment]
截图你改的。

**Comment by jianchang512** [comment]
还改为1吧
这个不是报错。

只是日志输出，温度不合适

**Comment by jianchang512** [comment]
set.ini中如果  condition_on_previous_text 不是 false，就改为 false，是就不需要动

**Comment by Lucas-cen-ai** [comment]
> set.ini中如果 condition_on_previous_text 不是 false，就改为 false，是就不需要动

是false的

**Comment by jianchang512** [comment]
DEBUG 不是报错，可以忽略

如果GPU独显小于12G，不要使用v3模型

**Comment by Lucas-cen-ai** [comment]
那集显是16g的推荐使用那个语言模型会更合适呢大佬

**Comment by jianchang512** [comment]
集显等于没显卡，纯CPU运行

small  medium

**Comment by Lucas-cen-ai** [comment]
n卡有应该4g的运行内存，这种推荐那种语言模型最合适呀大佬

**Comment by jianchang512** [comment]
最大也就是medium，如果视频也比较大，可能会闪退，如果闪退可以尝试 预先分割 模式
