### ISSUE TITLE
[feature] SRT subtile merging

### ISSUE THREAD

**Issue by cenfun** [jianchang512/pyvideotrans#427]
很好的工具，是否可以新增一个选项或者工具，用来合并多个字幕，也就是方便支持双语字幕

例如：
原始转换了英语字幕，然后翻译了中文字幕，最终想生成一个中英双语字幕，也就是将前面2个字幕合并
可以新增一个选项，翻译完成自动合并保存，或者单独一个工具可以提交2个字幕进行合并保持

是否已经有这样的功能，或者是否考虑支持？
谢谢

**Comment by ilyalev** [comment]
you can specify the subtitle file name as well as the video name, with the addition of a translation suffix?

**Comment by jianchang512** [comment]
update 1.95
