### ISSUE TITLE
模型列表的字母看不全

### ISSUE THREAD

**Issue by w254547764** [jianchang512/pyvideotrans#429]
只能看到tiny,small,base，其它的字母看不全。
如图
![无标题](https://github.com/jianchang512/pyvideotrans/assets/143796188/3328ead9-e296-49a8-8e41-2f9fab8bbbf9)

**Comment by jianchang512** [comment]
最大化软件
videotrans/set.ini 打开搜索 model_list 即是模型名列表

**Comment by w254547764** [comment]
好的
