### ISSUE TITLE
看到作者有另外一个项目clone-voice，有办法融合进videotrans项目吗

### ISSUE THREAD

**Issue by ztwe** [jianchang512/pyvideotrans#433]
现有项目里的clone-voice是付费的api，有办法把作者另一个项目clone-voice融合进来吗

**Comment by ilyalev** [comment]
you can add clone voice this author project. jianchang512/clone-voice. I did that. Start server clone voice and edit setting in pytransvideo.

**Comment by jianchang512** [comment]
https://pyvideotrans.com/guide.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%8E%9F%E8%A7%86%E9%A2%91%E4%B8%AD%E9%9F%B3%E8%89%B2%E9%85%8D%E9%9F%B3
