### ISSUE TITLE
大佬你好  代理被拒绝这个是什么意思

### ISSUE THREAD

**Issue by yyshijie** [jianchang512/pyvideotrans#437]
![微信图片_20240610163611](https://github.com/jianchang512/pyvideotrans/assets/172253006/e130eff7-25d6-4405-bc35-af49c339ea5b)

**Comment by jianchang512** [comment]
需要安装并启动 ChatTTS-ui 后才可使用

**Comment by yyshijie** [comment]
明白了 谢谢
