### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by midxplore** [jianchang512/pyvideotrans#44]
希望可以结合一下coqui-ai的XTTS： https://github.com/coqui-ai/tts ，这样可以结合视频的原声进行学习保留原视频的语调，另外腾讯开源的口型模型：https://github.com/OpenTalker/video-retalking 用于对齐是个不错的选择

**Comment by qudongdong123** [comment]
那这个工具就强大了

**Comment by nothing-byte** [comment]
现在的框架很好，再加上现在GPT的TTS，这个仓库潜力老大了

**Comment by jianchang512** [comment]
xtts一直在规划中，后续会使用，但不是本地部署版，而是使用 tts提供的官方api接口
本地部署太复杂了，包也太大了，而且coqui tts更适合部署在linux上

口型模型暂时先不考虑，这种只适合一直嘴巴露着的，而且面向国内法律风险太高

**Comment by nothing-byte** [comment]
嗯，不过对多角色言语的训练是否可以考虑自己另外部署一个TTS的服务（这样做是方便使用自己的模型）因为如果还是依赖官方就没办法自己去优化合成的效果

**Comment by jianchang512** [comment]
本地可以拿coqui的开源版部署训练 ，只是我这项目注重简单 方便打包，所以不会集成太重的东西，重点在支持三方api
