### ISSUE TITLE
cuBLASxx.dll

### ISSUE THREAD

**Issue by noveldig** [jianchang512/pyvideotrans#443]
下载链接失效了 。
提示404

**Comment by jianchang512** [comment]
在哪个地方的链接失效了？
https://pyvideotrans.com/gpu.html 
文档中正常

**Comment by noveldig** [comment]
页面地址
https://pyvideotrans.com/model.html
页面底部

cuBLASxx.dll下载
[**下载cuBLAS dll 文件**](https://github.com/jianchang512/stt/releases/download/0.0/cuBLAS_win.7z) 如果遇到 "cublasxxx.dll不存在"，请下载该文件，然后将里面的dll文件复制到 C:/Windows/System32 目录下

链接地址
https://github.com/jianchang512/stt/releases/download/0.0/cuBLAS_win.7z
