### ISSUE TITLE
中译英字母错乱的问题。。

### ISSUE THREAD

**Issue by noveldig** [jianchang512/pyvideotrans#444]
通过多个文件测试，发现都是同样的问题。版本1.90

16
00:00:42,510 --> 00:00:44,650
以下这些段落的翻译全部出现在这个位置。

17
00:00:44,650 --> 00:00:45,630

18
00:00:45,630 --> 00:00:48,110

19
00:00:48,110 --> 00:00:49,350

20
00:00:49,350 --> 00:00:52,350

21
00:00:52,350 --> 00:00:54,810

22
00:00:55,270 --> 00:00:57,250

23
00:00:57,770 --> 00:00:59,330

24
00:00:59,330 --> 00:01:00,350

25
00:01:00,350 --> 00:01:02,470

26
00:01:02,470 --> 00:01:04,620

27
00:01:04,620 --> 00:01:06,640

28
00:01:06,640 --> 00:01:08,140

29
00:01:08,140 --> 00:01:09,460

30
00:01:10,070 --> 00:01:11,370

**Comment by jianchang512** [comment]
使用的哪个翻译渠道

**Comment by noveldig** [comment]
![2](https://github.com/jianchang512/pyvideotrans/assets/120369782/0bc15d52-e8e2-4528-a564-b0bea6d90e9a)


配置如图

**Comment by jianchang512** [comment]
videotrans/set.ini里搜索 trans_thread=15改为=1
