### ISSUE TITLE
后续是否可以考虑支持mkv格式的视频转写

### ISSUE THREAD

**Issue by gtzxxel** [jianchang512/pyvideotrans#446]
主要用途是给一无资源二无字幕的国外老剧加字幕并翻译
种子拖下来大多都是mkv格式的视频，很少有mp4或者mov格式
所以音视频转文字那栏用不了
已尝试的途径：
① 单独抽取音频轨 这个分视频 有些视频音频轨拖下来可以用 有些拖下来时长啥啥都变了 没法转文字
② 把视频音频轨都抽取后再封装为mp4 试过了能播放 但是还是转写失败 不知道为啥

**Comment by heheda123123** [comment]
现在支持mkv的格式，但是批量转换里面不支持，是否可以加上支持，ffmpeg是可以处理的

**Comment by jianchang512** [comment]
支持原视频是mkv格式的。输出是mp4

你是说要输出 mkv ？

**Comment by heheda123123** [comment]
> 支持原视频是mkv格式的。输出是mp4
> 
> 你是说要输出 mkv ？

可能我表达有误，我的需求和它这个不一样。我主要是用“视频转为字幕”功能，这里支持mkv格式。但是在“音视频转字幕”里面没法指定mkv

**Comment by heheda123123** [comment]
> 支持原视频是mkv格式的。输出是mp4
> 
> 你是说要输出 mkv ？

我重新提了个issue https://github.com/jianchang512/pyvideotrans/issues/463
