### ISSUE TITLE
Polish language support, pls

### ISSUE THREAD

**Issue by FreddyAlf** [jianchang512/pyvideotrans#449]
Hi, Your app is great and works fantastic!!! 

but I can't find Polish. 

I know from another issue that this requires a new compilation - is it possible that the Polish language will be added in the next version? Either way - I keep my fingers crossed for your app!

**Comment by jianchang512** [comment]
update 1.95

**Comment by FreddyAlf** [comment]
Thx, now for me your application will be even more useful, thank you for your time and response to my request and the implementation of Polish language support :)

**Comment by FreddyAlf** [comment]
Thx, now you app will be for me very usfull🤩😘

śr., 19 cze 2024 o 11:29 okmyworld ***@***.***> napisał(a):
