### ISSUE TITLE
Mac安装报错：samplerate==0.2.1无法安装

### ISSUE THREAD

**Issue by summerlovestudy** [jianchang512/pyvideotrans#452]
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (samplerate)

其他包都已安装好，只有samplerate==0.2.1无法安装
安装命令：pip3 install -r requirements.txt --no-deps

**Comment by jianchang512** [comment]
单独执行  `pip3 install samplerate`

**Comment by summerlovestudy** [comment]
谢谢，已经调试成功
最后安装的是：samplerate==0.1.0

> 单独执行 `pip3 install samplerate`
