### ISSUE TITLE
字幕每次出现三行，如何控制呢？

### ISSUE THREAD

**Issue by wgb0451** [jianchang512/pyvideotrans#459]
翻页后字幕总是三行，如何实现一句一行呢？

**Comment by jianchang512** [comment]
版本号？
操作系统 ？

**Comment by baiwei0703** [comment]
我用的是windows预打包的1.99版，生成效果如下图
![image](https://github.com/jianchang512/pyvideotrans/assets/34114426/af48eaa4-f7da-4e74-92d8-483195d760c8)

**Comment by jianchang512** [comment]
faster模式还是openai模式，或者其他？
操作时软件主界面设置截大图

**Comment by baiwei0703** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/34114426/5c0ff427-68a0-44d2-824d-c0e753043c7d)
![image](https://github.com/jianchang512/pyvideotrans/assets/34114426/425eb81b-74af-484f-a5bb-cda663ed76a0)
貌似是拆句子的问题。只有这一段会这样，后面拆得比较短，就没事了

**Comment by baiwei0703** [comment]
就像这样：

**Comment by jianchang512** [comment]
使用更大的模型  medium
