### ISSUE TITLE
chatgpt翻译接口的问题

### ISSUE THREAD

**Issue by Meteor2017** [jianchang512/pyvideotrans#46]
卡死在wait chatgpt response

**Comment by liwei19840921** [comment]
俺也一样

**Comment by jianchang512** [comment]
看下 video.log 里，错误日志
编译版还是源码，openai更新了sdk到1.2，变化很大，如果更新了openai，需要修改源码

**Comment by liwei19840921** [comment]
编译版，video.log最后一行：
ERROR:VideoTrans:Get_large_audio_transcription error:'code'

**Comment by jianchang512** [comment]
我本地测试可以
明晨更新下新版本

**Comment by liwei19840921** [comment]
还是不行，是不是只能官方接口，我用的不是官方的
ERROR:VideoTrans:chatGPT response:'ChatCompletion' object has no attribute 'code'
ERROR:VideoTrans:[error]:测试视频 ChatGPT 翻译出错:[error]:chatGPT response error:'ChatCompletion' object has no attribute 'code'
ERROR:VideoTrans:sp.py :You stop it

**Comment by jianchang512** [comment]
第三方接口设计不同，分别试试加上和去掉末尾的v1，看看有没有可以

**Comment by liwei19840921** [comment]
去掉V1后：
ERROR:VideoTrans:chatGPT response:'str' object has no attribute 'code'
ERROR:VideoTrans:[error]:测试视频 ChatGPT 翻译出错:[error]:chatGPT response error:'str' object has no attribute 'code'
ERROR:VideoTrans:sp.py :You stop it

**Comment by liwei19840921** [comment]
去掉连不上，后台看不到消费；有V1能看到消费

**Comment by admin888-byte** [comment]
chatgpt 接口地址大佬用的哪个

**Comment by admin888-byte** [comment]
https://platform.openai.com/api-keys  另外大佬chatgpt的key是在这生成的，调用多少次就开始花钱了

**Comment by admin888-byte** [comment]
虚心请教大佬们，感谢

**Comment by jianchang512** [comment]
新号有免费额度，用完就需要绑定信用卡


官方接口需要末尾带  /v1 ,但第三方如何实现就不确定了，有的要求带，有的不能带，只能试试了

**Comment by liwei19840921** [comment]
第三方的试了三家了，都是这个提示：chatGPT response:'ChatCompletion' object has no attribute 'code'

**Comment by liwei19840921** [comment]
![微信截图_20231115022336](https://github.com/jianchang512/pyvideotrans/assets/109659199/270574ea-3522-4e21-a148-d1cc86f5ce27)

**Comment by liwei19840921** [comment]
消费都可以看到，连接是正常的
![微信截图_20231115022645](https://github.com/jianchang512/pyvideotrans/assets/109659199/fd519b53-5586-4685-917e-11ff9ab7fd0b)

**Comment by jianchang512** [comment]
这种一般是接口地址问题。分别试试带末尾 /v1 和不带的
