### ISSUE TITLE
点击“开始处理”后，程序闪退

### ISSUE THREAD

**Issue by jcbay** [jianchang512/pyvideotrans#460]
PYTHON3.12版本，启动软件后，下载使用faster模式的base模型，操作界面如图，选择的视频文件为MOV格式，点击开始处理按钮就闪退，终端输入错误如图，最后输出的是一个M4A的音频文件，谢谢。
![image](https://github.com/jianchang512/pyvideotrans/assets/8156438/9ed84b16-4add-43c3-adaf-b562ea181ae3)
![image](https://github.com/jianchang512/pyvideotrans/assets/8156438/a4318e75-9c54-4e2d-b36e-bead8d713206)
![image](https://github.com/jianchang512/pyvideotrans/assets/8156438/b76cbda0-1012-484b-88f8-0a25dc709d05)

**Comment by jianchang512** [comment]
软件logs目录下 所有文件删除，然后重试一次，再闪退时，将logs下生成的log文件上传下

**Comment by jcbay** [comment]
INFO:VideoTrans:37397133651c5411204b194b4779e5d4
INFO:VideoTrans:分析视频数据，用时可能较久请稍等..
INFO:VideoTrans:112.mov
INFO:VideoTrans:开始处理
INFO:VideoTrans:no
INFO:VideoTrans:runffmpeg-arg=['-y', '-i', '/Users/alex.zhang/Desktop/112.mov', '-an', '-c:v', 'libx264', '-crf', '0', '/Users/alex.zhang/Desktop/112/novoice.mp4']
INFO:VideoTrans:runffmpeg-arg=['-y', '-i', '/Users/alex.zhang/Desktop/112.mov', '-vn', '-ac', '1', '-c:a', 'aac', '/Users/alex.zhang/Desktop/112/zh-cn.m4a']
INFO:VideoTrans:runffmpeg-tihuan:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', '/Users/alex.zhang/Desktop/112.mov', '-vn', '-ac', '1', '-c:a', 'aac', '/Users/alex.zhang/Desktop/112/zh-cn.m4a']
INFO:VideoTrans:runffmpeg-arg=['-y', '-i', '/Users/alex.zhang/Desktop/112/zh-cn.m4a', '-ac', '1', '-ar', '16000', '/Users/alex.zhang/Desktop/112/shibie.wav']
INFO:VideoTrans:runffmpeg-tihuan:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', '/Users/alex.zhang/Desktop/112/zh-cn.m4a', '-ac', '1', '-ar', '16000', '/Users/alex.zhang/Desktop/112/shibie.wav']
INFO:VideoTrans:开始进行语音识别
INFO:VideoTrans:开始进行语音识别
INFO:VideoTrans:runffmpeg-tihuan:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', '/Users/alex.zhang/Desktop/112.mov', '-an', '-c:v', 'h264_videotoolbox', '-crf', '0', '/Users/alex.zhang/Desktop/112/novoice.mp4']
INFO:faster_whisper:Processing audio with duration 00:13.073
INFO:faster_whisper:VAD filter removed 00:10.489 of audio
DEBUG:faster_whisper:VAD filter kept the following audio segments: [00:01.820 -> 00:02.404], [00:02.588 -> 00:03.812], [00:06.556 -> 00:07.332]
DEBUG:faster_whisper:Processing segment at 00:00.000
INFO:VideoTrans:1
00:00:01,820 --> 00:00:06,970
你好。喂。你好。评职。


INFO:VideoTrans:当前字幕行数  1
DEBUG:faster_whisper:Processing segment at 00:02.220

**Comment by jcbay** [comment]
原视频是使用mac自带的quickTime Player随意录屏，只是短短13秒的MOV格式视频，谢谢

**Comment by jianchang512** [comment]
没看出来什么错误，没有生成srt字幕吗

使用 openai模式试试

**Comment by jcbay** [comment]
> 没看出来什么错误，没有生成srt字幕吗
> 
> 使用 openai模式试试

换成openai模式可以了，谢谢。但现在又发现两个问题

1：生成的视频清晰度很差，原视频是MPEG-4格式，ACC H.264编码，32.1M大小，生成的MP4文件却只有7.6M.
已经尝试修改了videotrans/set.ini ,设置了crf=0 （默认13）,重启软件重试后清晰度没有变化
2：生成的视频中没有了背景声音，已经选择了保留背景音
[video-20240630.log](https://github.com/user-attachments/files/16044747/video-20240630.log)

**Comment by jianchang512** [comment]
嵌入软字幕，硬字幕会重新编码，质量会降低

日志中没看到背景分离错误，实测也未出错，默认背景音会降低音量到50%合并。

可以通过修改 set.ini 中 backaudio_volume=1或 1.5 试试
