### ISSUE TITLE
pip安装依赖报错

### ISSUE THREAD

**Issue by owelinux** [jianchang512/pyvideotrans#462]
**出错信息**

ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tbb==2021.11.0 (from versions: none)
ERROR: No matching distribution found for tbb==2021.11.0

**复现步骤**
pip3 install -r requirements.txt --no-deps

**操作系统**
MacOS

**软件左上角版本号数字**
python 3.10.12

**Comment by jianchang512** [comment]
打开 requirements.txt
删除tbb后的==和数字

**Comment by owelinux** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/43465732/b74ceebe-2ac0-4352-ac12-a0a8e02f0acf)
还是一样

**Comment by owelinux** [comment]
顺便说下，我是mac m2

**Comment by owelinux** [comment]
可以了，谢谢
