### ISSUE TITLE
批量音视频转字幕不支持mkv格式

### ISSUE THREAD

**Issue by heheda123123** [jianchang512/pyvideotrans#463]
**出错信息**
"批量音视频转字幕"这里不支持mkv格式
![image](https://github.com/jianchang512/pyvideotrans/assets/97490782/99fe0138-f89c-464f-b3ee-baea9ad42b78)
但是在"视频转为字幕"功能里面，是支持mkv的
![image](https://github.com/jianchang512/pyvideotrans/assets/97490782/96d27e93-4f11-4fb7-8df5-76ab7f7365ac)
是不是漏掉了

**复现步骤**

**操作系统**
windows

**软件左上角版本号数字**
2.03

**Comment by jianchang512** [comment]
v2.04
