### ISSUE TITLE
建议增加  CosyVoice 语音模型

### ISSUE THREAD

**Issue by miyunwangluo** [jianchang512/pyvideotrans#464]
https://github.com/FunAudioLLM/CosyVoice

**Comment by jianchang512** [comment]
这个项目没有提供api。暂无法加入。

**Comment by yunshenwuji** [comment]
> 这个项目没有提供api。暂无法加入。

请问[SenseVoice](https://github.com/FunAudioLLM/SenseVoice) 可以加入吗？
或许是whisper系列的一个新的替代

**Comment by jianchang512** [comment]
有空了可以看看

CosyVoice后续将加入，目前已写好接口 https://github.com/jianchang512/cosyvoice-api
