### ISSUE TITLE
当视频文件名含有不止后缀名前的“.”时，无法拖拽进软件

### ISSUE THREAD

**Issue by dcyy-l** [jianchang512/pyvideotrans#465]
在使用“批量音视频转字幕”功能时，尝试将要转的视频拖拽进去，“视频.mp4”能直接拖拽进去，“1.视频.mp4”拖拽不进去

**Comment by dcyy-l** [comment]
win10
v2.06

**Comment by dcyy-l** [comment]
还有就是能不能增加字幕生成到音频或视频所在目录的选项？

**Comment by dcyy-l** [comment]
当“批量音视频转字幕"批量放进去的视频中存在没声音的视频时，到了那个视频就会报错并中断。显示：”识别出错:list index out of range“

**Comment by jianchang512** [comment]
更新到最新2.08

**Comment by dcyy-l** [comment]
> 当“批量音视频转字幕"批量放进去的视频中存在没声音的视频时，到了那个视频就会报错并中断。显示：”识别出错:list index out of range“

模型选用的是zh_recogn中文识别

**Comment by jianchang512** [comment]
更新到 2.08
