### ISSUE TITLE
使用字节火山api翻译出现翻译出的中文字幕带有英文

### ISSUE THREAD

**Issue by peet2269** [jianchang512/pyvideotrans#466]
**出错信息**

使用字节火山api翻译出现翻译出的中文字幕带有英文，然后就导致在配音的时候中英文都会配上

用的最新版本2.0.6

![PixPin_2024-07-11_18-34-52](https://github.com/jianchang512/pyvideotrans/assets/116452440/03506803-0ecc-4871-b0a4-ca2167e85142)

英文识别使用的是豆包识别

**Comment by jianchang512** [comment]
字节翻译问题

1. 使用更大更好的模型， 
2.  videotrans/zijie.txt 中自行修提示词调整

**Comment by peet2269** [comment]
好的。谢谢 已解决
