### ISSUE TITLE
[功能请求] 增加video_autorate选项

### ISSUE THREAD

**Issue by photkey** [jianchang512/pyvideotrans#47]
类似于：`--voice_autorate: 如果翻译后的音频时长超过原时长，是否强制加速播放翻译后的音频，以便对齐时长`
有时候音频加速太快 以至于都完全无法听清，所以是否可以提供一个自动调整视频的选项，把对应时段内的视频慢放，以对齐时长

**Comment by jianchang512** [comment]
只ffmpeg应该也能实现

比如 音频片段是 5-10s区间的5s，配音后，音频变为了 12s时长。

那么就对原始视频 5-10s区间应用2.4倍降速播放，时长就是12s，ffmpeg可以取出这个降速后的片段视频 a

然后再对原始视频中 0-5s的片段b，和10s-结束的片段c截取出来。

最后 连接 b a c 这3个片段就行了


当然如果只有一二个片段还好说，不过一般都是几十个片段甚至更多，所以更复杂也更慢了

**Comment by jianchang512** [comment]
不必那么精准吧，到秒或者 0. 几秒也就够了，本身就是降速延时处理的，再精确也没多大意义

只测试过 0.几秒即数百ms的，倒还算精确。

一个视频处理不只是一个片段，整体下来计算量非常庞大，即便GPU加速，也会非常慢的

**Comment by jianchang512** [comment]
如果要精确到ms，确实使用 cv2更方便，按帧读取，然后调整fps，重新输出视频片段，再拼接

**Comment by MedalCollector** [comment]
有没有可能像剪映一样，增加一个“定格”功能，即原始视频画面内容不懂，如果需要延长视频时间和音频同步，就将一部分画面定格一段时间。这样就相当于从原始视频中抽了一些帧做了延时，再插入到原来的视频里，不涉及原始视频的大量计算，会不会更快一些？

**Comment by MedalCollector** [comment]
有没有可能像剪映一样，增加一个“定格”功能，即原始视频画面内容不动，如果需要延长视频时间和音频同步，就将一部分画面定格一段时间。这样就相当于从原始视频中抽了一些帧做了延时，再插入到原来的视频里，不涉及原始视频的大量计算，会不会更快一些？

**Comment by jianchang512** [comment]
> 有没有可能像剪映一样，增加一个“定格”功能，即原始视频画面内容不动，如果需要延长视频时间和音频同步，就将一部分画面定格一段时间。这样就相当于从原始视频中抽了一些帧做了延时，再插入到原来的视频里，不涉及原始视频的大量计算，会不会更快一些？

有打算在视频的最后，复制最后一帧做视频延长到和音频一致，中间定格实际计算量还是很大的，所谓延时，本质就是将抽出的帧不断复制，直到达到所需时长，然后再插入原视频，而插入，实质上需要将原视频在插入点截断为2个视频片段，然后3个视频再拼接一切。定格点多了一样需要较大计算量，也很复杂。

而且定格这个功能，只界面都挺复杂了，对于这个没有商业计划的小项目来说，过于复杂了。

**Comment by jianchang512** [comment]
已实现视频自动降速。对应片段降低帧率实现。
默认情况下通过延长视频最后一帧画面实现
