### ISSUE TITLE
STT功能出错

### ISSUE THREAD

**Issue by rqi14** [jianchang512/pyvideotrans#478]
**出错信息**
![image](https://github.com/user-attachments/assets/011e542b-5f4b-4351-bbe8-b1fa4f062576)

**复现步骤**
1. STT
2. faster模式
3. tiny

**操作系统**
 - Windows 11

**软件左上角版本号数字**
v2.10

**Comment by jianchang512** [comment]
https://github.com/jianchang512/pyvideotrans/releases/download/v2.10/win-PatchUpdate-2.12.7z

下载这个补丁包覆盖试试

**Comment by rqi14** [comment]
> https://github.com/jianchang512/pyvideotrans/releases/download/v2.10/win-PatchUpdate-2.12.7z
> 
> 下载这个补丁包覆盖试试

这个windows defender会报毒自动删除
![image](https://github.com/user-attachments/assets/920bab98-74fd-404e-9bb8-18f6878f1596)

<img width="743" alt="image" src="https://github.com/user-attachments/assets/ab074cee-33fd-404b-9fd2-c16059cfc18a">

**Comment by jianchang512** [comment]
正常。无数字签名，pyinstaller简单打包的。信任或忽略

要么就源码部署

**Comment by rqi14** [comment]
> 正常。无数字签名，pyinstaller简单打包的。信任或忽略
> 
> 要么就源码部署

安装补丁之后是可以的。

补丁是2.12但是版本显示还是2.11

**Comment by jianchang512** [comment]
没关系，能用就行，如果可用，就稍后更新

**Comment by rqi14** [comment]
> 没关系，能用就行，如果可用，就稍后更新

我发现 distil-whisper-large-v2和v3出来字幕是英语的，尽管我已经设置发音语言是中文

![image](https://github.com/user-attachments/assets/c208089d-958f-4f11-b58b-220fa9292685)

**Comment by jianchang512** [comment]
有说明啊，带distil的只能识别英语

**Comment by rqi14** [comment]
> 有说明啊，带distil的只能识别英语

明白了。

我切换到v3。我发现如果用均等分割就会出现很多类似这样的字幕

```
2
00:00:10,000 --> 00:00:20,000
segment at end of each sentence. .
```

如果是整体识别就不会。但是整体识别好像会少几段话

**Comment by jianchang512** [comment]
什么叫均等啊。就是强制分割成一样的时间段，不管是不是断句

用更大的模型可能会好点
