### ISSUE TITLE
0.9.1版本在window11上面不能用

### ISSUE THREAD

**Issue by admin888-byte** [jianchang512/pyvideotrans#48]
文字识别和翻译出错:[Errno 2] N such file or directory:'C:/Users/阮欣怡/Desktop/video-translate-v0.9.1.21tmp/BIiAylzA5M jMxNDEyHTRfMTUwOTM1NzQ5HV8xHTzODU5KTEwTRfF8z bB6cef7fc7e49f44410a8bae92bdaffe85/##BIAylzA5M MxNDEyTRNTUw0TH1NzQ5HY8xHTMzDU5HTEwHTRfNF8z b B6cef7fc7e49f44410a8bae92bdaffe85_tmp/letected voice.ison
BIiAyIzA5M iMxIDEyITRMTUwOTH1N2Q5HV8xTIZODU5MTEwMTRN8z b Bce7c7e49f44410a8bae92bdafte85 对音频文件按静音片段分割处理
B机iAvIzA5K讯xNDEYlTRNTUMTH1N205KV8xITHZODU5HTEMTRNF8z  Bce7c7e49f44410a8bae92bdaffe85 M视频中抽离音家

开始执行后，报这个错，我查了tmp文件夹是自动创建的，也是有权限的，但还是报这个错

**Comment by jianchang512** [comment]
先这样试试

1. 不要放在中文文件夹下
2. 路径中不要包含有空格的文件夹

可以把 video.log 放上来看看
