### ISSUE TITLE
mac源码部署闪退

### ISSUE THREAD

**Issue by fighter2011** [jianchang512/pyvideotrans#482]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。

**复现步骤**
1. 使用的哪个功能 
音频转字幕
2. faster模式/openai模式？
faster模式
3. 使用的模型名
tiny

**操作系统**
 - Windows/Linux/MacOS
 mac

**软件左上角版本号数字**
2.18

命令行最后输出 segmentation fault

**Comment by jianchang512** [comment]
出错信息太少，打开logs文件夹下最新的log文件，底部的相关出错信息

**Comment by fighter2011** [comment]
日志很少
2024-07-25 09:50:27,986 - VideoTrans - INFO - start tiny 
2024-07-25 09:50:29,353 - VideoTrans - INFO - 开始识别字幕:c7890a33dafe4e8d89f9c1b875495b83.mp3.wav
2024-07-25 09:50:29,353 - VideoTrans - INFO - 49%
2024-07-25 09:50:29,354 - VideoTrans - INFO - faster模式 整体识别

控制台日志
启动用时：4.794930934906006
2024-07-25 09:50:27,986 - VideoTrans - INFO - start tiny 
INFO:VideoTrans:start tiny 
2024-07-25 09:50:29,353 - VideoTrans - INFO - 开始识别字幕:c7890a33dafe4e8d89f9c1b875495b83.mp3.wav
INFO:VideoTrans:开始识别字幕:c7890a33dafe4e8d89f9c1b875495b83.mp3.wav
audio_path='/Users/wuqiulin/Videos/pyvideotrans/tmp/c7890a33dafe4e8d89f9c1b875495b83.mp3.wav'
2024-07-25 09:50:29,353 - VideoTrans - INFO - 49%
INFO:VideoTrans:49%
2024-07-25 09:50:29,354 - VideoTrans - INFO - faster模式 整体识别
INFO:VideoTrans:faster模式 整体识别
[2024-07-25 09:50:29.771] [ctranslate2] [thread 30733552] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
INFO:faster_whisper:Processing audio with duration 06:37.824
INFO:faster_whisper:VAD filter removed 04:19.912 of audio
DEBUG:faster_whisper:VAD filter kept the following audio segments: [00:00.924 -> 00:15.780], [00:15.932 -> 00:32.388], [00:36.572 -> 00:38.692], [00:39.548 -> 00:42.596], [00:46.492 -> 00:48.004], [00:51.676 -> 00:53.764], [00:54.364 -> 00:55.940], [00:57.500 -> 00:59.108], [01:10.076 -> 01:12.356], [01:17.116 -> 01:19.268], [01:22.076 -> 01:23.492], [01:40.380 -> 01:41.828], [01:44.124 -> 01:47.428], [01:49.244 -> 01:51.652], [02:22.364 -> 02:23.172], [02:24.220 -> 02:27.620], [03:06.364 -> 03:07.396], [03:08.412 -> 03:10.212], [03:13.180 -> 03:14.532], [03:24.060 -> 03:25.796], [03:27.708 -> 03:28.932], [03:29.500 -> 03:30.852], [03:31.452 -> 03:32.580], [04:02.684 -> 04:05.444], [04:11.004 -> 04:12.580], [04:16.220 -> 04:18.180], [05:05.084 -> 05:06.660], [05:09.116 -> 05:11.076], [05:23.196 -> 05:26.052], [05:29.436 -> 05:31.940], [05:36.636 -> 05:46.148], [05:46.812 -> 05:48.772], [05:49.628 -> 05:52.356], [05:52.860 -> 06:07.780], [06:07.868 -> 06:16.900], [06:17.916 -> 06:24.004], [06:24.412 -> 06:26.532], [06:26.780 -> 06:28.772], [06:29.468 -> 06:33.732]
DEBUG:faster_whisper:Processing segment at 00:00.000
[1]    83672 segmentation fault  python sp.py

**Comment by fighter2011** [comment]
更新到最新代码尝试，依旧是音频转字幕闪退，视频分离音频也正常，没有过多日志

**Comment by jianchang512** [comment]
`pip3 install --force-reinstall faster-whisper==1.0.1  ctranslate2==3.24.0`

试试

**Comment by fighter2011** [comment]
> `pip3 install --force-reinstall faster-whisper==1.0.1 ctranslate2==3.24.0`
> 
> 试试

不行，装不上，版本有冲突

**Comment by jianchang512** [comment]
提示有冲突不代表安装不了。最后有 success 提示即是成功

**Comment by fighter2011** [comment]
> 提示有冲突不代表安装不了。最后有 success 提示即是成功

没有success，直接就退出了

**Comment by jianchang512** [comment]
重新安装，截图终端所有信息，logs文件夹下最新的log文件上传

**Comment by isunkit** [comment]
> > 提示有冲突不代表安装不了。最后有 success 提示即是成功
> 
> 没有success，直接就退出了

和你问题一样，安装这个也是显示代码冲突。
请问你解决了吗？
