### ISSUE TITLE
Translation error using Gemini!!!

### ISSUE THREAD

**Issue by cuongnguyen9463** [jianchang512/pyvideotrans#483]
The translation error you're encountering when using Gemini to translate from Chinese to Portuguese, specifically with SRT files, seems to be related to content repetition. You mentioned that translating 15 lines results in the same translation being repeated numerous times, sometimes even dozens of times.

**Comment by jianchang512** [comment]
I don't quite understand, can you give an example?

**Comment by cuongnguyen9463** [comment]
For example, this is the file I want to translate.
1
00:00:00,450 --> 00:00:01,883
中海电视台的小姐姐
2
00:00:01,883 --> 00:00:03,250
既然被林毅给迷住了
3
00:00:03,250 --> 00:00:05,083
不得不说她的魅力是真的大
4
00:00:05,083 --> 00:00:06,400
沈淑瑜看着自己的女儿
5
00:00:06,400 --> 00:00:07,483
跟林毅这般亲密
-----------------------
6
00:00:07,483 --> 00:00:09,566
心想他们到底走到哪一步了
7
00:00:09,566 --> 00:00:11,283
随后便问林毅小毅
8
00:00:11,283 --> 00:00:12,933
我听说你在研发光客机
9
00:00:12,933 --> 00:00:13,850
有什么困难吗
10
00:00:13,850 --> 00:00:16,050
比如说资金方面或其他的支持
.................................
270
00:05:40,133 --> 00:05:42,283
刻后还是签下了自己的名字

This is the file after translation.
1
00:00:00,450 --> 00:00:01,883
A senhorita da Televisão Zhonghai
2
00:00:01,883 --> 00:00:03,250
Já que foi enfeitiçada por Lin Yi
3
00:00:03,250 --> 00:00:05,083
Tenho que dizer que o seu charme é realmente grande
4
00:00:05,083 --> 00:00:06,400
Shen Shuyu olhou para a sua filha
5
00:00:06,400 --> 00:00:07,483
Tão íntima com Lin Yi
-----------------------------------
6
00:00:07,483 --> 00:00:09,566
A senhorita da Televisão Zhonghai
7
00:00:09,566 --> 00:00:11,283
Então perguntou a Lin Yi Xiaoyi
8
00:00:11,283 --> 00:00:12,933
Já que foi enfeitiçada por Lin Yi
9
00:00:12,933 --> 00:00:13,850
Tenho que dizer que o seu charme é realmente grande
10
00:00:13,850 --> 00:00:16,050
Shen Shuyu olhou para a sua filha

Each time I translate 5 lines. When translating to a certain point, the returned results are all the same. The content is the same, but the time is different. Sometimes it only repeats once or twice. Sometimes it repeats 30-40 times. I don't know if it's due to Gemini or a tool error.

**Comment by jianchang512** [comment]
Unzip and overwrite sp.exe and try

https://github.com/jianchang512/pyvideotrans/releases/download/v2.19/sp.zip
