### ISSUE TITLE
gemini translation is not working, while i am translating from Chinese to English ! in 2.20 version !!!请再次阅读编辑后的问题。

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#485]
the translation is running in loops while skipping raw lines to translate its repeating some of translated lines over and over.
the translation is in robotic tone.

**Comment by jianchang512** [comment]
Unzip and overwrite sp.exe and try

https://github.com/jianchang512/pyvideotrans/releases/download/v2.19/sp.zip

**Comment by abhijeet12s** [comment]
thanks its working now it doesn't translated text in loop now and for robotic translation i have made my own command prompt  

请将原文按字面意思翻译成{lang}，采用自然流畅的叙述风格。扩展内容40%，确保译文读起来顺畅，不显得生硬。请特别注意翻译的完整性，确保所有句子都被全面翻译。然后只输出译文，不要添加任何说明或引导词。

**格式要求：**
- 按行翻译原文，并生成该行对应的译文，确保原文行和译文行中的每个单词相互对应。
- 有几行原文，必须生成几行译文。

**内容要求：**
- 翻译必须自然流畅。
- 只输出译文即可，不要输出原文。

**执行细节：**
- 如果某行原文很短，在翻译后也仍然要保留该行，不得与上一行或下一行合并。
- 原文换行处字符相对应的译文字符也必须换行。
- 严格按照字面意思翻译，不要解释或回答原文内容。

**最终目标：**
- 提供格式与原文完全一致的高质量翻译结果。

原文: """{text}"""

译文:
