### ISSUE TITLE
高级设置（set.ini）的问题

### ISSUE THREAD

**Issue by steven225** [jianchang512/pyvideotrans#487]
如果我把高级设置的temperature改成1时，将音频转成字幕的过程中，快完成时程序会闪退，最终字幕并没有成功被产出，想请问是否为我的显卡效能不够的问题？ 我的显示是GTX4070，只有12G，感谢。

**Comment by jianchang512** [comment]
faster-whisper的bug，暂时设为吧，效果差别不大

**Comment by steven225** [comment]
十分谢谢说明
