### ISSUE TITLE
subtitle extraction

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#489]
Could you add a subtitle extractor for videos? It would be very useful. Currently, I am using YaoFANGUK/video-subtitle-extractor to extract subtitles in SRT format. While it's good, it does miss a few subtitles during extraction. You could improve it by updating the requirements, Update Libraries so that it works better with the GPU, Parallel Processing, Using Advanced OCR it currently uses old version of paddle OCR .

你能添加一个视频的字幕提取器吗？这将非常有用。目前，我正在使用 YaoFANGUK/video-subtitle-extractor 提取 SRT 格式的字幕。虽然它很好，但在提取过程中会漏掉一些字幕。你可以通过更新需求、更新库来改进它，以便更好地利用 GPU，进行并行处理，并使用更高级的 OCR。它目前使用的是旧版本的 Paddle OCR。

**Comment by jianchang512** [comment]
What you are currently using is a great program and not planning to join within that program would result in an oversized and overly complex program
