### ISSUE TITLE
D:/capcut expo/sect1/sect part 1/sect part 1.srt出错:Gemini:2 retries after error persists :429 Resource has been exhausted (e.g. check quota).

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#492]
please fix this error

**Comment by jianchang512** [comment]
Looking at the error report, it's your gemini resource request that's limited, not buggy
The number of requests per minute for the gemini free number is very low.

**Comment by abhijeet12s** [comment]
> Looking at the error report, it's your gemini resource request that's limited, not buggy The number of requests per minute for the gemini free number is very low.

How can I solve this issue? Is there way to send requests slowly in pyvideo trans.

**Comment by jianchang512** [comment]
Currently there is nothing to set up except to modify the source code.
Consider adding a limit later.
Please use other translation channels first, such as google
