### ISSUE TITLE
why is gemini translation working in pyvideotrans 1.14 but not 2.21 and 2.20 , i have uploaded screenshots. 

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#493]
why is gemini translation working in pyvideotrans 1.14 but not 2.21 and 2.20
![Screenshot 2024-08-01 232026](https://github.com/user-attachments/assets/b3dc2f54-6ba6-402f-a1e5-a6b05efb6e96)
![Screenshot 2024-08-01 232111](https://github.com/user-attachments/assets/07c654db-8c7e-4a59-80d4-63c031fe860b)

**Comment by jianchang512** [comment]
Try recreating a gemini key

**Comment by abhijeet12s** [comment]
> Try recreating a gemini key

i tried recreating gemini api key but its not working. in pyvideotrans 1.13 its uses gemini-pro and in  pyvideotrans 2.21 it uses gemini 1.5 pro i think its related to that. can i somehow change it to gemini 1.5flash

**Comment by jianchang512** [comment]
Yes. Updated to 1.5 model.
Re-create the key and you should be good to go.
