### ISSUE TITLE
视频加字幕，部分对话没有有字幕

### ISSUE THREAD

**Issue by MisteryLiuCode** [jianchang512/pyvideotrans#496]
**出错信息**
使用标准功能给视频加字幕，字幕显示断断续续，一部分有字幕，有的没有

**复现步骤**
1. 使用的哪个功能
标准功能
3. faster模式/openai模式？
openai模式
5. 使用的模型名 
large-v3

**操作系统**
 - Windows/Linux/MacOS
macos
**软件左上角版本号数字**
v2.22

**Comment by jianchang512** [comment]
没看明白什么意思

标准功能模式每个选项的所有设置截图

“部分对话没有有字幕” 的截图

2种语言的srt字幕文件上传

**Comment by MisteryLiuCode** [comment]
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/60a2b374-c432-43a7-833f-8f08a51c4a7a">
我现在用的批量给视频加字幕，都是中文视频。比如说视频里有5句话，可能有两句话没有显示字幕，我用的腾讯翻译，large-v3模型，是什么原因造成这种情况呢

**Comment by jianchang512** [comment]
看不懂，你截图显示的功能是字幕识别，即从视频中生成srt字幕文件，不存给视频加字幕

如果你说的是左侧“字幕嵌入视频”，那么仅仅是将已有的字幕文件嵌入视频。用不到腾讯翻译。

搞不明白。你录个操作视频

**Comment by MisteryLiuCode** [comment]
在上面选择一个没有字幕的视频，运行之后会生成一个字幕文件，再用视频播放器加载视频和生成的字幕文件就可以实现给视频加上字幕，应该是用不到腾讯翻译，用到了语音识别

**Comment by jianchang512** [comment]
这是正常的，语音识别无法保证里面的每句话都识别出来，比如 语音清晰度、音量、噪声等很多因素都会影响识别结果。
可以再使用 faster模式-large-v2模型试试

**Comment by MisteryLiuCode** [comment]
这种模式是最精确的吗，请问哪种是最精确的？

**Comment by jianchang512** [comment]
faster模式  large-v2 large-v3 是最精确的

如果视频是中文的，可以尝试使用 zh_regcon ，效果更好

**Comment by MisteryLiuCode** [comment]
zh_regcon，请问这个是哪个模型呢？我在文档中没找到，google也找不到
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/0c930597-5015-4122-b261-c16c42ea8793">

**Comment by jianchang512** [comment]
https://pyvideotrans.com/zh_recogn.html

**Comment by MisteryLiuCode** [comment]
好的，非常感谢，我试一下

**Comment by MisteryLiuCode** [comment]
而且我发现 faster模式 large-v3 竟然不占cpu，openai 的 large-v3 电脑要起飞了

**Comment by MisteryLiuCode** [comment]
zh_regcon 确实没有这个问题了，而且翻译的质量更好
