### ISSUE TITLE
Network traffic exceeded, ytwin32.exe can be removed from the repository.

### ISSUE THREAD

**Issue by iBoostAI** [jianchang512/pyvideotrans#497]
Error downloading object: ffmpeg/ytwin32.exe (160b304): Smudge error: Error downloading ffmpeg/ytwin32.exe (160b304bef9fa134d523b46cc3647a727e40584338379eb4e0d1047de945fad9): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by jianchang512** [comment]
git pull try
