### ISSUE TITLE
The model `gpt-4o` does not exist or you do not have access to it. how to install it

### ISSUE THREAD

**Issue by DuongTrung2212** [jianchang512/pyvideotrans#499]
Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}},api_url='https://api.openai.com/v1'

**Comment by jianchang512** [comment]
use gpt-4o-mini

**Comment by DuongTrung2212** [comment]
thanks bro
