### ISSUE TITLE
求助，生成后视频无声音

### ISSUE THREAD

**Issue by aimarxjg** [jianchang512/pyvideotrans#5]
求助，原视频边上也生成了字幕文件，但是翻译后的视频就是无声音（字幕正常嵌入），什么声音都没有，请大佬帮我看下，是不是少了什么模型文件，谢谢
![173250](https://github.com/jianchang512/pyvideotrans/assets/132532636/f14597fe-fb27-4055-bbc5-7ad71015f8ae)

**Comment by jianchang512** [comment]
是源码部署 使用 python sp.py 执行的，还是自己打包后执行的？
如果是自己打包的，尝试从 Lib/site_package 下复制  edge_tts edge_placback 到 打包后目录下的 _internal 中。

如果是源码部署 python sp.py，用命令执行下看看

**Comment by jianchang512** [comment]
系统什么版本，有edge浏览器吗

**Comment by aimarxjg** [comment]
是WIN11，今天晚7点才更新了1波，有EDGE浏览器
![Uploading QQ图片20231102203558.png…]()

**Comment by aimarxjg** [comment]
是WIN11，今天晚7点才更新了1波，有EDGE浏览器
![QQ图片20231102203558](https://github.com/jianchang512/pyvideotrans/assets/132532636/f89789ba-df02-4c7c-99af-6a97f0b5d5ca)

**Comment by jianchang512** [comment]
启动执行后，当前目录下会生成tmp目录，会持续产生wav文件，在最终结束之前将这些wav复制到其他地方，这些是临时文件，结束后会自动删除
复制到其他地方后，打开看看有没有声音
另外当前目录下有个log格式文件，打开复制里面内容贴上

**Comment by aimarxjg** [comment]
回大佬，按您要求在生成视频85%时候将2个TMP文件夹复制出来，并且把 软件文件里面的 VIDEO.LOG复制到了这2个文件里面。（在软件执行过程中，它分别在 原始视频文件 下面 和  软件本身文件夹里面产生了2个TMP文件夹）1个是WAV 1个是MP3，2类文件单独播放都有声音。操作后软件界面停止，控制台叫我按Q继续，之后报错，依然输出了没有任何声音的视频
![2205405](https://github.com/jianchang512/pyvideotrans/assets/132532636/eafe8f47-50ca-4e2b-88c0-192901147ff7)
![02210036](https://github.com/jianchang512/pyvideotrans/assets/132532636/13807f35-ab81-4669-8405-dcd1f3867465)
![QQ图片20231102210019](https://github.com/jianchang512/pyvideotrans/assets/132532636/b49a3502-e7a8-4506-92f3-6e4dd3a1863c)

**Comment by jianchang512** [comment]
有错误产生但看不全是什么错误，那个控制台红色行向上一段范围都要截图，不要按q

然后log日志传上来看看

**Comment by aimarxjg** [comment]
早上重试了下，还是没声音，一下控制台信息，LOG文件已上传
t='中文简',vt='zh'
{'source_mp4': 'C:/Users/22659/Music/1282348298-1-16.mp4', 'target_dir': 'c:/users/22659/videos/desktop', 'source_language': 'en', 'detect_language': 'en', 'target_language': 'zh-cn', 'subtitle_language': 'chi', 'voice_role': 'zh-CN-YunxiaNeural', 'voice_rate': '0', 'voice_silence': 500, 'whisper_model': 'base', 'insert_subtitle': True, 'voice_autorate': False, 'remove_background': False, 'proxy': 'http://127.0.0.1:1080'}
sowshisls
ffmpeg version N-112170-gb61733f61f-20230924 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230924
  libavutil      58. 25.100 / 58. 25.100
  libavcodec     60. 27.100 / 60. 27.100
  libavformat    60. 13.100 / 60. 13.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:/Users/22659/Music/1282348298-1-16.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
  Duration: 00:00:30.88, start: 0.000000, bitrate: 187 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 149 kb/s, 24 fps, 24 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 32 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:/Users/22659/Music/1282348298-1-16.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
    ISFT            : Lavf60.13.100
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.27.100 pcm_s16le
[out#0/wav @ 0000021b6b4c51c0] video:0kB audio:2660kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.002864%
size=    2660kB time=00:00:30.83 bitrate= 706.7kbits/s speed= 451x
ffmpeg version N-112170-gb61733f61f-20230924 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230924
  libavutil      58. 25.100 / 58. 25.100
  libavcodec     60. 27.100 / 60. 27.100
  libavformat    60. 13.100 / 60. 13.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:/Users/22659/Music/1282348298-1-16.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
  Duration: 00:00:30.88, start: 0.000000, bitrate: 187 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 149 kb/s, 24 fps, 24 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 32 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output #0, mp4, to 'E:/video-translate-v0.7.0/tmp/novoice_1282348298-1-16.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
    encoder         : Lavf60.13.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 149 kb/s, 24 fps, 24 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[out#0/mp4 @ 000001decf4636c0] video:561kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.393453%
frame=  736 fps=0.0 q=-1.0 Lsize=     574kB time=00:00:30.50 bitrate= 154.2kbits/s speed=1.61e+03x
ffmpeg version N-112170-gb61733f61f-20230924 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230924
  libavutil      58. 25.100 / 58. 25.100
  libavcodec     60. 27.100 / 60. 27.100
  libavformat    60. 13.100 / 60. 13.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:/video-translate-v0.7.0/tmp/novoice_1282348298-1-16.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.13.100
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
  Duration: 00:00:30.67, start: 0.046000, bitrate: 153 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 149 kb/s, 24 fps, 24 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[aist#1:0/pcm_s16le @ 00000239590df980] Guessed Channel Layout: mono
Input #1, wav, from 'E:/video-translate-v0.7.0/tmp/1282348298-1-16.mp4.wav':
  Duration: 00:00:30.88, bitrate: 384 kb/s
  Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, 1 channels, s16, 384 kb/s
Output #0, mp4, to 'E:/video-translate-v0.7.0/tmp/addvoice-1282348298-1-16.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
    encoder         : Lavf60.13.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 149 kb/s, 24 fps, 24 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1: Audio: pcm_s16le (ipcm / 0x6D637069), 24000 Hz, mono, s16, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[out#0/mp4 @ 00000239590c4280] video:561kB audio:1448kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.850311%
frame=  736 fps=0.0 q=-1.0 Lsize=    2026kB time=00:00:30.80 bitrate= 538.6kbits/s speed=4.37e+03x
ffmpeg version N-112170-gb61733f61f-20230924 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230924
  libavutil      58. 25.100 / 58. 25.100
  libavcodec     60. 27.100 / 60. 27.100
  libavformat    60. 13.100 / 60. 13.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[aist#0:1/pcm_s16le @ 00000251a285ed80] Guessed Channel Layout: mono
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:/video-translate-v0.7.0/tmp/addvoice-1282348298-1-16.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.13.100
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
  Duration: 00:00:30.88, start: 0.000000, bitrate: 537 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 149 kb/s, 24 fps, 24 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: pcm_s16le (ipcm / 0x6D637069), 24000 Hz, 1 channels, s16, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Input #1, srt, from 'C:/Users/22659/Music/1282348298-1-16.srt':
  Duration: N/A, bitrate: N/A
  Stream #1:0: Subtitle: subrip
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 2, only the last option '-c:s mov_text' will be used.
Output #0, mp4, to 'c:/users/22659/videos/desktop/1282348298-1-16.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    description     : Bilibili VXCode Swarm Transcoder v0.7.68
    encoder         : Lavf60.13.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 149 kb/s, 24 fps, 24 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: pcm_s16le (ipcm / 0x6D637069), 24000 Hz, mono, s16, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2(chi): Subtitle: mov_text (tx3g / 0x67337874)
    Metadata:
      encoder         : Lavc60.27.100 mov_text
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #1:0 -> #0:2 (subrip (srt) -> mov_text (native))
Press [q] to stop, [?] for help
[out#0/mp4 @ 00000251a0be2700] video:561kB audio:1448kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.028657%
frame=  736 fps=0.0 q=-1.0 Lsize=    2029kB time=00:00:30.84 bitrate= 538.9kbits/s speed=1.25e+03x


[video.log](https://github.com/jianchang512/pyvideotrans/files/13245605/video.log)

**Comment by aimarxjg** [comment]
试了很久，发现是我播放器缘故，我这PC只有 完美解码 能播放出来，别的播放器（暴风 迅雷，WIN11自带的）都不行。是不是缺少了什么解码器，不管怎么样，谢谢大佬了~

**Comment by jianchang512** [comment]
新版放在了软件目录下的 models 里

**Comment by leedstyh** [comment]
我下载的release里的

转化的是youtube下载的视频，用win11自带的，没声音没字幕。用@aimarxjg 说的《完美解码》，只有字幕，没用声音

**Comment by aimarxjg** [comment]
@leedstyh  你是不是昨天也更新了WIN11到最新版了？ 我尝试WIN10和11 用完美解码播放翻译出来的都是正常的，不知道系统少了什么解码器

**Comment by leedstyh** [comment]
@aimarxjg 确实，浏览器可以播放，但是没字幕，我也再研究研究怎么回事

**Comment by jianchang512** [comment]
软字幕方式嵌入的，显示或隐藏字幕需要播放器支持，在网页里是无法直接显示的，需要再单独处理， 原始视频同目录下会生成srt字幕文件

或者考虑加个硬字幕嵌入选项，直接硬编码嵌入视频，在任何地方均可显示

没有声音的，可以将软件目录下的 video.log 日志上传上来，直接拖到这个编辑框内即可，看看什么原因

**Comment by leedstyh** [comment]
[video.log](https://github.com/jianchang512/pyvideotrans/files/13249815/video.log)

**Comment by leedstyh** [comment]
@jianchang512 能看出来是什么原因嘛

因为srt文件不在_video_out里，我就以为是硬字幕。应该不会自动读取上一个目录下的srt文件吧

**Comment by jianchang512** [comment]
会加载同目录下的同名srt字幕，但mp4对字幕支持有限，网页里不可直接显示字幕，除非硬字幕嵌入。

目前是软字幕，一般有字幕管理的播放器都应该可以显示或隐藏。

至于无法播放的问题，可能是因为合成时没有再对视频编码，直接复制的源流，不是标准h264。下版重新编下码

下次加个硬字幕选项，只要播放就始终显示字幕。

没声音看起来是edge tts响应失败，没有合成声音。打开下edge浏览器，随便找个网页，右键朗读，看看有没有声音

**Comment by leedstyh** [comment]
> 没声音看起来是edge tts响应失败，没有合成声音。打开下edge浏览器，随便找个网页，右键朗读，看看有没有声音

@jianchang512 有朗读声音

**Comment by aimarxjg** [comment]
@jianchang512，感谢大佬又更新了😊
又出新的模型了呢~https://twitter.com/xiaohuggg/status/1720623532223103420

**Comment by jianchang512** [comment]
> @jianchang512，感谢大佬又更新了😊 又出新的模型了呢~https://twitter.com/xiaohuggg/status/1720623532223103420

currently only available for English speech recognition

**Comment by leedstyh** [comment]
更新0.7.4后，win11自带的播放器正常了，有声音和字幕，不过似乎声音时间轴要落后一些，没有对齐

**Comment by jianchang512** [comment]
选中 自动加速

这个是没啥办法的，不同语言下，时长肯定会有变化的，比如中文3s说完的内容，翻译成英文后可能5s或者更多，选中 自动加速后，可以强制对齐，不过速度最高提升2倍，免得过快

**Comment by leedstyh** [comment]
哦原来是这个原因，了解了，我试下。

感谢大佬的幸苦工作
