### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2922832737C** [jianchang512/pyvideotrans#50]
刚开始的时候我还运行起来了，还转来几个视频，后来我使用openaiTTS，配置了代理还有key,转成一次之后，在次进行翻译配音的时候就不行了
![image](https://github.com/jianchang512/pyvideotrans/assets/115255509/64e6305f-30c9-43df-b8a6-633861aec56e)

**Comment by jianchang512** [comment]
video.log能否上传下

**Comment by 2922832737C** [comment]
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:Will execute: ffmpeg -y -i "C:/Users/chang/Desktop/38bcad4551e799d0abe5aa23ed8e1be6.mp4" -ac 1 "C:/Users/chang/Desktop/pyvideotrans-main/tmp/38bcad4551e799d0abe5aa23ed8e1be6/38bcad4551e799d0abe5aa23ed8e1be6.wav"
INFO:VideoTrans:Will execute: ffmpeg -y -i "C:/Users/chang/Desktop/38bcad4551e799d0abe5aa23ed8e1be6.mp4" -an "C:/Users/chang/Desktop/pyvideotrans-main/tmp/38bcad4551e799d0abe5aa23ed8e1be6/novoice.mp4"
INFO:VideoTrans:执行 异步ffmpeg命令：ffmpeg -hide_banner -y -i "C:/Users/chang/Desktop/38bcad4551e799d0abe5aa23ed8e1be6.mp4" -an "C:/Users/chang/Desktop/pyvideotrans-main/tmp/38bcad4551e799d0abe5aa23ed8e1be6/novoice.mp4"
INFO:VideoTrans:folder_path='C:/Users/chang/Desktop/pyvideotrans-main/tmp/38bcad4551e799d0abe5aa23ed8e1be6'
aud_path='C:/Users/chang/Desktop/pyvideotrans-main/tmp/38bcad4551e799d0abe5aa23ed8e1be6/38bcad4551e799d0abe5aa23ed8e1be6.wav'
sub_name='C:/Users/chang/Desktop/pyvideotrans-main/tmp/38bcad4551e799d0abe5aa23ed8e1be6/38bcad4551e799d0abe5aa23ed8e1be6.srt'
INFO:VideoTrans:for i in nonsilent_data
ERROR:VideoTrans:sp.py :You stop it

**Comment by jianchang512** [comment]
软件关闭再重新打开也不行？

**Comment by 2922832737C** [comment]
不行，它还是
![image](https://github.com/jianchang512/pyvideotrans/assets/115255509/4dbe58d7-5de7-4fed-b35e-bd22c13c66ea)
我重新将项目拉下来重新运行还是这个问题

**Comment by jianchang512** [comment]
软件放在哪里的，右键管理员权限运行试试

还不行的话，一会我打包个新版试试

**Comment by 2922832737C** [comment]
我的项目是放在桌面上的，我是通过pytgon sp.py运行的

**Comment by jianchang512** [comment]
项目下 tmp里有没有创建srt文件，里面有没有内容，删掉里面的所有内容，再试试

**Comment by 2922832737C** [comment]
我刚把那个里边的删除之后就好了，现在又有一个新的问题，语音也已经改成相应的，但是这个视频不会播放了，他定格在开始，一直到语音结束

**Comment by jianchang512** [comment]
晚上更新个新版本，再试试

**Comment by 2922832737C** [comment]
好的，感谢

**Comment by admin888-byte** [comment]
chatgpt的api接口地址用的是哪个，求问各位大佬

**Comment by jianchang512** [comment]
> chatgpt的api接口地址用的是哪个，求问各位大佬

官方，或者第三方很多。chat.swoole.com

**Comment by admin888-byte** [comment]
谢谢回复，我用的官方的，但不确认您开发的这个软件是对应chatgpt官方的哪个api接口，官方接口众多，麻烦能发下调用官方的具体api地址吗

**Comment by jianchang512** [comment]
> 谢谢回复，我用的官方的，但不确认您开发的这个软件是对应chatgpt官方的哪个api接口，官方接口众多，麻烦能发下调用官方的具体api地址吗

https://api.openai.com/v1
