### ISSUE TITLE
audio and video footage does not match!! 另外，请在Gemini-Pro和Gemini-1.5-Pro前添加Gemini-1.5-Flash模型，因为每当我尝试保存Gemini-1.5-Flash时，它都无法保存，我不得不一次又一次地重新添加。

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#501]
i am using  windows platform and audio and video does not match in videotrans 2.25 in 2.20 and 2.21 version audion and video was matching as long as video lenghth  was speed to match audio length in capcut on speed pannel, my videos only use video slow function because i am dubbing in english from chinese. please fix this !!

also add gemini-1.5-flash model Infront of gemini-pro and gemini-1.5-pro because whenever i try to save  gemini-1.5-flash  it doesn't get saved and i have to put it again and again.

我正在使用Windows平台，VideoTrans 2.25版本中的音频和视频不同步，而在2.20和2.21版本中，只要在CapCut的速度面板上调整视频长度以匹配音频长度，音频和视频是同步的。我的视频只使用视频减速功能，因为我正在将中文配音翻译成英文。请修复这个问题！

另外，请在Gemini-Pro和Gemini-1.5-Pro前添加Gemini-1.5-Flash模型，因为每当我尝试保存Gemini-1.5-Flash时，它都无法保存，我不得不一次又一次地重新添加。

**Comment by jianchang512** [comment]
Gemini model save issue udpate to v2.27


The video slowdown issue tests fine, and this has not been adjusted for these releases and should not have changed
