### ISSUE TITLE
YouTube视频无法下载

### ISSUE THREAD

**Issue by taiguguai** [jianchang512/pyvideotrans#505]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。

**复现步骤**
1. 使用的哪个功能
2. faster模式/openai模式？
3. 使用的模型名

**操作系统**
 - Windows/Linux/MacOS

**软件左上角版本号数字**

**Comment by jianchang512** [comment]
？什么叫无法下载
点击后无反应？
下载中出错？
源码部署还是预打包版？
操作系统？

https://pyvideotrans.com/youtube.html
