### ISSUE TITLE
1 bug with cli.py

### ISSUE THREAD

**Issue by tzf-omkey** [jianchang512/pyvideotrans#51]
get_large_audio_transcriptioncli函数在检查srt字幕文件是否存在时，有判断逻辑错误。

[fix]
if os.path.exists(sub_name) or os.path.getsize(sub_name) == 0:
VVVV
if not os.path.exists(sub_name) or os.path.getsize(sub_name) <= 0:

**Comment by jianchang512** [comment]
thanks
