### ISSUE TITLE
Mac 一直出现这个报错

### ISSUE THREAD

**Issue by LeonRui** [jianchang512/pyvideotrans#513]
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d2/05/e6600db80270777c4a64238a98d442f0fd07cc8915be2a1c16da7f2b9e74/sympy-1.12-py3-none-any.whl (5.7 MB)
ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 6.0.0 Requires-Python >=3.6, <3.10; 6.0.1 Requires-Python >=3.6, <3.10; 6.0.2 Requires-Python >=3.6, <3.10; 6.0.3 Requires-Python >=3.6, <3.10; 6.0.4 Requires-Python >=3.6, <3.10; 6.1.0 Requires-Python >=3.6, <3.10; 6.1.1 Requires-Python >=3.6, <3.10; 6.1.2 Requires-Python >=3.6, <3.10; 6.1.3 Requires-Python >=3.6, <3.10
ERROR: Could not find a version that satisfies the requirement tbb==2021.11.0 (from versions: 2018.0.4.1, 2019.0, 2021.1.1, 2021.2.0, 2021.3.0, 2021.4.0, 2021.5.0, 2021.6.0, 2021.7.0, 2021.7.1, 2021.8.0, 2021.9.0, 2021.10.0)
ERROR: No matching distribution found for tbb==2021.11.0

关键我改成python3.8之后，又有新的python版本冲突，说要大于等于3.9版本

**Comment by LeonRui** [comment]
pip install -r mac-requirements.txt --no-deps
pip install -r mac-requirements.txt  --ignore-installed --no-deps
运行了这两个代码都不行

**Comment by jianchang512** [comment]
使用 python3.10版本
打开 requirements.txt。删掉  `tbb` 这行

**Comment by supercar280** [comment]
(venv) lutter@lutterdeMacBook-Air pyvideotrans % pip install -r mac-requirements.txt  --ignore-installed --no-deps
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'mac-requirements.txt'
(venv) lutter@lutterdeMacBook-Air pyvideotrans %

**Comment by jianchang512** [comment]
use requirements.txt
