### ISSUE TITLE
2.32调用本地OLLama错误..

### ISSUE THREAD

**Issue by 487306** [jianchang512/pyvideotrans#514]
在Chatbox上和终端是能正常调用的.但是在软件是测试无法连接.
![Snipaste_2024-08-22_09-17-33](https://github.com/user-attachments/assets/54b477f1-48d4-446e-9db9-93523504922c)
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。

**复现步骤**
1. 使用的哪个功能
2. faster模式/openai模式？
3. 使用的模型名

**操作系统**
 - Windows/Linux/MacOS

**软件左上角版本号数字**

**Comment by jianchang512** [comment]
填写  `http://localhost:11434/v1` 试试

**Comment by 487306** [comment]
加上v1后测试通过了..感谢!
