### ISSUE TITLE
can you add transcription using gemini api in the pyvideotrans ?

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#515]

**Comment by jianchang512** [comment]
![image](https://github.com/user-attachments/assets/fe644dce-c7a1-4511-8853-cea2d6891c72)

**Comment by abhijeet12s** [comment]
> ![image](https://private-user-images.githubusercontent.com/3378335/360559082-fe644dce-c7a1-4511-8853-cea2d6891c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTA2NzgsIm5iZiI6MTcyNDM1MDM3OCwicGF0aCI6Ii8zMzc4MzM1LzM2MDU1OTA4Mi1mZTY0NGRjZS1jN2ExLTQ1MTEtODg1My1jZWEyZDY4OTFjNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMTgxMjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZmNmZjNDY5MjQ3ZDgxNDgzNTdkNWUzNGZiZjJkYTIyY2NiZGU2YThjYWVhYmZhNDRkNDc1MzRiZjk1YzE1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8kWHqkFClvwseIR8UNzu0S23dyunQTvd1uYQpm1MA4s)

"No, I don't mean translation. I want to convert speech to text using Gemini Transcription." , “不，我不是指翻译。我想用Gemini Transcription将语音转换为文本。”

**Comment by jianchang512** [comment]
convert speech to text using Gemini Transcription

where Gemini document?

ocr  https://github.com/YaoFANGUK/video-subtitle-extractor

**Comment by abhijeet12s** [comment]
> Owner

YaoFANGUK / video-subtitle-extractor doesent work properly it misses lot of subtitles maybe it can be solved using different ocr library ?

**Comment by jianchang512** [comment]
The ocr recognition of hard subtitles in video is more complex and the project is also larger, at present there is no energy to get a separate project. Suggested to mention ISSUE in YaoFANGUK / video-subtitle-extractor project.
