### ISSUE TITLE
cosyvoice设置 使用9880端口测试api报错，无法使用自定义音色

### ISSUE THREAD

**Issue by beavermarine** [jianchang512/pyvideotrans#516]
**出错信息**
配置cosyvoice的设置中，点击测试api如图报错。
![852](https://github.com/user-attachments/assets/63fac38f-e6c2-46b5-9183-07cc9f16b253)
按说明添加角色后无法使用
服务端报错：TypeError: unhashable type: 'dict'
INFO:werkzeug:127.0.0.1 - - [23/Aug/2024 01:52:55] "POST / HTTP/1.1" 500 -

**复现步骤**
1.打开配置cosyvoice页面.
2.填写配置，点击测试api按钮
3.提示错误。
使用v3ucn的0819整合包，使用postman测试api正常
测试url：http://127.0.0.1:9880/?text=text，1，2，3。&speaker=（自定义音色名）&new=1

**操作系统**
 - Windows 10

**软件左上角版本号数字**
2.32

**Comment by jianchang512** [comment]
为什么想到填写 37.pt，按要求使用

**Comment by beavermarine** [comment]
> 为什么想到填写 37.pt，按要求使用

试过填写角色名，角色名.pt均报错。

**Comment by beavermarine** [comment]
该项留空，点击测试api仍然报相同错误。

**Comment by jianchang512** [comment]
你用的是那个cospyvoice的windows整合包吧，先去搞明白那个整合包的api如何使用、如何填写角色名，然后再这里使用

角色名需要填写整合包支持的名称。

**Comment by beavermarine** [comment]
> 你用的是那个cospyvoice的windows整合包吧，先去搞明白那个整合包的api如何使用、如何填写角色名，然后再这里使用
> 
> 角色名需要填写整合包支持的名称。

使用整合包，不论自定义角色还是预训练角色都可以在postman跑通。在本软件只有预设角色可以使用，使用自定义角色时报上述unhashable错误。
同时端口只要是9880点测试api就会报上图错误。是否需要我把各种情况都截成图发过来？
ps，该包在0721版有一次修复api的改动，自定义角色需添加new=1才能使用，不知道你是否知晓？

**Comment by jianchang512** [comment]
发一个postman上成功的 请求参数信息、返回参数信息 完整截图

上图报错时，api终端黑窗口的输出信息完整截图

**Comment by beavermarine** [comment]
这是postman截图及api信息，
![100](https://github.com/user-attachments/assets/554eb294-2f58-4e50-ae29-da6f173933e2)
![101](https://github.com/user-attachments/assets/e444d10f-4025-4298-8ccc-36d8cb1e2282)
这是点击api测试后的截图，
![102](https://github.com/user-attachments/assets/6741f5a6-040e-4260-b126-16832a72a096)
这是保存的设置以及点击自定义音色配音试听后的截图，
![104](https://github.com/user-attachments/assets/f23e5729-9193-4d8a-8901-afb30bd2fdd8)
![103](https://github.com/user-attachments/assets/55eab63a-1da3-480c-b53b-f9dc094506ae)
附0819整合包内自带的post_api测试文件及api端截图，经测试可正常生成。
![105](https://github.com/user-attachments/assets/165cd37e-6750-4c7c-9c27-ab83b348879f)
![106](https://github.com/user-attachments/assets/20954332-7f9d-40aa-ab1a-5efa9035cedb)

**Comment by jianchang512** [comment]
![image](https://github.com/user-attachments/assets/1562f8e4-68ab-4ba4-9857-fc19d1599ec5)

这个去掉 "new":1 和 "streaming":1 ，试试还能成功吗

**Comment by beavermarine** [comment]
同时去掉两项
![107](https://github.com/user-attachments/assets/d73a2fe8-5c1b-46ff-908a-8f2c051314c3)
去掉new
![108](https://github.com/user-attachments/assets/a45ab386-7799-41e1-87bf-8f3ba9b787b3)
去掉streaming
![109](https://github.com/user-attachments/assets/ca679975-c5d1-49b8-94d2-f9970c597b1d)

**Comment by jianchang512** [comment]
也就是自定义角色时必须添加 `"new":1` 对吧

**Comment by beavermarine** [comment]
> 也就是自定义角色时必须添加 `"new":1` 对吧

我不是计算机相关从业人员，对这些不太了解。建议您找整合包作者沟通相关问题。

**Comment by jianchang512** [comment]
升级到2.35试试

**Comment by beavermarine** [comment]
> 升级到2.35试试

使用2.35， 2.36与2.37，仍报相同错误。
![180](https://github.com/user-attachments/assets/10296bf7-21ac-4b6d-b3c9-f90f3773e210)

**Comment by beavermarine** [comment]
> 重新测试下，然后将翻译软件目录下logs文件夹中最新的log文件上传

[video-20240827.log](https://github.com/user-attachments/files/16756673/video-20240827.log)

**Comment by jianchang512** [comment]
试听时要选择目标语言啊

**Comment by beavermarine** [comment]
> 试听时要选择目标语言啊

使用预设角色试听配音如图，
![190](https://github.com/user-attachments/assets/fd2e50b3-b73b-4e77-924c-369e0a04df3c)
使用自定义角色试听配音如图，
![191](https://github.com/user-attachments/assets/4f8bf529-c3cf-4287-a42e-5c50ac20db33)
附log，
[video-20240827.log](https://github.com/user-attachments/files/16758648/video-20240827.log)

**Comment by beavermarine** [comment]
使用2.38，仍报错，如图

![782](https://github.com/user-attachments/assets/05206367-3624-4fd2-9a86-af681b4d9fd9)

**Comment by jianchang512** [comment]
1. 点的哪里测试的
2. 菜单-设置 cosyvoice如何填写的

**Comment by jianchang512** [comment]
直接点击主界面中的“试听配音”试试
