### ISSUE TITLE
pyvideotrans 2.34 is not printing progress of translating , transcribing, and because of that if there is sudden error happens ! i cannot copy progress .....................⬇️⬇️⬇️⬇️⬇️⬇️⬇️

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#518]
Problem:
1 )No Progress Display: The current version of pyvideotrans (2.34) doesn't print or display the progress of tasks like translating and transcribing in its interface.
2) Impact of Errors: Because the progress isn't being shown, if an error occurs suddenly during the process, you can't see how far the task has progressed or what specifically has been done up until the error.
3) Time Wasted: You're forced to wait until the entire process (which can take up to an hour) is complete to find out if there were any mistakes in my work or script. In previous versions, the software would print out the tasks it had completed in real-time, allowing you to monitor progress and catch errors as they happened.
4) No Text Output: The lack of real-time updates in the small window of the software means you can't copy or review the progress if something goes wrong. Previously, this wasn't an issue because the software would display the work it had done in the panel as it progressed.  

问题:
1) **没有进度显示**：当前版本的 pyvideotrans (2.34) 不会在界面中打印或显示翻译和转录等任务的进度。
2) **错误的影响**：由于进度没有显示，如果在过程中突然发生错误，你无法看到任务已经进行到什么程度或具体完成了哪些内容。
3) **时间浪费**：你不得不等待整个过程（可能长达一小时）完成后，才能发现工作或脚本中是否有错误。在以前的版本中，软件会实时打印它已经完成的任务，这样你就可以监控进度并在出现错误时及时发现。
4) **没有文本输出**：软件的小窗口中缺乏实时更新，意味着如果出现问题，你无法复制或查看进度。以前这不是问题，因为软件会在其面板中显示已完成的工作内容。

**Comment by abhijeet12s** [comment]
my main issue is because gemini api  stops translating out nowhere sometimes. i copy progress done and start translating whats not done. and now i cant do that!

**Comment by jianchang512** [comment]
this?
![image](https://github.com/user-attachments/assets/871c7903-31b7-4356-90fa-e7725252cf8f)



The current small window has not yet been added to the progress, if you just recognize it, you can first use the 

![image](https://github.com/user-attachments/assets/66d3ba2b-86cc-495d-a91a-f66ddb4e291a)

**Comment by jianchang512** [comment]
update to 2.35
