### ISSUE TITLE
英文视频提取字幕缺少了一部分

### ISSUE THREAD

**Issue by boystray** [jianchang512/pyvideotrans#519]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。
提取的字幕，第一段时间是00:00:07,130 --> 00:00:10,而第二段时间是00:00:43,290 --> 00:00:48,040，中间缺失了30秒钟的字幕。

2024-08-25 06:18:22,283 - VideoTrans - INFO - Start speech recognition
INFO:VideoTrans:Start speech recognition
[2024-08-25 06:18:23.509] [ctranslate2] [thread 14791] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
INFO:faster_whisper:Processing audio with duration 04:28.190
INFO:faster_whisper:VAD filter removed 00:45.628 of audio
DEBUG:faster_whisper:VAD filter kept the following audio segments: [00:07.132 -> 00:10.916],###  **[00:11.548 -> 00:13.284], [00:14.652 -> 00:16.932], [00:17.148 -> 00:19.300], [00:19.580 -> 00:21.764], [00:21.980 -> 00:24.100], [00:24.380 -> 00:29.060], [00:29.500 -> 00:29.988],** [00:30.652 -> 00:35.524], [00:35.804 -> 00:37.860], [00:38.012 -> 00:39.492], [00:41.084 -> 00:44.868], [00:45.372 -> 00:49.092], [00:49.212 -> 00:51.236], [00:51.516 -> 00:55.716], [00:55.868 -> 01:05.988], [01:06.364 -> 01:09.188], [01:09.468 -> 01:11.172], [01:11.484 -> 01:12.356], [01:12.572 -> 01:13.476], [01:13.596 -> 01:14.948], [01:15.068 -> 01:17.124], [01:18.108 -> 01:22.916], [01:23.004 -> 01:26.276], [01:26.684 -> 01:27.460], [01:27.708 -> 01:34.436], [01:34.780 -> 01:36.932], [01:37.180 -> 01:42.948], [01:43.292 -> 01:44.676], [01:44.828 -> 01:48.036], [01:48.316 -> 01:52.292], [01:52.540 -> 01:54.756], [01:55.196 -> 01:57.924], [01:58.172 -> 01:59.140], [01:59.644 -> 02:00.356], [02:01.020 -> 02:03.844], [02:03.932 -> 02:06.116], [02:06.588 -> 02:07.492], [02:08.444 -> 02:09.412], [02:12.444 -> 02:16.324], [02:17.500 -> 02:18.596], [02:18.780 -> 02:20.324], [02:20.796 -> 02:22.692], [02:23.228 -> 02:25.796], [02:26.076 -> 02:28.452], [02:28.668 -> 02:41.476], [02:41.756 -> 02:44.932], [02:45.084 -> 02:49.028], [02:49.116 -> 02:52.772], [02:52.892 -> 02:56.516], [02:56.732 -> 03:00.580], [03:03.068 -> 03:08.004], [03:08.188 -> 03:11.908], [03:12.828 -> 03:17.092], [03:17.212 -> 03:23.236], [03:23.420 -> 03:25.828], [03:26.044 -> 03:32.708], [03:32.828 -> 03:33.828], [03:34.716 -> 03:36.228], [03:40.828 -> 03:42.180], [03:42.268 -> 03:44.004], [03:44.252 -> 03:46.980], [03:47.132 -> 03:51.012], [03:51.484 -> 03:58.564], [03:58.876 -> 04:01.700], [04:01.916 -> 04:03.012], [04:03.260 -> 04:05.412], [04:05.692 -> 04:08.996], [04:09.340 -> 04:10.788], [04:11.772 -> 04:14.436], [04:14.972 -> 04:18.532], [04:18.684 -> 04:23.428], [04:26.108 -> 04:28.190]
DEBUG:faster_whisper:Processing segment at 00:00.000
2024-08-25 06:18:27,780 - VideoTrans - INFO - 1
00:00:07,130 --> 00:00:10,630
Not being able to communicate is so frustrating and demoralizing.

**INFO:VideoTrans:1
00:00:07,130 --> 00:00:10,630**
Not being able to communicate is so frustrating and demoralizing.

2024-08-25 06:18:27,780 - VideoTrans - INFO - subtitles Line  1
INFO:VideoTrans:subtitles Line  1
DEBUG:faster_whisper:Processing segment at 00:30.000
**2024-08-25 06:18:29,353 - VideoTrans - INFO - 2
00:00:43,290 --> 00:00:48,040**
called Brigade 2. The idea is people living with conditions like

INFO:VideoTrans:2
00:00:43,290 --> 00:00:48,040
called Brigade 2. The idea is people living with conditions like
**复现步骤**
1. 使用的哪个功能 视频提取字幕，因为原始英文字母缺少了一段，导致后面翻译成中文，也缺少了一段。
2. faster模式/openai模式？ faster
3. 使用的模型名 tiny

**操作系统**
 - Windows/Linux/MacOS
linux
**软件左上角版本号数字**

**Comment by jianchang512** [comment]
尝试使用 small  medium large等更大的模型，tiny是最小模型，精确度也最差

**Comment by boystray** [comment]
好，用largeV3Model试试

**Comment by boystray** [comment]
换成large v3就可以了。
