### ISSUE TITLE
某次更新之后，YouTube下载器就不能用了

### ISSUE THREAD

**Issue by taiguguai** [jianchang512/pyvideotrans#520]
某次更新之后，YouTube下载器就不能用了，永远都是超时无响应

**Comment by jianchang512** [comment]
更新到2.36版本是可以的
注意youtube现在反爬严格，很多机场节点是无法下载的，会要求登录，提示会是无响应或400错误

**Comment by taiguguai** [comment]
更新2.37后，可以正常使用了
