### ISSUE TITLE
建议：是否考虑增加 自定义STT API 功能？

### ISSUE THREAD

**Issue by thomas19940617** [jianchang512/pyvideotrans#524]
需求背景：
虽然软件内置faster模式（small、medium、large）、openai模式、googlespeech模式、zh_recogn中文模式、豆包模型识别。但是在使用中发现各有缺陷。因此想使用一些其他平台的ASR API。

需求描述：
希望可以增加自定义ASR API 功能，感谢

**Comment by jianchang512** [comment]
已实现
