### ISSUE TITLE
im trying install in another PC windows 10 with CUDA

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#528]
I install and setup all, but when i want to use, show me this:

![SNAG-0127](https://github.com/user-attachments/assets/99108fbf-d332-44f3-b96f-a2205a41c4c8)

how solve this issue?

**Comment by jianchang512** [comment]
This is not a bug, if you want to use openaiTTS, then you need to fill in the Openai chatgpt information, in the menu - Settings.

**Comment by johnfelipe** [comment]
I need only transcribe and translate, then which one need to select?

**Comment by jianchang512** [comment]
If you don't want a voiceover, set the voiceover character to No.
If you want to use 
openaitts dub, you have to set the OpenAI related sk in Menu - Settings - OpenAI.

**Comment by johnfelipe** [comment]
solved
