### ISSUE TITLE
啥时候能弄双语字幕

### ISSUE THREAD

**Issue by martjay** [jianchang512/pyvideotrans#529]
就纯中文字幕有时候不准，所以想弄双语字幕，弄不了吗现在？
还有就是想弄两个逗号或者标点符号一段字幕，一个逗号太短了字幕跳太快。

**Comment by jianchang512** [comment]
字幕嵌入类型中选择带“双”字的

**Comment by martjay** [comment]
> 字幕嵌入类型中选择带“双”字的

那字幕怎么弄长一点呢

**Comment by jianchang512** [comment]
单行长度？菜单-工具-高级选项--找到调整
![image](https://github.com/user-attachments/assets/2b977108-4ac7-4a12-9544-c7046acb30cb)

**Comment by martjay** [comment]
> 单行长度？菜单-工具-高级选项--找到调整 ![image](https://private-user-images.githubusercontent.com/3378335/363477836-2b977108-4ac7-4a12-9544-c7046acb30cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODA5MDksIm5iZiI6MTcyNTE4MDYwOSwicGF0aCI6Ii8zMzc4MzM1LzM2MzQ3NzgzNi0yYjk3NzEwOC00YWM3LTRhMTItOTU0NC1jNzA0NmFjYjMwY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMDg1MDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzIxMzIzZThjODFmZWZhZTVmODRlMjY3ZjZhOTI1NjZjZWJjNzJjN2RlNjM3NDg0YzM3YzE4ZWZkODU4Y2YzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YFmgchk_MrrAFc-LNnkezLcFw42i1hpjMwmP2BS86yY)

字幕嵌入类型 好像是嵌入视频的 但是我想要的是双语字幕srt

**Comment by martjay** [comment]
就是说翻译出来直接是双语字幕

**Comment by martjay** [comment]
这个好像是srt文件也无法调整单行长度，希望能加入通过几个标点符号分段的选项

**Comment by jianchang512** [comment]
只有嵌入硬字幕时才可同时显示双语，上下两行，一行一种语言。软字幕嵌入无固定长度，播放器自动断行，软字幕时只可同时显示一种语言的

如果你想软字幕也像硬字幕一样上下两种语言，可使用菜单-工具-合并两个字幕，然后手动使用  音视频字幕合并 功能嵌入

**Comment by martjay** [comment]
> 只有嵌入硬字幕时才可同时显示双语，上下两行，一行一种语言。软字幕嵌入无固定长度，播放器自动断行，软字幕时只可同时显示一种语言的
> 
> 如果你想软字幕也像硬字幕一样上下两种语言，可使用菜单-工具-合并两个字幕，然后手动使用 音视频字幕合并 功能嵌入

2.33没有看到在工具选项看到合并字幕的功能

**Comment by jianchang512** [comment]
2.40

**Comment by martjay** [comment]
> 更新 2.40

OK，用了感觉还行，但是很麻烦啊，不能直接把双语字幕直接整合到翻译字幕里面吗，比如说目标语言加双语选项，不然你提取完输出一个目录，翻译后输出另一个目录，然后手动一个个选，管理员身份是没法拖拽文件的，合并后又输出了一个新目录，太麻烦了，这是我之前用过的一个软件，这个就是直接输出双语字幕的，也许你能有一点想法吧。

https://github.com/1c7/Translate-Subtitle-File

**Comment by martjay** [comment]
而且他这个还支持自定义术语库，就是比如说翻译完字幕后会根据你写的术语替换错词。

**Comment by jianchang512** [comment]
现在最新版本不论是软字幕还是硬字幕，选中“双”后都是同时显示2种语言字幕，上下两行，你试下就知道了，嵌入字幕类型选择带双字的

**Comment by martjay** [comment]
> 现在最新版本不论是软字幕还是硬字幕，选中“双”后都是同时显示2种语言字幕，上下两行，你试下就知道了，嵌入字幕类型选择带双字的

我没有在翻译页面的目标语言看到有“双”

**Comment by jianchang512** [comment]
批量翻译字幕 功能是不可以的，这仅仅是单纯翻译而已。
