### ISSUE TITLE
日志输出界面会一直有输出

### ISSUE THREAD

**Issue by TimeVfx** [jianchang512/pyvideotrans#53]
1.字幕编辑的时候会一直输出 “等待修改字幕”
 2. 在右边修改字幕的时候，右边每输入一个字符  左边输出框就会输出“等待编辑字幕(点击继续合成)”  
 

这条可以酌情修改
如果一开始没有选择配音角色，等待生成完字幕后，在右边编辑完字幕，再选择配音角色 然后再点”继续合成“，最终结果不会有配音，还是原始的音频

![image](https://github.com/jianchang512/pyvideotrans/assets/49233971/75971f09-61ba-4db7-80c0-89b28608f815)

**Comment by jianchang512** [comment]
日志输出是为了提醒可以合成，这个有点太多了，可以减少点

开始之后，所有选项都已经确定了，不可再更改了，当前开始后没有禁用，后续会禁用
