### ISSUE TITLE
批量字幕配音 问题

### ISSUE THREAD

**Issue by skysun329** [jianchang512/pyvideotrans#530]
您好！批量字幕配音，生成的音频文件只有几秒钟长，似断断续续的杂音，请问如何正确设置使用程序？谢谢！

**Comment by dangehub** [comment]
我也遇见这个问题了,一键操作的时候，配音是正常的.但是只要用字幕配音，就会出现这个问题

**Comment by jianchang512** [comment]
使用的哪个配音渠道？

**Comment by beavermarine** [comment]
在使用cosyvoice时出现相同问题。

**Comment by dangehub** [comment]
> 应该和所选配音渠道油管，使用的哪个配音渠道，如果不是edgeTTS，就试试使用这个

edgetts和cosyvoice都有同样问题，tmp文件夹里切片和最后整合都有，但是tts文件夹内只有一个空音频。

**Comment by jianchang512** [comment]
删掉 logs文件夹内所有文件，然后重新测试一个，结束时将 logs内新生成的文件上传

**Comment by jianchang512** [comment]
更新 2.41 补丁覆盖 https://github.com/jianchang512/pyvideotrans/releases/download/v2.40/win-PatchUpdate-2.41.7z

**Comment by dangehub** [comment]
> 更新 2.41 补丁覆盖 https://github.com/jianchang512/pyvideotrans/releases/download/v2.40/win-PatchUpdate-2.41.7z

感谢您的工作，我升级后此bug已修复！

**Comment by skysun329** [comment]
谢谢您！
----- 原始邮件 -----
发件人：dangehub ***@***.***>
收件人：jianchang512/pyvideotrans ***@***.***>
抄送人：skysun329 ***@***.***>,  Author ***@***.***>
主题：Re:_[jianchang512/pyvideotrans]_批量字幕配音_问题_(Issue_#530)
日期：2024年09月01日 18点06分



更新 2.41 补丁覆盖 https://github.com/jianchang512/pyvideotrans/releases/download/v2.40/win-PatchUpdate-2.41.7z

感谢您的工作，我升级后此bug已修复！

**Comment by skysun329** [comment]
谢谢您！
----- 原始邮件 -----
发件人：okmyworld ***@***.***>
收件人：jianchang512/pyvideotrans ***@***.***>
抄送人：skysun329 ***@***.***>,  Author ***@***.***>
主题：Re:_[jianchang512/pyvideotrans]_批量字幕配音_问题_(Issue_#530)
日期：2024年09月01日 17点27分


更新 2.41 补丁覆盖 https://github.com/jianchang512/pyvideotrans/releases/download/v2.40/win-PatchUpdate-2.41.7z
