### ISSUE TITLE
2.47使用自定义本地API连接报错，切换回2.43又都能正常使用。

### ISSUE THREAD

**Issue by Veer8** [jianchang512/pyvideotrans#535]
**出错信息**
![2024-09-09_210720](https://github.com/user-attachments/assets/67061db6-2fdd-4633-ad91-699149498dbf)
![2024-09-09_211756](https://github.com/user-attachments/assets/bc46f542-1e60-4a66-bbbf-1f8e0fc0ba80)

2.47使用自定义本地API连接报错，切换回2.43又都能正常使用。

**复现步骤**
chatgpt及兼容api
本地兼容openai大模型翻译
自定义翻译api

**操作系统**
 - Windows

**软件左上角版本号数字**
2.47

**Comment by NoclubOIRzXx** [comment]
我去，一样。我还以为我的问题，一直试到现在。其他例如LobeChat和沉浸式翻译都没问题。

**Comment by 15921483570** [comment]
> **出错信息** ![2024-09-09_210720](https://private-user-images.githubusercontent.com/22994000/365662972-67061db6-2fdd-4633-ad91-699149498dbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDQ3NjksIm5iZiI6MTcyNjA0NDQ2OSwicGF0aCI6Ii8yMjk5NDAwMC8zNjU2NjI5NzItNjcwNjFkYjYtMmZkZC00NjMzLWFkOTEtNjk5MTQ5NDk4ZGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA4NDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YjZhM2ZiNDhiMjRiNGYzYmVkZTI4YjdjMGQwMmVkYjAwYzZlZDczYjY3M2YxYjcwZWQ1YzBhOWE3MjA1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6pIBTNe4b80Q0Cd6wN2CV3iO0hiHYYwwyvB396JMrxo) ![2024-09-09_211756](https://private-user-images.githubusercontent.com/22994000/365665641-bc46f542-1e60-4a66-bbbf-1f8e0fc0ba80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDQ3NjksIm5iZiI6MTcyNjA0NDQ2OSwicGF0aCI6Ii8yMjk5NDAwMC8zNjU2NjU2NDEtYmM0NmY1NDItMWU2MC00YTY2LWJiYmYtMWY4ZTBmYzBiYTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA4NDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZmY4MzMxYjBjNTlhM2MxMmYyNDUwMTRlYTU1YmM0MmM2MWQxZDRkNjM1N2JkODM0OWJiNWIyYzQyYmJjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRS-EHuH6phHuYycffNbQyHFVx2Ewuft003KtGhzS0U)
> 
> 2.47使用自定义本地API连接报错，切换回2.43又都能正常使用。
> 
> **复现步骤** chatgpt及兼容api 本地兼容openai大模型翻译 自定义翻译api
> 
> **操作系统**
> 
> * Windows
> 
> **软件左上角版本号数字** 2.47

感谢老哥，我下了2.43，现在正常了@Veer8

**Comment by jianchang512** [comment]
下版修复

**Comment by NoclubOIRzXx** [comment]
> 下版修复

大佬还是没用 已经感谢了，下的2.48完整包
![oe35trgc pqp](https://github.com/user-attachments/assets/c6fd3832-857b-41bd-a5f6-4481707c63bf)
[20240913.log](https://github.com/user-attachments/files/16989201/20240913.log)

**Comment by jianchang512** [comment]
2.49包覆盖下。代理设置问题。

**Comment by NoclubOIRzXx** [comment]
> 2.49包覆盖下。代理设置问题。

2.50版本问题解决了
