### ISSUE TITLE
API调用翻译设置100行，到后面提交时候就1行1行提交了

### ISSUE THREAD

**Issue by microbabywe** [jianchang512/pyvideotrans#537]
我用阿里的通译千问，API调用翻译设置的是100行，一开始正常的，到后面提交时候就1行1行提交了，用deepseek好像就不会
翻译还有错行的问题。。。今天有个1个半小时的字幕，前后交错了。

**Comment by jianchang512** [comment]
在翻译时，默认trans_thread=15，即15行字幕同时发给翻译引擎进行翻译，某些比较智能的翻译引擎，比如AI ChatGPT DeepL等，会根据语义优化翻译，结果就导致给它是15行原始文本，返回的并不会是对应的15行翻译结果，可能会是 14行 13行甚至更少。

当不对应时,会重新一行一行翻译。
