### ISSUE TITLE
How to connect to ollama run local http://localhost:11434

### ISSUE THREAD

**Issue by emourdavid** [jianchang512/pyvideotrans#539]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。
![image](https://github.com/user-attachments/assets/4e9fa4c3-a6ab-459b-99e0-90c4f1dc89a7)

**复现步骤**
Translate Channel : i want to use ollama running on local http://localhost:11434 but dont know how to connect from your app

**操作系统**
 - Windows: v2.47

**软件左上角版本号数字**

**Comment by jianchang512** [comment]
`http://localhost:11434/v1 `
