### ISSUE TITLE
设置家目录不起作用

### ISSUE THREAD

**Issue by yqsphp** [jianchang512/pyvideotrans#543]
**出错信息**
![1726200477895](https://github.com/user-attachments/assets/69f2adc7-4f53-4559-b657-a47225bdf614)

**复现步骤**
1. 使用菜单【工具/选项】-》【高级选项】设置家目录不起做用

**操作系统**
 - Windows 100

**软件左上角版本号数字**
v2.48

**Comment by jianchang512** [comment]
已修复
