### ISSUE TITLE
极不合理的设计-合并功能

### ISSUE THREAD

**Issue by taiguguai** [jianchang512/pyvideotrans#544]
所有的合并功能都要求文件名称一致，我相信作者没有真正的做过大量的翻译工作，在合并前，原文字幕会有很多个版本，甚至原视频也会被拆分为很多个版本，那么现在使用软件还必须将版本之间进行对齐，这无形中增加了工作量，为什么不能像之前一样，自行选择原视频和字幕文件呢，建议作者考量。

**Comment by jianchang512** [comment]
“批量视频和字幕合并”这是新增的功能，以前是没有这功能的，何来“不能像之前一样”？

之前该怎样操作还怎样操作，觉得这个功能不合理，不使用这个功能，还使用以前操作不就就行了


以前只有单个视频和单个字幕合并功能，可以自己选择视频和字幕，现在依然有这个功能“音视频字幕合并”


批量操作必然要求有命名规则，不然程序怎么知道谁和谁合并，自行选择只能一次合并一个视频和字幕。
