### ISSUE TITLE
第三方代理的openai报错

### ISSUE THREAD

**Issue by Doutianbao** [jianchang512/pyvideotrans#56]
文字识别和翻译出错：list index out of range

链接是：代理网址/v1.    平时使用其它服务都没有问题
语音模型是base或者small.

难道是高并发导致罢工了？

有用第三方代理的openai成功的大佬吗？
![image](https://github.com/jianchang512/pyvideotrans/assets/25342342/91d7690c-6525-4bd4-9641-7c65fbe8818b)

**Comment by Doutianbao** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/25342342/0cab4239-9b37-4156-812b-a6a2da6980b8)
deeplx也报错，地址和沉浸式翻译插件里填写的一样，翻译插件能够注册使用

**Comment by Doutianbao** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/25342342/982f257f-eb87-4b80-953d-1eef75472252)

baidu(nokey)的情况= =

**Comment by Doutianbao** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/25342342/61303b07-be94-4367-918a-f2b2de2a661c)


感动，Google saves me :)

**Comment by jianchang512** [comment]
地方的api地址要分别测试 带 /v1 和不带 /v1 的地址

至于末尾是否带，要看具体三方的设计，无法确定

**Comment by jianchang512** [comment]
> ![image](https://user-images.githubusercontent.com/25342342/283498216-0cab4239-9b37-4156-812b-a6a2da6980b8.png) deeplx也报错，地址和沉浸式翻译插件里填写的一样，翻译插件能够注册使用

具体填写的什么地址，发下

**Comment by jianchang512** [comment]
> ![image](https://user-images.githubusercontent.com/25342342/283498216-0cab4239-9b37-4156-812b-a6a2da6980b8.png) deeplx也报错，地址和沉浸式翻译插件里填写的一样，翻译插件能够注册使用


deepl有2个，一个是DeepL,一个是DeepLX,后者是需要自己部署在自己电脑上的，两回事。沉浸式翻译不支持DeepLX，只支持DeepL

**Comment by Doutianbao** [comment]
> > ![image](https://user-images.githubusercontent.com/25342342/283498216-0cab4239-9b37-4156-812b-a6a2da6980b8.png) deeplx也报错，地址和沉浸式翻译插件里填写的一样，翻译插件能够注册使用
> 
> 具体填写的什么地址，发下
![image](https://github.com/jianchang512/pyvideotrans/assets/25342342/14878c7c-e35c-4b91-ac0d-0fb775ab6153)

地址是https://api.deeplx.org/translate

**Comment by Copy2Translator** [comment]
可能是你的 IP 被 DeepL 限制了，短时间内请求次数太多了吧

**Comment by Doutianbao** [comment]
经过测试。**尽量不要勾选配音自动加速~** 
不然声音（陪饮角色？）会抽

**Comment by Doutianbao** [comment]
> 可能是你的 IP 被 DeepL 限制了，短时间内请求次数太多了吧

DEEPLX

**Comment by Copy2Translator** [comment]
> > 可能是你的 IP 被 DeepL 限制了，短时间内请求次数太多了吧
> 
> DEEPLX

DeepLX 也是白嫖的 DeepL

**Comment by Copy2Translator** [comment]
> > ![image](https://user-images.githubusercontent.com/25342342/283498216-0cab4239-9b37-4156-812b-a6a2da6980b8.png) deeplx也报错，地址和沉浸式翻译插件里填写的一样，翻译插件能够注册使用
> 
> deepl有2个，一个是DeepL,一个是DeepLX,后者是需要自己部署在自己电脑上的，两回事。沉浸式翻译不支持DeepLX，只支持DeepL

如果 DeepLX 无法调整并发，作者这里能不能把请求并发限制一下来缓解这个问题呢，不是很懂这些，随口提一下

**Comment by Doutianbao** [comment]
> > > ![image](https://user-images.githubusercontent.com/25342342/283498216-0cab4239-9b37-4156-812b-a6a2da6980b8.png) deeplx也报错，地址和沉浸式翻译插件里填写的一样，翻译插件能够注册使用
> > 
> > 
> > deepl有2个，一个是DeepL,一个是DeepLX,后者是需要自己部署在自己电脑上的，两回事。沉浸式翻译不支持DeepLX，只支持DeepL
> 
> 如果 DeepLX 无法调整并发，作者这里能不能把请求并发限制一下来缓解这个问题呢，不是很懂这些，随口提一下

我也不是很懂，但是使用翻译插件的请求和并发可能不低于用于视频的翻译，具体为啥用不了还需要麻烦作者大大调试

**Comment by jianchang512** [comment]
被限制了，返回的并不是有效的json格式
deeplx不要使用那个公共节点，自己本地电脑部署。

**Comment by jianchang512** [comment]
是按照字幕一条一条去翻译的，如果一个视频字幕解析后有100条信息，那么就会持续发送100条翻译请求，不会合并为一个，因为字幕内容可能太长，合并发送会超出内容长度

**Comment by Doutianbao** [comment]
> 是按照字幕一条一条去翻译的，如果一个视频字幕解析后有100条信息，那么就会持续发送100条翻译请求，不会合并为一个，因为字幕内容可能太长，合并发送会超出内容长度

原来如此，但是我自己部署的实际体验还不如这个公共节点 :(

**Comment by jianchang512** [comment]
> > 是按照字幕一条一条去翻译的，如果一个视频字幕解析后有100条信息，那么就会持续发送100条翻译请求，不会合并为一个，因为字幕内容可能太长，合并发送会超出内容长度
> 
> 原来如此，但是我自己部署的实际体验还不如这个公共节点 :(

公共节点所有人的请求都是同一个ip，肯定会限制。
我自己部署，感觉还可以
