### ISSUE TITLE
MAIN-2.80 2024-10-16 built in Window11 Exception: list index out of range

### ISSUE THREAD

**Issue by RaidOpe** [jianchang512/pyvideotrans#573]
**Info**
![image](https://github.com/user-attachments/assets/4fd79743-781a-492f-a771-461fd5d2b73f)

**Step**
1. Convert audio to subtitles
2. Use faster or openai
3. base 

**System**
 - Windows11

**2.80**

**Comment by RaidOpe** [comment]
[20241017.log](https://github.com/user-attachments/files/17406573/20241017.log)

**Comment by jianchang512** [comment]
更新到2.80补丁包
