### ISSUE TITLE
打开就报错

### ISSUE THREAD

**Issue by kk84214** [jianchang512/pyvideotrans#578]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。
![新建 BMP 图像](https://github.com/user-attachments/assets/bdebfaf1-90de-407b-a5a4-3f657e134896)

**复现步骤**
昨天晚上还好好的，今天打开就这样了，昨天版本是2.82，看到今天有更新，现在更新到了2.83，还是一样的错误

**操作系统**
 - Windows11

**Comment by jianchang512** [comment]
删除 videotrans/cfg.json 文件，重新打开

**Comment by kk84214** [comment]
感谢大佬！
