### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by popdog0** [jianchang512/pyvideotrans#58]
非常感谢你创建了如此优秀的工具，有两个小小的建议
1.保留原始语言的字幕文件，这个就可以制作双语字幕
2.可选生成带字幕的视频，对太多数人来说，只要有翻译后的字幕文件就够了。

**Comment by jianchang512** [comment]
1. 以前版本搞过双语字幕，有时字幕太长，2个语言版本屏幕占一半，就放弃了，后续可以在目标文件夹srt下存放一个原语言字幕文件
2. 没看懂，现在也可以不生成带字幕视频，意思是：既不需要配音，也不需要嵌入字幕，仅仅是想通过软件生成一个字幕文件？

**Comment by popdog0** [comment]
第2个就是你理解的意思。

**Comment by popdog0** [comment]
看你的发布日志，这两个功能似乎都实现了，但是我试用0.9.3.2版本后，发现没有效果，不知道是不是我用的方法不正确?
这两个功能需要怎么设置参数?

**Comment by jianchang512** [comment]
> 看你的发布日志，这两个功能似乎都实现了，但是我试用0.9.3.2版本后，发现没有效果，不知道是不是我用的方法不正确? 这两个功能需要怎么设置参数?

0.9.4.3 版本

生成结束后，到目标文件夹中，打开视频同名子文件夹，里面会有 两种语言的srt字幕文件
