### ISSUE TITLE
不知道是程序的问题还是DeepL的问题

### ISSUE THREAD

**Issue by steven225** [jianchang512/pyvideotrans#581]
**出错信息**
![image](https://github.com/user-attachments/assets/b4a1ba51-03e1-4705-b683-bc0f7ccb8a48)

人在国外，不用使用代理。我先使用UVR把影片的人声撷取出来成mp3檔，然后使用Fast-whisper本地Large-v3将mp3檔转录出日文字幕来，再来使用批量翻译srt字幕的DeepL翻译成简中时，进行到一半就会出现上图失败的讯息。我发现使用DeepL来翻译其他日文字幕也会遇到相同的问题。不知道是程序的问题，还是DeepL的问题？使用其他翻译渠道（ChatGPT和Google翻译是没问题的）

**复现步骤**
1. 使用的哪个功能：批量翻译srt字幕
2. faster模式/openai模式？Fast-whisper本地
3. 使用的模型名？Large-v3

**操作系统**
 - Windows

**软件左上角版本号数字**
 - 2.84

**Comment by jianchang512** [comment]
上传出错时软件目录下logs文件夹下的最新log文件

**Comment by steven225** [comment]
[20241020.log](https://github.com/user-attachments/files/17450782/20241020.log)
谢谢

**Comment by jianchang512** [comment]
[DeepL]请求数据:data=['ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー', 'ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー'],config.params["deepl_gid"]=''

都是无效字符，无法翻译
