### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by zach106** [jianchang512/pyvideotrans#59]
用deepl 接口，提示str object has not attribute text  然后gbt3.5 提示可能是文本过长，这个怎么解决呀

**Comment by zach106** [comment]
[error]chatGPT 请求失败:'ChatCompletion'
object has no attribute 'code'

**Comment by jianchang512** [comment]
> [error]chatGPT 请求失败:'ChatCompletion' object has no attribute 'code'

第三方接口是吗，分别试试接口末尾加 /v1 和 不加 /v1 试试

**Comment by Bromaomao** [comment]
我试了chatgpt官方接口https://api.openai.com/v1和第三方的接口，报同样的错误：ERROR:VideoTrans:error:list index out of range，但是用谷歌翻译就是正常的

**Comment by jianchang512** [comment]
video.log 上传看看

**Comment by jianchang512** [comment]
> 用deepl 接口，提示str object has not attribute text 然后gbt3.5 提示可能是文本过长，这个怎么解决呀

有点bug，下版修复
