### ISSUE TITLE
无法正常开始：终端提示 'proxy''proxy'

### ISSUE THREAD

**Issue by switchchow** [jianchang512/pyvideotrans#590]
Mac源码安装 python 3.10.15
默认配置，微软翻译，Edge-TTS配置，faster-whisper tiny ,总提示'proxy''proxy'，无法正常开始工作 
![screenshot-20241026-115039](https://github.com/user-attachments/assets/93fbdc2c-5892-4f59-ac9a-39f4e4db7998)

**Comment by baibinghere** [comment]
我也遇到相同的情况，每次点击“开始处理”，都会在终端打印一行 `proxy`

```
2024-10-26 15:26:38.672 Python[18399:115824] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
'proxy'
```

**Comment by jianchang512** [comment]
软件目录下 logs文件夹内出错当时的日志文件上传下

**Comment by switchchow** [comment]
[20241026.log](https://github.com/user-attachments/files/17540472/20241026.log)

**Comment by switchchow** [comment]
> 软件目录下 logs文件夹内出错当时的日志文件上传下

已上传

**Comment by baibinghere** [comment]
@switchchow 最新的代码已经解决
check: https://github.com/jianchang512/pyvideotrans/pull/592
