### ISSUE TITLE
使用deepl翻译出错

### ISSUE THREAD

**Issue by gatsby-coder** [jianchang512/pyvideotrans#596]
![sp_OriGzb7iGi](https://github.com/user-attachments/assets/d1522d38-a543-43f0-b30f-2f3cbba51ddc)
![sp_dAmqQw56DE](https://github.com/user-attachments/assets/d63bf0a8-a91c-4645-b508-69882afe203b)
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。

**复现步骤**
1. deepl翻译
2. 批量翻译
3. 使用的模型名

**操作系统**
 - Windows10

**2.92**

**Comment by jianchang512** [comment]
2.93补丁

**Comment by gatsby-coder** [comment]
> 2.93补丁

更新了还是不行
![sp_kWPkuqHquD](https://github.com/user-attachments/assets/aca9c02e-a42d-4226-9dce-5db8799ce121)
