### ISSUE TITLE
使用时遇到的问题

### ISSUE THREAD

**Issue by moriaty2013** [jianchang512/pyvideotrans#60]
在选择软字幕后，输出的视频换了多个播放器后，均没有嵌入的字幕。对比示例视频，工作流少了字幕嵌入的过程。
如图所示：
![没有字幕嵌入的过程](https://github.com/jianchang512/pyvideotrans/assets/5159076/82b5d56e-ec1d-4ac5-9318-49402ddac0d7)
![案例](https://github.com/jianchang512/pyvideotrans/assets/5159076/e8f28406-91f4-4b68-a748-c53b73c8da98)
还有个小问题，语音识别的时间是以10秒为一部分，这一部分时间可以自定义修改吗？因为一些台词比较密的视频，会出现字幕都堆到一起情况

**Comment by jianchang512** [comment]
目前最新是0.9.3.2，先到最新
软字幕方式，国内很多播放器是不支持的，需要把同名字幕srt文件和视频放一起，才能显示

在目标文件夹中srt里。有生成的字幕文件，和视频放弃再打开播放，如果乱码，就把srt打开转为gbk格式


第二个问题，新版语音模型后可以选择整体识别方式

**Comment by jianchang512** [comment]
目前最新是0.9.3.2，先到最新
软字幕方式，国内很多播放器是不支持的，需要把同名字幕srt文件和视频放一起，才能显示

在目标文件夹中srt里。有生成的字幕文件，和视频放弃再打开播放，如果乱码，就把srt打开转为gbk格式


第二个问题，新版语音模型后可以选择整体识别方式

**Comment by jianchang512** [comment]
已处理
