### ISSUE TITLE
請修正api.py translate_srt 錯誤

### ISSUE THREAD

**Issue by moseleman** [jianchang512/pyvideotrans#605]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。
translate_srt 接口報錯

**复现步骤**
1. 使用的哪个功能
2. faster模式/openai模式？
3. 使用的模型名

經程式修正後可用，以下為修正方式:
api.py 第211行
is_allow=translator.is_allow_translate(translate_type=cfg['translate_type'],show_target=cfg['target_language'],return_str=True)
要修正為
is_allow=translator.is_allow_translate(translate_type=cfg['translate_type'],show_target=cfg['target_code'],return_str=True)

**操作系统**
 - Windows/Linux/MacOS
 Linux

**软件左上角版本号数字**
Git main主支線

**Comment by jianchang512** [comment]
fixed, 3q
