### ISSUE TITLE
第三方接口

### ISSUE THREAD

**Issue by Bromaomao** [jianchang512/pyvideotrans#61]
日志报错：INFO:httpx:HTTP Request: POST https://api.chatanywhere.cn/v1/chat/completions "HTTP/1.1 200 OK"
ERROR:VideoTrans:【chatGPT Error-2】翻译失败:openaiAPI=https://api.chatanywhere.cn/v1 :'ChatCompletion' object has no attribute 'code'

**Comment by jianchang512** [comment]
填写接口时去掉末尾v1再试试

**Comment by jianchang512** [comment]
打开video.log，看看有没有从chatgpt返回的详细信息

**Comment by zach106** [comment]
去掉v1还是不行

**Comment by zach106** [comment]
去掉 v1  并且pip install --upgrade openai 之后正常

**Comment by jianchang512** [comment]
1. 首先确保第三方接口正常，那天你用的那个接口挂了
2. 确定是编译版还是源码版，源码版必须升级 openai，新版openai库变化很大

**Comment by yuanjie-ai** [comment]
https://api.chatllm.vip/
这个可以，啥时候打算重构下这个项目

**Comment by jianchang512** [comment]
> https://api.chatllm.vip/ 这个可以，啥时候打算重构下这个项目

？？这个不是第三方接口吗，如果他返回的数据格式和官方一模一样，那么理论上是支持的
