### ISSUE TITLE
v3.09 batch translate didn't work after press Start button

### ISSUE THREAD

**Issue by trinhvinhxuan** [jianchang512/pyvideotrans#612]
After import file srt into the box of import text to be translated from a file. Whole list of srt file appearred. But after press Start>. There are nothing run and boxes are blank, without any results.
![Screenshot 2024-11-12 155621](https://github.com/user-attachments/assets/b154a6c7-d1dc-4b19-8b50-b6de32dca647)
![Screenshot 2024-11-12 155914](https://github.com/user-attachments/assets/e4da1b38-519b-4c5a-817a-11876490389e)

**Comment by jianchang512** [comment]
What you're typing here isn't srt.

**Comment by trinhvinhxuan** [comment]
It's not work with Google translate channel. Then I changed to Microsoft and it work.
