### ISSUE TITLE
配音自动加速功能听起来比较奇怪？

### ISSUE THREAD

**Issue by MedalCollector** [jianchang512/pyvideotrans#62]
感谢您的项目，非常棒。目前使用下来感觉有一个问题，就是汉语视频翻译为英文视频后，时长往往会增加，当我点击视频自动加速功能后，生成出来的视频有一些片段是被加速的，有一些没有被加速，被加速的部分听起来会非常奇怪，这个有没有什么未来的优化点？

**Comment by jianchang512** [comment]
自动加速就是倍速播放，肯定和正常是不一样的，就像在b站看视频时开启2倍速

这个没有太好的办法，语音时长大于原时长，要对齐，要么就加速语音倍速播放，要么就降速慢放视频，不管哪一种都有缺陷。

或者考虑语音正常速度播放，在视频最后重复复制最后一帧，延长视频以便对齐语音时间

**Comment by MedalCollector** [comment]
理解，尝试了下，手工调整配音语速感觉最终效果比较好。但是一个十分钟的视频，不同的片段需要的配音语速不太一样，比如有些片段需要+20，有些需要+10，如果整段视频使用同一个配音语速又会不合适，能否快速的手动调节各段的配音语速呢？比如在语音合成成功后，加一个切割分段调节配音语速的功能？

**Comment by zach106** [comment]
可以加入一个抽离背景音乐，做人声分离，最后再加入到视频内，这样就可以保留背景音乐

**Comment by jianchang512** [comment]
> 可以加入一个抽离背景音乐，做人声分离，最后再加入到视频内，这样就可以保留背景音乐

前几版搞过，但只适合背景是音乐的，而且模型体积也比较大，就去掉了。

**Comment by zach106** [comment]
声音的处理上，可以做一个变速不变调的处理，或者简单点把视频内容延长到和音频一致，如果在能加上一个背景音的处理，和语音情感识别，并加入到新和成的语音中，就完全可以商用了

**Comment by jianchang512** [comment]
去除背景音乐的以后打算单独出个工具，太大了，不适合集成
