### ISSUE TITLE
“ct-punc-c is not registered”错误

### ISSUE THREAD

**Issue by tcheoct** [jianchang512/pyvideotrans#621]
**出错信息**
中文视频转字幕时出现“ct-punc-c is not registered”错误，我感觉是视频太长了，超出免费范围了
![微信图片_20241118221925](https://github.com/user-attachments/assets/140c309f-79bb-4b47-84f5-17ae61f4a3f6)

**复现步骤**
1.音频视频转字幕
2. faster模式
3. models--Systran--faster-whisper-large-v3-turbo

**操作系统**
 - Windows

**3.16

**Comment by jianchang512** [comment]
取消中文重新断句，阿里funasr问题。本地模型哪有什么免费限制

**Comment by tcheoct** [comment]
好的
