### ISSUE TITLE
Request for Improved Timestamp Accuracy in Gemini using PySRT when using gemini recognition, i have provided my python code 

### ISSUE THREAD

**Issue by abhijeet12s** [jianchang512/pyvideotrans#624]
#Request for Improved Timestamp Accuracy in Gemini using PySRT#

Could you please ensure that timestamps for audio segments are generated using PySRT instead of relying on Gemini? When Gemini generates timestamps, they are often inaccurate and fall outside the video range.  
To address this issue, I provided my custom code that resolves the problem by implementing the following steps:  

 Features of My Code:

1. **Audio Splitting**:
   - The audio file is split into smaller segments based on silence detection, leveraging the capabilities of `pydub`.

2. **Transcription**:
   - Each segment is transcribed individually using the Gemini generative AI model.

3. **Accurate Timestamps**:
   - Start and end times for each segment are calculated based on the segment duration, ensuring precise alignment.

4. **SRT Generation**:
   - The transcriptions and their respective timestamps are combined into a single SRT file using `pysrt`.  

---

### Fixed Issue:
The issue of **inaccurate timestamps** generated by Gemini has been resolved. By utilizing PySRT, timestamps are calculated for each individual segment independently and then compiled into the final SRT file. This ensures accuracy and avoids inconsistencies.  

Let me know if you want to ask me about anything! 😊

code : 
import os
from pydub import AudioSegment, silence
import google.generativeai as genai
from pysrt import SubRipFile, SubRipItem, SubRipTime
from tqdm import tqdm

# Configure Gemini API
API_KEY = ".................................add your api key"
MODEL_NAME = "gemini-1.5-flash"
TRANSCRIPTION_PROMPT = "Please transcribe this audio."
TIMEOUT = 600  # Timeout for API requests in seconds

# Configure Generative AI
genai.configure(api_key=API_KEY)

def split_audio(audio_path: str, silence_thresh: int = -40, min_silence_len: int = 90, padding: int = 250):
    """
    Splits the input audio file into segments based on silence.

    Parameters:
        audio_path (str): Path to the input audio file.
        silence_thresh (int): Silence threshold in dB.
        min_silence_len (int): Minimum silence length in ms to detect splits.
        padding (int): Padding to add around detected silence in ms.

    Returns:
        List[AudioSegment]: List of audio segments.
    """
    audio = AudioSegment.from_file(audio_path)
    silent_ranges = silence.detect_silence(audio, min_silence_len=min_silence_len, silence_thresh=silence_thresh)
    silent_ranges = [(max(0, start - padding), min(len(audio), end + padding)) for start, end in silent_ranges]

    segments = []
    last_end = 0
    for start, end in silent_ranges:
        if last_end < start:
            segments.append(audio[last_end:start])
        last_end = end
    if last_end < len(audio):
        segments.append(audio[last_end:])
    return segments

def transcribe_audio_segment(segment: AudioSegment, temp_audio_path: str) -> str:
    """
    Transcribes a single audio segment using Gemini.

    Parameters:
        segment (AudioSegment): The audio segment to transcribe.
        temp_audio_path (str): Temporary file path to save the segment.

    Returns:
        str: Transcribed text.
    """
    # Export segment to a temporary WAV file
    segment.export(temp_audio_path, format="wav")

    # Transcribe using Gemini
    try:
        model = genai.GenerativeModel(model_name=MODEL_NAME)
        uploaded_file = genai.upload_file(temp_audio_path, mime_type="audio/wav")
        chat_session = model.start_chat(history=[{"role": "user", "parts": [TRANSCRIPTION_PROMPT]}])
        response = chat_session.send_message(uploaded_file, request_options={"timeout": TIMEOUT})
        return response.text.strip() if response and response.text else ""
    except Exception as e:
        print(f"Error transcribing segment: {e}")
        return ""

def generate_srt(subtitles, output_srt):
    """
    Generates an SRT file from the given subtitle data.

    Parameters:
        subtitles (List[Dict]): List of subtitles with start, end times, and text.
        output_srt (str): Path to save the SRT file.
    """
    srt_file = SubRipFile()
    for idx, sub in enumerate(subtitles):
        start_time = SubRipTime(seconds=sub["start"])
        end_time = SubRipTime(seconds=sub["end"])
        srt_item = SubRipItem(index=idx + 1, start=start_time, end=end_time, text=sub["text"])
        srt_file.append(srt_item)

    srt_file.save(output_srt, encoding="utf-8")
    print(f"SRT file saved to {output_srt}")

def process_audio_file(audio_path: str, output_srt: str):
    """
    Processes a single audio file: splits it into segments, transcribes each, and generates an SRT file.

    Parameters:
        audio_path (str): Path to the input audio file.
        output_srt (str): Path to save the generated SRT file.
    """
    try:
        temp_audio_path = os.path.join(os.path.dirname(audio_path), "temp_segment.wav")

        # Step 1: Split the audio file into segments
        print("Splitting audio into segments...")
        segments = split_audio(audio_path)
        print(f"Audio split into {len(segments)} segments.")

        # Step 2: Transcribe each segment and collect subtitles
        subtitles = []
        start_time = 0.0

        for segment in tqdm(segments, desc="Transcribing segments", unit="segment"):
            transcription = transcribe_audio_segment(segment, temp_audio_path)
            duration = len(segment) / 1000.0  # Convert duration to seconds
            end_time = start_time + duration

            if transcription.strip():
                subtitles.append({"start": start_time, "end": end_time, "text": transcription})

            start_time = end_time

        # Step 3: Generate the SRT file
        print("Generating SRT file...")
        generate_srt(subtitles, output_srt)

        # Cleanup
        if os.path.exists(temp_audio_path):
            os.remove(temp_audio_path)

    except Exception as e:
        print(f"Error processing audio file: {e}")

if __name__ == "__main__":
    audio_path = r"E:\New folder\3mau (enhanced).wav"  # Update with the path to your audio file
    output_srt = r"E:\New folder\output.srt"  # Update with the desired SRT file path

    if os.path.isfile(audio_path):
        process_audio_file(audio_path, output_srt)
    else:
        print("Invalid file path. Please check the path and try again.")

**Comment by jianchang512** [comment]
ok，i test it and add

**Comment by jianchang512** [comment]
An audio clip averages 3-10s, so that a 10-minute audio file may result in 60 requests being sent, and a 429 error is reported for such a short period of time. It's also easy to exceed gemini frequency limits

Are you a paid gemini account?

**Comment by abhijeet12s** [comment]
> An audio clip averages 3-10s, so that a 10-minute audio file may result in 60 requests being sent, and a 429 error is reported for such a short period of time. It's also easy to exceed gemini frequency limits
> 
> Are you a paid gemini account?
> 
> Maybe try to optimize the prompt words and strictly limit the return timestamp accuracy

I have tried in prompt to strictly create timestamps accurate to their corresponding length but for 2 months there is no result in both pyvideotrans and Gemini ai studio

**Comment by jianchang512** [comment]
Upgrade to 3.18, check the Voice Noise Reduction option, and try again with the following prompts

```
Please transcribe the audio I uploaded into subtitles in SRT format. Please note that the timestamp must be accurate to the level of a word, and return the legal SRT subtitle content after the transcription. Do not add any auxiliary marks or HTML tags, and each subtitle can have up to 2 lines, and the duration should be between 1 second and 12 seconds
```

**Comment by abhijeet12s** [comment]
Ok, I will do it.

**Comment by abhijeet12s** [comment]
i cant modify prompt for gemini recognition and i tried by modifying prompt in google ai studio and its still not giving accurate timestamp nomatter what. i tried by inputting small length audio tried by giving strict and hard prompt but still not working.  it works by giving it multiple small audio clips to transcribe and then giving those transcribed text srt by pysrt or other library

**Comment by abhijeet12s** [comment]
please add option to 1) split / segment clips by detecting audio silent or other method such as scene detection
                                   2)transcribe the segmented audio as text 
                                   3) using pysrt calculate the length of clips and create srt

**Comment by jianchang512** [comment]
Slicing for 1-10s, a 30-minute audio should initiate at least 200 requests, free accounts are not available at all, even for paid accounts, a large number of failures will be generated if the frequency of requests is not set to a very high level, in order to reduce the complexity of the error is not prompted, except for the connection error, and the first 90 characters of the cause of the error will be inserted directly into the subtitle position.


Also if there is noise or background sound in the audio, this way of segmentation will be very imprecise and produce not so good results.

Next version will add an option to use

**Comment by abhijeet12s** [comment]
About the background noise and background BGM songs, it can be solved by noise reduction and voice isolation. Even if it doesn't get solved, there is always the option of transcribing by equal division. The most important is recognition accuracy and accurate timestamps.  
I have an idea in which the issue of API request limits can be solved:  
1. Input the whole audio.  
2. Segment the audio and make the SRT timestamps of those clips.  
3. After each audio segment, add a voice clip created by Azure TTS with `### END SEGMENT ###`.  
4. Combine all audio into one audio file and send it to transcribe as text.  
5. The transcribed text file will be separated by recognizing `### END SEGMENT ###` text and filling each text segment in the previously created SRT.  

In pyvideotrans, it’s worrisome to add video to dub in one go without doing corrections in every part because when transcribing the video with OpenAI-Whisper, its accuracy in languages other than English is 40%, while it outputs `?` and doesn’t transcribe some segments. If there is some noise or BGM, the transcription is terrible. In English, the accuracy is 80%. For translation, if transcription is not correct, then there is no use of accurate translation, and so for dubbing.  

If you have ChatGPT Premium, the dubbing can be done in one click because of ChatGPT's transcription accuracy. However, to have ChatGPT-OpenAI Premium, you need a credit card or debit card from an international bank. After getting ChatGPT-OpenAI Premium for $20, there is a token cost, which is too pricey. Of course, this is assuming you can buy it in the first place, as many people don’t have access to it.  

Things get easier with Gemini because it’s as easy to get as downloading a game from a game store. You can get Gemini Premium from any wallet available in the local market. Secondly, when you buy premium for $20, you get free tokens. They are enough to create 7 hours of daily video by using all the tokens on these models:  
1. Gemini-1.0-Pro  
2. Gemini-1.5-Pro  
3. Gemini-Pro  
4. Gemini-1.5-Pro-002  
5. Gemini-1.5-Pro-Exp-0827  
6. Gemini-1.5-Flash  
7. Gemini-1.5-Flash-Exp-0827  
8. Gemini-1.5-Flash-8B-Exp-0924  
9. Gemini-1.5-Flash-002  

With these models, you can transcribe an hour or more of video using only one model. There are so many people with Gemini Premium, and it can transcribe no matter how much noise there is by detecting speakers.  
By using it, we can dub videos with just one click without worrying about inaccuracies.

**Comment by abhijeet12s** [comment]
> Slicing for 1-10s, a 30-minute audio should initiate at least 200 requests, free accounts are not available at all, even for paid accounts, a large number of failures will be generated if the frequency of requests is not set to a very high level, in order to reduce the complexity of the error is not prompted, except for the connection error, and the first 90 characters of the cause of the error will be inserted directly into the subtitle position.
> 
> Also if there is noise or background sound in the audio, this way of segmentation will be very imprecise and produce not so good results.
> 
> Next version will add an option to use

**Comment by jianchang512** [comment]
A lot of the audio is without a clear proper mute interval, and pydub's cut splits are too rough, especially when the sound isn't very clean.

Local tests using silero-vad simply do the cut, the effect is better than pydub, but for faster speech speed does not have enough time to mute the audio file, or there is background noise audio file, the effect is still not good, may appear tens of seconds of audio fragments.

Unless the background sound is clean and the audio has a clear long enough mute interval, it's not going to cut very well any way.

Fixed duration cuts work even worse, forcing a split in mid-sentence.

And Gemini transcribes a few seconds of audio at a time, compared to a few minutes or tens of minutes of audio at a time, with poor results and more non-existent transcriptions.

So far it seems to be a modeling issue with Gemini that causes the timestamp of the transcription output to always be larger than the actual audio duration.

ChatGPT's transcription interface is fine, but not necessary, and the local whisper or whisper-faster-whisper results are almost identical to the ChatGPT online api results.

**Comment by abhijeet12s** [comment]
then does this logic will not work ???   every one can use adobe podcast or capcuts sound isolation to remove songs and background songs ? both of them works at perfect 100% level i have been using it for two months and they are free !    ( After each audio segment, add a voice clip created by Azure TTS with ### END SEGMENT ###.Combine all audio into one audio file and send it to transcribe as text. The transcribed text file will be separated by recognizing ### END SEGMENT ### text and filling each text segment in the previously created SRT.  )  ? ????? ?

**Comment by jianchang512** [comment]
`add a voice clip created by Azure TTS with ### END SEGMENT ###.` ??

**Comment by abhijeet12s** [comment]
### END SEGMENT ###.      its just a particular keword that will be attached at the end of every audio segment then latter we can divide every line of transcribed text ahead and before of that text . so that we will be able fill our previously  timestamps.

**Comment by abhijeet12s** [comment]
### END SEGMENT ###.      its just a particular keword that will be attached at the end of every audio segment then latter we can divide every line of transcribed text ahead and before of that text . so that we will be able fill our previously  timestamps.

**Comment by abhijeet12s** [comment]
### **How to Use Markers to Break Big Audio into Small Pieces**

#### Step 1: Add a Special Sound to the End of Each Clip  
- Imagine you have three parts of a cooking story:  
  - The first part talks about preparing ingredients (0:00 - 0:30).  
  - The second part is about cooking (0:30 - 1:00).  
  - The third part talks about serving the dish (1:00 - 1:30).  

- At the end of each part, we’ll add something special that says, **“This is the end of this part!”** For example, a robot voice saying **"### END SEGMENT ###"** or a beep sound.  

  Example:  
  - First part: "Start by chopping the vegetables and seasoning the meat." + **"### END SEGMENT ###"**  
  - Second part: "Cook the ingredients on medium heat until tender." + **"### END SEGMENT ###"**  
  - Third part: "Plate the dish and garnish with herbs." + **"### END SEGMENT ###"**

#### Step 2: Put All the Clips Together  
- Now, we take all those parts with the **"### END SEGMENT ###"** added and combine them into one big audio file.

#### Step 3: Send the Big Audio File to the Transcription App  
- We’ll send this one big audio file to a transcription app or tool that turns the audio into text.

#### Step 4: Look for the Special Sound in the Text  
- When the tool finishes, it gives us all the words, but we can see the **"### END SEGMENT ###"** in the text where each part ends.

  Example:  
  - Transcription:  
    `"Start by chopping the vegetables and seasoning the meat. ### END SEGMENT ### Cook the ingredients on medium heat until tender. ### END SEGMENT ### Plate the dish and garnish with herbs. ### END SEGMENT ###"`

#### Step 5: Break the Text Into Smaller Pieces  
- Now, we use the **"### END SEGMENT ###"** to split the text into chunks:  
  - Chunk 1: "Start by chopping the vegetables and seasoning the meat."  
  - Chunk 2: "Cook the ingredients on medium heat until tender."  
  - Chunk 3: "Plate the dish and garnish with herbs."

#### Step 6: Match the Pieces to Time Stamps  
- We already know when each piece starts and ends:  
  - Chunk 1: 0:00 - 0:30  
  - Chunk 2: 0:30 - 1:00  
  - Chunk 3: 1:00 - 1:30  

#### Step 7: Write the Subtitles (SRT File)  
- We create a subtitle file (SRT) and write each chunk of text with its matching times:

  Example:  
  ```srt
  1
  00:00:00,000 --> 00:00:30,000
  Start by chopping the vegetables and seasoning the meat.

  2
  00:00:30,000 --> 00:01:00,000
  Cook the ingredients on medium heat until tender.

  3
  00:01:00,000 --> 00:01:30,000
  Plate the dish and garnish with herbs.
  ```

**Comment by abhijeet12s** [comment]
i have my classes of python now so i am going to the city. i will return after 3 hour  when i return from session i will create code and will send you. i am student and i get help of chatgpt to create codes.

**Comment by jianchang512** [comment]
1. This idea requires the addition of tts# audio in the corresponding language to the original audio, otherwise the English `hash tag` may not be recognized as a # symbol in other languages.


2. you need to make sure that the # symbols recognized must be 3 consecutive # symbols, I'm afraid gemini may not be able to guarantee this, how many tests have been done?


3. this only solves the problem of sending a large number of requests in a short period of time, but the processing is much more complicated, and if gemini does not return 3 consecutive #'s as expected, it will be messed up!

The vad cut I posted above works fine if you don't consider the problem of sending a lot of requests in a short period of time, the only problem is that you get subtitles that are tens of seconds long!
