### ISSUE TITLE
ffmpeg 执行结果：失败

### ISSUE THREAD

**Issue by wwwzhouhui** [jianchang512/pyvideotrans#63]
如题目，我电脑是windows 10  视频路径是不带英文的，执行结果报错了：ffmpeg 执行结果：失败

**Comment by jianchang512** [comment]
上传video.log

**Comment by wwwzhouhui** [comment]
感觉是ffmpeg  的问题，但是不知道问题在哪？

INFO:srt:Legalised content '希望对你有所帮助，下期视频再见。\n\n' to '希望对你有所帮助，下期视频再见。'
INFO:srt:Legalised content '大家好，我叫伊戈尔，今天我将向大家展示如何将长篇文本加载到聊天 Gpt 中。在这个例子中，我们将把一本 73 页的书加载到聊天 Gpt 中。\n\n' to '大家好，我叫伊戈尔，今天我将向大家展示如何将长篇文本加载到聊天 Gpt 中。在这个例子中，我们将把一本 73 页的书加载到聊天 Gpt 中。'
INFO:srt:Legalised content '我们可以使用一个名为 pdftxtconverter 的在线工具，下载 txt 文件。\n\n' to '我们可以使用一个名为 pdftxtconverter 的在线工具，下载 txt 文件。'
INFO:srt:Legalised content '现在，让我们使用 jetgpt splitter。不使用该工具，您可以加载文本，它将把长文本分割成小块。\n\n' to '现在，让我们使用 jetgpt splitter。不使用该工具，您可以加载文本，它将把长文本分割成小块。'
INFO:srt:Legalised content '现在，复制每块内容并粘贴到聊天 Gpt 中。\n\n' to '现在，复制每块内容并粘贴到聊天 Gpt 中。'
INFO:srt:Legalised content '.\n\n' to '.'
INFO:srt:Legalised content '现在，当您加载完所有分块后，只需就您的长文本向 chat.gpt 提问，它就会给出答案。您可以向它提出子问题。\n\n' to '现在，当您加载完所有分块后，只需就您的长文本向 chat.gpt 提问，它就会给出答案。您可以向它提出子问题。'
INFO:srt:Legalised content '希望对你有所帮助，下期视频再见。\n\n' to '希望对你有所帮助，下期视频再见。'
INFO:VideoTrans:准备合成语音 folder_path='E:/BaiduNetdiskDownload/video-translate-v0.9.3.2/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development'
INFO:VideoTrans:Creating TTS wav E:/BaiduNetdiskDownload/video-translate-v0.9.3.2/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development/tts-Input Files and Long Text Into ChatGPT - Tool by Optimus Development.wav
INFO:VideoTrans:准备完毕，开始合成视频，e:/video/_video_out/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4  E:/video/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4
INFO:VideoTrans:合成配音+软字幕
INFO:VideoTrans:runffmpeg Will execute: cmd='ffmpeg -hide_banner -y -i "E:/BaiduNetdiskDownload/video-translate-v0.9.3.2/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development/novoice.mp4" -i "E:/BaiduNetdiskDownload/video-translate-v0.9.3.2/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development/tts-Input Files and Long Text Into ChatGPT - Tool by Optimus Development.wav" -sub_charenc UTF-8 -f srt -i "E:/BaiduNetdiskDownload/video-translate-v0.9.3.2/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.srt" -c:v libx264 -c:a aac -c:s mov_text -metadata:s:s:0 language=chi "e:/video/_video_out/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4"'
INFO:VideoTrans:Will execute: ffmpeg  -y -i "E:/video/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4" -ar 8000  "C:/Users/Administrator/Videos/pyvideotrans/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4.wav"
INFO:VideoTrans:runffmpeg Will execute: cmd='ffmpeg -hide_banner  -y -i "E:/video/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4" -ar 8000  "C:/Users/Administrator/Videos/pyvideotrans/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4.wav"'
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans:Will execute: ffmpeg  -y -i "E:/video/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4" -ar 8000  "C:/Users/Administrator/Videos/pyvideotrans/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4.wav"
INFO:VideoTrans:runffmpeg Will execute: cmd='ffmpeg -hide_banner  -y -i "E:/video/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4" -ar 8000  "C:/Users/Administrator/Videos/pyvideotrans/tmp/Input Files and Long Text Into ChatGPT - Tool by Optimus Development.mp4.wav"'

**Comment by jianchang512** [comment]
去掉文件名里的空格，然后再试试

**Comment by wwwzhouhui** [comment]
是视频文件空格问题导致的，谢谢！
