### ISSUE TITLE
取消配音自动加速会导致合成的音频部分丢失

### ISSUE THREAD

**Issue by MedalCollector** [jianchang512/pyvideotrans#64]
您好作者，由于勾选配音自动加速会导致声音变调，不同段落的声音听起来很不同，所以我是打算先把原始音频转化到希望的语言，再把视频内容做一些调整，现在碰到的问题是，取消配音自动加速后，由于合成的英文语音长度比原始音频长，最后会有一段音频丢失了。有没有什么办法可以单独导出TTS之后的完整音频，而不做截断呢？谢谢

**Comment by jianchang512** [comment]
音视频要合成的话，需要两者时长相同，否则无法合成。

如果你使用的是源码版，可以改下 videotrans/configure/tools.py 中 `merge_audio_segments` 函数中
```
if len(merged_audio) > total_duration:
        merged_audio = merged_audio[:total_duration]
```
这两行注释掉，可以在目标文件夹视频同名子目录下看到目标语言的音频文件。但这样操作后，最后合成会失败，因为音视频时长不一致

**Comment by MedalCollector** [comment]
命令行版本，有办法像UI版本一样，语音识别后做一下人工校验、修改再进行合成吗？感觉完全自动化，翻译的内容还是有问题？

**Comment by jianchang512** [comment]
> 命令行版本，有办法像UI版本一样，语音识别后做一下人工校验、修改再进行合成吗？感觉完全自动化，翻译的内容还是有问题？

没办法，UI可以暂停，命令行没法暂停
