### ISSUE TITLE
elevenlabs dubbed english to spanish v3.2 / gemini 1.5 pro

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#642]
[Task 11 - cufe - v1-23-NOV.zip](https://github.com/user-attachments/files/17925573/Task.11.-.cufe.-.v1-23-NOV.zip)
[20241126.zip](https://github.com/user-attachments/files/17925583/20241126.zip)

pls review in middle of video, hear 2 voices at time

**Comment by johnfelipe** [comment]
this continue in newer version, i review in elevenlabs and is great but in video feel and hear same voice repeated again and again

**Comment by johnfelipe** [comment]
[englishandspanish.zip](https://github.com/user-attachments/files/17961848/englishandspanish.zip)

english audio is good
but spanish audio is very bad

**Comment by johnfelipe** [comment]
is better with this:

![SNAG-0111](https://github.com/user-attachments/assets/aed98cc9-0923-49e7-a8f2-d40b92f68d02)

noise reduction NOT

**Comment by jianchang512** [comment]
There is no way that this should be a problem with elevenlabs.io

**Comment by johnfelipe** [comment]
No, unselect noise reduction and it's perfect

**Comment by jianchang512** [comment]
Noise reduction models are only trained for Chinese and English, other languages may have poor results.
