### ISSUE TITLE
remove_noise ERROR

### ISSUE THREAD

**Issue by moseleman** [jianchang512/pyvideotrans#644]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。

出錯描述如以下:
6|pyvideotrans-9011  | ERROR:VideoTrans:'remove_noise'('remove_noise',)
6|pyvideotrans-9011  | ERROR:VideoTrans:'remove_noise'
6|pyvideotrans-9011  | Traceback (most recent call last):
6|pyvideotrans-9011  |   File "/.../pyvideotrans/videotrans/task/job.py", line 77, in run
6|pyvideotrans-9011  |     trk.recogn()
6|pyvideotrans-9011  |   File "/.../pyvideotrans/videotrans/task/_speech2text.py", line 72, in recogn
6|pyvideotrans-9011  |     if self.cfg['remove_noise']:
6|pyvideotrans-9011  | KeyError: 'remove_noise'
6|pyvideotrans-9011  | ERROR:VideoTrans:语音识别阶段出错:'remove_noise'

**复现步骤**
1. 使用的哪个功能
2. faster模式/openai模式？
3. 使用的模型名

api.py 中的 recogn 功能
openai-whisper和faster-whisper 都會出錯

**操作系统**
 - Windows/Linux/MacOS
 
 Ubuntu 22.04 main 最新布署

**软件左上角版本号数字**

報錯時間點: 2024.11.28 16:40

**Comment by jianchang512** [comment]
pyvideotrans/videotrans/task/_speech2text.py  72行  `self.cfg['remove_noise']` 改为 `self.cfg.get('remove_noise')`
