### ISSUE TITLE
error with 3.26 - TEST GET ROLES - elevenlabs with subscription - pydantic_core_pydantic_core.cp310-win_amd64.pyd

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#645]
cannot import name ‘from_json‘ from ‘pydantic_core._pydantic_core‘ (d:\Users\GAMEMAX\Downloads\win-videotrans\_internal\pydantic_core_pydantic_core.cp310-win_amd64.pyd)

![SNAG-0104](https://github.com/user-attachments/assets/49570a18-19ba-46ac-904b-1efbe61bf59a)

**Comment by jianchang512** [comment]
One less packet to pass. You can wait a little longer to download it or download the full package!

**Comment by johnfelipe** [comment]
i wait next with elevenlabs fixed, tnks
