### ISSUE TITLE
error with 3.26 - I cant see my custom profile in elevenlabs

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#646]
![SNAG-0105](https://github.com/user-attachments/assets/309663c3-627e-46be-88a8-3faa06d98678)

![SNAG-0106](https://github.com/user-attachments/assets/f470ab7a-9ba3-4e82-b2a4-927291005827)

**Comment by jianchang512** [comment]
menu   Elevlabs.io  test  

toggle  dubbing channel

**Comment by johnfelipe** [comment]
https://github.com/user-attachments/assets/53a3230d-7d4c-45d2-b3eb-a1b86e705864

is not working, even test get roles to
