### ISSUE TITLE
视频合成完毕 出错:ffmpeg执行结果:失败

### ISSUE THREAD

**Issue by guos** [jianchang512/pyvideotrans#65]
全部执行结束
任务处理结束,清理临时文件
xxxxxx 视频合成完毕
**出错:ffmpeg**执行结果:失败

使用的最新release 版本，windows 11

**Comment by jianchang512** [comment]
video.log上传下看看

**Comment by guos** [comment]
生成了en.wav 和zh-cn.wav, 


video.log 里面貌似没有报错信息 ，最后几行如下


INFO:srt:Legalised content 'atp完全靠自己后退，他们的接触点随着时间的推移会走得更远。所以这是完全凭直觉发生的事情，不应该被搞乱。\n\n' to 'atp完全靠自己后退，他们的接触点随着时间的推移会走得更远。所以这是完全凭直觉发生的事情，不应该被搞乱。'
INFO:srt:Legalised content '感谢大家观看这个视频，希望您喜欢它，请在下面的部分发表评论，我一定会回答，喜欢该视频并订阅（如果您还没有订阅的话）。\n\n' to '感谢大家观看这个视频，希望您喜欢它，请在下面的部分发表评论，我一定会回答，喜欢该视频并订阅（如果您还没有订阅的话）。'
INFO:srt:Legalised content '我下次再见..\n\n' to '我下次再见..'
INFO:VideoTrans:准备合成语音 folder_path='D:/video-translate-v0.9.4.1/tmp/ATP Forehand vs WTA Forehand (2018)'
INFO:VideoTrans:Creating TTS wav D:/video-translate-v0.9.4.1/tmp/ATP Forehand vs WTA Forehand (2018)/tts-ATP Forehand vs WTA Forehand (2018).wav
INFO:VideoTrans:准备完毕，开始合成视频，d://_video_out/ATP Forehand vs WTA Forehand (2018).mp4  D:/ATP Forehand vs WTA Forehand (2018).mp4
INFO:VideoTrans:合成配音+硬字幕
INFO:VideoTrans:runffmpeg Will execute: cmd='ffmpeg -hide_banner -y -i "D:/video-translate-v0.9.4.1/tmp/ATP Forehand vs WTA Forehand (2018)/novoice.mp4" -i "D:/video-translate-v0.9.4.1/tmp/ATP Forehand vs WTA Forehand (2018)/tts-ATP Forehand vs WTA Forehand (2018).wav" -c:v libx264 -c:a aac -vf subtitles=ATP Forehand vs WTA Forehand (2018).srt "d://_video_out/ATP Forehand vs WTA Forehand (2018).mp4"'

我尝试用一个短的小视频从中文翻译成英文好像没有问题，可以合并成mp4,但是这个英文翻译成中文，最后合并生成视频的时候就挂了

全部执行结束
任务处理结束,清理临时文件
ATP Forehand vs WTA Forehand (2018) 视频合成完毕
**出错:ffmpeg执行结果:失败**
ATP Forehand vs WTA Forehand (2018) 合成配音+硬字幕
合并后将创建到 d://_video_out/ATP Forehand vs WTA Forehand (2018).mp4
开始将视频、音频、字幕合并
准备进行 edgeTTS 语音合成，角色:zh-CN-YunjianNeural
开始配音操作:edgeTTS
0秒后自动合并
1秒后自动合并
2秒后自动合并
3秒后自动合并
4秒后自动合并
5秒后自动合并
6秒后自动合并
7秒后自动合并
8秒后自动合并
9秒后自动合

**Comment by jianchang512** [comment]
去掉名字和路径中的空格再试试

**Comment by guos** [comment]
嗯，重命名成2.mp4这种就ok，但是好像配音和视频有些不对称，口型对不上，这个跟modle选择不同有关系吗？现在用的base

**Comment by guos** [comment]
Ok, 要是能跟heygen一样就更棒了
