### ISSUE TITLE
video-trans-v0.9.4.3，腾讯KEY,提示错误！

### ISSUE THREAD

**Issue by qudongdong123** [jianchang512/pyvideotrans#66]
![微信图片_20231122111815](https://github.com/jianchang512/pyvideotrans/assets/127782496/60c6d3cf-64be-45f3-a81f-44c4df2d1625)
![微信图片_20231122111923](https://github.com/jianchang512/pyvideotrans/assets/127782496/7f48d10a-7711-46d9-96b7-c8034d0573c4)
[video.log](https://github.com/jianchang512/pyvideotrans/files/13433192/video.log)

**Comment by jianchang512** [comment]
能否在腾讯云那里调整请求频率，调大点，如果不能，下版我加个速度限制吧
现在是因为请求翻译频率太高，超出腾讯限制了

**Comment by MedalCollector** [comment]
百度那个好像也有请求频率的限制？

**Comment by jianchang512** [comment]
> 百度那个好像也有请求频率的限制？

百度每月只有5万字符免费，很快会耗尽，腾讯有500万字符免费。但请求频繁都很低。可以挂代理使用google
