### ISSUE TITLE
两个建议——跟进反馈

### ISSUE THREAD

**Issue by popdog0** [jianchang512/pyvideotrans#67]
针对#58提出的建议
看你的发布日志，这两个功能似乎都实现了，但是我试用0.9.3.2版本后，发现没有效果，不知道是不是我用的方法不正确?
这两个功能需要怎么设置参数?

**Comment by jianchang512** [comment]
不要选择配音，也不要选择嵌入字幕，然后开始任务，结束后，到目标文件夹，里面有个视频同名目录，打开会道2个srt字幕文件
