### ISSUE TITLE
got an unexpected keyword argument 'threshold'"

### ISSUE THREAD

**Issue by blissvisitor** [jianchang512/pyvideotrans#692]
**Can not work**
Exception: VadOptions.__init__() got an unexpected keyword argument 'threshold'
2024-12-24 18:12:36,223 - VideoTrans - ERROR - VadOptions.__init__() got an unexpected keyword argument 'threshold'
2024-12-24 18:12:36,223 - VideoTrans - ERROR - VadOptions.__init__() got an unexpected keyword argument 'threshold'("VadOptions.__init__() got an unexpected keyword argument 'threshold'",)
Error calling Python override of QThread::run(): 2024-12-24 18:12:36,224 - VideoTrans - ERROR - Uncaught exception

**复现步骤**
1. Standard Function Mode
2. faster

<img width="1718" alt="image" src="https://github.com/user-attachments/assets/eb176d0d-5cc3-4768-aca8-0ea381aff745" />

**操作系统**
MacOS M1 Max

**软件左上角版本号数字**

**Comment by jianchang512** [comment]
MacOS/Linux：

pip3 install --upgrade openai-whisper elevenlabs

pip3 install --no-deps --force-reinstall "faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz"

**Comment by kokusen26614** [comment]
> MacOS/Linux：
> 
> pip3安装--升级 openai-whisper Elevenlabs
> 
> pip3 安装 --no-deps --force-reinstall “faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz ”

window系统呢？也是这样做吗？ @jianchang512

**Comment by blissvisitor** [comment]
> MacOS/Linux：
> 
> pip3 install --upgrade openai-whisper elevenlabs
> 
> pip3 install --no-deps --force-reinstall "faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz"

It resolves the issue thanks!

**Comment by blissvisitor** [comment]
> > MacOS/Linux：
> 
> > 
> 
> > pip3安装--升级 openai-whisper Elevenlabs
> 
> > 
> 
> > pip3 安装 --no-deps --force-reinstall “faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz ”
> 
> 
> 
> window系统呢？也是这样做吗？ @jianchang512 

You can try,I think it's the same reason.

**Comment by kokusen26614** [comment]
> > > MacOS/Linux：
> > 
> > 
> > > 
> > 
> > 
> > > pip3安装--升级 openai-whisper Elevenlabs
> > 
> > 
> > > 
> > 
> > 
> > > pip3 安装 --no-deps --force-reinstall “faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz ”
> > 
> > 
> > window系统呢？也是这样做吗？ @jianchang512
> 
> You can try,I think it's the same reason.

You are right，it works，thanks.
