### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by troublemakerMibu** [jianchang512/pyvideotrans#71]
目前使用的0.9.4release版，体验下来有以下几点建议，希望作者能够采纳和改进：
1、对于文件夹或者文件名中存在中文字符的支持不是很好。
推测是由于使用了ffmpeg，导致不能支持中文字符。针对这一点我自己在其他项目使用的时候可以向ffmpeg传入带“”的绝对路径，可以解决。希望作者可以考虑这个方式。
2、自动处理缓存的处理方式可以优化。在ffmpeg错误，或者手动停止之后，需要手动删除缓存。在另一种使用场景下，ffmpeg出现错误后，程序的工作流被终止，于是我想要自己合并已经生成的字幕、音视频文件的时候，发现它们都已经被删掉了。
3、在代理不是很稳定的情况下，调用google翻译会存在api错误的情况，但是依然将报错信息添加到字幕文件中了，导致最终输出的视频字幕中会夹杂着报错信息。而且随着程序进程的推进，字幕文件也会被自动删除，导致无法手动修改字幕文件。
4、在视频工具箱中，我想要进行语音识别，同样因为ffmpeg的中文支持报错而无法执行。
主要原因是因为无法指定输出文件夹，而默认的输出文件夹中带有中文字符而导致错误。希望作者可以添加手动指定输出文件夹的选项。
5、在我的机器上使用whisper模型进行识别的时候，主要调用的是cpu进行处理。第一是速度较慢，第二是闲置了大量的显存资源。
ps：我的机器是2G显存的N卡gpu，在cpu模式下能够正常调用medium模型进行识别，占用系统内存大约4G左右，而不是显存。large模型还未测试。
6、字幕类型为软字幕的时候可以正常执行，但选择硬字幕嵌入时会出现ffmpeg报错。
7、能否支持其他的tts工具，例如bark，sovits等，让用户更加方便的选择模型和更多的音色

**Comment by jianchang512** [comment]
1. 下版会处理
2. 在目标文件夹下会生成srt和wav等素材
3. 同2
4. 下版处理
5. 配置好cuda环境，高级设置--选中CUDA
6. 空格名称导致的
7. 这个后续再考虑，目前先完善已有功能
