### ISSUE TITLE
大佬，使用GPT-3.5-turbo模型翻译，出现如下报错是啥原因呀？

### ISSUE THREAD

**Issue by zisanjun** [jianchang512/pyvideotrans#72]
我填的地址是http://103.214.168.87:3000/v1【one api程序搭建的站点】
看结果是有返回内容，但是报错翻译失败。

【chatGPT Error-0】翻译失败:openaiAPI=http://103.214.168.87:3000/v1:'ChatCompletion' object has no attribute 'data':ChatCompletion(id='chatcmpl-8Nyg1OIwGDRFzgCdkaGvs9ATJbjHP', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content="I can taste it at a glance\nAttention\nHis size is about the same\nLet him try on the suit first\nThere really is\nIt's over 200 yuan\nI'll give it back to you to try now\nGive him a little try\nYou love to create dust and rise for me\nWith you", role='assistant', function_call=None, tool_calls=None))], created=1700725477, model='gpt-3.5-turbo-0613', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=65, prompt_tokens=279, total_tokens=344))

**Comment by jianchang512** [comment]
是 0.9.4.3 版本吗，不是的话升级到最新
