### ISSUE TITLE
语音模型更换为large-v3，报错

### ISSUE THREAD

**Issue by zisanjun** [jianchang512/pyvideotrans#73]
mel_128 is not a file in the archive
![image](https://github.com/jianchang512/pyvideotrans/assets/57314603/6a987bfd-51eb-4bd1-8f84-e7d9a9fb8e5c)

**Comment by jianchang512** [comment]
源码版的需要更新下 openai-whisper
编译版等下次更新

**Comment by zisanjun** [comment]
收到 辛苦大佬啦，发现编译版0.9.5.0依旧会出现这个报错

**Comment by jianchang512** [comment]
语音模型后边，整体识别模式下试试

**Comment by jianchang512** [comment]
large-v3下载完整吗，重新下载，然后使用整体识别再试试

**Comment by SkywalkerJi** [comment]
一样。提示模型整体识别出错
<img width="657" alt="image" src="https://github.com/jianchang512/pyvideotrans/assets/22220678/83b5d896-2023-4f9b-bbc5-3a25d2985544">

**Comment by jianchang512** [comment]
启用cuda了？关闭

**Comment by zisanjun** [comment]
![ad88591632156484fa5e185a281679a](https://github.com/jianchang512/pyvideotrans/assets/57314603/5b6ac5b2-788b-4bbf-9419-7b5d1bcd40f8)
单独使用视频工具箱+base模型，会出现这个错误，是不是语法错误（缺少空格）啦？

**Comment by zisanjun** [comment]
![Uploading image.png…]()
反馈：语音识别环节，CPU快速跑满100%占用后闪退

**Comment by jianchang512** [comment]
> ![ad88591632156484fa5e185a281679a](https://user-images.githubusercontent.com/57314603/285453018-5b6ac5b2-788b-4bbf-9419-7b5d1bcd40f8.png) 单独使用视频工具箱+base模型，会出现这个错误，是不是语法错误（缺少空格）啦？

可能是ar 8000这个参数缘故
