### ISSUE TITLE
再某个时间范围内出现字幕合成失败

### ISSUE THREAD

**Issue by jasonsunsoa1983** [jianchang512/pyvideotrans#74]
![error](https://github.com/jianchang512/pyvideotrans/assets/43527952/96924970-fb26-44a4-ab18-f310b970c1c8)

![image](https://github.com/jianchang512/pyvideotrans/assets/43527952/ea2f0d7f-af29-4ad5-b7fc-a17690a98ba5)
您好！请问为什么会出现 某个时间范围内字幕合成失败的错误。

**Comment by jasonsunsoa1983** [comment]
这个现象还挺频繁的

**Comment by jianchang512** [comment]
这个时间范围内的文字在合成为语音时失败了
你可以对照字幕看看该范围内是否存在有效文字，包括原始字幕和翻译后的字幕

目标文件夹内视频同名子目录下存在字幕文件

**Comment by jasonsunsoa1983** [comment]
但是，执行第二次就好了。偶尔就会出现这个问题。

**Comment by jianchang512** [comment]
> 但是，执行第二次就好了。偶尔就会出现这个问题。

有可能那段时间的翻译失败了，执行太快了可能会被翻译渠道限制

**Comment by jasonsunsoa1983** [comment]
哦哦，谢谢。
