### ISSUE TITLE
字幕SRT文件直接导入情况下，是否可以添加先翻译再TTS的模式

### ISSUE THREAD

**Issue by MedalCollector** [jianchang512/pyvideotrans#75]
提一个建议，目前直接导入SRT文件，不导入视频的情况下，默认是直接对SRT文件的内容进行TTS，不进行翻译。是否可以添加一种模式，只导入SRT文件的情况下，也先经过翻译，再进行TTS。目前我的使用场景是：中文视频（十分钟左右）想翻译为英文，但是由于翻译的时长一般会长于原始视频，而打开自动加速又回导致听起来很奇怪，所以想先根据原始视频的SRT做成英文的语音文件，再自行编辑原始画面。这就需要根据中文SRT翻译，再进行TTS。

**Comment by jianchang512** [comment]
其实google翻译或者百度翻译里，直接粘贴srt全文，这样翻译更快也更简单。
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/337b218f-8416-49a4-8e17-3eeb9db13ecd)

你说的这个也是可以的，只是可能容易混淆，因为字幕编辑区一直都是显示的翻译后的字幕，如何设定让字幕再次翻译呢，而且如果翻译后的结果又应该再显示在哪里，如果对结果不满意应该在哪里进行修改，这都不太好处理

**Comment by MedalCollector** [comment]
OK. 我尝试下直接全文粘贴到谷歌翻译。不过我的建议是，是不是可以在左边和右边对称形式分别加上一个SRT显示区域，左边为原始的，右边为翻译结束的，我的习惯是在自动翻译后，要检查一遍翻译结果，再开始TTS，因为在一些比较要求精准度的场景，是需要手动调整的。这样左右两边分别放置原始的和翻译之后的字幕，也方便对照。另外，对于比较长的视频，感觉1分钟的检查时间不是很够，常常是还没有检查完内容，TTS就自动开始了，感觉这个1分钟倒计时自动TTS，是否可以去掉...在翻译完成后，在显示区域提示用户检查就可以了，如果不检查，就直接点击进行下一步？

**Comment by jianchang512** [comment]
右侧编辑区随便编辑下， 比如按个回车 或者 空格，就自动停止倒计时的
