### ISSUE TITLE
视频自动慢速和音频加速 出错失败不知道什么原因，最新版

### ISSUE THREAD

**Issue by q247574452** [jianchang512/pyvideotrans#78]
INFO:VideoTrans:offset=70892>0，需要末尾添加延长视频帧 70892秒
INFO:VideoTrans:runffmpeg Will execute: cmd='ffmpeg -hide_banner -y -i "F:/Userfile/下载/Compressed/video-trans-v0.9.5.0/tmp/11月24日/novoice.mp4" -i "F:/Userfile/下载/Compressed/video-trans-v0.9.5.0/tmp/11月24日/1700833156.132638.mp4" -filter_complex "[0:v]setsar=1[v0];[1:v]setsar=1[v1];[v0][v1]concat=n=2:v=1:a=0[outv]" -map "[outv]" -c:v libx264 -y "F:/Userfile/下载/Compressed/video-trans-v0.9.5.0/tmp/11月24日/novoice.mp4-tmp.mp4"'
ERROR:VideoTrans:[error]ffmpeg执行结果:失败 cmd='ffmpeg -hide_banner -y -i "F:/Userfile/下载/Compressed/video-trans-v0.9.5.0/tmp/11月24日/novoice.mp4" -i "F:/Userfile/下载/Compressed/video-trans-v0.9.5.0/tmp/11月24日/1700833156.132638.mp4" -filter_complex "[0:v]setsar=1[v0];[1:v]setsar=1[v1];[v0][v1]concat=n=2:v=1:a=0[outv]" -map "[outv]" -c:v libx264 -y "F:/Userfile/下载/Compressed/video-trans-v0.9.5.0/tmp/11月24日/novoice.mp4-tmp.mp4"'
INFO:VideoTrans:配音完毕，开始将视频、音频、字幕合并

![111屏幕截图 2023-11-24 223154](https://github.com/jianchang512/pyvideotrans/assets/77397079/5d6ab415-d69f-4812-aa3c-b69c6494ec38)

最后合成文件下，都是一个音频文件，新版的视频文件也无法生成了，

**Comment by jianchang512** [comment]
已修复
