### ISSUE TITLE
使用了源码版，但无法启用cuda

### ISSUE THREAD

**Issue by SkywalkerJi** [jianchang512/pyvideotrans#79]
按源码版部署，安装了CUDA Toolkit和requirements-gpu.txt
但看负载只有cpu跑了70%，任务管理器里cuda占用为0，3d有10%左右负载。是不是没有启动cuda。

9.5.0

**Comment by SkywalkerJi** [comment]
另外想请问一下是什么阶段会启动cuda加速？视频整体识别 和模型识别音频=>字幕 这两个过程都会调用cuda吗？

我目前识别的2个小时视频，看log提示在ffmpeg不再输出log之后到code==200间有很大一段时间静默，这段时间是在进行视频整体识别吗？

**Comment by jianchang512** [comment]
语音识别阶段会使用GPU
ffmpeg视频切片 处理也会使用

先确定 cuda 生效
`torch.cuda.is_available()` 执行这个看看是否有输出，有输出才说明cuda版本、torch版本匹配，不匹配是无法使用cuda的

上面确定后，界面-高级设置-选中 CUDA加速

**Comment by jianchang512** [comment]
可以激活虚拟环境
然后 `pip uninstall torch torchvision torchaudio` 先卸载
然后去 
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/521d8623-fc91-43cb-bed4-e21b9b87f39d)
根据你的操作系统版本和CUDA版本，获取下面那个 pip 安装命令，将 pip3 改为 pip，然后去安装

至于 CUDA 版本，可以cmd命令行中执行 `nvidia-smi` 查看

**Comment by SkywalkerJi** [comment]
好的，cuda我再尝试一下。

还有一个问题：

我选的是日翻中，gui右侧有正确显示中文字幕。但是识别全部结束之后，_video_out中只有ja.srt日文字幕，没有生成中文字幕文件，我测试了两个视频都是如此。

**Comment by jianchang512** [comment]
> 好的，cuda我再尝试一下。
> 
> 还有一个问题：
> 
> 我选的是日翻中，gui右侧有正确显示中文字幕。但是识别全部结束之后，_video_out中只有ja.srt日文字幕，没有生成中文字幕文件，我测试了两个视频都是如此。 选项选的是配音角色no，也不添加字幕。

![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/363b35b5-a7e3-4ac8-837c-ed6af094f344)

**Comment by SkywalkerJi** [comment]
> 可以激活虚拟环境 然后 `pip uninstall torch torchvision torchaudio` 先卸载 然后去 ![image](https://private-user-images.githubusercontent.com/3378335/285566255-521d8623-fc91-43cb-bed4-e21b9b87f39d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODg5MjgsIm5iZiI6MTcwMDg4ODYyOCwicGF0aCI6Ii8zMzc4MzM1LzI4NTU2NjI1NS01MjFkODYyMy1mYzkxLTQzY2ItYmVkNC1lMjFiOWI4N2YzOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjVUMDUwMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYzMGY0YzQ1ZDRmYjI4ODgxYTY3MDIwNWViYzBkZjliMmVjMjdkNTYwMGQ4YjQ3OGE0ZDE1ODk3NGJiMWM2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VxRetuwQcHfbiltcHeKSKdbrW1NEoOHJ__RMVlLmLNU) 根据你的操作系统版本和CUDA版本，获取下面那个 pip 安装命令，将 pip3 改为 pip，然后去安装
> 
> 至于 CUDA 版本，可以cmd命令行中执行 `nvidia-smi` 查看

成功启用cuda了。多谢。

**Comment by SkywalkerJi** [comment]
> > 好的，cuda我再尝试一下。
> > 还有一个问题：
> > 我选的是日翻中，gui右侧有正确显示中文字幕。但是识别全部结束之后，_video_out中只有ja.srt日文字幕，没有生成中文字幕文件，我测试了两个视频都是如此。 选项选的是配音角色no，也不添加字幕。
> 
> 什么都不选，那就不会翻译也不会配音，自然没有中文字幕。看说明，这种仅是用来从视频中提取出来字幕
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/285566511-363b35b5-a7e3-4ac8-837c-ed6af094f344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTc4MDQsIm5iZiI6MTcwMDkxNzUwNCwicGF0aCI6Ii8zMzc4MzM1LzI4NTU2NjUxMS0zNjNiMzViNS1hN2UzLTRhYzgtODM3Yy1lZDZhZjA5NGYzNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjVUMTMwNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmZiOTU4MjZlNTNmYTVhNjBlMmQwZGM2OGZmN2I3NjgzNjAxZWFlYmJjNzVlNmEyMTBiZDM5ZTI5N2NhMmVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rLWYeVtI3SDPM7ONesjQjUtxN1jNyQAUNoqaCHJwiGU)

可不可以出一个只生成外挂字幕的模式

**Comment by SharkTal** [comment]
我在运行源码版中，发生了同样无法调用GPU的情况，是否可以在Readme中更新解释。谢谢 @jianchang512

**Comment by SharkTal** [comment]
> 语音识别阶段会使用GPU ffmpeg视频切片 处理也会使用
> 
> 先确定 cuda 生效 `torch.cuda.is_available()` 执行这个看看是否有输出，有输出才说明cuda版本、torch版本匹配，不匹配是无法使用cuda的
> 
> 上面确定后，界面-高级设置-选中 CUDA加速

@jianchang512 能否在ReadMez 增加调用GPU CUDA加速的说明。
