### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by topkof** [jianchang512/pyvideotrans#8]
若调用openai-whisper的翻译能力就好了，准确度应该远超google，而且是离线，或者用fast-whisper

**Comment by WangShuXian6** [comment]
请求加入其他的API翻译选项，例如免费的GPT3.5和gpt4。
我有付费的gpt

**Comment by jianchang512** [comment]
> 若调用openai-whisper的翻译能力就好了，准确度应该远超google，而且是离线，或者用fast-whisper

whisper 只能将其他语言翻译为英文，不适合目标语言不是英文的情况
