### ISSUE TITLE
翻译出错 文字翻译出错:list index out of range

### ISSUE THREAD

**Issue by qq296141266** [jianchang512/pyvideotrans#83]
![image](https://github.com/jianchang512/pyvideotrans/assets/23265417/afa0d8a2-9b99-4f6a-8cb0-19f61c2bea70)
![QQ截图20231126142724](https://github.com/jianchang512/pyvideotrans/assets/23265417/b08ff298-053b-4519-a59c-d3b850b2cee0)
文字翻译出错:list index out of range

**Comment by jianchang512** [comment]
语音模型后边改成整体识别试试

**Comment by jianchang512** [comment]
新版再试试
