### ISSUE TITLE
1

### ISSUE THREAD

**Issue by cui4919** [jianchang512/pyvideotrans#84]
选择翻译那里选择的是google，代理地址127.0.0.1:10809   网络能正常访问谷歌
开始任务后提示这个错误，更换节点也不行，请问下有解决方法吗？？
[error google api] Please check the
connectivity of the proxy or
consider changing the IP address.

**Comment by jianchang512** [comment]
是不是代理软件只开启了 sock5 代理，需要开启http代理

软件设置和代理软件设置截图

**Comment by cui4919** [comment]
> 是不是代理软件只开启了 sock5 代理，需要开启http代理
> 
> 软件设置和代理软件设置截图

非常感谢  仔细看了一下  软件默认的是10809端口   代理软件是7890  在软件里面改成7890端口现在可以正常翻译了   再次感谢
