### ISSUE TITLE
批量翻译视频闪退

### ISSUE THREAD

**Issue by hkuyt2006** [jianchang512/pyvideotrans#85]
翻译第一个视频没问题，开始翻译第二个不久后就闪退，还没开始音频拆分就闪退了，就是刚开始提示在分析视频的时候，也没报什么错，最新发布的3个打包版都是如此，我用的百度api，win10.

另外，打包版可否上传到阿里云盘，百度云盘太慢了。。。

**Comment by jianchang512** [comment]
logs目录下日志

可github下载

**Comment by hkuyt2006** [comment]
> logs目录下日志
> 
> 可github下载

INFO:VideoTrans:准备合成语音 folder_path='D:/迅雷下载/video-trans-v0.9.4.3/tmp/5'
INFO:VideoTrans:Creating TTS wav D:/迅雷下载/video-trans-v0.9.4.3/tmp/5/tts-5.wav
INFO:VideoTrans:准备完毕，开始合成视频，d:/output/5.mp4  C:/5.mp4
INFO:VideoTrans:合成配音+硬字幕
INFO:VideoTrans:runffmpeg Will execute: cmd='ffmpeg -hide_banner -y -i "D:/迅雷下载/video-trans-v0.9.4.3/tmp/5/novoice.mp4" -i "D:/迅雷下载/video-trans-v0.9.4.3/tmp/5/tts-5.wav" -c:v libx264 -c:a aac -vf subtitles=5.srt "d:/output/5.mp4"'
INFO:VideoTrans:runffmpeg Will execute: cmd='ffmpeg -hide_banner -y -i "C:/6.mp4" -ac 1 "D:/迅雷下载/video-trans-v0.9.4.3/tmp/6/6.wav"'


这是最后几行

**Comment by jianchang512** [comment]
或者是权限问题
不要直接放硬盘根目录下，尤其是c盘根目录下

**Comment by hkuyt2006** [comment]
ok
