### ISSUE TITLE
最新的这个版本有问题

### ISSUE THREAD

**Issue by jasonsunsoa1983** [jianchang512/pyvideotrans#87]
无论是分段，还是整体识别，最后都失败。反复重试反复失败。

**Comment by jianchang512** [comment]
总有错误提示说明吧

**Comment by jasonsunsoa1983** [comment]
最后都是合成失败

**Comment by jianchang512** [comment]
测试未发现

logs下  最新日志最后几十行

**Comment by jasonsunsoa1983** [comment]
![Uploading error1.png…]()

**Comment by jasonsunsoa1983** [comment]
![error1](https://github.com/jianchang512/pyvideotrans/assets/43527952/8b777885-0028-4158-8f51-0199fc287ed3)

**Comment by jasonsunsoa1983** [comment]
![error2](https://github.com/jianchang512/pyvideotrans/assets/43527952/c50f5571-60e6-4fd0-a6b8-1de93dca53ab)
9.5.1整体识别也报错

**Comment by jasonsunsoa1983** [comment]
9.5.3分段识别报 文字翻译出错:list index out of range  这个同样的错误。

**Comment by jianchang512** [comment]
视频所在路径找个正常没有空格和特殊符号的再试试

**Comment by jasonsunsoa1983** [comment]
![error3](https://github.com/jianchang512/pyvideotrans/assets/43527952/b102eb2a-9fcc-492b-adf2-3465cf7b8f56)
把视频放到没有空格没有特殊字符的文件夹下，先看这个视频自动降速的选项。视频没有合成成功。

**Comment by jasonsunsoa1983** [comment]
[video-20231126.log](https://github.com/jianchang512/pyvideotrans/files/13466759/video-20231126.log)

**Comment by jianchang512** [comment]
视频名字空格也去掉再试试  

是不是本地已有的视频

**Comment by jasonsunsoa1983** [comment]
![error4](https://github.com/jianchang512/pyvideotrans/assets/43527952/fbf27afa-ded3-4b11-8bac-cd521827e7e8)
把视频放到没有特殊符号，没有空格的文件夹中，0.9.5.3音频自动加速选项，视频可以合成出来了，但是与一个报错提示。

**Comment by jianchang512** [comment]
视频名字里面明显有空格
先去掉，名字和路径都不要有空格，看看是不是这个原因导致的
![Uploading image.png…]()

**Comment by jasonsunsoa1983** [comment]
测试了一下儿，应该是文件名称空格的问题。

**Comment by jasonsunsoa1983** [comment]
这个问题，还得麻烦您处理一下儿，要不然大量文件还得一个一个修改名称有点儿麻烦。

**Comment by Copy2Translator** [comment]
这个路径有空格的问题急需解决啊，不然每次用了的人都来报错，然后大多数都是这个原因，你解释都太耗时耗精力了

**Comment by jianchang512** [comment]
应该可以了
