### ISSUE TITLE
经常出现某些语音合成失败

### ISSUE THREAD

**Issue by jasonsunsoa1983** [jianchang512/pyvideotrans#88]
![error5](https://github.com/jianchang512/pyvideotrans/assets/43527952/b050d9c1-c26c-4da6-b7a4-fdd40ed0da32)
![error6](https://github.com/jianchang512/pyvideotrans/assets/43527952/5c1ad412-935e-4b8a-bcb6-8b553bd7c101)
尤其是，输出文件夹下边儿有多个文件夹的时候，非常频繁的出现语音合成失败。

**Comment by jasonsunsoa1983** [comment]
[video-20231126.log](https://github.com/jianchang512/pyvideotrans/files/13467209/video-20231126.log)

**Comment by jianchang512** [comment]
可能是翻译太频繁限制了
使用其他的翻译
deepl等
