### ISSUE TITLE
Unable to open 1.srt [AVFilterGraph @ 000001b6c79c6f40] Error initializing filters

### ISSUE THREAD

**Issue by tiejiang8** [jianchang512/pyvideotrans#9]
[Parsed_subtitles_0 @ 000001b6c79c6fc0] libass API version: 0x1701000
[Parsed_subtitles_0 @ 000001b6c79c6fc0] libass source: commit: 5c15c883a4783641f7e71a6a1f440209965eb64f-dirty
[Parsed_subtitles_0 @ 000001b6c79c6fc0] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 8.2.1 (COMPLEX)
[Parsed_subtitles_0 @ 000001b6c79c6fc0] Unable to open 1.srt
[AVFilterGraph @ 000001b6c79c6f40] Error initializing filters
[vost#0:0/libx264 @ 000001b6c7962ac0] Error initializing a simple filtergraph

![image](https://github.com/jianchang512/pyvideotrans/assets/32443751/0ca8d8a6-bfd8-4e9c-a86c-58210a1d9a0e)

**Comment by perfectbullet** [comment]
相同的问题

**Comment by perfectbullet** [comment]
字幕格式问题， 把时间
0:00:00 --> 0:00:10,500

修改为
0:00:00,000 --> 0:00:10,500
就可以了
