### ISSUE TITLE
文字翻译错误

### ISSUE THREAD

**Issue by demon-os** [jianchang512/pyvideotrans#98]
<img width="437" alt="2023-12-01_071536" src="https://github.com/jianchang512/pyvideotrans/assets/152586863/4977d00c-2613-40c5-ba01-e35420cf3d9f">

**Comment by jianchang512** [comment]
logs下日志信息

**Comment by jianchang512** [comment]
更换翻译渠道
首先要看右侧字幕区域是否有识别出的字幕，如果没有，那肯定无法翻译

**Comment by Levisper** [comment]
> 更换翻译渠道 首先要看右侧字幕区域是否有识别出的字幕，如果没有，那肯定无法翻译

遇到同样问题，字幕已经识别出来，但是无法翻译，网络没有问题，日志报错同上。

**Comment by Levisper** [comment]
> 更换翻译渠道 首先要看右侧字幕区域是否有识别出的字幕，如果没有，那肯定无法翻译

更换翻译引擎依旧无法解决此问题。

**Comment by jianchang512** [comment]
> > 更换翻译渠道 首先要看右侧字幕区域是否有识别出的字幕，如果没有，那肯定无法翻译
> 
> 更换翻译引擎依旧无法解决此问题。

logs目录下最新的日志文件上传下看看。

**Comment by demon-os** [comment]
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:VideoTrans::::开始处理第1个视频(共1个):【Z:/宝宝搞笑/1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日.mp4】
INFO:VideoTrans:正在处理第1个视频(共1个):【Z:/宝宝搞笑/1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日.mp4】
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 分析视频数据
INFO:VideoTrans:准备分割数据后进行语音识别
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 对音频文件按静音片段分割处理
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 音频处理进度0.8%
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 音频处理进度16.3%
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 音频处理进度31.9%
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 音频处理进度47.4%
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 音频处理进度63.0%
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 音频处理进度78.5%
INFO:VideoTrans:1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日 音频处理进度94.0%
INFO:VideoTrans:字幕识别完成，共7条字幕
INFO:VideoTrans:等待修改原语言字幕/继续
INFO:VideoTrans:60 秒后自动翻译，你可以停止倒计时后去修改字幕，以便翻译更准确
INFO:VideoTrans:59 秒后自动翻译，你可以停止倒计时后去修改字幕，以便翻译更准确
INFO:VideoTrans:58 秒后自动翻译，你可以停止倒计时后去修改字幕，以便翻译更准确
INFO:VideoTrans:开始翻译字幕文件
INFO:VideoTrans:倒计时停止，清空字幕区文字
INFO:VideoTrans:文字翻译出错:list index out of range
INFO:VideoTrans:已停止
INFO:VideoTrans:翻译出错.
INFO:VideoTrans:本次任务全部结束

**Comment by jianchang512** [comment]
这是要翻译为哪种语言
看看目标文件夹内有没有 srt 格式文件，有几个，里面有没有内容，截图

**Comment by demon-os** [comment]
<img width="1113" alt="2023-12-01_094510" src="https://github.com/jianchang512/pyvideotrans/assets/152586863/c21bc97a-04f3-4545-a0b9-2412e757f49d">
<img width="877" alt="2023-12-01_094607" src="https://github.com/jianchang512/pyvideotrans/assets/152586863/844512ab-5c2f-4d17-928f-ca93ecc960d8">
中fan翻英

**Comment by demon-os** [comment]
1.使用预先分割，直接无法翻译
2.使用整体识别可以正常翻译使用
3.使用自己的srt文件，logs显示如下
INFO:VideoTrans:开始配音操作:edgeTTS,en-US-GuyNeural
INFO:VideoTrans:准备合成语音 self.cache_folder='E:/剪辑软件/video-trans-v0.9.6.1/tmp/1_世界所有核弹同时引爆，能否毁灭人类？其危害究竟有多大？（上篇）#科普 #核弹 #世界末日'
ERROR:VideoTrans:[error]组装配音所需数据时出错:not enough values to unpack (expected 2, got 1)
INFO:VideoTrans:本次任务全部结束

自己的srt如下：
1
00:00:00,933 --> 00:00:07,266
All nuclear bombs in the world explode together
Can they destroy the Earth?
August 6, 1945

2
00:00:07,266 --> 00:00:13,466
The U.S. military dropped the first atomic bomb in human history on Hiroshima, Japan, called "Little Boy"

3
00:00:13,466 --> 00:00:19,400
The bomb weighed about 4,100 kilograms and exploded with the equivalent of TNT explosive

4
00:00:19,500 --> 00:00:24,033
Causing 80,000 people to die instantly, 120,000 people missing, and 40,000 people injured

5
00:00:24,500 -->00:00:32,333
Unfortunately, the tragedy of Hiroshima did not make Japan surrender. They tried to cover up the truth. August 9, 1945

6
00:00:32,333 --> 00:00:39,800
The U.S. military dropped the second atomic bomb on Japan, called "Fat Man." It weighed about 4,500 kilograms

7
00:00:40,266 --> 00:00:47,866
With the explosive power equivalent to 20,000 tons of TNT, it caused 73,000 people to die instantly, and over 350,000 people

8
00:00:47,866 --> 00:00:54,433
Suffered from the trauma and radiation of the atomic bomb and died in the following days. This is also the only time in human history

9
00:00:54,500 -->00:01:00,400
That atomic bombs were directly used in war. The tremendous destructive power brought by atomic bombs

10
00:01:00,400 --> 00:01:04,333
Made humanity realize the undeniable power of nuclear weapons

**Comment by jianchang512** [comment]
预先分割有点问题

ERROR:VideoTrans:[error]组装配音所需数据时出错:not enough values to unpack (expected 2, got 1)

这个使用的什么模式，使用自己的字幕打算做什么，只嵌入还是有配音

**Comment by demon-os** [comment]
使用自己的字幕，配音然后和视频画面进行匹配，不知道支持不。

**Comment by jianchang512** [comment]
没看明白这是做什么

**Comment by demon-os** [comment]
<img width="1056" alt="2023-12-01_095914" src="https://github.com/jianchang512/pyvideotrans/assets/152586863/c311609a-7f16-4e13-a603-ac617263dae5">

**Comment by jianchang512** [comment]
没这样测试过，应该是支持的
你试试吧，先使用整体识别

**Comment by demon-os** [comment]
使用自己的字幕报错ERROR:VideoTrans:[error]组装配音所需数据时出错:not enough values to unpack (expected 2, got 1)
0.9.6.0昨天用的时候预先分割可以正常使用。

**Comment by jianchang512** [comment]
使用整体识别

**Comment by jianchang512** [comment]
字幕时间格式需要是
00:00:01,125 --> 00:00:02,152

逗号隔开的后边3位数字，可能格式不正确

**Comment by jianchang512** [comment]
0.9.6.2试试

**Comment by demon-os** [comment]
预先分割可以正常使用了
