### ISSUE TITLE
本地运行cuda版本时报错

### ISSUE THREAD

**Issue by yuppiesnotzhuhao** [jianchang512/pyvideotrans#99]
(.venv) PS D:\pyvideotrans> python sp.py
pygame 2.5.2 (SDL 2.28.3, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:\pyvideotrans\sp.py", line 1340, in <module>
    with open(f'{config.rootdir}/videotrans/styles/style.qss','r',encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/pyvideotrans/videotrans/styles/style.qss'
QThread: Destroyed while thread is still running

**Comment by jianchang512** [comment]
拉取最新版

**Comment by yuppiesnotzhuhao** [comment]
> 拉取最新版

我从预编译版本中把styles/style.qss这个文件放进去可以跑了，可以发一下Discord吗

**Comment by jianchang512** [comment]
重新拉取源码，已加进源码

**Comment by yuppiesnotzhuhao** [comment]
可以了
